### ISSUE TITLE
Make separate line history view more discoverable

### ISSUE THREAD

**Issue by eamodio** [gitkraken/vscode-gitlens#1217]
Refs: #1177

**Comment by adamreisnz** [comment]
Please add back the separate line history view and UI toggle option. This is the most useful feature of Gitlens for us.

**Comment by eamodio** [comment]
@adamreisnz This exists today, see here:

![image](https://user-images.githubusercontent.com/641685/104657578-2f5f0300-568f-11eb-881f-b2b1a20a9830.png)

**Comment by eamodio** [comment]
But I'm still considering adding a "pop-out" button or something to the view as well.

**Comment by adamreisnz** [comment]
Ok I didn't see that option. I had to add the config manually via code as
per the instructions in the linked issue.

I was surprised that it doesn't just exist as a toggleable option by
default like File history.

Usually when developers start hiding features it's a precursor to removing
them completely.

**Comment by eamodio** [comment]
What do you mean by this?
> I was surprised that it doesn't just exist as a toggleable option by
default like File history.

Do you mean this? Clicking that will toggle between File & Line history.
![image](https://user-images.githubusercontent.com/641685/104688713-3c034b80-56cf-11eb-848d-ccc2e8053e4f.png)

Initially the plan was the completely remove the independent _Line History_ view, since I integrated as a toggle on the _File History_ view, but because enough users still want it as an additional view, I am keeping it.

**Comment by adamreisnz** [comment]
Ok, yes I see that button now.
A separate Line history view would be great, thanks.

**Comment by eamodio** [comment]
As I mentioned, Line History exist as _both_ a mode of the File History view and as it's own Line History view today.

**Comment by eamodio** [comment]
This has been resolved a while ago, since the Line History view is enabled by default on the GitLens Inspect sidebar
