### ISSUE TITLE
GitLense disabled with LiveShare

### ISSUE THREAD

**Issue by MaKaNu** [gitkraken/vscode-gitlens#1232]
- GitLens Version: 11.0.6
- Git Version: 2.29.2.windows.2

- VSCode Version: 1.51.1
- OS Version: WIndows_NT x64 10.0.18363

Steps to Reproduce:
  
**Disclaimer**: I am not 100% sure about what created the problem, but I have a direction

1. The problems occurs after a test Session with the LiveShare Extension.
1. An error with relation to gitlense poped up after launching a live share.
1. At this moment I sadly didn't cared to much about it and I am unable to create this error again.
1. Since that Session I don't get any GitLense UI for all files in a specific folder.
1. The file was opend while the LiveShare Session was running.

![GITLENSEFehler01](https://user-images.githubusercontent.com/32844273/100884442-c42be980-34b1-11eb-8f4f-3e265b5d0e0b.png)

This Image shows a working file from this Repo.

![GITLENSEFehler02](https://user-images.githubusercontent.com/32844273/100884542-e32a7b80-34b1-11eb-9d09-10840fbfd7ad.png)

This Image shows a not working file from the same Repo but in a different subfolder.

**Comment by rbreaves** [comment]
This appears to still be a problem and I believe this is related. My guest is also unable to show the gitlens blame notations.

#596

**Comment by cotneit** [comment]
Same issue, at first there was a warning from GitLens, something about guest access on host machine, I checked that and it was already enabled, then I decided to update VSCode and it still doesn't work, but now there's not even a warning.

**Comment by eamodio** [comment]
Can you please see if this issue is still reproducible in the latest version of GitLens? Thanks!
