### ISSUE TITLE
Add GitLab rich integration

### ISSUE THREAD

**Issue by kpaxton** [gitkraken/vscode-gitlens#1236]
My company has a privately hosted GitLab instance. I read in the docs that the Pull-Requests should be visible in the Commits View, but I'm not seeing them. I've set up the domain and type in the `gitlens.remotes` settings, but I am not seeing any Merge Requests in the view. 

Is there something else I need to set up for this to work or is GitLab not fully supported for that feater?

**Comment by eamodio** [comment]
The rich integration support is currently only implemented for GitHub, but its extensible to support any remote provider. So if someone would create a PR talk to the GitLab (or BitBucket, AzureDev Ops, etc) APIs it could be integrated. But it is unlikely that I will add that support myself, as I don't use the other providers and it would take a lot of time for me to setup and test.

**Comment by kpaxton** [comment]
Thanks Eric.

**Comment by eamodio** [comment]
Just to be clear, I'd love to have support for other providers -- and would definitely help anyone who wants to start on this.

**Comment by kpaxton** [comment]
I can take a look, but I can't guarantee anything time wise. 

One thing I do notice right now is that GitLab's GraphQL interface doesn't seem to be full-fledged. So is there an http client that you would prefer using instead of the native http client or just use the native?
@eamodio

**Comment by eamodio** [comment]
Thanks -- let me know if you need any help or have any questions.

If the GraphQL support won't work, I would recommend using the `node-fetch` library, that way we can work in the desktop and browser.

You can join the [VS Code Development Community Slack](https://aka.ms/vscode-dev-community) or we can use the newly enabled GitHub Discussions on this repo.

**Comment by kpaxton** [comment]
The discussions or Gitter.im is probably best for me. but I'll also try and
set up the slack, I'm having issue on my current machine due to a work
internet filter that seems to be blocking that url.

**Comment by eamodio** [comment]
Closed by fd61e1d355f8f44befb186ed316deab6457eca12
