### ISSUE TITLE
Strange Behavior On Markdown Files While Collapsing Sections

### ISSUE THREAD

**Issue by atom0s** [gitkraken/vscode-gitlens#1310]
- GitLens Version: v11.1.3
- Git Version: 2.29.1.windows.1
- VSCode Version: 1.53.0-insider
- OS Version: Windows 10 (Windows NT x64 10.0.18363)

Steps to Reproduce:

1. Open a markdown file.
2. Create a lot of different sections broken into varying levels of headings.
3. Collapse (fold) a handful of the headings in VSCode's editor.
4. Click a blank line after a folded heading.

At this point, there is a high-chance that GitLens will bug out and pop open the changes mini-window and then scroll to the bottom of the document immediately.

As an example:
![https://i.imgur.com/Bm61y3s.png](https://i.imgur.com/Bm61y3s.png)

With the above all collapsed, if I click the blank line between 'Scope' and 'Globals' here, the issue will happen 100% of the time.

This is enough to test the bug:
```
# This is a test to reproduce the bug.

## Sub-Section

### Mini-Section

  - A list entry.
  - A list entry.
  - A list entry.
  - A list entry.

### Mini-Section

  - A list entry.
  - A list entry.
  - A list entry.
  - A list entry.

## Sub-Section

### Mini-Section

  - A list entry.
  - A list entry.
  - A list entry.
  - A list entry.

### Mini-Section

  - A list entry.
  - A list entry.
  - A list entry.
  - A list entry.
```

Create a new repo, commit this file to it and begin editing it locally. Collapse each mini-section then click blank lines between them. GitLens will explode with the bug each time.

Edit: Also forgot to mention; when this bug happens, the scrollbar preview feature breaks in VSCode.
![https://i.imgur.com/fSC4GJw.png](https://i.imgur.com/fSC4GJw.png)

This stops functioning and reverts back to a standard scrollbar instead.

**Comment by socketbox** [comment]
@atom0s Did anyone ever address this issue? Has it been resolved?

**Comment by atom0s** [comment]
Nope. No idea if its fixed either, I don't use GitLens anymore due to how buggy it was and getting no answers/responses.

**Comment by eamodio** [comment]
I can't reproduce any such behavior and GitLens doesn't scroll the document nor do anything with folding. Can you provide more details (including what other extensions are installed) and a video/gif?
