### ISSUE TITLE
Add autolinks editing to GitLens Setting UI

### ISSUE THREAD

**Issue by eamodio** [gitkraken/vscode-gitlens#1315]
Today you need to use the json editor to create or edit autolinks. It would be great add this add/editing capability to the GitLens Settings UI to provide a far richer experience. We could even offer the ability to enter example text and show what the resulting autolink would be.

**Comment by pelukron** [comment]
hey @eamodio, if nobody is working on it, I could try to add this feature on Settings UI

Can I go ahead?
Can you share me any advice on this?
I have not much context on the repo so far

**Comment by pelukron** [comment]
Actually, have some doubts about what could be the best approach on this.
I mean,
- should I continue with new section as  blame line? 
- should I just add this feature on any of those sections?

// D
