### ISSUE TITLE
Filter out Merge Commits in Commit View

### ISSUE THREAD

**Issue by hoodie** [gitkraken/vscode-gitlens#1399]
Hi there, love the product.
In our project we have a lot of merge commits, do you think it would be feasible to have a flag on the commit view to filter those?

This would basically be like `git log --no-merges`

Thanks a lot.

**Comment by eamodio** [comment]
While this is a good idea, it isn't something that I will likely add myself (anytime soon). So if you or the if the community wants to champion it, and provide a PR (after discussions) I'm certainly open to it — depending, of course, on the complexity and scope of the changes involved.

**Comment by Shashank-Shastri** [comment]
@eamodio @hoodie Implemented this here: https://github.com/eamodio/vscode-gitlens/pull/1540. Let me know if I missed something or if you need any info from me.

**Comment by jorisa** [comment]
I am really looking forward to this feature!

**Comment by obxpete** [comment]
Thanks, @d13  for connecting my feature request.  Clearly I too am really looking forward to this new feature!  

I do note thought that #1540 code has run stale and is reported to cause conflicts in its current state.  

If this could get implemented I'll be taking up licensing with my team leader as this is an awesome tool!

thanks

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's (`v2023.10.22xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by axosoft-ramint** [comment]
Verified in 14.5.0
