### ISSUE TITLE
Support VSCodium in interactive rebase editor

### ISSUE THREAD

**Issue by jingyu9575** [gitkraken/vscode-gitlens#1473]
[VSCodium](https://github.com/VSCodium/vscodium) is an open source build of vscode, and this extension works well on it. However, it uses the command `codium` instead of `code` and the interactive rebase editor is not launching. 

Could you add a branch to the appName switch:

https://github.com/eamodio/vscode-gitlens/blob/2b8a300703103b12ab90b17e1ad0a2d6c9ece1e6/src/commands/git/rebase.ts#L81-L91

```js
 	case 'VSCodium': 
 		editor = 'codium --wait --reuse-window'; 
 		break; 
```

Thank you!

**Comment by matronator** [comment]
Duplicate #1430

**Comment by jingyu9575** [comment]
@matronator I think this issue is easier to implement than Github auth in #1430. It only needs a branch in the switch code.

**Comment by pmahend1** [comment]
I don't think this logic will work for authentication provision #1430 , it involves redirection code.

**Comment by Earthnuker** [comment]
> 
> 
> [VSCodium](https://github.com/VSCodium/vscodium) is an open source build of vscode, and this extension works well on it. However, it uses the command `codium` instead of `code` and the interactive rebase editor is not launching.
> 
> Could you add a branch to the appName switch:
> 
> https://github.com/eamodio/vscode-gitlens/blob/2b8a300703103b12ab90b17e1ad0a2d6c9ece1e6/src/commands/git/rebase.ts#L81-L91
> 
> ```js
>  	case 'VSCodium': 
>  		editor = 'codium --wait --reuse-window'; 
>  		break; 
> ```
> 
> Thank you!

I just tested the change suggested here and it works without issue, i don't see what authentication has to do with this since git rebase only modifies the local repository and does not talk to the remote

Best regards,

Earthnuker

**Comment by diggit** [comment]
I've also stumbled on this issue.
Hard coding executable names seems too fragile to me.
At least default should be empty so git configuration may work as fallback. User might have configured `sequence.editor`.
Or expose executable name through extension config.

**Comment by eamodio** [comment]
Fixed in https://github.com/gitkraken/vscode-gitlens/commit/9994e1351eaf6243c5342455fb77e78b1182f948

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by pmahend1** [comment]
@eamodio thanks. I did a quick test on preview version and this seems to be working fine.

```
git -c sequence.editor="codium --wait --reuse-window" rebase --interactive blahblahblacksheep
hint: Waiting for your editor to close the file... 
```
