### ISSUE TITLE
Annoying Github login request

### ISSUE THREAD

**Issue by metalim** [gitkraken/vscode-gitlens#1506]
Loved the tool. Have to uninstall it unfortunately.

If I don't allow github access, then this bugger `1` is there permanently.
![Code_2021-05-14_21-16-50](https://user-images.githubusercontent.com/230431/118312268-c468f000-b4f9-11eb-9cc0-4bd2fffbcb5f.png)

And this makes no sense, especially in corporate sector, where you try to restrict as much as possible. I simply don't need it to access github at all, not even read-only.
![chrome_2021-05-14_21-18-34](https://user-images.githubusercontent.com/230431/118312593-43f6bf00-b4fa-11eb-9077-265ebe21702e.png)

Thanks for your efforts, though.

**Comment by eamodio** [comment]
Yeah, I really wish the user experience of this was better in VS Code (I've opened this issue: https://github.com/microsoft/vscode/issues/118668). Until that gets resolved, you can completely disable GitLens rich integrations by setting the `"gitlens.integrations.enabled": false`, that will avoid this completely.

**Comment by eamodio** [comment]
VS Code just added a way for extensions to avoid that badge! 🎉 So GitLens will no longer annoy you all with that badge -- sorry it took so long.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.
