### ISSUE TITLE
Add option to make git blame date more precise

### ISSUE THREAD

**Issue by Cheldon** [gitkraken/vscode-gitlens#1546]
It is really useful to see the "ago" time in days, weeks, then months, but once it goes to years it loses a lot of precision. "1 year ago" can mean 365 days or it can mean (2 years - 1 day).

I think knowing something was 14 months ago would be more useful than an ambiguous "1 year" = 12-24 months ago. But after 24 months I wouldn't want as much precision.

Perhaps the best option would be to show "1 year, 2 months ago" instead of an arbitrary cutoff (like 12 or 24) for when months turn into years.

Maybe there's a way to use something from `agoOrDate `or gitlens.`defaultDateSource`?

Created feature request from [Q&A #1539](https://github.com/eamodio/vscode-gitlens/discussions/1539)

**Comment by thewindsofwinter** [comment]
Hi! I could work on this if no one's doing it already, although it might take me a bit :)

**Comment by Cheldon** [comment]
Maybe gitlens updated recently because I noticed today my gitlens said "You, last year" instead of "You, a year ago" but the date is October 2020 so "last year" isn't even correct here. This is one of the places where "You, 17 months ago" would make more sense to me.

**Comment by eamodio** [comment]
In GitLens 12.0.2 (should be out once the CI finishes), it will now show dates >= 1 year but < 2 years to be shown in months. Hopefully that addresses most of the request here.

**Comment by Cheldon** [comment]
Tried it out and looks great, thanks!
