### ISSUE TITLE
Fetch does not work when local branch name differs from remote branch name

### ISSUE THREAD

**Issue by Arnall** [gitkraken/vscode-gitlens#1549]
- GitLens Version: v11.5.1
- Git Version: git version 2.31.1.windows.1

- VSCode Version: 1.57.1
507ce72a4466fbb27b715c3722558bb15afa9f48
x64
- OS Version: Windows 10 21H1 19043.1052

Steps to Reproduce:

1. right click on a branch on remote > "Create Branch..." 
2. give the branch a different name from the remote branch ( ex: master -> local_master)
3. in the "branches" widget click on the fetch button on the local branch (local_master)

What I see: 

error message : `Unable to fetch repository. See output channel for more details`
output channel:
```
[2021-06-18 08:52:01:108] [c:/....] Git Command failed: C:\Program Files\Git\cmd\git.exe -c core.longpaths=true -c core.quotepath=false -c color.ui=false fetch sysadmin local_master • couldn't find remote ref local_master • the remote end hung up unexpectedly • 390 ms 
[2021-06-18 08:52:01:109] c:\Users\...\.vscode\extensions\eamodio.gitlens-11.5.1\dist\gitlens.js:55:36671
Error: Command failed: C:\Program Files\Git\cmd\git.exe -c core.longpaths=true -c core.quotepath=false -c color.ui=false fetch sysadmin local_master
fatal: couldn't find remote ref local_master
fatal: the remote end hung up unexpectedly
```

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's pre-release edition of GitLens?

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)
