### ISSUE TITLE
Left / right side filter doesn't work

### ISSUE THREAD

**Issue by bd-dgonano** [gitkraken/vscode-gitlens#1591]
Issue Type: <b>Bug</b>

Similar to https://github.com/eamodio/vscode-gitlens/issues/1035, if you do a comparison with working-tree the `show left/right side files only` filter doesn't work. 
It does work if you do it with current branch and another reference. 

Extension version: 11.6.0
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 4.15.0-151-generic snap
Restricted Mode: No

**Comment by eamodio** [comment]
Can you please see if this issue is still reproducible in the latest version of GitLens? Thanks!
