### ISSUE TITLE
`Compare HEAD with branch_name` created when selecting `Compare with HEAD` from the context menu

### ISSUE THREAD

**Issue by tamuratak** [gitkraken/vscode-gitlens#1592]
- GitLens Version:  11.6.0
- Git Version: git version 2.21.1 (Apple Git-122.3)

Version: 1.59.0-insider
Commit: 955a1aca9a2e4473eec4f4bdc70506a3a7c43ca7
Date: 2021-07-26T05:12:43.446Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Open Branch View.
2. Right-click a branch and select `Compare with HEAD`
3. A created entry in the Search and Compare View is `Compare HEAD with branch_name`

An entry `Compare branch_name with HEAD` should be created.

We can see the same issue for `Compare with Working Tree`.

![スクリーンショット 2021-07-27 17 42 16](https://user-images.githubusercontent.com/10665499/127124319-9a542584-4339-42ca-b421-a618a2f44d87.png)

![スクリーンショット 2021-07-27 17 44 13](https://user-images.githubusercontent.com/10665499/127124561-471eda29-fc39-46ef-96a1-bcf3623fc465.png)

**Comment by eamodio** [comment]
This is by design though it is certainly a matter of opinion.
