### ISSUE TITLE
Add a better time sample in "Dates & Times" setting

### ISSUE THREAD

**Issue by AliabbasMerchant** [gitkraken/vscode-gitlens#1601]
I (and maybe others also) prefer time in 24H format. So we need to change the date format string. The sample time provided helps in validating whether the resulting date time is in the proper expected format or not.  

The current example date and time sample is: July 26th, 2018 4:48am  
In this, for checking the final output, since the time is 4:48am, 12h and 24h both have the same representation (04). I would suggest changing it to 4:48pm, so that 12h representation is 04 and 24h is shown as 16.

**Comment by AliabbasMerchant** [comment]
Okay, so the sample datetime in the code is `Wed Jul 25 2018 19:18:00 GMT-0400`, which changes according to the timezone, hence for example for those of us in India, it is shown as July 26, 4:48am in our timezone.

Any way in which we can circumvent this?  
Maybe by having 2 examples?  
I believe directly removing the timezone would not work, as it is also essential.

**Comment by eamodio** [comment]
I'm am now normalizing the default date to be relative to the current timezone, which should help.

Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by AliabbasMerchant** [comment]
I installed the insiders edition now. The default date is still "July 26th, 2018 4:48am"
