### ISSUE TITLE
Blame hover shows PR merge commit instead of specific commit

### ISSUE THREAD

**Issue by jasonvarga** [gitkraken/vscode-gitlens#1615]
- GitLens Version: 11.6.0
- Git Version: 2.30.1
- VSCode Version: 1.59.1
- OS Version: MacOS 11.4

Steps to Reproduce:

1. Hover a blame on a line
2. Within the hover, click the globe.
3. You get taken to the merge commit rather than the specific commit within the PR.

The PR was merged using a squash. 
At one point, clicking the globe would take me to the specific commit within that PR, even if the PR was squashed, which was awesome.

Apologies if this is a duplicate. I wasn't sure what else to search for.

**Comment by jasonvarga** [comment]
> At one point, clicking the globe would take me to the specific commit within that PR, even if the PR was squashed

I'm now second guessing myself. Maybe it never did that. It works fine if PRs were merged using a regular merge commit.

Perhaps this could be changed to a feature request? It would still be awesome if it _could_ get the appropriate commit on a PR.

**Comment by eamodio** [comment]
@jasonvarga Sorry, I'm not sure what behavior you are expecting. If the PR was squashed then the commit Git sees would be the squashed commit only as you would have squashed away the details of the original commits.

**Comment by jasonvarga** [comment]
Yeah I don't think it ever worked when the PR was squashed.
The times I saw it work, the PR was probably merged without squashing. My mistake.

Feel free to just close this. 👍 Although it would be pretty cool if it was possible, but I doubt it.
e.g. You can see the PR merge commit... so I would think technically you could look at that PR's branch commit history and do a blame in there, but that sounds super complicated.

**Comment by eamodio** [comment]
Ah, I see. Yeah that would not be easy (if it was really possible) and most workflows suggested deleting the PR branch after merge too.

Given that, I'm going to close this out as I think this is beyond the scope of what we add to GitLens. Thanks though!
