### ISSUE TITLE
Provide ability to get commit/file differences relative to @{upstream} rather than @{push}

### ISSUE THREAD

**Issue by studgeek** [gitkraken/vscode-gitlens#1628]
GitLens using the following `git log` call with a revision range of `@{push}..` to get the changed commits for features like [Gutter Changes](https://github.com/eamodio/vscode-gitlens/#gutter-changes-) and Gutter Heatmap.

```
/usr/bin/git -c core.quotepath=false -c color.ui=false -c log.showSignature=false log --format=%x3cr%x3e%x20%H --follow @{push}.. -- my_server/main.cc
```
Using the reference `@{push}` works sub-optimally (or even fails in some setups) for developers who are working in a triangle flow where their fetch/merge/upstream and push are different destinations. There are also push flows that use special destination paths (e.g. [Gerrit uses a destination of `refs/for/branch`](https://gerrit-review.googlesource.com/Documentation/user-upload.html#push_create)).

For these situations it would be helpful to have the option of using the reference `@{upstream}` instead of `@{push}`. I think one could even argue that changes relative to `upstream` is actually what the user is usually looking to see with features like Gutter Changes (and that `push` just happens to often be the same destination).

**Comment by eamodio** [comment]
We believe this issue has been resolved in the latest (or recent) version of GitLens. If you are still experiencing this please let us know and we can re-open the issue or open a new issue if this is already locked.
