### ISSUE TITLE
Unclear how to prevent annotations from blaming uninteresting reformating revisions

### ISSUE THREAD

**Issue by Chealer** [gitkraken/vscode-gitlens#1631]
I changed indentation in a project, and now GitLens 11.6.0 often blames me as the last developer who changed lots of lines, even though the revision was entirely cosmetic.

It would be great to tell GitLens to ignore that revision, and ticket #413 seems to indicate that is feasible, but I find it unclear how that could be done. It would be good to either document the process or clarify the preference(s) involved.

**Comment by eamodio** [comment]
Sorry for the long delay here. You can add a `.git-blame-ignore-revs` file to your repo and GitLens will automatically apply it to blames.

You can find more information about `.git-blame-ignore-revs` here:
https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view
