### ISSUE TITLE
Heatmap as a annotation background color

### ISSUE THREAD

**Issue by AlexSapoznikov** [gitkraken/vscode-gitlens#1637]
It would be nice if heatmap could be shown as a background color for annotation line, like this:
![image](https://user-images.githubusercontent.com/12024168/133076858-9742f94f-cccf-4a74-9c04-3c054bdfd545.png)

It could be configured in **Gitlens > Blame > Heatmap: Location** and option "as a background"

**Comment by eamodio** [comment]
I agree that would be a nice option!

**Comment by eamodio** [comment]
We believe this has been resolved in the latest (or recent) version of GitLens. GitLens has options on the Heatmap to add line highlights and even fade out older lines.
