### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [gitkraken/vscode-gitlens#1645]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by eamodio** [comment]
@JamieSlome sorry for the delay here 😢. You can reach me on gmail @ my github user name.

**Comment by JamieSlome** [comment]
@eamodio - if you would prefer, you can view the report directly here:

https://huntr.dev/bounties/80651d7d-a6aa-4f5f-8853-c0177a25ffb8/
