### ISSUE TITLE
The `gitlens.codeLens.enabled = false` does not work.

### ISSUE THREAD

**Issue by ddnexus** [gitkraken/vscode-gitlens#1646]
- GitLens Version: 11.6.0
- Git Version: 2.20.1
- VSCode Version: 1.60.1
- OS Version: Linux x64 5.11.0-34-generic and Ubuntu 2021.04

 It doesn't work neither in the settings nor in the GitLens UI.

Steps to Reproduce:

1. Go to the GitLens: the main `Git Code Lens` checkbox is disabled (it should be enabled by default)
2. The info still appears in the documents
3. If you use the `GitLens: Toggle Git Code Lens` command it switches it OFF, however next time you re-open the same file it will be ON again, and you will have to use the toggle command again
4. If you try to use the main `Git Code Lens` checkbox, it enables it for a second and it immediately disables it. At least that is what you see in the UI. The actual behavior is still enabled by default anyway.

There are no GitLens entries in the Log.

What else should I check?
Thanks

**Comment by ddnexus** [comment]
I could disable it by adding to the settings:

```json
    "gitlens.codeLens.enabled": false,
    "gitlens.codeLens.authors.enabled": false,
    "gitlens.codeLens.authors.command": false,
    "gitlens.codeLens.recentChange.enabled": false,
    "gitlens.codeLens.recentChange.command": false
```
At this point I am not sure I understand correctly what the ` "gitlens.codeLens.enabled": false` does. Shouldn't it work as the main ON/OFF switch?

**Comment by JonathanHeinz** [comment]
Agree, i have the same issue.

**Comment by eamodio** [comment]
Yes, `gitlens.codeLens.enabled` is the main switch -- so turning it off should turn all the code lens off (though just the code lens, not the current line blame or anything else). 

Can you show a gif/video of the behavior?
