### ISSUE TITLE
Closing interacteractive rebase editor after "git rebase --edit" aborts rebase-in-progress

### ISSUE THREAD

**Issue by bmartin** [gitkraken/vscode-gitlens#1652]
If I'm starting a new rebase, the behavior that closing the editor (CTRL+w) aborts the rebase is natural and reasonable. Basically you need to use CTRL+ENTER to start the rebase. However, if I'm in the middle of a rebase, this behavior is really bad, to the point where I've now disabled the editor.

- GitLens Version: v11.6.0

Steps to Reproduce:

1. Start interactive rebase and use Edit on some commit down the list, then hit CTRL+ENTER to start
2. In the terminal, enter "git rebase --edit" and edit the rebase. (I used "r e" in edamagit)
3. Decide you don't want to edit, so close window with CTRL+w
4. Notice that you are no longer in a rebase and all future commits are lost
5. Break out "git revlog HEAD" and swear a lot to recover the lost commits

The workflow of just closing the editor if nothing is wrong works for amending a commit, so it is really natural to do for the rebase editor. Emptying out the git-rebase-todo file is surprising in this case.

I'm not entirely sure if there is a way to differentiate between in-progress and proposed rebase sessions, so I'm not sure how hard this is to fix.

**Comment by eamodio** [comment]
Hrm, let me think about this to see how this would work. But once the rebase starts -- you'd expect that closing the editor would continue the rebase?

**Comment by eamodio** [comment]
Unfortunately I've had to remove the "close to abort" functionality altogether, as recent versions of VS Code changed the event timing and I can no longer reliably get it to work. So now, closing the editor will always start the rebase -- as I can't even control the closing of the editor at all now.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's pre-release edition of GitLens?

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)

**Comment by bmartin** [comment]
Will do
