### ISSUE TITLE
Vscode-gitlens messy interface

### ISSUE THREAD

**Issue by imswk** [gitkraken/vscode-gitlens#1653]
- GitLens Version: v11.6.0
- Git Version: git version 2.30.1 (Apple Git-130)
- VSCode Version: 1.60.2 (Universal)
- OS Version: macOS Big Sur v11.5.2

![image](https://user-images.githubusercontent.com/23303044/134443586-fc6699d3-4691-4f89-babc-ccc3dc9c67e3.png)

Steps to Reproduce:

1. Normal use
2. Receive the github email pull request prompt, switch back to the gitlens plugin page

**Comment by eamodio** [comment]
Does this still happen with the latest version of VS Code and GitLens? If so, I would recommend opening an issue ont the VS Code repository, as GitLens doesn't actually control the rendering of those view (only the content).
