### ISSUE TITLE
open commit on gitlab, the url schema is https, but my repos hosted on gitlab which self-hosted without https

### ISSUE THREAD

**Issue by jeffery9** [gitkraken/vscode-gitlens#1654]
- GitLens Version:  v11.6.0
- Git Version:   git version 2.30.1 (Apple Git-130)

- VSCode Version:  1.60.2
- OS Version:
mac os  11.5.2
Steps to Reproduce:

1.

**Comment by eamodio** [comment]
@jeffery9 Is this still an issue with the latest version of GitLens (12.1.2)?
