### ISSUE TITLE
Stash pop

### ISSUE THREAD

**Issue by rebeccazee** [gitkraken/vscode-gitlens#1656]
I noticed in the stashes view that there is not an option to pop a stash. I know you could apply the stash and then delete it or drop it right afterwards but this would not make use of the pop feature. Since the pop feature combines applying the stash and deleting the stash afterwards without having to manually do these, it would be easier and a nice addition if this option can be included. I am just saying that it would be nice if this was added and not to get rid of the other options. Sometimes I apply the stash to possibly save it for later and other times I pop the stash using the terminal. If this option can be added, I would appreciate it.

**Comment by eamodio** [comment]
@rebeccazee When you click the apply stash button it will prompt you to choose between apply and pop as below:

![image](https://user-images.githubusercontent.com/641685/147052563-ccc04439-63ec-4e7d-ba37-901f66e454fd.png)

Do you not see that?

But I think it would be a nice feature to be able to <kbd>alt</kbd>+<kbd>click</kbd> the apply icon and have it do a pop instead.
