### ISSUE TITLE
Support VScode for the web

### ISSUE THREAD

**Issue by gglin001** [gitkraken/vscode-gitlens#1657]
Will vscode-gitlens support VScode for the web one day? 

<img width="956" alt="Screen Shot 2021-09-29 at 11 25 59 AM" src="https://user-images.githubusercontent.com/13805221/135198248-69f16391-894a-4d43-834d-f920bd49469d.png">

**Comment by eamodio** [comment]
I am actively working on this.

**Comment by gglin001** [comment]
seems it works now! 👍

**Comment by eamodio** [comment]
Wow, forgot this was still open. This shipped back in March of 2022 😄
