### ISSUE TITLE
Merge Branch into Current Branch dialog is broken or illogical

### ISSUE THREAD

**Issue by donlassini** [gitkraken/vscode-gitlens#1660]
I have a repo, BranchTest, with 2 branches: main and Testbranch.
I have made changes in both branches.

I want to merge the changes from Testbranch into main.
But when I try do do that, I get a dialog that is either faulty or I don't know how to fill out.

- GitLens Version: 11.6.0
- Git Version: 2.33.0.windows.2

- VSCode Version: 1.60.2 7f6ab5485bbc008386c4386d08766667e155244e x64
- OS Version: Windows 10, 21H1, build 19043.1237

Steps to Reproduce:
I open the main branch; I verify that it's selected in the left part of the bottom status bar.
I go to GitLens > Branches > Testbranch.
GitLens shows that "Branch Testbranch is 2 commits behind".
I right click and select Merge Branch into Current Branch.

I get a dialog that says "Confirm merge into branch main"
There's an edit box with the text "Confirm Merge".
There's an option below the box that says
"Cancel Merge. Branch main is up to date with branch Testbranch".
There's also a button with a check mark that says "Will always confirm".

![Dialog](https://user-images.githubusercontent.com/33486910/135527323-4d9d3b7b-6354-4dc6-ae30-a763b0f04151.png)

**Comment by alexwilczewski** [comment]
+1

**Comment by ic-768** [comment]
Don't know if this'll help, but I had this issue when I forgot to `git fetch` before attempting to merge.
After fetching, the dialog gave me the options I was expecting.

**Comment by Golikum** [comment]
Same problem.

**Comment by tobidelbruck** [comment]
Same problem for me, using vscode 1.81.3... confirm merge will just not happen even if I push the little checkbox at top right of confirm dialog

**Comment by jkelroy** [comment]
Hello all, this can happen if your branch is already up to date with the branch you are trying to merge into i.e. in the original screenshot it mentions that main is already up to date with testBranch. As there is nothing to merge, canceling is the only option. We will look into making this flow more clear.

However, if you are seeing a different behavior where the branch is not up to date and merging should be possible, can you please share more information like a video of the behavior?

**Comment by eamodio** [comment]
In tomorrow's pre-release the messaging around this will be a better too

![image](https://github.com/gitkraken/vscode-gitlens/assets/641685/1639c989-ce7d-4aa8-a154-f8e1f0f57a84)
