### ISSUE TITLE
Disable option for rebase interactive editor is not honoured

### ISSUE THREAD

**Issue by richard-swyftx** [gitkraken/vscode-gitlens#1687]
The setting `"git-rebase-todo": "default"` is not honoured

- GitLens Version: 11.6.1
- Git Version: 2.25.1
- VSCode Version: 1.61.0
- OS Version: Linux 5.11.0-37-generic, 20.04.2-Ubuntu

NOTE: _Perform a git rebase interactive_ == terminal/command-line: `git rebase -i origin/dev`

Steps to Reproduce:

Option 1)
1. Perform a git rebase interactive
2. Select the "Disable rebase editor" -> This updates the VSCode settings file (like option 2)
3. Perform a git rebase interactive - Still displays the UI editor, instead of the text editor

Option 2)
1. Edit the VSCode settings file and add:
```
  "workbench.editorAssociations": {
    "git-rebase-todo": "default"
  }
```
2. Perform a git rebase interactive - Still displays the UI editor, instead of the text editor

**Comment by eamodio** [comment]
@richard-swyftx I can't see to reproduce this -- How are you performing a rebase? Directly from the terminal?

**Comment by samlh** [comment]
I was hitting this too - it happens to me when rebasing from the command line, with VS Code not already open.

**Comment by richard-swyftx** [comment]
@samlh happens when I rebase from the command line.

**Comment by gardenvarietyse** [comment]
this started happening for me too recently when I rebase from terminal, for example `git rebase -i HEAD~2`, with interactive editor disabled in settings

vscode is invoked like so:
```
$ echo $EDITOR
/usr/local/bin/code -n -w
```

vscode version: `1.62.1` on macbook pro m1
gitlens: `11.6.1`
git: `2.30.1 (Apple Git-130)`

**Comment by andrewnystrom** [comment]
Same issue for me as well. Happy to help diagnose. 
Visual Studio Code version: Version: 1.62.1
MacOS: 12.0.1
GitLense: v11.6.1

**Comment by rivy** [comment]
Same problem from the Windows command line...

Windows: v10.0.19042.1348
VSC version: 1.62.2 , 3a6960b964327f0e3882ce18fcebd07ed191b316 , x64
GitLens: v11.6.1

And being forced into the UI is breaking some more complex rebase chains.

**Comment by fai814** [comment]
在 2021年11月14日週日 上午1:46，Roy Ivy III ***@***.***> 寫道：

**Comment by medifle** [comment]
Same issue.

macOS@11.6
git@2.33.1
VSCode@1.62.2
GitLens@11.6.1

With a VSC workspace opened and `Interactive Rebase Editor` disabled in `GitLens Settings`, I tried `git rebase -i <commit>` on a feature branch and got the UI editor instead of text editor.

**Comment by eamodio** [comment]
I'm really sorry that a lot of you are experiencing this issue, but unfortunately I can't seem to reproduce it or see how to fix it. VS Code doesn't provide much for extension when registering this type of custom editor (the rebase UI is a custom editor based on the `git-rebase-todo` file). The only way VS Code allows an extension to change the custom editor usage is through the `workbench.editorAssociations` setting.

With the setting set as follows -- the GitLens Interactive Rebase Editor should not be used. At least for when it gets invoked from a terminal -- if you start an interactive rebase from GitLens, via content menu or Git Command Palette, it will still default to the UI.

```json
  "workbench.editorAssociations": {
    "git-rebase-todo": "default"
  }
```

If the setting is missing or there is no entry for `"git-rebase-todo"` or `"git-rebase-todo": "gitlens.rebase"` then the GitLens UI will be used.

Can you all verify that the setting is set appropriately? Thanks for any help you all can provide.

**Comment by eamodio** [comment]
@mjbvz Do you have any ideas on how I could debug this?

**Comment by rivy** [comment]
Cross-post as a bug to [vscode](https://github.com/microsoft/vscode)?

**Comment by PiterGoCompany** [comment]
Same issue:
Windows 11 Pro 21H2 22000.318
Visual Studio Code: 1.62.3
GitLens: 11.7.0
GIT: 2.34.0.windows.1

**Comment by eamodio** [comment]
Cross-posted: https://github.com/microsoft/vscode/issues/137675

**Comment by eamodio** [comment]
It looks like this is a VS Code bug -- can any of you confirm that this only happens when there is no other VS Code window already open?

**Comment by thec0keman** [comment]
This happens to me frequently when there is another VS Code window open.

**Comment by PiterGoCompany** [comment]
@eamodio indeed it happens when there is no other VS Code window.

**Comment by rivy** [comment]
@eamodio , thanks for looking into this and creating an issue on the VSCode repo.

As this breaks my more complicated rebases, I'll have to hold at VSCode v1.59.1 until this is fixed.

**Comment by eamodio** [comment]
I'm really sorry, and am hoping VS Code will fix this very soon. Other than removing the interactive rebase completely, there isn't anything that I know of that GitLens can do to help this (because of the static registration VS Code requires for custom editors).

At the same time, @rivy can you tell me (or file a new issue ideally) to what complicated rebases that the interactive rebase editor breaks?

**Comment by torokati44** [comment]
> Other than removing the interactive rebase completely

I really don't mean to sound entitled or rude, but this is about the third time this feature (which I have never asked for) causes me annoyance and inconvenience, and this will be the third time that I will try really hard to disable it. So, I wouldn't miss it. :/

**Comment by eamodio** [comment]
@torokati44 Believe me I really sympathize and am frustrated by this situation as well. Please up vote and add your feed back to the VS Code bug that is causing this: https://github.com/microsoft/vscode/issues/137675.

I am going to try out a possible workaround (mentioned in that issue), that might avoid the issue, but it's not a great long term solution -- as I really don't like changing user preferences without their input.

**Comment by lramos15** [comment]
This has now been fixed upstream https://github.com/microsoft/vscode/issues/137675. Feel free to test it out in the latest insiders https://code.visualstudio.com/insiders/
