### ISSUE TITLE
[command] Open current branch on remote

### ISSUE THREAD

**Issue by zardoy** [gitkraken/vscode-gitlens#1718]
Using `gitlens.openBranchOnRemote` is cool, but it always showing select, which is annoying for me.

I propose to add `gitlens.openCurrentBranchOnRemote` command for this

**Comment by fai814** [comment]
Fai tai




在 2021年11月12日週五 上午8:24，Vitaly ***@***.***> 寫道：

**Comment by tjx666** [comment]
loving this
