### ISSUE TITLE
File changes do not work with git branch --set-upstream-to=upstream/main <branch>

### ISSUE THREAD

**Issue by jfarrell468** [gitkraken/vscode-gitlens#1728]
- GitLens Version: 11.6.1
- Git Version: 2.34.0.rc1.387
- VSCode Version: 1.61.2
- OS Version: Linux x64 5.10.46 (remote), MacOS 12.0.1 (local)

Steps to Reproduce:

1. Fork repo on github
2. git clone forked repo.
3. git remote add upstream <original repo>
4. git checkout -b <branchname> main
5. --set-upstream-to=upstream/main <branchname>
6. "Toggle File Changes"

Result:

* File annotations icon briefly flashes orange
* Gutter does not display changed lines.

Debug output:

[2021-11-17 17:28:24:603] [/usr/local/google/home/jamesfarrell/llvm-project] git log --format=%x3cr%x3e%x20%H --follow @{push}.. -- llvm/lib/Support/Triple.cpp • FAILED 25 ms 

Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false -c log.showSignature=false log --format=%x3cr%x3e%x20%H --follow @{push}.. -- llvm/lib/Support/Triple.cpp
fatal: cannot resolve 'simple' push to a single destination

(I removed the upstream, and verified that "Toggle File Changes" works)

**Comment by eamodio** [comment]
We believe this issue has been resolved in the latest (or recent) version of GitLens. If you are still experiencing this please let us know and we can re-open the issue or open a new issue if this is already locked.
