### ISSUE TITLE
"gitlens.hovers.detailsMarkdownFormat" edit error

### ISSUE THREAD

**Issue by weqopy** [gitkraken/vscode-gitlens#1735]
- GitLens Version: v11.7.0
- Git Version: git version 2.30.1 (Apple Git-130)

- VSCode Version: Version: 1.62.3
- OS Version: macOS Monterey 12.0.1

Steps to Reproduce:

1. default "gitlens.hovers.detailsMarkdownFormat" setting
`${avatar} &nbsp;__${author}__, ${ago}${' via 'pullRequest} &nbsp; _(${date})_ ${message}${commands}${---footnotes}`
<img width="283" alt="image" src="https://user-images.githubusercontent.com/10494196/144033400-dd5e17e5-f222-4c07-9638-aae73e564f10.png">

2. remove & readd(not reset) one character like `(` in `(${date})`
<img width="271" alt="image" src="https://user-images.githubusercontent.com/10494196/144033481-ee279e38-41f4-4b60-9e1d-cdd754e71938.png">
and this is still showing
<img width="592" alt="image" src="https://user-images.githubusercontent.com/10494196/144033621-d354e646-1471-4579-8092-f9d8148de258.png">

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by weqopy** [comment]
@eamodio GitLens insiders v2021.12.2203 works fine now.
Thanks!
