### ISSUE TITLE
New file lines keep jumping down

### ISSUE THREAD

**Issue by rzhao271** [gitkraken/vscode-gitlens#1742]
Issue Type: <b>Bug</b>

Identified with extension bisect
See https://github.com/microsoft/vscode/issues/138541

Extension version: 2021.12.612
VS Code version: Code - Insiders 1.63.0-insider (d09289a2b6dd0e56b2a264a8e9380685498e10d6, 2021-12-04T02:02:08.723Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 4|
|Memory (System)|16.00GB (8.58GB free)|
|Process Argv|--user-data-dir=udd2 --crash-reporter-id 495f2d6e-8718-4a98-90fb-0942ef10cefe|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
vsaa593cf:30376535
vsc1dst:30396469
vsena315cf:30406436
pythonvs932:30404738
vscop804:30404766
vscop453:30404998
vsclayoutctrc:30405799
py55gd98:30408621
vscexrecpromp3c:30407757

```

</details>

**Comment by kevinneufeld** [comment]
I am experiencing this with the latest release `v12.0.0`.  It is so distracting I disabled Gitlens.

System Info:
macos: Big Sur v11.6.4 on Intel 2.7GHz Quad-Core i7
VSCode: 
```
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:58.347Z (2 wks ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by rzhao271** [comment]
I'm unable to repro the issue now even on Stable. Leaving the verification to @kevinneufeld

**Comment by SuperSecureHuman** [comment]
Yes, this fix works well in the insider's release

https://user-images.githubusercontent.com/88489071/156280631-98c23e73-18ad-4bd2-8c76-3a371f593a9a.mp4


BTW, this was how it was (I opened an issue #1850 


https://user-images.githubusercontent.com/88489071/156280658-6f487791-b9a5-41c1-bee2-747e8d36d00e.mp4

**Comment by SuperSecureHuman** [comment]
Instead of removing it altogether, why not provide info like - `last modified time | untracked file`

Just so that its consistent overall.
