### ISSUE TITLE
autolinks.url encodes hash char 

### ISSUE THREAD

**Issue by xmedeko** [gitkraken/vscode-gitlens#1745]
- GitLens Version: 11.7
- Git Version: 2.33.1
- VSCode Version: 1.62.3
- OS Version: Windows 10

Steps to Reproduce:

I have `gitlens.autolinks.url`  like `https://bugs.company.com#id=<num>`. However, clicking the bug number in commit message opens URL `https://bugs.company.com%23id=<num>`, so it does not work.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by xmedeko** [comment]
Thanks for the quick fix. I'll be on holidays after few hours. I'll try to check it later.

**Comment by xmedeko** [comment]
@eamodio Fix in GitLens Insider works well 👍 thanks!
