### ISSUE TITLE
Line history view gone missing again

### ISSUE THREAD

**Issue by fishpen0** [gitkraken/vscode-gitlens#1748]
#1286 mentions linehistory view going missing
The workaround in the issue is to add `"gitlens.views.lineHistory.enabled": true,` to settings

Adding that to the settings now throws an error stating:
```
Deprecated. This setting is no longer used (2)
```
And line history continues to be missing

**Comment by eamodio** [comment]
Yeah, that setting is no longer required. You can show the view either via the _Show Line History View_ command in the Command Palette or by right-clicking on another GitLens view header and checking the _Line History_ view:
![image](https://user-images.githubusercontent.com/641685/147049033-39e4a08f-747a-4d46-a0f6-b52c56fe5309.png)
