### ISSUE TITLE
env: node: No such file or directory

### ISSUE THREAD

**Issue by jonkelling** [gitkraken/vscode-gitlens#1766]
I use gitlens on a daily basis. Today, all of a sudden, unable to commit. I get an error, and when I click "Show Command Output", I see the following message:

```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
env: node: No such file or directory
husky - pre-commit hook exited with code 127 (error)
```

**Comment by eamodio** [comment]
Hi, sorry for the inconvenience, but this issue is with VS Code, not GitLens. GitLens doesn't provide commit support, that's provided by VS Code directly. Can you please open this issue on the VS Code repository? Thanks!
