### ISSUE TITLE
Line annotations seem to be overlapping with modified text in Inline View for diffs

### ISSUE THREAD

**Issue by macintacos** [gitkraken/vscode-gitlens#1775]
- GitLens Version: 11.7.0
- Git Version: 2.33.1

- VSCode Version:
1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
x64
- OS Version: macOS 11.6.2

Steps to Reproduce:

1. Open a diff in Inline View mode (click three dots top right, click "Inline View"), where the line that is being diff'd has a text annotation. You'll see something like the following:

![CleanShot Visual Studio Code 2022-01-18 at 23 42 43](https://user-images.githubusercontent.com/8128941/150065662-06d31fe3-3ed6-403f-9ccd-4621c7967353.png)

The above is Go code, if that matters. From the screenshots, it seems like there's a gap above the red line where the annotations would "traditionally" go, but they're blank. When I turn off Inline View and go back to side-by-side, the problem goes away:

![CleanShot Visual Studio Code 2022-01-18 at 23 29 35](https://user-images.githubusercontent.com/8128941/150065373-1c658701-11b6-4b6f-915c-6261eefd6238.png)

I'm honestly not sure if the "Inline View" is a VSCode feature or some other extension, however the issue goes away when I don't use GitLens (because it doesn't add the annotations). I'm honestly not sure where to open this issue (VSCode? This extension? Somewhere else?) but I figured I would open it here and if the maintainer says that this is something they have no control over, I'm happy to open this issue elsewhere.

**Comment by eamodio** [comment]
If this is still happening this is unfortunately a bug in VS Code itself. Can you please [open an issue](https://github.com/microsoft/vscode/issues/new?assignees=&labels=&template=bug_report.md) on the VS Code repository? Thanks!
