### ISSUE TITLE
copy/open remote url always points to https:// (also for repos at http://) 

### ISSUE THREAD

**Issue by ghuber-github** [gitkraken/vscode-gitlens#1778]
I work on an internal repo that is located at a `http://` address. However, copying or opening a remote url always points to `https://` (the rest of the url is correct).
This includes (at least) the following functionality
- from the "Remotes" tab in the "Source Control" panel
  - `open repository on remote`
  - `copy remote repository url`
- right mouse click in a file 
  - `copy remote file url`
  - `copy remote file url from`
  - `copy remote commit url`

This problem exists independent of the remote url protocol, i.e. for `ssh` as well as `http`

**Comment by jsangmeister** [comment]
For anyone stumbling here, the solution is to add the following entry to your `settings.json`:
```
"gitlens.remotes": [
    {
        "domain": "prefix.example.com", // domain without protocol
        "type": "GitLab", // your git provider
        "protocol": "http",
    }
]
```
