### ISSUE TITLE
Remove '-review' from Gerrit Remote reviewDomain()

### ISSUE THREAD

**Issue by Levistator** [gitkraken/vscode-gitlens#1787]
Please remove the addition of '-review' to the subdomain portion of the get reviewDomain() function.

It is potentially breaking for Gerrit installations that are at `gerrit.example.com` instead of `gerrit-review.example.com`

This should either be a configurable option or not assumed at all.

**Comment by adambadura** [comment]
I have exactly this issue. Or even worse I think... We have `gerrit-wrsl1.int.net.nokia.com` host and for the `Change-Id:` link it is changed to `gerrit-wrsl1-review.int.net`. Not only `-review` is added to the first component, which should not (in our setup) but also `.nokia.com` suffix is somehow dropped.

**Comment by felipecrs** [comment]
https://github.com/gitkraken/vscode-gitlens/pull/1954 aims to solve this issue.
