### ISSUE TITLE
Add support for emojis in interactive rebase editor

### ISSUE THREAD

**Issue by albinpk** [gitkraken/vscode-gitlens#1789]
- GitLens Version: **v11.7.0**
- Git Version: **2.34.1**

- VSCode Version: **1.63.2**
- OS Version: **5.10.89-1-MANJARO**

---

### Commits view
![gitlense-commits-view](https://user-images.githubusercontent.com/56157868/151653858-d7ed6c56-2960-4cb0-bae3-673d66a6ec45.png)

### Interactive rebase
![gitlense-rebase](https://user-images.githubusercontent.com/56157868/151653791-0689979b-333b-453a-b442-934ee39f1ebf.png)

**Comment by scruel** [comment]
Like this https://github.com/zielu/GitToolBox
Please add this function for a completion for inputting the emoji text.
THX!
