### ISSUE TITLE
[File Watcher (parcel)] ignoring a path for watching who's parent is already watched

### ISSUE THREAD

**Issue by tjx666** [gitkraken/vscode-gitlens#1804]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/152850974-881eb92d-c387-4925-983e-17ba2a5f0629.png">

- GitLens Version: insider v2022.2.712
- Git Version: 2.35.1

- VSCode Version: 1.65.0-insider
- OS Version: MacOS 12.2

Steps to Reproduce:

1. clone https://github.com/tjx666/study-rust
2. open workspace in VSCode
3. open devtools to see the warnings

**Comment by eamodio** [comment]
@bpasero are these logs expected?

**Comment by bpasero** [comment]
Is `files.watcherInclude` configured?

**Comment by tjx666** [comment]
No.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/153910676-2e763283-db10-4968-b14d-908cd4e2c3f5.png">
