### ISSUE TITLE
Ambiguous error message on GitHub authentication errors

### ISSUE THREAD

**Issue by joyceerhl** [gitkraken/vscode-gitlens#1818]
- GitLens Version: latest Insiders
- Git Version: Run `git --version`

- VSCode Version: 1.65.0-insider
- OS Version: Windows 11

Steps to Reproduce:

1. In vscode.dev/github or github.dev with GitLens Insiders installed, open a GitHub repo
2. Open a file within a workspace (at least IIRC that's all I did)
3. Get this error message: ![image](https://user-images.githubusercontent.com/30305945/153644720-79b81d45-a530-4d0b-a55c-b9968eca9692.png)

**Comment by joyceerhl** [comment]
Seeing more errors like this when reentering an existing workspace: 
![image](https://user-images.githubusercontent.com/30305945/153912330-d31192c9-c543-4fdb-907f-106999f5b7d6.png)

**Comment by eamodio** [comment]
I believe that 2nd issue is GitHub just giving up on returning the blame on a large-ish file. And it's a bogus error result
