### ISSUE TITLE
Reduce re-rendering by disabling animation in blame info in the status bar

### ISSUE THREAD

**Issue by gdh1995** [gitkraken/vscode-gitlens#1829]
#### Currently behavior

1. Currently Gitlens shows blame information in the status bar (controlled by `gitlens.statusBar.*`)
2. When I move caret to another line, it will update the blame information
3. When `gitlens.statusBar.reduceFlicker` is `true` by default, there's a "turning circle" before blame info before new info gets loaded

#### What I want

I want (a new setting item) to replace the circle animation with:
- either a "static icon" which means "updating"
- or keep the icon unchanged, and switch to another icon on further errors or timeout events

#### The benefits of this feature

Firstly, this means: further reduce flickers; easier to read; not attract attention in any sense.

Secondly, a static icon will save computer power a lot: during my tests using `Developer Tools -> Render -> Paint flashing`,
1. with the turning circle, moveing caret causes to render many UI parts
- 1. if a VS Code window is small, then many left icons flash
![with-turning-circle](https://user-images.githubusercontent.com/5547703/155251685-fa0e8865-148f-43e9-9c4e-476b2c39abf8.gif)
- 2. if a window is large, then there're a strange full-area rendering, like:
![large-window-with-turning-circle](https://user-images.githubusercontent.com/5547703/155253039-6a3cc2e6-bba8-48c6-9eda-8e8fe35a21df.gif)
2. when `reduceFlicker=false`, there's no turning circle, and then
![without-circle](https://user-images.githubusercontent.com/5547703/155253119-9d20ad7a-f1f2-419b-a4a8-0ccbab96c58c.gif)

**Comment by eamodio** [comment]
I've changed this from a spinner to just a `watch` icon to reduce the visual noise. FYI, in the current insiders version of VS Code the re-rendering issue you are seeing above seems to be resolved whether a spinning icon is used or not.
