### ISSUE TITLE
Login with an account pending to be verified and log out, leaves commands in an undefined state

### ISSUE THREAD

**Issue by joseleon-axosoft** [gitkraken/vscode-gitlens#1833]
- GitLens Version: Insiders 2022.2.2417
- VSCode Version: vscode.dev
- OS Version: Chrome

Steps to Reproduce:

1. See attached gif
2. If you log in with an account that is pending to be verified, it works OK
3. Once you log out, you cannot execute the sign in command again
4. You need to reload the window in order to be able to log in again
5. This does NOT happen if the account is verified, you can sign out and log in again without any issue

![gitlens_issue_2](https://user-images.githubusercontent.com/90340232/155694675-b557ab79-13ff-406a-8b3e-db0446874a4c.gif)

**Comment by eamodio** [comment]
@joseleon-axosoft Can you try again with today's version? I think this should be resolved.
