### ISSUE TITLE
Incorrect wording and CTA on the status item

### ISSUE THREAD

**Issue by joseleon-axosoft** [gitkraken/vscode-gitlens#1835]
- GitLens Version: 2022.2.2147
- VSCode Version: vscode.dev
- OS Version: Chrome

Steps to Reproduce:

1. See attached gif
2. Sign in with an unverified account
3. Mouse over the status item
4. You get a message with instructions to verify your account
5. It includes a "Click for details", which is not clear where the user needs to click

![gitlens_issue_3](https://user-images.githubusercontent.com/90340232/155699794-61f5eab1-418d-4a93-bb90-b5f22b76205e.gif)

**Comment by eamodio** [comment]
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/1832 -- since it should be opening the side bar
