### ISSUE TITLE
The GitHub.com account provider is used for GitHub Enterprise remotes

### ISSUE THREAD

**Issue by kamaln7** [gitkraken/vscode-gitlens#1845]
- GitLens Version:`12.0.0` and `11.7.0`
- Git Version: git version 2.34.1
- VSCode Version: 1.64.2
- OS Version: Darwin x64 21.2.0

**Steps to Reproduce:**

1. Open a github.com repo and log in to your GitHub account
2. Add your GitHub Enterprise instance to the `gitlens.remotes` setting
3. Open a GitHub Enterprise repo 
4. GitLens will try to use the GitHub.com token to authenticate and fail to enable any rich integrations due to this
5. GitLens will pop up a notification saying `Error: Your 'github' credentials are either invalid or expired` 

**✨ Steps to Fix:**

I went down a rabbit hole trying to figure out what this wasn't working but I found the cause:

https://github.com/gitkraken/vscode-gitlens/blob/6387420080211d3a1d6c6340ddbc1f43eaa7fe33/src/git/remotes/github.ts#L20

which is used here:

https://github.com/gitkraken/vscode-gitlens/blob/0f0a1d62e8e1b59ffc3b50ef50fafc3f014013db/src/git/remotes/provider.ts#L583-L586

The `id` being set to `github` makes VSCode's auth provider return the github.com token.

```diff
-const authProvider = Object.freeze({ id: 'github', scopes: ['repo', 'read:user', 'user:email'] });
+const authProvider = Object.freeze({ id: 'github-enterprise', scopes: ['repo', 'read:user', 'user:email'] });
```

After making this change and reloading, VSCode prompted me for my GitHub Enterprise token and then GitLens was able to issue API requests (e.g. showing a PR that is associated with a commit).

I would've submitted a PR but the real fix obviously isn't to hardcode `github-enterprise` 😛

**Comment by eamodio** [comment]
This should be resolved in GitLens 12.2 or later. Please let me know if this is still an issue.
