### ISSUE TITLE
CodeLens buggy when trying to edit new file with 'File Scope' option turned on

### ISSUE THREAD

**Issue by SuperSecureHuman** [gitkraken/vscode-gitlens#1850]
- GitLens Version:v12.0.0
- Git Version: 2.35.1

- VSCode Version: 1.64.2
- OS Version: Arch Linux

Steps to Reproduce:

1. Enable File Scope in CodeLens

![image](https://user-images.githubusercontent.com/88489071/156122946-5f84317c-0437-4fe0-9373-c0b6c37ec7a4.png)

2. Create a new file in a existing project.

3. Try to edit it. You will notice this buggy, line moving thing. IDK how to describe it properly. Check the below video

https://user-images.githubusercontent.com/88489071/156123111-2df8bf75-c346-4e64-90b8-bde8822346a3.mp4

4. Here, you can see when I add anything to the file (its a brand new file BTW) it tries to do the CodeSnap thing (the 3 dots) and goes away. This thing is disturbing cause no one wants jumping lines :rofl: 

Update - This dosent happen after staging that file. After staged, its consistent like this

![image](https://user-images.githubusercontent.com/88489071/156123800-a3ee414d-4c9b-4f49-a13d-afad208ff501.png)

Thanks!

**Comment by daniel-stoneuk** [comment]
Seems like this is fixed following #1742

**Comment by SuperSecureHuman** [comment]
Yes, the fix works in the insider's build of gitlens.

I'll close this issue.

If I face any more issues related to this, I'll put them on #1742 (or make a new issue, based on the issue).


Thanks!
