### ISSUE TITLE
After todays update, extensions shows all my repos have the same name

### ISSUE THREAD

**Issue by pentago** [gitkraken/vscode-gitlens#1854]
Just updated the extension and found this in my repository/remotes views:

![GitLens](https://i.imgur.com/eQpfe2f.png)

How do I restore my repository names as `aux` is the name od directory where all these repositories are at?

**Comment by eamodio** [comment]
So sorry for this issue. I've just kicked off a new insiders build which should be available with the fix in the next ~5m or so.

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by pentago** [comment]
Thanks for the update @eamodio though it can still be better.

Not sure why the directory name where repos are stored has to be mentioned in the repo name, why not just repo name, without the directory?

This is how it looks for me now:

![screenshot](https://i.imgur.com/sJssOTT.png)

For example, instead of being listed as `aux (base-php-image)`, can it be simply `base-php-image`?

The same is for all other views and it kinda sucks.

This is how the default Source Control view looks (_this is what I'm after_):

![screenshot](https://i.imgur.com/axQwDRT.png)

**Comment by eamodio** [comment]
@pentago I agree but was hesitant to change the existing behavior from GitLens 11.7. How do others feel about changing it as suggested?

**Comment by pentago** [comment]
I think the best way to check is to make this change I suggested and wait to see if someone gets bothered enough to open an issue. Even then, this view setting could be an optional configuration perhaps?

Would that work?

**Comment by pentago** [comment]
Amazing, thanks!

**Comment by pedaars** [comment]
Thanks for the quick fix

**Comment by Skyline124** [comment]
Awesome thank you so much for the lightning-quick fix @eamodio ! <3
