### ISSUE TITLE
GitLens dates use system locale instead of vscode language setting

### ISSUE THREAD

**Issue by ImRodry** [gitkraken/vscode-gitlens#1859]
- GitLens Version: 12.0.0
- Git Version: 2.35.1.windows.2

- VSCode Version: 1.64.2 f80445acd5a3dadef24aa209168452a3d97cc326 x64
- OS Version: Windows 11 version 21H1 OS build 22000.527

Steps to Reproduce:

1. Set your system date locale to something different from your vscode language. On Windows you can do this by going to the Control Panel - Clock and Region - Region - Format and pick a country from the ones in the dropdown
2. Enable a setting that shows when something happened (using the $ago variable). I'll be using "Current line blame" for this example
3. Go to a line of code in your git project and observe the language the $ago variable is using:
![image](https://user-images.githubusercontent.com/38259440/156168098-8704d064-cbfe-464f-b43c-e7a4ed41c4a7.png)

**Comment by eamodio** [comment]
I'm adding a new `gitlens.defaultLocale` setting to control this and it will be in the insiders version shortly.
@ImRodry I'm not aware of a VS Code language -- what setting controls that?

**Comment by ImRodry** [comment]
> @ImRodry I'm not aware of a VS Code language -- what setting controls that?

@eamodio VS Code lets you pick the locale through a command. You can read more about that here: https://code.visualstudio.com/docs/getstarted/locales

**Comment by eamodio** [comment]
Ugh, I knew that too -- sorry :( Will look add an option to follow that too.

**Comment by ImRodry** [comment]
@eamodio instead of a new option you can just default that option you added to the current vscode locale IMO
