### ISSUE TITLE
VSCode View with settings.json

### ISSUE THREAD

**Issue by KodaCHC** [gitkraken/vscode-gitlens#1861]
I would like to have a way to store the look of VSCode for GitLens in settings.json so that I can also synchronize the look of GitLens.

What I would like to see here above all:

- Hide Icon in Activity Bar (Since the new version I have the GitLens Icon only for the Premium informations - I Use default source control layout)
- Disable/Hide Items in the side bar (example Worktrees)

**Comment by eamodio** [comment]
This has been resolved in the latest GitLens insiders edition (should be coming to GitLens stable soon). I added a new `gitlens.premiumFeatures.enabled` setting to control those views.

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by KodaCHC** [comment]
Thank you. I will try. 

Have you a solution for the second part too?

**Comment by eamodio** [comment]
What 2nd part?

**Comment by KodaCHC** [comment]
> What 2nd part?

This :)
Disable/Hide Items in the side bar (example Worktrees)

**Comment by eamodio** [comment]
That setting hides all premium features (so all premium views, etc)

**Comment by KodaCHC** [comment]
My goal would be to personalize the sidebar more. I can already hide every menu item in the sidebar of GitLens, but not in the settings.json so it doesn't sync.
<img width="300" alt="Screenshot 2022-03-02 175813" src="https://user-images.githubusercontent.com/61413942/156410170-bd4914ab-bcb2-48ef-b6fa-8cd8291e6451.png">
.
