### ISSUE TITLE
Hanging in SSH scenarios

### ISSUE THREAD

**Issue by tanhakabir** [gitkraken/vscode-gitlens#1878]
https://github.com/microsoft/vscode-remote-release/issues/6399#issuecomment-1057455645

cc @nntantidakis for more details

**Comment by eamodio** [comment]
The GK Auth extension has been removed as a dependency, so hopefully this is resolved. Please re-open if not.

**Comment by tanhakabir** [comment]
@eamodio fyi: https://github.com/microsoft/vscode-remote-release/issues/6399#issuecomment-1058536665

**Comment by eamodio** [comment]
@tanhakabir Do you have any more details on this?
