### ISSUE TITLE
I have to roll back GitLens to version 11.7.0 to uninstall this ext.

### ISSUE THREAD

**Issue by rise-worlds** [gitkraken/vscode-gitlens#1879]
fuck `GitKraken Authentication` in GitLens !

**Comment by eamodio** [comment]
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/1853

**Comment by rise-worlds** [comment]
I think you're doing the dirty work. You thought GitKraken was beautiful.

**Comment by eamodio** [comment]
Not sure I understand. What do you mean?
