### ISSUE TITLE
Add compact file-only view when comparing in Search & Compare

### ISSUE THREAD

**Issue by letmaik** [gitkraken/vscode-gitlens#1884]
This is what it looks like currently:

<img src="https://user-images.githubusercontent.com/530988/156650881-223a90be-fe74-49db-a8ed-bf748485247f.png" width=200>

I'm rarely interested in specific commits or the count of files that changed. I'd prefer a more compact style like that:

<img src="https://user-images.githubusercontent.com/530988/156651277-d048d746-34e9-4147-901a-8a20e31ce723.png" width=200>

Is this something that makes sense as an option?

**Comment by eamodio** [comment]
This has been implemented: See the files mode for many views:

![image](https://github.com/gitkraken/vscode-gitlens/assets/641685/1ef85381-bac9-4ce1-8376-b754e06afa3f)
