### ISSUE TITLE
Set the author to the local .git/config of the directory and not the global gitconfig of the system

### ISSUE THREAD

**Issue by OdinsHat** [gitkraken/vscode-gitlens#1885]
At the moment when making a commit in Gitlens it will assign the author from the global gitconfig. Rather than reading the local `.git/config` user details and using those.

It would make more sense to use the local `.git/config` rather than the global gitconfig.

Or provide the choice?

It seem's a similar idea was mentioned in close issue [#341](https://github.com/gitkraken/vscode-gitlens/issues/341)

**Comment by eamodio** [comment]
GitLens doesn't offer commit actions -- committing is performed via the built-in Git support in VS Code. I would recommend opening an issue there. Sorry.
