### ISSUE TITLE
Error: "https://api.github.com/graphql failed, reason: self signed certificate in certificate chain"

### ISSUE THREAD

**Issue by runfaj** [gitkraken/vscode-gitlens#1886]
I'm getting that error several times anytime a new file is opened or switched to in the editor. The output logs say

<img width="844" alt="image" src="https://user-images.githubusercontent.com/3292053/156804562-4a13c41e-b3e2-4a5f-9717-9dbbbc8333f9.png">

It appears that no functionality is affected for the extension, but the errors that pop up constantly (literally every file) makes the usage of the entire extension tough to justify.

- GitLens Version: 12.0.1
- Git Version: 2.33.0
- VSCode Version: 1.65.0
- OS Version: macos 12.2.1

Steps to Reproduce:

I'm not sure. We recently switched some IT processes which included installing windows defender on a mac, but it doesn't have seem to affected anything across all the day-to-day. Typically for other extensions, an additional config is needed to remove this error. Something like:
```
"vscode-graphql.rejectUnauthorized": false
```
or
```
"gitlab.ignoreCertificateErrors": true
```

**Comment by eamodio** [comment]
I've added proxy support now, so by default GitLens will honor/follow the VS Code proxy settings (`http.proxy` & `http.proxyStrictSSL`) or fallback to the OS configuration. You can also override the proxy behavior using the new `gitlens.proxy` setting:

```json
{
  "gitlens.proxy": {
    "url": string,
    "strictSSL": boolean,
  }
}
```

So specifically for this cert error issue, you can set `http.proxyStrictSSL` to `false` for VS Code & any extensions that honor that settings, or specifically for GitLens:

```json
{
  "gitlens.proxy": {
    "strictSSL": false
  }
}
```

Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by runfaj** [comment]
@eamodio Looks to be working! Thanks!!

**Comment by eamodio** [comment]
Thanks you!
