### ISSUE TITLE
Gitlens breaks vscode auto repository detection settings

### ISSUE THREAD

**Issue by sinbino** [gitkraken/vscode-gitlens#1888]
- GitLens Version: v12.0.1
- Git Version: git version 2.25.1

- VSCode Version: 1.65.0 b5205cc8eb4fbaa726835538cd82372cc0222d43 x64
- OS Version: Ubuntu 20.04

Steps to Reproduce:
I set the "Git: Auto Repository Detection" setting in vscode to "subFolders".
This setting does not add git repositories outside of the folder open in vscode to source control.
Gitlens breaks this behavior. (It adds the external git repository to the source control.)

**Comment by sinbino** [comment]
This problem does not occur in versions 11.7.0 and earlier; it was added in gitlens version 12.0.0.

**Comment by eamodio** [comment]
@sinbino Thanks for the report and sorry for the trouble. I will be working on this ASAP.
