### ISSUE TITLE
can no longer see untracked files in stashes

### ISSUE THREAD

**Issue by waveforms** [gitkraken/vscode-gitlens#1890]
### Discussed in https://github.com/gitkraken/vscode-gitlens/discussions/1889

<div type='discussions-op-text'>

<sup>Originally posted by **waveforms** March  4, 2022</sup>
Using VScode version 1.65.0 and the latest git lens that shipped this week, I can no longer see untracked files in my stashes. I used this feature heavily before, often creating new files and stashing them if I had to switch away. Now when I go back to my stash list I cannot tell which stash has the new untracked files.  I have set showIncludeUntracked in my local git config file to be true but still cannot see them. Is this a bug or is there a setting in git lens I should adjust? Unfortunately I lost a couple of days work on this but I did manage to learn a lot more about the git.
Thanks for this useful extension. Anybody else having this issue?

VScode:
Version: 1.65.0
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T11:11:20.886Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.3.0</div>

**Comment by eamodio** [comment]
Sorry for the regression, this should now be fixed. Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by waveforms** [comment]
Confirmed. I can see the untracked files using GitLens Insiders, Thanks for the prompt fix!

**Comment by eamodio** [comment]
Thank you!
