### ISSUE TITLE
GitLens should not set itself as my git mergetool without asking

### ISSUE THREAD

**Issue by anentropic** [gitkraken/vscode-gitlens#1894]
- GitLens Version: `v12.0.1`
- Git Version: `git version 2.34.0`

- VSCode Version: ```code --version
1.65.0
b5205cc8eb4fbaa726835538cd82372cc0222d43
arm64```
- OS Version: macos 12.2.1

Steps to Reproduce:

1. manually configure your git mergetool e.g. https://www.sublimemerge.com/docs/command_line
2. install GitLens in VS Code
3. from the cli, do a merge with conflicts, then `git mergetool`
4. VS Code opens to the GitLens interface, instead of the tool I had previously configured for myself

**Comment by eamodio** [comment]
@anentropic GitLens does not set itself as a git `mergetool` or override any other git configuration. Can you show the behavior you are seeing?

**Comment by anentropic** [comment]
AFAICT, installing GitLens in VS Code set VS Code as my git mergetool

**Comment by eamodio** [comment]
@anentropic GitLens doesn't have any code to change ANY git config settings. Why do you think it was GitLens?

**Comment by anentropic** [comment]
just from a coincidence in time, I had recently installed GitLens and had not taken any deliberate action myself to install VS Code as my mergetool, but there it was

ok no worries, sorry to bother you :)
