### ISSUE TITLE
Repeated GitHub errors when offline

### ISSUE THREAD

**Issue by srl295** [gitkraken/vscode-gitlens#1897]
#152 asked: "How far can I go without an internet connect?" Answer is _not very far_.  GitLens is great, BUT this is a bug.

- GitLens Version: v12.0.2 
- Git Version: git version 2.32.0

- VSCode Version:
1.66.0-insider
e80a0ca648fe9bef07070e4f7fb04e67f2243252
x64

- OS Version:
macos monterey 12.2.1 (21D62)

Steps to Reproduce:

1. Fire up VSCode
2. Click on source lines
3. Get lots of annoying popups

Instead, just work with data you have, maybe show a broken symbol in the status bar or on popups.   

￼I have to include this screenshot, with the irony of an "unobtrusive" feature…

![BUGS- GitLens](https://user-images.githubusercontent.com/855219/157512506-567158a5-175a-4cfa-8233-46251bee63dd.jpeg)

**Comment by eamodio** [comment]
Sorry for the trouble on this one, I got overzealous on displaying errors 😢. These should be completely silenced now.
