### ISSUE TITLE
Support replacing mirror/replica domain with main domain for remote provider

### ISSUE THREAD

**Issue by adambadura** [gitkraken/vscode-gitlens#1902]
In our setup with Gerrit (however, I believe this may apply to other types as well) there is one main domain and many local replicas. The replicas are used for fetching, the main one is used for pushing and other Gerrit operations (including REST API, review query, etc.)

It seems however GitLens doesn't support such an approach. Instead, it keeps using the fetch remote to form the `Gerrit Id:` links. Moreover, due to issue #1787 even the mirror domain is broken.

**Comment by felipecrs** [comment]
https://github.com/gitkraken/vscode-gitlens/pull/1954 aims to solve this issue.

**Comment by adambadura** [comment]
To complete the analysis from #1954, with the setup of the main server and mirrors GitLens configuration should mention only the main server - the one used for pushing.
