### ISSUE TITLE
Lots of problems since v12 update

### ISSUE THREAD

**Issue by jbeckton** [gitkraken/vscode-gitlens#1906]
VS Code & Git integration now useless since GitLens v12 installed. First my SSH Remote to our BitBucket server stopped working so I switched to HTTPS. I can only do push/pull/fetch commands with success from the command line. My remotes pane never updates and shows the branches available on the remote repo. So therefor when I use VS Code UI to for example pull my develop branch I cannot complete the command because there are no branches available on the remote.

I have had to resort to using another Git UI app in order to talk to my repos. I am not seeing any errors, I have Git debug enabled. The extension simply does not work. 

Extension version: 12.0.4
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

Steps to Reproduce:

1. Update to GitLens v12

**Comment by eamodio** [comment]
@jbeckton Really sorry for the trouble you are seeing.

Can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the both _GitLens_ and _GitLens (Git)_ channels.

It would be great to know if you can still reproduce this in the GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). 

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by DanieleMar** [comment]
> [2022-03-15 11:10:34.781] [renderer1] [error] Non è possibile leggere il file 'gitlens://privateInfo/c:/Users/Daniele/source/repos/projectFolder/.vscode/launch.json?{"path":"/c:/Users/Daniele/source/repos/projectFolder","ref":"privateInfo","repoPath":"c:/Users/Daniele/source/repos/projectFolder"}' (SyntaxError: Unexpected end of JSON input): Error: Non è possibile leggere il file 'gitlens://privateInfo/c:/Users/Daniele/source/repos/projectFolder/.vscode/launch.json?{"path":"/c:/Users/Daniele/source/repos/projectFolder","ref":"privateInfo","repoPath":"c:/Users/Daniele/source/repos/projectFolder"}' (SyntaxError: Unexpected end of JSON input)

**Comment by DanieleMar** [comment]
also in insider edition

**Comment by jbeckton** [comment]
@eamodio Thanks for the help but I have decided that I don't have any more time to spend on this problem, I have been dealing with this for about 2 weeks now. I'll just disable GitLens and switch back to Tower Git client.

**Comment by eamodio** [comment]
@jbeckton sorry you feel that way and for the trouble this has caused you.

@DanieleMar Can you please open a new issue with specific details of what you issue you are experiencing. Thanks!

**Comment by jbeckton** [comment]
I am going to install GitKraken trial and see if I can manage to get GitLens working too.

**Comment by jbeckton** [comment]
@eamodio  Installed GitKraken, set it up to talk to my Bibucket repo, created a new branch named 'testing', made a simple change to a README file, commited, and when I push I get this error.

Stage Readme.md for commit: started.[13:20:17] Stage Readme.md for commit: finished.1.408s[13:20:33] Commit: started.[13:20:34] Commit: successfully created commit 3144de16f71ef00e143ad1a241f47cc004d39441[13:20:34] Commit: finished679ms[13:20:43] Push testing: started.[13:20:50] Set upstream for refs/heads/testing: started.[13:20:51] Set upstream for refs/heads/testing: finished.530ms[13:20:51] Push testing: Cannot read property 'fullName' of undefined[13:20:51] Push testing: finished with errors.7.56s[13:21:08] Push testing: started.[13:21:17] Set upstream for refs/heads/testing: started.[13:21:17] Set upstream for refs/heads/testing: finished.245ms[13:21:17] Push testing: Cannot read property 'fullName' of undefined[13:21:17] Push testing: finished with errors.

**Comment by jbeckton** [comment]
@eamodio I was able to push a new branch via the GitKraken command line but when using the UI ( right click on branch and select push from context menu ) I get the toast message " Cannot read property 'fullName' of undefined"

**Comment by DanieleMar** [comment]
> @jbeckton sorry you feel that way and for the trouble this has caused you.
> 
> @DanieleMar Can you please open a new issue with specific details of what you issue you are experiencing. Thanks!

Now it works

**Comment by eamodio** [comment]
@jbeckton Very glad to hear that things are resolved. I've reported the issue you ran into and while it looks like a "known issue" (https://support.gitkraken.com/known-issues/common-errors/#error-when-pushing-a-branch) we are going to look more into it.

FYI, for GK Client issues its best to report them here: https://www.gitkraken.com/gitkraken-pro-support
