### ISSUE TITLE
GitLens is asking me to sign into GitLens+

### ISSUE THREAD

**Issue by surferjeff** [gitkraken/vscode-gitlens#1907]
I've been using GitLens with vscode for at least a year.

Today, it's asking me to sign into GitLens+

![image](https://user-images.githubusercontent.com/3111162/158276849-e09eaf5d-bd86-4819-bf07-68e978029e74.png)

I don't want to sign in.  How do I dismiss this screen and use the basic features of GitLens?

**Comment by surferjeff** [comment]
I clicked on the wrong tool.

**Comment by dantenol** [comment]
How did you get through this screen?

**Comment by surferjeff** [comment]
I didn't get through it.  I got around it.  I clicked on the other branch-looking icon in the side bar, and all gitlens's features are there:

![image](https://user-images.githubusercontent.com/3111162/159591227-d40eaced-6f2d-4e4e-9cae-1d494530bf62.png)

**Comment by eamodio** [comment]
Yeah, to be clear there isn't anything to "get around" -- by default GitLens views are added into the Source Control side bar. Currently the GitLens side bar isn't used for anything other than the Welcome and GitLens+ introduction/status (and we are working on better ways to make that more clear). In the future, the GitLens side bar will also be the home for other GitLens views that aren't explicitly SCM related (a teams view, etc).
