### ISSUE TITLE
Unable to get absolute uri between ex.txt and z:; Base path 'z:' must be an absolute path

### ISSUE THREAD

**Issue by rasa** [gitkraken/vscode-gitlens#1928]
In Windows, if I edit the file ex.txt in the root of a mapped network drive, say `Z:\`, I get this error:

```
Unable to get absolute uri between ex.txt and z:; Base path 'z:' must be an absolute path
```
This is because this code:
https://github.com/gitkraken/vscode-gitlens/blob/8d8ba961ccf32064bafd60b3e6c5847bb2d59fa7/src/system/path.ts#L169-L171
is removing the trashing slash. This works for all paths except for paths in the root folder, where the trailing slash should remain. This could be fixed via:
```typescript
if (path.charCodeAt(path.length - 1) === slash) { 
  // Don't remove the trailing slash on Windows root folders, such as z:\
  if (path.length != 3 || (path.length == 3 && path.charCodeAt(1)  != ':')) {
    path = path.slice(0, -1); 
  }
} 
```

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.
