### ISSUE TITLE
Pull request autolink doesn't work for Bitbucket Server 7

### ISSUE THREAD

**Issue by smartinio** [gitkraken/vscode-gitlens#1932]
The default merge commit message casing of "pull request" was changed to "Pull request" in Bitbucket Server 7. Therefore, the autolink no longer works.

- GitLens Version: 12.0.5
- Git Version:  2.32.0
- VSCode Version: 1.65.2
- OS Version: macOS Monterey 12.3

Steps to Reproduce:
1. Hover a line that was committed via a pull request in Bitbucket Server < 7
2. The part "pull request #<num>" is clickable
3. Hover a line that was committed via a pull request in Bitbucket Server >= 7
3. The part "Pull request #<num>" is not clickable

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by smartinio** [comment]
> Can you please verify this fix in tomorrow's GitLens insiders edition?
> 
> You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).
> 
> Please be sure to disable or uninstall the stable version of GitLens first.

Will do 👍

**Comment by smartinio** [comment]
@eamodio Tested insider. Works! The link leads to the correct PR as well.
<img width="260" alt="Screenshot 2022-04-02 at 12 42 33" src="https://user-images.githubusercontent.com/26303911/161379587-035f5f83-4b69-47b5-9250-5abbcd0eb61f.png">
