### ISSUE TITLE
"in the morning" date format

### ISSUE THREAD

**Issue by endquote** [gitkraken/vscode-gitlens#1959]
- GitLens Version: 12.0.5
- Git Version: 2.35.1
- VSCode Version: 1.66.1 / 8dfae7a5cd50421d10cd99cb873990460525a898 / x64
- OS Version: macOS 12.3.1

Steps to Reproduce:

Just a very weird date format. The meridiem (AM/PM) portion of the date is displayed like "in the morning" for AM.

Not only is this a long and strange date format, there's no space before this string.

Setting a different value for `gitlens.defaultDateFormat` and `gitlens.defaultDateShortFormat` like `MMM Do, YYYY H:ma` has no effect.

For me, this issue appears on any file across multiple computers.

![Screen Shot 2022-04-09 at 7 53 24 AM](https://user-images.githubusercontent.com/330010/162579469-77a788a5-7412-4b55-8e2f-9a2f045a6745.png)

**Comment by n-thumann** [comment]
I experience the same issue, however setting `gitlens.defaultDateFormat` to `MMMM Do, YYYY h:mm a` (notice the space before the `a`) resolves the issue for me :v:
Before:
![default time formatting](https://user-images.githubusercontent.com/46975855/162637037-ca08d971-e3b1-4270-90b8-b89979271304.png)
After:
![with space in formatting](https://user-images.githubusercontent.com/46975855/162637035-6312fadd-c3e0-4584-b024-707aa0ade628.png)

**Comment by endquote** [comment]
Interesting that changing the setting had an impact for you. I think the issue that lowercase "a" in the format string should be "am" or "pm". I don't even see "in the morning" in the format docs. 

https://momentjs.com/docs/#/displaying/format/

**Comment by n-thumann** [comment]
Maybe https://github.com/moment/moment/search?q=night is related to this, because `a`/`A` can also result in `night`, `morning` etc. in other languages, but I have no idea why moment.js would do this on my system 🤷🏻‍♂️

**Comment by endquote** [comment]
No longer seeing this in GitLens 12.0.6 and VScode 1.66.2.
