### ISSUE TITLE
Git Lens forces "Comments" View to open even when disabled.

### ISSUE THREAD

**Issue by WissenIstNacht** [gitkraken/vscode-gitlens#1962]
- GitLens Version: 12.0.5
- Git Version: 2.30.1

- VSCode Version: 1.66.1
- OS Version:

Steps to Reproduce:

1. Open a Github Pull Request on a file that has comments on it. This will open a Git Lens panel with a "Comments" tab (showing all comments in the current PR).
2. Right click on that tab, uncheck "Comments".
3. Open a Github Pull Request on a file that has comments on it. The Panel with the "Comment" tab will reappear, although it should have been disabled in the previous step.

 Additional info:

This only started with the last update. Since then, Git Lens would open a panel with a tab to show the new "Visual History" feature as well as the "Comments" tab. Disabling "Visual History" (by right clicking the tab and unchecking "Visual History") works as expected, it no longer pops up. But the "Comments" tab from that same panel does.

**Comment by eamodio** [comment]
@WissenIstNacht The Comments panel is built-in to VS Code itself and is used by the GitHub Pull Requests & Issues extension. GitLens doesn't provide nor contribute to that panel.
