### ISSUE TITLE
Unable to fetch repository. See output channel for more details

### ISSUE THREAD

**Issue by ghost** [gitkraken/vscode-gitlens#1968]
I'm getting this output when clicking `fetch` in `remotes` in `source control`: 

`Unable to fetch repository. See output channel for more details`

```
[2022-04-15 14:41:40.931] [ xxxx] LocalGitProvider.fetch — failed • 347 ms
Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch origin BRANCH_NAME
fatal: could not read Username for 'https://github.com': No such device or address

[2022-04-15 14:41:40.931] [ xxxx] GitProviderService.fetch — failed • 347 ms
Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch origin BRANCH_NAME
fatal: could not read Username for 'https://github.com': No such device or address

[2022-04-15 14:41:40.931] /home/username/.vscode/extensions/eamodio.gitlens-12.0.6/dist/gitlens.js:36:7507
Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch origin BRANCH_NAME
fatal: could not read Username for 'https://github.com': No such device or address
```

- GitLens Version: 12.0.6
- Git Version: 2.25.1
- VSCode Version: 1.66.2
- OS Version: Ubuntu 20.04

If I press Ctrl-Shift-P and use native Fetch there, it works (but not `fetch` by GitLens). Also push and pull in VScode itself works (not sure how to test it with GitLens). Also switching to another branch in `remotes` works. 

I'm signed in with GitHub in VSCode.

**Comment by mr-yt12** [comment]
Or maybe I'm confusing something, and this is not a GitLens issue? I thought `Remotes` was added by GitLens

**Comment by mr-yt12** [comment]
This seems similar to this issue:
https://github.com/gitkraken/vscode-gitlens/issues/1093

There is a question: 

> Can you fetch from another terminal (not the integrated one)?

In my case, I can't, git will ask me for credentials. 
If I use VSCode terminal, it doesn't ask for credentials.
