### ISSUE TITLE
Don't show line blame for uncommitted lines

### ISSUE THREAD

**Issue by janlarres-msft** [gitkraken/vscode-gitlens#1987]
Line blames are quite useful for committed lines, but for uncommitted lines it doesn't really show you any information you don't already know. But more importantly if you use other extensions that show line annotations, for example compiler errors, then those can be pushed out of the window by the blame, making them unreadable. So it would be very useful if you could disable line blames for uncommitted lines, especially since these are the lines that are most likely to contain errors that would need to be annotated.

Is that possible? There doesn't seem to be an option for it, but I'm not even sure if VS Code's API would support this.

**Comment by HebaruSan** [comment]
Hi, I just came here to request this. "You, 1 second ago"? Yes, I know that. And now I'm thinking about that text instead of the changes I'm making.

**Comment by dieegorenan** [comment]
Hi, I get the point when you are doing a small feature and commit often. But sometimes when you start a big refactoring, moving some code around, doing some copy and paste, you might get lost and this information can be helpful.

**Comment by eamodio** [comment]
@janlarres-msft @HebaruSan would you want the annotation removed completely or would you like it shorter/less distracting -- maybe something like (e.g. replacing the text with a ✏️)

![image](https://user-images.githubusercontent.com/641685/182732432-f3b81d39-2add-4018-9fa4-d26e281a1aef.png)

@dieegorenan If implemented, this would be an opt-out setting, so this wouldn't impact anyone who gets value out of it today.

**Comment by janlarres-msft** [comment]
I think either would be fine for me - a single emoji doesn't take up much space, so it wouldn't make much of a difference for the main issue of obscuring other annotations.

**Comment by eamodio** [comment]
@janlarres-msft Do you have a screenshot/example of another anotation being pushed out of view? I want to make sure I have a test case to make sure it works correctly.

**Comment by eamodio** [comment]
Thinking about it more, a better alternative, imo, is to have a new setting similar to `gitlens.currentLine.format` but for uncommitted lines (e.g. `gitlens.currentLine.formatUncommitted`), which would allow you to replace the format string for uncommitted lines. Then you can customize it how you see fit, or leave it blank to nuke the annotation all together.

**Comment by eamodio** [comment]
Added a new `gitlens.currentLine.uncommittedChangesFormat` -- setting it to `null` (the default) follows the `gitlens.currentLine.format` settings, while setting it to an empty string will disable the annotations on uncommitted changes.

Here's where you can customize the setting:

![image](https://user-images.githubusercontent.com/641685/182778369-bfcbd414-0d92-45a7-9d3d-ef7c62fa986f.png)

Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by janlarres-msft** [comment]
It's working fine for me, thanks!
