### ISSUE TITLE
Gitlens is not installing in WSL2 in Window 10

### ISSUE THREAD

**Issue by sainipankaj15** [gitkraken/vscode-gitlens#2001]
- GitLens Version:
- Git Version: Run `git --version`

- VSCode Version: Run `code --version`
- OS Version:

Issue is that 
Git-lens is not installing in WSL2 in window 
![image](https://user-images.githubusercontent.com/72148087/168740283-8a2a05e1-0d69-4ef1-b719-64588cb4e949.png)

**Comment by eamodio** [comment]
@sainipankaj15 That is by design -- you'll need to install GitLens inside the WSL remote.
