### ISSUE TITLE
GitHub pull requests link to the wrong repo in commit message

### ISSUE THREAD

**Issue by GreenGremlin** [gitkraken/vscode-gitlens#2002]
Issue Type: <b>Bug</b>

Hover over a GitLens blame entry and click the pull request link in the commit message. GitLens attempts to open a pull request with the correct pull request id, but the wrong repo. This also replicates when hovering over commits in the commit pane.

For example, it opens:
https://github.com/company/repo-a/pull/1234
but should open:
https://github.com/company/repo-b/pull/1234

It's possible this might be some configuration issue on my side. This is for an enterprise GitHub repo. The repo the pull request is opening in is our legacy mono repo. I'm not sure if it is set as some type of default repo somewhere and I'm not sure how to troubleshoot this. Is there a way I can replicate how GitLens resolves the repo path?

Extension version: 12.0.6
VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:16.526Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 7, 7|
|Memory (System)|32.00GB (0.66GB free)|
|Process Argv|--crash-reporter-id 3f5fe63c-d813-41a5-90bb-2d01017f5202|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vsclangdc:30486549

```

</details>

**Comment by GreenGremlin** [comment]
I just connected my GitHub account to GitLens and now the link at the top of the commit popup that reads "2 weeks ago via PR #1234" is working, but the PR link in the commit message still links to the wrong repo.

**Comment by eamodio** [comment]
@GreenGremlin In the GitLens Remotes view, so you see multiple remotes? Or a remote to the legacy repo? If there are multiple remotes, you can right-click on the one you want, and choose "Set as Default" to make that remote the default for all commands/links

**Comment by GreenGremlin** [comment]
> @GreenGremlin In the GitLens Remotes view, so you see multiple remotes? Or a remote to the legacy repo? If there are multiple remotes, you can right-click on the one you want, and choose "Set as Default" to make that remote the default for all commands/links

@eamodio the remotes view only shows the new repo.

**Comment by GreenGremlin** [comment]
It is marked as default.

**Comment by eamodio** [comment]
Can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the _GitLens_ channels.

Thank you!

**Comment by eamodio** [comment]
@GreenGremlin Does this happen on all issue/pr autolinks or just a single one? Can you post the raw commit message?
