### ISSUE TITLE
Pro Login not retained for more than a day or two when using worktrees

### ISSUE THREAD

**Issue by mauricedoepke** [gitkraken/vscode-gitlens#2003]
- GitLens Version: 12.0.6
- Git Version: Run: 2.35.1
- VSCode Version: 1.68.0-insider
- OS Version: mac os 12.1

If I want to use the workspace feature which is included in my pro subscription I have to login my self every 1-2 days.
For some reason gitlens fails to store my session for a longer time.
This is really annoying

**Comment by eamodio** [comment]
Can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ channel in the _Output_ pane.

Once enabled, please wait until the issue reproduces and attach the log from the _GitLens_ channel.

Thank you!

**Comment by mauricedoepke** [comment]
Seems to work now
