### ISSUE TITLE
GitLens doesn't let my 'tasks' work

### ISSUE THREAD

**Issue by bagermen** [gitkraken/vscode-gitlens#2006]
- GitLens Version: 12
- Git Version: 2.28.0.windows.1
- VSCode Version: 1.67.2 c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5 x64
- OS Version: Windows 10 Pro

Steps to Reproduce:
1. Install Gitlens 12 (12.0.0 - 12.0.6)
2. Try to select and run a task

I had to downgrade back to Gitlens 11 to make it work again

**Comment by eamodio** [comment]
Can you provide more details? What type of tasks are you running? I can't see how GitLens could affects (as it doesn't interact with them in any way).

Can you also please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the _GitLens_ channels.

Thank you!

**Comment by bagermen** [comment]
It can be closed. I have no idea how, but after computer reboot the issue has gone and 'tasks' functionality works. I've tested with 12.0.6 and 12.0.7
