### ISSUE TITLE
Gitlens+ pro keeps signing out

### ISSUE THREAD

**Issue by eamodio** [gitkraken/vscode-gitlens#2017]
### Discussed in https://github.com/gitkraken/vscode-gitlens/discussions/2005

<div type='discussions-op-text'>

<sup>Originally posted by **lee1409** May 23, 2022</sup>
I realize GitLen+ keeps signing out and asking me to sign in again. I use my GitHub account to sign in.</div>

**Comment by eamodio** [comment]
@lee1409 So every time you restart (just vscode or the whole machine) you have to log in again, even if there is only minutes between logging in and rebooting?

**Comment by eamodio** [comment]
@lee1409 can you provide any more details as to when you see this? I would love to get it resolved.

**Comment by lee1409** [comment]
> @lee1409 can you provide any more details as to when you see this? I would love to get it resolved.

Hi Eric, sorry for the late reply. I couldn't gather any more meaningful insight from the logs and this is what I have for now. But here are 3 related info that may cause the issue.

1. I realize the problem doesn't happen every time I reopen my laptop. Sometimes it keeps logged sometimes it is not. I guess the time for the session token is too short?

2. When signing in, it will automatically try to open my default browser (Chrome for dev) to authorize. But I will copy the link and open it using Microsoft edge to authorize.

3. I did use GitHub acc to sign into my vscode for git and other stuff.


Thanks!

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.
