### ISSUE TITLE
Source Control list of folders does not Sort

### ISSUE THREAD

**Issue by tonypags** [gitkraken/vscode-gitlens#2029]
Issue Type: <b>Bug</b>

1. Open multiple folders in your workspace from multiple parents so that you can test all sorting options. 
2. Click 3 dots on source control top of element > View & Sort > Sort Changes by XXXX
3. Chose any option, then chose another, then the final one. 
4. Witness it does not change the order of the folders in the list. 

![Animation](https://user-images.githubusercontent.com/19650592/173127836-4da02bef-cecc-45a4-8d5d-ab2e3177d7e0.gif)

Extension version: 12.0.7
VS Code version: Code 1.68.0 (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:44:16.822Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (0.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by eamodio** [comment]
The _Source Control_ view is provided by VS Code, not GitLens, so you'll need to open a bug report on the VS Code repository.
