### ISSUE TITLE
Need language spell checking  in commit message input box

### ISSUE THREAD

**Issue by FishingGo** [gitkraken/vscode-gitlens#2038]
It would be great if the gitlens can support the spell checking when I edit the commit log.
Or if I missed some info that gitlens already support it?
![gitlens](https://user-images.githubusercontent.com/43175250/173717635-fedc1d0b-ec29-483f-bb74-19d106bfff37.jpg)

**Comment by eamodio** [comment]
VS Code has added support for this natively.
