### ISSUE TITLE
Interactive rebase: Add a way to search for commit messages

### ISSUE THREAD

**Issue by The-Compiler** [gitkraken/vscode-gitlens#2050]
I'm currently working with a [branch of my project](https://github.com/qutebrowser/qutebrowser/compare/qt6-v2) with a major rewrite, with almost 200 commits on top of the default branch.

From time to time, I notice there's some small aspect I've missed in an earlier part of the rewrite, so I create a follow-up fixup commit. Then I'd like to rebase to integrate the commit into the original one.

However, with 200 commits, it gets hard to find the commit I'd like to combine the new one with! It would help tremendously if I had a way to search in the list of commits, similarly to what's possible when using a normal text editor for the git-rebase-todo file. Matching words in the commit subjects would then be highlighted, so that I can locate the commit and move the newest one there.

**Comment by d13** [comment]
@The-Compiler 

I bring good news! We have a [Search & Compare view](https://github.com/gitkraken/vscode-gitlens#search--compare-view-) in the _Source Control_ panel which can search through commit messages.

Once you find the commit in your search, you can additionally right-click it and select _Rebase Current Branch onto Commit..._ 

![Screen Shot 2022-06-22 at 11 51 57 AM](https://user-images.githubusercontent.com/293282/175077145-bd2f9f38-6ea0-4413-8b43-cef65d1fe3e5.png)

Which will then provide options on how you want to rebase, including _interactive_
![Screen Shot 2022-06-22 at 11 57 49 AM](https://user-images.githubusercontent.com/293282/175077920-a17f5991-8d5f-492c-8492-1752a60b6512.png)

Let me know if this solves your issue?

**Comment by woobione** [comment]
➕1️⃣ on this one! Would be an amazing feature 🤗

**Comment by eamodio** [comment]
This feature has been added in the latest GitLens insiders edition (should be coming to GitLens stable soon).
You can now press Ctrl+F to search for text in the Interactive Rebase Editor. Try it out and let me know what you think.

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by woobione** [comment]
> This feature has been added in the latest GitLens insiders edition (should be coming to GitLens stable soon). You can now press Ctrl+F to search for text in the Interactive Rebase Editor. Try it out and let me know what you think.
> 
> You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).
> 
> Please be sure to disable or uninstall the stable version of GitLens first.

Amazing! Just what I've been wanting 😍 It's a little bit slow/sluggish in the search, tried on a miniature rebase with only a single commit and still takes about 1 second to highlight the searched string - but guessing the feature is a work in progress? No matter - lovely! 👍

**Comment by eamodio** [comment]
Yeah, it seems like the 1s delay seems to be largely consistent whether there a couple of commits or hundreds.

Unfortunately, as it is currently implemented, VS Code is actually providing this search facility. I opened this issue to track that: https://github.com/microsoft/vscode/issues/157050

Eventually we will probably be moving the rebase editor to be a virtualized list (for better performance for large rebases) and we'll need to provide our own search. Although, that work isn't high on the list right now.

**Comment by The-Compiler** [comment]
This is great, thanks @eamodio and @d13! :heart: For anyone looking for the commit implementing this, it seems to be 0e7efb2a83ac907e8f7c850c12ddc5414e49e5c4 (whoa, single-line change!).

Do you have any idea if it's possible to trigger the search widget programmatically somehow? I'd be great to also have it bound to `/` for the people who prefer vim-like controls (e.g. me :wink:), but I can't seem to find a way to do that...

**Comment by The-Compiler** [comment]
I finally got it figured out - this in `keybindings.json` does the trick:

```json
    {
        "key": "/",
        "command": "editor.action.webvieweditor.showFind",
        "when": "gitlens:enabled && activeCustomEditorId == gitlens.rebase"
    }
```

Maybe that should be a default binding, given that the editor also already supports `j`/`k`/`J`/`K`? Though I suppose it's somewhat inconsistent that this would be handled as a command, while the other keybindings in the rebase webview are hardcoded.

**Comment by eamodio** [comment]
@The-Compiler I've added `/` to open the find widget now 😄
