### ISSUE TITLE
Interactive Rebase fails to start when using xonsh shell due to command quoting

### ISSUE THREAD

**Issue by Eisfunke** [gitkraken/vscode-gitlens#2052]
- GitLens Version: v12.1.1
- Git Version: 2.36.1

- VSCode Version: Codium 1.68.1
- OS Version: Arch Linux

**Steps to Reproduce:**

1. Use the [xonsh shell](https://github.com/xonsh/xonsh).
2. Start an interactive rebase
3. GitLens will then call this in the integrated shell: `git -c sequence.editor="codium --wait --reuse-window" rebase --interactive COMMITHASH`
4. It fails with the following error message:

```
hint: Waiting for your editor to close the file... "codium --wait --reuse-window": line 1: codium --wait --reuse-window: command not found
error: There was a problem with the editor '"codium --wait --reuse-window"'.
```

As far as I understand, this is due to xonsh not removing quotes *inside* arguments, so git will actually receive `'sequence.editor="codium --wait --reuse-window"'` as argument. It will therefore try to call a binary file named `"codium --wait --reuse-window"`, which fails for obvious reasons.

bash on the other hand removes quotes inside arguments and calls git with `'sequence.editor=codium --wait --reuse-window'` as argument, which works fine.

See my [previous issue over at xonsh](https://github.com/xonsh/xonsh/issues/4849) and the [xonsh manual](https://xon.sh/tutorial_subproc_strings.html#the-quotes-stay).

The fix would be easy: Just change the quotes in [Line 99 in rebase.ts](https://github.com/gitkraken/vscode-gitlens/blob/7b5205412dc333b7bc744ca00011f73e3304cfa2/src/commands/git/rebase.ts#L99) to cover the entire argument, like this: ``configs = ['-c', `"sequence.editor=${editor}"`];``. This would still work in shells like sh and bash, but also in xonsh, and I'd argue that it's more correct anyway.

I understand you can't prioritize compatability with uncommon shells, but as the fix is easy and shouldn't have any downsides, I hope you'll consider it. I can make a corresponding PR if you wish, of course.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's pre-release edition of GitLens?

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)

**Comment by Eisfunke** [comment]
Yes, that fixed it. Thank you very much!
