### ISSUE TITLE
Heatmap - incorrect behavior of `gitlens.heatmap.fadeLines` with `gitlens.heatmap.ageThreshold` 

### ISSUE THREAD

**Issue by RomanKornev** [gitkraken/vscode-gitlens#2069]
A picture is worth a thousand words. So this is a heatmap at `ageThreshold`=30:
![image](https://user-images.githubusercontent.com/5807561/177164477-9bf3cbe1-9a63-4821-8f4c-d77de3867a29.png)
File blame view:
![image](https://user-images.githubusercontent.com/5807561/177164563-35191a21-9b32-4383-8cb2-b768b4a147e0.png)
This behavior is not what I expected. The README states that `ageThreshold` specifies the age of the most recent change (in days) after which the file heatmap annotations will be cold rather than hot. So how come with `ageThreshold=30` 2 hours ago is hot, 2 weeks ago is cold, and 30 days ago is hot again?

The behavior should be either:
- Everything from now to 30 days ago should be white and everything after 30 days gradually falls to black up-to 365 days (or for any X\*30, for example at 2*30 is fully black)

OR
- Everything from now to 30 days would gradually change from white to black, and everything after 30 days would be fully black.

But definitely not what we have here right now. This is confusing.

- GitLens Version: v12.1.1
- Git Version: 2.33.0.windows.2
- VSCode Version: 1.68.1
- OS Version: Windows 10 x64

Steps to Reproduce:
1. Generate a bunch of commits with `git commit -a --date="N days ago" -m "commit message"`
2. Open heatmap view
3. Change the `ageThreshold` and see the inconsistency

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by RomanKornev** [comment]
Seems to be fixed now. Thanks!
![image](https://user-images.githubusercontent.com/5807561/179294794-d658a149-2ad9-4124-89be-2dee290c79b1.png)
