### ISSUE TITLE
Quoted HTML / JSX syntax is not escaped correctly

### ISSUE THREAD

**Issue by equt** [gitkraken/vscode-gitlens#2070]
- GitLens Version: v12.1.1
- Git Version: git version 2.32.1 (Apple Git-133)

- VSCode Version: 1.68.1 arm64
- OS Version: macOS 12.4

Steps to Reproduce:

1. Create a commit like ``feat: HTML like tag `<Input />` is not escaped correctly``
2. It will be rendered as
  ![popover window](https://user-images.githubusercontent.com/17521736/177232102-e4bdd520-9637-43b9-acbf-eff73a4a2b33.png)

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by equt** [comment]
I've confirmed that this has been fixed.
