### ISSUE TITLE
`GitLens+: Hide GitLens+ Features` hides the GitLens icon on the activity bar

### ISSUE THREAD

**Issue by d13** [gitkraken/vscode-gitlens#2072]
- GitLens Version: 12.1.1
- Git Version: 2.35.1
- VSCode Version: 1.68.1
- OS Version: macOS 12.4

Steps to Reproduce:

1. From the command palette, run `GitLens+: Hide GitLens+ Features`

**Comment by eamodio** [comment]
Currently this is by design -- because the Home view doesn't really offer any functionality (other than the resource links) outside of GitLens+. This will change in the future as we add more functionality to the GitLens activity bar.
