### ISSUE TITLE
"Work in progress" section similar to staged changes

### ISSUE THREAD

**Issue by chrisd08** [gitkraken/vscode-gitlens#2077]
Would it be possible to somehow flag a changed file in the working directory as WIP, so it's similar to a staged file but will not be part of the commit? So for instance instead of Staged Changes + Changes you'd have Staged Changes + Work In Progress Changes + Changes?

![image](https://user-images.githubusercontent.com/39047/178012329-bae0f375-7090-4b4b-8eb3-f7fb54ff1d9b.png)

This could be particularly helpful when you have a lot of active changes and are trying to separate them into separate commits

**Comment by eamodio** [comment]
Not sure I fully understand the request. By default vscode (and Git) only commit staged changes. So the `Changes` section is the WIP in your example.

Additionally this would really need to be a request on the VS Code repository as that view is provided by VS Code not GitLens.
