### ISSUE TITLE
show git diff shortstat in comparison.

### ISSUE THREAD

**Issue by ShafinKhadem** [gitkraken/vscode-gitlens#2078]
When comparing, it's sometimes useful to know the amount of changes (number of lines added & deleted, obtainable by `git diff --shortstat`). It would be nice to have an option to show these stats in comparison.

**Comment by eamodio** [comment]
Here's what it looks like: 
![image](https://user-images.githubusercontent.com/641685/179904285-8ae6fc02-de96-4b06-9429-af6e8960bf4d.png)
