### ISSUE TITLE
Always show "GitLab failed to respond and might be experiencing issues."

### ISSUE THREAD

**Issue by eamodio** [gitkraken/vscode-gitlens#2080]
### Discussed in https://github.com/gitkraken/vscode-gitlens/discussions/2076

<div type='discussions-op-text'>

<sup>Originally posted by **tonythere** July  8, 2022</sup>
![CleanShot 2022-07-08 at 16 20 25@2x](https://user-images.githubusercontent.com/1900855/177960846-d7e50424-890b-4425-b73b-629e47122893.png)

My machine always shows this message very noisy, can anyone explain what is this and how to fix it? Thanks so much</div>

**Comment by eamodio** [comment]
@tonythere Can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the _GitLens_ channels.

Thank you!

**Comment by tonythere** [comment]
ya, I see my internal gitlab respond error

```
[2022-07-14 04:28:13.245] [  372] [GITLAB] POST https://gitlab.MYSERVER/api query findUser • 212 ms
[2022-07-14 04:28:13.245] U.graphql
Error: GitLab request failed: (500) Internal Server Error. 
```

Can I disable this feature on some particular gitlab server? The popup jumps out too frequently, it's quite noisy.

Thank you!

**Comment by tonythere** [comment]
ah, I got the issue. The popup will show when I hover on lines that had been written by a deactivated GitLab user. Seem Gitlab returns 500 when querying deactivated users.

**Comment by eamodio** [comment]
This should largely be resolved (though further improvements to integration error reporting will come in a future release) in the latest insiders build, can you please verify it?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by eamodio** [comment]
This should be resolved in the latest insiders build, can you please verify it?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.
