### ISSUE TITLE
Search & Compare - commits are swapped in diffs

### ISSUE THREAD

**Issue by jaklan** [gitkraken/vscode-gitlens#2097]
### GitLens Version

v12.1.2

### VS Code Version

Version: 1.69.1
Commit: b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a
Date: 2022-07-12T08:22:10.822Z (6 days ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.4.0

### Git Version

git version 2.32.1 (Apple Git-133)

### Description

1. `GitLens: Compare References...`
2. Select e.g. `origin/develop` as the source branch, `origin/release` as the target branch
3. In the `Search & compare` view you get `Comparing origin/develop with origin/release`
4. Select any file from the `XYZ files changed` list
5. The diff is opened:
<img width="595" alt="image" src="https://user-images.githubusercontent.com/24907857/179483078-66ee1a42-643e-4e16-955a-7261fd38c784.png">
<img width="379" alt="image" src="https://user-images.githubusercontent.com/24907857/179483141-dea4e914-70e3-413d-a26d-89c9b7c57aa9.png">

but what actually happens - the left commit is from the `origin/release` branch and the right commit is from the `origin/develop` branch, so it's reversed.

To confirm it, when you run `git diff origin/develop..origin/release` (which should be the CLI equivalent of the GitLens command), you get:
<img width="311" alt="image" src="https://user-images.githubusercontent.com/24907857/179483624-3fe3e0c6-fe23-4640-ad84-04ef9d98209b.png">

Probably related issue:
https://github.com/gitkraken/vscode-gitlens/issues/2092

**Comment by jaklan** [comment]
One more comment - the first branch we select is defined as `Choose a reference to compare` and the second one - `Choose a reference to compare with`, which is then reflected in the title: `Comparing branch_1 with branch_2`. So thinking about it one more time - it can be indeed understood as `git diff branch_2..branch_1` instead of `git diff branch_1..branch_2`, so then there's no bug. But imho it's quite confusing anyway, because the order of branches you specify is reversed in comparison to the order you provide in `git diff`, so maybe it would be worth to actually swap the order and start with `Choose a reference to compare with`, and then ask about `Choose a reference to compare` (probably a bit rephrased descriptions would be helpful then).

**Comment by eamodio** [comment]
Unfortunately there has been confusion around the comparison feature since its inception, and the place it is at now has caused the least confusion -- an imo the selection order and display make sense.

You first pick the branch you want as the base/anchor and then you pick the branch you want to compare the first branch with.

So if you first pick your main branch, and then pick an older tag, then you will see how far ahead main is when compared with that tag. Where as if you do the reverse, you will see how far behind the tag is when compared to main.

I hope that helps.
