### ISSUE TITLE
Why the lens shows before the code?

### ISSUE THREAD

**Issue by AurevoirXavier** [gitkraken/vscode-gitlens#2106]
### GitLens Version

v12.1.2

### VS Code Version

Version: 1.69.2 (Universal)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:57.074Z (2 days ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.5.0

### Git Version

git version 2.37.1

### Description

See the screenshot.

### Logs, Screenshots, Screen Captures, etc

<img width="928" alt="image" src="https://user-images.githubusercontent.com/16152305/180112730-ea376f97-94a0-43f6-bc43-a58d88e4fc5f.png">

**Comment by Novtopro** [comment]
Got the same issue, pretty annoying.

**Comment by AurevoirXavier** [comment]
I'm using error-lens + rust-analyzer.

If rust-analyzer crash, then this will happen.
