### ISSUE TITLE
Add a commit details view

### ISSUE THREAD

**Issue by d13** [gitkraken/vscode-gitlens#2130]
Now:

- [x] Open from "show" menu
- [x] Add boxed treatment to commit message, highlight first line and honor formatting (whitespace, tabs, etc)
- [x] Theme colors to match VSCode tree views
- [x] Avatar styling
- [x] Hide committer (for now) and change "authored" to "committed"
- [x] Empty state message for autolinks
- [x] Create defined sections for autolinks and files with subheadings
- [x] Dates: honor settings for relative/absolute and formats 
- [x] Add sha
- [x] Follow mode toggle
  - watches selected commit in graph || active line > activeEditor
  - add arg to control whether the view should continue to follow 
- [x] Find all the places we should be able to open the commit details & graph @eamodio 
  - opening from the visual file history / timeline view
  - open from status bar
- [x] Selected state for files to match vscode
- [x] Keyboard up/down (space for select) in files list

Soon:

- [x] Empty states for autolinks to connect rich provider or configure autolinks

Later:

- [x] Clamped titles should be expandable
- [x] Collapsable sections for autolinks, files, etc

**Comment by eamodio** [comment]
@d13 Let's split out the work to be done here into a new issue for the next iteration. Thanks!

**Comment by d13** [comment]
Work to be done is added to the project board
