### ISSUE TITLE
Use VS Code as core.editor

### ISSUE THREAD

**Issue by ShafinKhadem** [gitkraken/vscode-gitlens#2134]
A superset of #2084, currently git's global `core.editor` is used to edit commit messages instead of VSCode in scenarios merge, pull, cherry-pick etc. I would like to be able to use VSCode to edit commit messages without changing global config.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's pre-release edition of GitLens?

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)

**Comment by ShafinKhadem** [comment]
I have verified that this issue has been fixed in pre-release edition of GitLens. Thanks.
