### ISSUE TITLE
Authorship turned on by default for docker compose files

### ISSUE THREAD

**Issue by rtfmoz2** [gitkraken/vscode-gitlens#2153]
### GitLens Version

v12.1.2

### VS Code Version

Version: 1.70.2 (Universal)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:37.829Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.6.0

### Git Version

git version 2.37.2

### Description

Gitlens has authorship turned on for docker compose files by default. Unless my fat fingers toggled it somehow but in two years it has yet to happen. So I had to go into settings and turn it off. Strange behaviour... i figured it came in a update.

### Logs, Screenshots, Screen Captures, etc

<img width="565" alt="Screen Shot 2022-08-19 at 7 33 29 am" src="https://user-images.githubusercontent.com/40995106/185500622-c853de2a-8a49-4d37-a17b-c9a615d10448.png">

**Comment by lucasayb** [comment]
Same problem here.

**Comment by jkelroy** [comment]
@lucasayb @rtfmoz2 I am unable to open this by simply disabling _Git  CodeLens_ in the GitLens Settings and then opening up a docker-compose.yml file (for example from this [repository](https://github.com/temporalio/docker-compose)). Are there any additional steps you took to see this behavior?

If you can reproduce this, can you please enable debug logging by running the _GitLens: Enable Debug Logging_ command from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ & _GitLens (Git)_ channels in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the logs from the _GitLens_ and _GitLens (Git)_ channels.

**Comment by eamodio** [comment]
GitLens didn't change anything here. My guess is that another extension (Docker?) is now providing language services (symbols, etc) for docker compose files and GitLens is now able to consume them to provide Git CodeLens.

These can be customized per-language, e.g.

```json
"[dockerfile][dockercompose]": {
	"gitlens.codeLens.scopes": [
		"document"
	]
}
```

That should limit the Git CodeLens to only the document root.

I've also added the above to the GitLens default configuration, so in tomorrow's pre-release this should just work out of the box.

**Comment by eamodio** [comment]
Can you please verify this fix in the latest pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)
