### ISSUE TITLE
Reduce extension package size

### ISSUE THREAD

**Issue by kidonng** [gitkraken/vscode-gitlens#2156]
GitLens is a very popular extension, which means every small improvement it makes results in huge gains. It is also a very large extension, both in scale and disk usage. I think we can do better in the latter.

The latest version (12.1.2) of GitLens is 11M when packed up, and 22.3M when unpacked.

- With `images/docs` ignored, package size goes down to 7.3M.

  They are [mostly used in walkthroughs](https://github.com/gitkraken/vscode-gitlens/search?q=images%2Fdocs), so changing the relative paths to GitHub links should be able to free the images from the package.

- With `dist/**.map` ignored, package size goes down to 9.1M.

  Sourcemaps are uncommon and less useful in Node programs, especially for end users. It is more suitable to keep them out of the final package.

**Comment by eamodio** [comment]
I've removed the source-maps and some other unused files. As for the images, I don't want to use GitHub links, because then the walkthroughs won't work offline.

**Comment by kidonng** [comment]
I think users are mostly likely to take walkthroughs when they just installed the extension, and it should be rare people installing extensions offline via extension packages. That said, I fully support this decision. But maybe we can use more efficient format than GIF, like MP4 video or WebP images.

**Comment by eamodio** [comment]
Unfortunately vscode doesn't support video formats in webviews or walkthroughs, but the large gif is already excluded. As for the images, we can definitely convert them to webp, as I've already done for all the webview images.

**Comment by kidonng** [comment]
Thanks for the info, I didn't know about that.

Also, if you are interested why I am pushing a little hard about this kind of little thing, it's because I found it's [a common problem among extensions](https://github.com//microsoft/vscode/issues/158670), and I'd really like to see the situation improved. In the case of GitLens things are not that bad, but still thanks for working on this!
