### ISSUE TITLE
Can't find git

### ISSUE THREAD

**Issue by EchoZhaoH** [gitkraken/vscode-gitlens#2157]
### GitLens Version

12.1.2

### VS Code Version

Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:37.829Z (5 days ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.6.0

### Git Version

git version 2.33.1

### Description

![image](https://user-images.githubusercontent.com/23427655/185829706-26f9c395-9137-4d15-a18a-b4446d750e5f.png)
![image](https://user-images.githubusercontent.com/23427655/185829716-fab9f25f-e4d9-4f09-8662-c158d554a7b0.png)

can't find the git

### Logs, Screenshots, Screen Captures, etc

![Uploading image.png…]()

**Comment by d13** [comment]
It appears VS Code itself can't see your git installation, which GitLens depends on. You'll need to make sure xcode is installed and xcode command line tools are installed as well.

Running this command in the terminal will install the command line tools:
```
xcode-select --install
```

**Comment by EchoZhaoH** [comment]
@d13 Got it, I'll try this command next time I encounter this error, thanks!
