### ISSUE TITLE
copy remote  file url

### ISSUE THREAD

**Issue by enjoycx** [gitkraken/vscode-gitlens#2162]
### GitLens Version

v12.1.2

### VS Code Version

mac golang 

### Git Version

git version 2.24.3 (Apple Git-128)

### Description

https://*******/*******/******/-/blob/cabf7237591ba9b4504cfc0026cb9be2f34af0ef/controller/mail/mail_test.go#L120

/-/  need delete
![image](https://user-images.githubusercontent.com/56945691/186610436-d627d088-33fa-4cf0-a449-839e61d00b01.png)

**Comment by eamodio** [comment]
Unfortunately this is as-designed -- see for more details https://github.com/gitkraken/vscode-gitlens/issues/2021 and https://github.com/gitkraken/vscode-gitlens/pull/2022#issuecomment-1151081157
