### ISSUE TITLE
No file history could be found

### ISSUE THREAD

**Issue by robcdd** [gitkraken/vscode-gitlens#2165]
### GitLens Version

v12.1.2

### VS Code Version

Version: 1.70.2 (Universal)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:37.829Z (1 wk ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.6.0

### Git Version

git version 2.37.2

### Description

I'm using this extension at work and it works fine with some repos, but not for others. Both are in the same org.

I've enabled logging for gitlens and I can't see anything different between the repos that work correctly and those that don't. At first I thought this might be related, but I see the same thing in both projects. Also, `getRepository` only returns `undefined` on the third attempt, and it looks like the input path is wrong on that third call, but again, this is happening in both projects.
```
[2022-08-26 21:21:31.111] [  308] GitProviderService.getRepository — s=Uri(file:///javascript/tsproto/geo-intelligence/common/money.ts)
[2022-08-26 21:21:31.111] [  308] GitProviderService.getRepository returned undefined • 0 ms
```

I can see the remotes in the remotes view, and I can see history there, but file history shows "No file history could be found", and line history shows "No line history could be found"

### Logs, Screenshots, Screen Captures, etc

I'm not sure if it's a good idea for me to share the log output since this is my work machine.

**Comment by Pictor13** [comment]
Is there any updated? 

I have the same issue.
Most files work fine, with diff gutters and per-line blame.
But on specific files it seems to not be able to get the history of the file or of the line, to show gutters nor blames.
Exactly on the file I needed to merge urgently 😓

I tried downgrading from VSCode 1.71 to 1.70 but didn't help.

**Comment by eamodio** [comment]
Can you please enable debug logging by running the _GitLens: Enable Debug Logging_ command from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ & _GitLens (Git)_ channels in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the logs from the _GitLens_ channel and the _GitLens (Git)_ channel.

If you don't want to post the full logs -- check in the _GitLens (Git)_ channel for a line similar to:
```
git log --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cn%x3e%x20%cN%n%x3cm%x3e%x20%cE%n%x3cc%x3e%x20%ct%n%x3cp%x3e%x20%P%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e%n%x3cf%x3e -n41 --follow --first-parent -m --numstat --summary -- <your-file-name-here>
```

If you take the same command and run it on the command line to you get any output?

Thank you!
