### ISSUE TITLE
Commits view files are sometimes not shown when expanding folders

### ISSUE THREAD

**Issue by Davidsastresas** [gitkraken/vscode-gitlens#2185]
### Description

In any repo, in the commits view, when expanding folders or commits the files changed on that commit do not appear. You can right click and select open changes and they will get opened in your editor, but in the commits view they are not shown. I have tested this consistently on several repos, it works correctly in 12.1.0 though, also tested in all the repos that doesn't work in 12.1.2

### GitLens Version

12.2.0

**Comment by eamodio** [comment]
Sorry, this should now be fixed in 12.2.1 which was just published.

**Comment by eamodio** [comment]
I'm really sorry for the issues here. I think I've solved them in the latest GitLens Insiders edition. Can any of you experiencing this problem please verify this fix?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by eamodio** [comment]
GitLens 12.2.2 has been released with this fix
