### ISSUE TITLE
Sometimes GitLens fails to do interactive staging properly

### ISSUE THREAD

**Issue by DevilXD** [gitkraken/vscode-gitlens#2191]
### Description

I know this bug report isn't ideal, because I have no real repro steps for it. I've ran into it today yet again though, so I figured I'd at least make a report for it. It has to do with the interactive stage feature of the extension, where one clicks on the colored stripes on the left side of the code lines: blue for changes areas, green for additions and a red arrow-like thingy for deletions - to selectively stage parts of a file for a commit.

What happens sometimes is that, when I stage one change and try to stage another, the first one unstages. This continues over and over, with me trying to stage a couple of changes together, but only the last one actually ended up being staged.

Now, I normally solve this by using the "Reload Window" option of VSCode, which restarts GitLens and everything works normally after that, and I'm able to stage multiple changes together. But it's annoying having to do so every time, hence this report.

I will try to watch it going forward and get some decent repro steps for this issue, or at least Git output from the console, next time it will eventually happen, and then comment them under here. For now, I'm leaving this issue up for anyone else to comment on the matter.

### GitLens Version

v12.2.1

### VS Code Version

Version: 1.70.3 (system setup)
Commit: a21a160d630530476218b85db95b0fd2a8cd1230
Date: 2022-08-31T08:03:55.990Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 6.1.7601

### Git Version

git version 2.37.3.windows.1

**Comment by eamodio** [comment]
The interactive staging feature is provided by VS Code itself, and not from GitLens, so you'll need to open an issue on the VS Code repository -- sorry.
