### ISSUE TITLE
Cannot "Open Changes" on files in Commit list

### ISSUE THREAD

**Issue by chanep** [gitkraken/vscode-gitlens#2193]
### Description

In commit list, cicking on a changed file or even selecting "Open Changes" in context menu does nothing.
It should open changes in editor as always.
After clicking new Feature "Show commit Graph" over a specific commit, "open changes" is restored on that specific commit but still fails in all other commits. 

### GitLens Version

12.2.1

### VS Code Version

1.71

**Comment by derMart** [comment]
For me also all the other actions in the context menu do nothing. Very problematic is also that no error comes up or anything is shown in the debug panel of vscode

**Comment by chanep** [comment]
It seems downgrading to 12.1.2 fixes the problem

**Comment by StraightOuttaCrompton** [comment]
12.2.0 seems to have introduced the issue

**Comment by StraightOuttaCrompton** [comment]
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/2177 ?

**Comment by chanep** [comment]
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/2177
