### ISSUE TITLE
Setting to toggle commit graph button in source control view

### ISSUE THREAD

**Issue by boraozgen** [gitkraken/vscode-gitlens#2198]
Hi, as a non-plus user, I would like to hide the "show commit graph" button in the source control view. Could we add a settings option for this, similar to `gitlens.graph.statusBar.enabled`?

**Comment by eamodio** [comment]
See the discussion here: https://github.com/gitkraken/vscode-gitlens/discussions/2196

But keep in mind that the Graph (and soon all current GitLens+ features), doesn't require anything (no account or anything) to use on local and public repos only private repos require a paid account.
