### ISSUE TITLE
GitLens bottom bar view unreadable in certain themes

### ISSUE THREAD

**Issue by atjbramley** [gitkraken/vscode-gitlens#2202]
### Description

When going through the sign-in process, the bottom bar is unreadable in certain themes.  

Similar to previous issue https://github.com/gitkraken/vscode-gitlens/issues/2082 (now fixed)

See screenshot:

<img width="658" alt="Screenshot 2022-09-07 at 19 25 08" src="https://user-images.githubusercontent.com/71517198/188941162-8484cc5c-128f-4faa-9aed-622ce3b10306.png">
<img width="1312" alt="Screenshot 2022-09-07 at 19 25 25" src="https://user-images.githubusercontent.com/71517198/188941210-1d5de3d9-9d6a-47a9-8f74-1771ca32921a.png">

### GitLens Version

v2022.8.3105

### VS Code Version

Version: 1.71.0 (Universal)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:25:38.437Z (6 days ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No

### Git Version

git version 2.32.1 (Apple Git-133)

**Comment by d13** [comment]
@atjbramley what themes did you see this with?

**Comment by atjbramley** [comment]
Hi, 

My theme is custom, based off  Mariana Sublime, however it occurred with several themes.

However, I went back to get a list for the report and I can't reproduce this any more - one of the intermediate updates must have changed something.

Will re-open if it comes back.
