### ISSUE TITLE
When click on the commit message

### ISSUE THREAD

**Issue by Khamphay** [gitkraken/vscode-gitlens#2204]
This extension is useful, I think is great if click on the commit message and show file changes.
![Group 1](https://user-images.githubusercontent.com/61783889/189037902-f7a18a1f-7cf6-4ac4-b86b-10fe1af4e4a0.png)

**Comment by eamodio** [comment]
This feature is available today via the _Commit Details_ view:

![image](https://user-images.githubusercontent.com/641685/192341504-2785f766-c0e1-4f96-9c35-3502e48b7179.png)

The _Commit Details_ view should open automatically as you select items in the graph. 

We recommend dragging the _Commit Details_ view to the area you have highlighted in your image and it will move into VS Code's "Secondary Side Bar". Unfortunately VS Code doesn't allow extensions to target the secondary side bar directly, so users' have to move it manually: https://github.com/microsoft/vscode/issues/151681

Which will then look like this:

![image](https://user-images.githubusercontent.com/641685/192342103-f4b75094-deb4-447f-aea7-40277d1d427c.png)
