### ISSUE TITLE
Not separating a file  node_modules when I change between branches

### ISSUE THREAD

**Issue by abdalshafiealmajdoup** [gitkraken/vscode-gitlens#2217]
### Description

Not separating a file  node_modules when I change between branches ،
Which makes me delete anode_modules file and a file dist and a file package.lock.json  ،  and reinstall again it via npm install && npm run build 

### GitLens Version

v12.2.2

### VS Code Version

Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:12:14.256Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.18.0-kali7-amd64
Sandboxed: No

### Git Version

git version 2.35.1

**Comment by eamodio** [comment]
Can you please add more detail as to the issue you are experiencing and/or the steps to reproduce it?

Thank you!
