### ISSUE TITLE
show commit graph bug

### ISSUE THREAD

**Issue by liushouqian** [gitkraken/vscode-gitlens#2226]
### Description

what happend?
![Uploading image.png…]()
![Uploading image.png…]()

### GitLens Version

12.2.2

### VS Code Version

版本: 1.71.2
提交: 74b1f979648cc44d385a2286793c226e611f59e7
日期: 2022-09-14T21:05:37.721Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
沙盒化: No

### Git Version

git version 2.32.1 (Apple Git-133)

**Comment by liushouqian** [comment]
![Xnip2022-09-22_11-39-40](https://user-images.githubusercontent.com/18477421/191653248-3d0f1acc-adf9-4a0b-8be9-cbfb816f4501.jpg)

**Comment by zakke27** [comment]
Try the [GitLens (Insiders)](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders) and update vscode to 1.72 version .

**Comment by liushouqian** [comment]
> Try the [GitLens (Insiders)](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders) and update vscode to 1.72 version .

GitLens Version
v2022.8.3105(Insiders)

VS Code Version
版本: 1.72

error: command 'gitlens.views.home.refresh' not found
<img width="306" alt="image" src="https://user-images.githubusercontent.com/18477421/195271259-5cd1f3cd-f49a-4e87-8b1d-155a32b96510.png">
Been loading....

sad...

**Comment by zakke27** [comment]
Maybe there's an answer you need here - [discussions](https://github.com/gitkraken/vscode-gitlens/discussions/2158#discussioncomment-3644738) .

**Comment by liushouqian** [comment]
> 

Thank you so much for the link, you helped me

**Comment by d13** [comment]
This is fixed with https://github.com/gitkraken/vscode-gitlens/commit/7082b1597e13faa65cb042557411c1c06b1ccb9d
