### ISSUE TITLE
Graph commit settings are not applying the settings if the Graph webview is opened in a different tab (we need to restart the graph as workaround))

### ISSUE THREAD

**Issue by ericf-axosoft** [gitkraken/vscode-gitlens#2227]
### Description

Steps to reproduce the problem:
1. Open a repository and open the graph webview.
2. Open Gitlens -> Graph Settings webview in a different tab (make sure you do not open settings tab and graph tab to be seen at the same time).
3. Select the Graph Settings tab and change a setting (uncheck `Gitlens>Graph>:Avatars` for example).
4. Select the Graph tab.

Actual result:
- Settings are not applied to the graph until we restart it.

Expected result:
- Settings must be applied without restarting the graph.

Original comment: https://github.com/gitkraken/GitKrakenComponents/pull/80#issuecomment-1255902090

See attached recording for more details.

### GitLens Version

12.0.0

### Logs, Screenshots, Screen Captures, etc

https://user-images.githubusercontent.com/90025366/191929828-ac9e98c7-b96b-42a8-bbde-1f5b3dc3f9fc.mov

**Comment by eamodio** [comment]
This is now fixed

**Comment by sergeibbb** [comment]
Hi @ericf-axosoft
Thank you for precise steps to reproduce and for the video. It's much easier to verify when the are presented.
