### ISSUE TITLE
`j` and `k` are inverted in ascending rebase order.

### ISSUE THREAD

**Issue by lgarron** [gitkraken/vscode-gitlens#2230]
### Description

Config:

```js
  "gitlens.rebaseEditor.ordering": "asc"
```

When navigating a rebase file with the keyboard, the `j` and `k` keys work to navigate up and down — except `k` goes down and `j` goes up, which is the opposite of expected. This is probably because the fix to #1190 didn't take keyboard input into account.

### GitLens Version

v12.2.2

### VS Code Version

Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:07:15.900Z (1 wk ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No

### Git Version

git version 2.37.0 (Apple Git-136)

**Comment by d13** [comment]
Fixed with: https://github.com/gitkraken/vscode-gitlens/commit/f7ef0a7fe4017018523001e5775df5c4bb3bda9e

**Comment by d13** [comment]
This fix is now available in the latest GitLens Insiders release. Please note you need to be running VS Code Insider edition in order to use this GitLens Insiders release.
