### ISSUE TITLE
The search of the commit graph does not work correctly when using stashes

### ISSUE THREAD

**Issue by ericf-axosoft** [gitkraken/vscode-gitlens#2231]
### Description

- Steps to reproduce:
   1. Open a repository with stashes and open `Gitlens+ Commit Graph` webview.
   2. Ensure that first commit of the list is an stash
   3. Search for a text that is contained in the description of a few stashes and commits.
- Actual result:
   - If we use the down arrow button of the search toolbar to move to the next result, it does not work: the selected commit is still the same and it is not the next result as expected.
   - Some of the results containing that text are not highlighted as expected.
- Expected result:
   - Arrow buttons should work as expected and select next/prior commit when using stashes. 
   - All results should be highlighted even if stashes are used.

See attached files for more details.

### GitLens Version

12.0.0

### Logs, Screenshots, Screen Captures, etc

<img width="814" alt="Captura de pantalla 2022-09-26 a las 13 01 52" src="https://user-images.githubusercontent.com/90025366/192260731-dcd04cf6-4f8e-417d-8faa-dc1e263b50ac.png">

https://user-images.githubusercontent.com/90025366/192257919-92b66715-2cd5-4191-a415-fb7c7844a973.mov

**Comment by sergeibbb** [comment]
@eamodio @d13 


The reported problem, how it's described, seems to be fixed. But there are still some problems. Regardles of what is on the first line, a stash or a commit, down arrow sometime navigates to something invisible:

https://github.com/user-attachments/assets/d9084475-255d-40c8-8f2e-1e5af8ee1571

https://github.com/user-attachments/assets/2e878e0b-ee73-4c25-91ed-d51eee9759d0
