### ISSUE TITLE
Javascript error when searching for a non-existent commit in the graph webview

### ISSUE THREAD

**Issue by ericf-axosoft** [gitkraken/vscode-gitlens#2232]
### Description

- Steps to reproduce:
   1. Open a repository and open `Gitlens+ Commit Graph` webview.
   2. Open `dev tools` and select `console` tab.
   3. Search for a non-existent commit (for example type to search `dsfgdfghfdgh`).
- Actual result:
  - A javascript error is displayed in the `developer tools` and the Graph component disappears.
- Expected result:
  - Search result should be 0 elements found.
  - No javascript errors should be displayed and the Graph component should not disappears.

See attached files for more details.

### GitLens Version

12.0.0

### Logs, Screenshots, Screen Captures, etc

![Captura de pantalla 2022-09-26 a las 13 00 23](https://user-images.githubusercontent.com/90025366/192260321-62f46579-7b9e-4d77-b993-3e1dede84599.png)

https://user-images.githubusercontent.com/90025366/192260054-d412aaf6-e4ff-453a-9bdb-2f348b816648.mov

**Comment by eamodio** [comment]
Fixed by https://github.com/gitkraken/vscode-gitlens/commit/891241e81d0b63099ea11d0107c6c1f54f97f127
