### ISSUE TITLE
Ignoring workspace folder

### ISSUE THREAD

**Issue by brainz80** [gitkraken/vscode-gitlens#2236]
Type: <b>Bug</b>

I keep getting the following warning:

"Ignoring workspace folder (unsupported or invalid URI) gitlens://7b22726566223a2265346264333535353631396635653532656434323638623462306233313535643261313730356131222c227265706f50617468223a22643a2f50726f6a656374732f446f636b65722f6e65747469782f61736f2d617070227d/d%3A/Projects/Docker/nettix/aso-app?%7B%22ref%22%3A%22e4bd355%22%7D. This is most likely bug, please report it."

and tasks and PHP-debugging won't run.

Disabling GitLens fixes the problem.

Extension version: 12.2.2
VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.35GB (17.68GB free)|
|Process Argv|--crash-reporter-id f331158c-b76c-4212-9fc0-84faccb73710|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
fc301958:30573243

```

</details>

**Comment by eamodio** [comment]
Can you provide more details on what you are doing when you get that error? Can you also show a screenshot? Thanks!
