### ISSUE TITLE
Incorrectly sanitized commit message

### ISSUE THREAD

**Issue by jkjustjoshing** [gitkraken/vscode-gitlens#2242]
### Description

This is a commit I just made, printed using `git log`
![Screen Shot 2022-09-30 at 9 22 45 AM](https://user-images.githubusercontent.com/813192/193279316-8edd721e-e20b-43ae-b1b6-ab4f77c37bbd.png)

This is that same commit, shown in the GitLens tooltip
![Screen Shot 2022-09-30 at 9 22 54 AM](https://user-images.githubusercontent.com/813192/193279312-e25dd50e-6dff-4fa6-8010-320e2bc7f4a1.png)

The text `<Image>` is not being displayed, which makes me think that there's some HTML character escaping that's not happening.

### GitLens Version

12.2.2

### VS Code Version

Version: 1.71.2 (Universal)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:05:37.721Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No

### Git Version

git version 2.32.1 (Apple Git-133)

### Logs, Screenshots, Screen Captures, etc

Note that the inline text is also correctly escaped, but non in the tooltip
![Screen Shot 2022-09-30 at 10 02 24 AM](https://user-images.githubusercontent.com/813192/193287076-7a4c989f-e009-463f-9aeb-ba9ef9a7a788.png)

**Comment by eamodio** [comment]
This should be resolved in GitLens 13.
