### ISSUE TITLE
Autolinks not works in Timeline view

### ISSUE THREAD

**Issue by HuangZhuo** [gitkraken/vscode-gitlens#2253]

**Comment by felipecrs** [comment]
I can confirm this.

**Comment by eamodio** [comment]
If you are talking about the VS Code Timeline view, that is not provided by GitLens (and until the timeline API is finalized GitLens can't contribute to it). Can you show a screenshot of the view?

**Comment by HuangZhuo** [comment]
Yes, as you said. Thank you for the explanation. I've also found an alternative option called **File History** which serves the same purpose.

![image](https://user-images.githubusercontent.com/5159053/195573361-2e427f0f-4ae5-46b8-91b2-030fb412e86e.png)
