### ISSUE TITLE
Extension periodically refreshes the file under review, resetting the view position

### ISSUE THREAD

**Issue by RikkiGibson** [gitkraken/vscode-gitlens#2259]
### Description

1. Install both GitLens and https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github (v0.50.0)
2. Open a pull request in the extension and begin reviewing a file
3. Proceed with review for about 1-2 minutes

Expected behavior: editor view position is only affected by user actions (e.g. navigation commands, scrolling)
Actual behavior: editor view position is periodically reset, disrupting the review.

Note that this behavior only occurs when *both* the GitLens and GitHub extensions are enabled. When I disable the GitLens extension, the bad behavior stops. I am not sure which extension is to "blame" in this scenario, so I'm taking the liberty of filing a bug both here and at microsoft/vscode-pull-request-github#4031.

### GitLens Version

12.2.2

### VS Code Version

Version: 1.72.0 (user setup)
Commit: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
Date: 2022-10-04T23:20:39.912Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

### Git Version

git version 2.30.0.windows.2

### Logs, Screenshots, Screen Captures, etc

This recording roughly shows the bad behavior, which occurs once every 1-2 minutes. Note that several different activity indicators are popping up in the left sidebar before the editor tab goes blank and refreshes.
![ghpri-refresh-bug-3](https://user-images.githubusercontent.com/5833655/194938256-59190ba8-7b50-4355-a923-06a379152ed1.gif)

**Comment by eamodio** [comment]
The issue was found in GHPR so closing this.
