### ISSUE TITLE
Blame annotation on hover doesn't work

### ISSUE THREAD

**Issue by hyposlasher** [gitkraken/vscode-gitlens#2261]
### Description

Blame annotation on hover doesn't work

### GitLens Version

12.2.2

### VS Code Version

Version: 1.72.0 (Universal)
Commit: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
Date: 2022-10-04T23:21:58.256Z (6 days ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No

### Git Version

git version 2.37.0 (Apple Git-136)

### Logs, Screenshots, Screen Captures, etc

https://user-images.githubusercontent.com/13961762/195087164-0c9b1c0d-760e-412a-946c-aff1d993f328.mov

**Comment by eamodio** [comment]
Do you have this setting unchecked?
![image](https://user-images.githubusercontent.com/641685/196590229-22b909c3-5dee-4709-8ff3-1b59522c4244.png)

If so that is expected behavior as the note below the setting explains.

**Comment by hyposlasher** [comment]
@eamodio I did everything like you have in the screenshot, still no annotation on hover. Checking and unchecking "Include the annotation when scrolling the editor horizontally" didn't helped.

<img width="904" alt="Screen Shot 2022-10-19 at 15 54 54" src="https://user-images.githubusercontent.com/13961762/196630672-ea8e1808-ca86-4f13-80f0-be19cb6e0b6c.png">

**Comment by eamodio** [comment]
In the Hovers section in the GitLens settings are they all enabled properly? Can you send all the `gitlens.*` and `editor.*` settings in your user `package.json`? Does this happen on all files? If you toggle on the File Blame do you see hovers?

**Comment by aimad-majdou** [comment]
I have the same issue, and these are my settings:

![image](https://user-images.githubusercontent.com/16216620/210244406-3cd646b5-e256-41b4-bf50-1b94a722b036.png)

**Comment by jkvim** [comment]
try to remove this line in settings.json
```
"gitlens.mode.active": "zen"
```

**Comment by hyposlasher** [comment]
@jkvim you are my hero. I helped! thank you!
