### ISSUE TITLE
line blame re-activates itself when opening a project

### ISSUE THREAD

**Issue by ivanschuetz** [gitkraken/vscode-gitlens#2263]
### Description

Always when opening a project line blame is automatically reactivated. I have to call "Gitlens: toggle line blame" to deactivate it. It should stay deactivated until manually activating it again.

### GitLens Version

12.2.2

### VS Code Version

Version: 1.72.0 (Universal)
Commit: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
Date: 2022-10-04T23:21:58.256Z (1 wk ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No

### Git Version

git version 2.37.0 (Apple Git-136)

**Comment by eamodio** [comment]
How are you "deactivating" it? If via the toggle command that is the designed behavior -- as it is just for the current session. If you want it to default it off, until you toggle it on via the command, you can turn off the line blame feature in the GitLens settings.

**Comment by ivanschuetz** [comment]
Ah that works, thanks!
