### ISSUE TITLE
pull request support for custom github domain (Github Enterprise)

### ISSUE THREAD

**Issue by tjx666** [gitkraken/vscode-gitlens#2266]
### Description

With settings: 

```
 "gitlens.remotes": [
        {
            "name": "origin",
            "type": "GitHub",
            "domain": "git.xxx.com",
            "protocol": "https",
            "urls": {
                "repository": "https://git.xxx.com/hammer/${repo}",
                "branches": "https://git.xxx.com/hammer/${repo}/branches",
                "branch": "https://git.xxx.com/hammer/${repo}/commits/${branch}",
                "commit": "https://git.xxx.com/hammer/${repo}/commit/${id}",
                "file": "https://git.xxx.com/hammer/${repo}?path=${file}${line}",
                "fileInBranch": "https://git.xxx.com/hammer/${repo}/blob/${branch}/${file}${line}",
                "fileInCommit": "https://git.xxx.com/hammer/${repo}/blob/${id}/${file}${line}",
                "fileLine": "#L${line}",
                "fileRange": "#L${start}-L${end}"
            }
        }
    ]
```

1. I can't see associated pull request in commits view
2. command `GitLens: Open Associated Pull Request` doesn't work

### GitLens Version

Insiders v2022.10.1405

### VS Code Version

Version: 1.73.0-insider (Universal)
Commit: 7ef8e6b87a2a5a25ba1ef946bd1640ca3510956c
Date: 2022-10-14T05:18:26.756Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: Yes

### Git Version

2.38.0

**Comment by tjx666** [comment]
maybe related to https://github.com/gitkraken/vscode-gitlens/issues/1845

**Comment by eamodio** [comment]
Can you try just setting the `gitlens.remotes` setting to:
```json
"gitlens.remotes": [{ "domain": "git.xxx.com", "type": "GitHub" }]
```

**Comment by tjx666** [comment]
I still can't see the associated pull request in remote:

![image](https://user-images.githubusercontent.com/41773861/196590858-8eb5272e-5f41-475b-a499-70d2377e1bef.png)

**Comment by tjx666** [comment]
I had opened a pull request which merge current branch to master on rmeote:

<img width="713" alt="image" src="https://user-images.githubusercontent.com/41773861/196591046-9060f8be-c4cb-494b-b3db-9e534155c437.png">

**Comment by eamodio** [comment]
@tjx666 Can you open the Remotes view and see if it says Connect to Remote or not?

![image](https://user-images.githubusercontent.com/641685/197248282-20885cbc-707f-4045-bfbc-5b875159aee8.png)

**Comment by tjx666** [comment]
My company github enterprise version is: 

<img width="298" alt="image" src="https://user-images.githubusercontent.com/41773861/197293226-07a51900-7db1-4e5d-a8b6-d9f87c287f51.png">

**Comment by eamodio** [comment]
Ah that version is too old for the apis we are using. We only officially support the "supported" versions of GitHub Enterprise. Though we currently do work many more versions back, just not that far.

We definitely need to improve the messaging there tho.

**Comment by eamodio** [comment]
Closing this and opened: https://github.com/gitkraken/vscode-gitlens/issues/2308
