### ISSUE TITLE
cherry-pick should wrap path with quote to deal with path contains space

### ISSUE THREAD

**Issue by tjx666** [gitkraken/vscode-gitlens#2271]
### Description

![image](https://user-images.githubusercontent.com/41773861/196391194-38e54a3b-23e8-4900-9253-2c054d458b2a.png)

### GitLens Version

v2022.10.1718

### VS Code Version

```
Version: 1.73.0-insider (Universal)
Commit: 1c78193f54fac6036829ec554ce218d99afc1f15
Date: 2022-10-18T07:28:15.245Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: Yes
```

### Git Version

2.38.0

**Comment by eamodio** [comment]
Sorry for the troubles on this one. Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by tjx666** [comment]
Had you checked https://github.com/gitkraken/vscode-gitlens/issues/2266 and  https://github.com/gitkraken/vscode-gitlens/issues/1845. I think these two issues are more serious. I subcribe the gitlen plus mainly because the github enterprise integrate for private project.

**Comment by eamodio** [comment]
@tjx666 those are unrelated this this issue and haven't gotten to investigate them yet (they aren't new from the GitLens 13 release).

**Comment by DBojsen** [comment]
@eamodio solution confirmed in todays release.  Thank you.
