### ISSUE TITLE
Viewing the commit graph makes VS Code hang

### ISSUE THREAD

**Issue by svenax** [gitkraken/vscode-gitlens#2272]
### Description

In a fairly small git repo, viewing the commit graph makes VS Code hang completely. I then have to force quit the program. I activated debug logs but am not seeing anything interesting. The Gitlens (Git) log is attached below. After a while some process consumes all available memory. 

This happens every time. It could be some other plugin that is causing this, but it is at least triggered by Gitlens.

### GitLens Version

v13.0.2

### VS Code Version

Version: 1.72.2
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:55.763Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No

### Git Version

git version 2.37.0 (Apple Git-136)

### Logs, Screenshots, Screen Captures, etc

![CleanShot 2022-10-18 at 14 03 49](https://user-images.githubusercontent.com/8472/196426475-4ecb7da0-a4b2-459b-9139-f023010963e4.png)

![CleanShot 2022-10-18 at 14 06 45](https://user-images.githubusercontent.com/8472/196425038-5fcbdc50-545c-43cc-ba08-0768fdf22ed3.png)

**Comment by eamodio** [comment]
Sorry for the troubles. Does the main `GitLens` log show anything abnormal (e.g. looping or anything)? What do you see when this happens? Does the Graph show at all? I assume you can't share this repo, so can you see if you see the same thing on a clean clone of it? Do you have a lot of stashes?

**Comment by svenax** [comment]
The graph shows up normally and immediately after that it hangs. The end of the GitLens log is attached. I don't think it shows anything out of the ordinary. I tested some more and it looks like all my repos where Bitbucket is remote hangs like this. Repos on Github seem to work OK.

![CleanShot 2022-10-18 at 16 49 50](https://user-images.githubusercontent.com/8472/196465221-70c3712f-254a-4fbf-bc44-59823b66233f.png)

**Comment by eamodio** [comment]
Can you try setting `"gitlens.graph.showDetailsView": false` in your user `settings.json` to see if it makes any difference -- this turns off the automatic openning of the Commit Details view, also please make sure that view is collapsed or closed.

**Comment by zioroboco** [comment]
I'm also seeing what I suspect is the same issue, except I've noticed that it seems to be caused by revealing the gitlens commit details view, which is opened automatically when the commit graph is opened.

I can answer some of these questions in my own case (using GitLens v13.0.2, VSCode v1.72.2, git v2.38.0):

> What do you see when this happens?

The git graph renders, followed by the commit details view, and then vscode immediately becomes unresponsive (noting that this also happens when the commit details view is opened independently of the git graph).

> Does the main GitLens log show anything abnormal (e.g. looping or anything)?

There is no output to the gitlens log prior to vscode crashing.

> can you see if you see the same thing on a clean clone of it? Do you have a lot of stashes?

This happens on all repos, including on a newly created repo containing a single commit.

**Comment by eamodio** [comment]
@zioroboco Can you try the same from here: https://github.com/gitkraken/vscode-gitlens/issues/2272#issuecomment-1282548009

**Comment by svenax** [comment]
Turning off `showDetailsView` seems to fix it for me.

**Comment by zioroboco** [comment]
@eamodio That prevents the commit details view from opening automatically, and hence I'm able to open the git graph without vscode crashing. However, if I open the commit details view, it still crashes.

**Comment by eamodio** [comment]
OK, great -- we've narrowed it down more. If either of you hover over the HEAD commit in the _Commits_ view -- do you see the hover show up appropriately?

Do either of you have any custom autolinks? Or custom remotes configured in GitLens? What hosting provider are your remotes pointing to (GitHub, GitLab, BitBucket, etc)?

**Comment by eamodio** [comment]
Also, if you keep the Graph closed, but open the Commit Details view, and open a file or select a commit in the _Commits_ view does it still crash?

**Comment by zioroboco** [comment]
> If either of you hover over the HEAD commit in the Commits view -- do you see the hover show up appropriately?

I see no hovers for commits in the git graph (but I'm not sure what I'd expect to see here either). Basically, nothing has a hover / tooltip-like thing show up except avatars, which shows the name of the committer.

> Do either of you have any custom autolinks? Or custom remotes configured in GitLens? What hosting provider are your remotes pointing to (GitHub, GitLab, BitBucket, etc)?

I can reproduce this on a brand new local repo with a single commit and no remotes.

**Comment by svenax** [comment]
Yes, the hover shows correctly. Interestingly I also get this hang in GitLens Preferences after selecting *GitLens: Configure Autolinks* in the command palette.

**Comment by zioroboco** [comment]
I'm also seeing hovers rendering correctly in the commits view.

**Comment by pomdtr** [comment]
I encounter the same issue on MacOS. The extension is also causing a crash when I open at the worktree view

**Comment by eamodio** [comment]
@svenax @zioroboco @pomdtr Do any of you have any custom autolinks configured in GitLens? Or custom remotes configured in GitLens? What hosting provider are your remotes pointing to (GitHub, GitLab, BitBucket, etc)? Did you connect GitLens to your remote host (GitHub or GitLab only)?

**Comment by pomdtr** [comment]
I'm only using github, and I don't remember customizing anything related to my remote.

Is there any settings I can look at to check this ?

**Comment by pomdtr** [comment]
It also hangs on my side (and I need to kill the process afterwise using the activity monitor).

**Comment by svenax** [comment]
I do not have any autolinks configured. However, as stated above, I get the same hang when selecting Configure Autolinks in GitLens Preferences so this may mean that autolinks are involved somehow. I have Github and Bitbucket remotes and the same issue occurs with both.

**Comment by eamodio** [comment]
Does opening `GitLens: Open Settings` from the Command Palette cause the same issue for all of you?

**Comment by eamodio** [comment]
@zioroboco & @pomdtr what OS/version are you on?

**Comment by svenax** [comment]
`GitLens: Open Settings` does not cause any issues, but `GitLens: Configure Autolinks` does every time.

**Comment by pomdtr** [comment]
MacOS Monterey (12.6)

**Comment by eamodio** [comment]
@svenax Really? Hrm -- they both open the same thing, except the `itLens: Configure Autolinks` just jumps down to the autolinks section. If you run `GitLens: Open Settings` and scroll down to the autolinks section does it also hang?

**Comment by svenax** [comment]
Hm, I swear the first time I tried, Open Settings did not cause a hang. But now it does so immediately, no need to scroll the view.

**Comment by eamodio** [comment]
Can you send your `settings.json` file to see if there is some "bad" data or something in there causing it.

**Comment by eamodio** [comment]
I'm really at a loss here. We've tried to reproduce this internally with the same OS version and VS Code versions and don't see any issues. It there anything special about your setups, your VS Code installation, or anything you can think of? Since it happens on the Settings page too, it seems extremely unlikely it would be repo related.

Could you try to install the Insiders version of VS Code to see if you see the same behavior or maybe try re-installing VS Code or even GitLens?

I've also asked here to see if there is anything known: https://twitter.com/eamodio/status/1583192217581424640

**Comment by pomdtr** [comment]
Would a screen share session help to debug the issue ? I've been a loyal user of the extension for multiple years, it it the least I can do :)

**Comment by eamodio** [comment]
@pomdtr I really appreciate that and might take you up on it. My thinking right now is that this is likely a VS Code issue.

And it could be a corrupted install, or something else -- so I would ask you to try those steps above first.

Also, if you open the `GitLens: Welcome (Quick Setup)` from the command palette does that also hang things? That is a simplier webview as compared to the Settings page.

**Comment by svenax** [comment]
@eamodio After yesterdays update of GitLens to version 13.0.3 everything seems to work for me. No hangs anywhere as far as I can see. As to what changed, I have no idea. The GitLens changelog says that something was updated for the details view. Maybe that also affected this issue?
Is it working for @zioroboco and @pomdtr too, or was I just lucky? 🙂

**Comment by eamodio** [comment]
Nothing intentionally changed in 13.0.3 (and very little actually changed). If it is truly resolved, I wonder if it was an installation issue -- something corrupted that the upgrade overwrote.

**Comment by pomdtr** [comment]
To check this, I did remove uninstall the extension, remove the `vscode/extension/<gitlens>` folder and install it again. I still encounter the issue :/

**Comment by pomdtr** [comment]
This is also maybe related to a vscode release. I did find out that the gitless extension (fork of gitlens `v11.7.2`) also triggers the error.

**Comment by eamodio** [comment]
@mjbvz @deepak1556 Any ideas here?

**Comment by pomdtr** [comment]
The issue is resolved on my end 🤷‍♂️

**Comment by eamodio** [comment]
@phyllisstein Sorry for the trouble, but I can't reproduce this on any of our machines, and GitLens (nor any extension with a webview) should not be able to hang VS Code -- unless there is a VS Code bug. @deepak1556 any ideas here?

@phyllisstein Can you also provide your OS and VS Code version?

**Comment by phyllisstein** [comment]
Thanks for offering to dig in! It seems to have worked itself out. Maybe it was a VSCode update, as some folks mentioned I also removed the macOS app, `$HOME/.code`, and `$HOME/Library/Application Support/Code`, then re-synced my settings back down, to make sure I wasn't holding bad state somewhere---which wouldn't surprise me. Sorry to have been tart about it! Thanks again for trying to troubleshoot.
