### ISSUE TITLE
Unable to sign commits with GitLens

### ISSUE THREAD

**Issue by hyoretsu** [gitkraken/vscode-gitlens#2274]
### Description

Simply set up GPG signing and try to commit through GitLens. You'll get a `Git: gpg failed to sign the data` error.

### GitLens Version

13.0.2

### VS Code Version

Version: 1.72.1 (system setup)
Commit: 129500ee4c8ab7263461ffe327268ba56b9f210d
Date: 2022-10-10T17:22:48.346Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22623
Sandboxed: No

### Git Version

gi version 2.34.1

**Comment by eamodio** [comment]
GitLens doesn't offer functionality to commit -- that is provided by VS Code itself. You'll need to open an issue on the VS Code repository for this, sorry!
