### ISSUE TITLE
Search commit by Sha not working in Gitlens side bar

### ISSUE THREAD

**Issue by nrubio-powellsoftware** [gitkraken/vscode-gitlens#2276]
### Description

In the Gitlens side bar, the commit search feature by SHA no longer works since the 13.0 update.
I always get the message "No results for xxxx".

Other filters works well.

### GitLens Version

13.0

### VS Code Version

Version: 1.72.2 (user setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.0740Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22622

### Git Version

git version 2.36.0.windows.1

### Logs, Screenshots, Screen Captures, etc

![image](https://user-images.githubusercontent.com/68747237/196728861-ae1645fe-9784-42bb-a3dc-ce6946dc8e09.png)

**Comment by christofjans** [comment]
I'm experiencing the same issue since the 13.0 update.

**Comment by xidianzhangjun** [comment]
> I'm experiencing the same issue since the 13.0 update.

+1
