### ISSUE TITLE
Primary side bar "Source Control" icon is duplicated

### ISSUE THREAD

**Issue by opensas** [gitkraken/vscode-gitlens#2279]
### Description

The Source Control icon on the Primary side bar is duplicated

I have the original Source Control icon and, apart from that, a new one handled by GitLens

This is the one from gitlens:

![image](https://user-images.githubusercontent.com/481687/196856553-6765f04a-3815-40b1-898a-5215f47b92ae.png)

and below it is the original one:

![image](https://user-images.githubusercontent.com/481687/196856591-1f0fece2-8ef5-463c-b329-394a42ba1f52.png)

Pressing Ctrl-Shift-U takes me to the original one

![image](https://user-images.githubusercontent.com/481687/196856790-f060ca9b-3e0a-4b10-b7b2-0d89daeb9a9a.png)

I tried uninstalling it several times with the same result

### GitLens Version

v13.0.2

### VS Code Version

Version: 1.72.2
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:16:26.920Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.4.0-86-generic
Sandboxed: No

### Git Version

git version 2.38.1

**Comment by opensas** [comment]
also a SO question I posted, just to keep track of it: https://stackoverflow.com/questions/74111434/how-do-i-restore-the-stashes-menu-in-visual-studio-codes-source-control-panel?noredirect=1#comment130862743_74111434

**Comment by eamodio** [comment]
Right-click on the icon and select "Reset location", or you might have to do it on each view itself. I've seen that happen in rare scenarios where vscode gets view containers mixed up.

**Comment by opensas** [comment]
Thanks a lot, that solved the problem.
