### ISSUE TITLE
Push and Pull buttons missing from the commits view w/ integrations disabled

### ISSUE THREAD

**Issue by UndefinedOffset** [gitkraken/vscode-gitlens#2281]
### Description

It looks like in version 13.0.0+ the push and pull buttons have gone missing from the commit view, this was a pretty handy feature.

**13.0.3**
![13-commits-view](https://user-images.githubusercontent.com/1391558/196969166-4474d114-3aa9-4aaa-a443-f1a56676b97f.png)

**12.2.2**
![12-commits-view](https://user-images.githubusercontent.com/1391558/196969502-9e6435ac-fc3b-4577-9cdd-817e082891d1.png)

### GitLens Version

13.0.3

### VS Code Version

Version: 1.72.2 (user setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19043
Sandboxed: No

### Git Version

git version 2.35.2.windows.1

**Comment by eamodio** [comment]
I can't reproduce this nor see how it could happen, unless the folder/workspace opened is untrusted or virtual, or the repository doesn't have any remotes. Are any of those the case here?

**Comment by eamodio** [comment]
Ah -- I see the bug now. Thanks!
