### ISSUE TITLE
Commit button doesn't work after solving merge conflicts

### ISSUE THREAD

**Issue by dylandifilippo** [gitkraken/vscode-gitlens#2287]
### Description

1. I merge the develop branch with my current branch
2. I resolve the conflicts
3. I stage the files
4. Cannot click on the commit button (disabled)
5. I have to use the command + return to be able to commit

### GitLens Version

13.0.3

### VS Code Version

Version: 1.72.0
Commit: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
Date: 2022-10-04T23:19:55.212Z (2 wks ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No

### Git Version

git version 2.37.2

### Logs, Screenshots, Screen Captures, etc

![commit problem](https://user-images.githubusercontent.com/53791026/197213470-f5a3de47-4bd8-454d-b39d-d7b4dc5d1751.png)

**Comment by d13** [comment]
GitLens doesn't provide the commit button, that feature is from VS Code itself. If you are having trouble with it, please [open an issue on the VS Code repository](https://github.com/microsoft/vscode/issues). Sorry!
