### ISSUE TITLE
Push button in BranchTrackingStatusNode of non-current branch does not trigger "Push force"

### ISSUE THREAD

**Issue by ShafinKhadem** [gitkraken/vscode-gitlens#2292]
### Description

From a non-current branch's BranchTrackingStatusNode, push button is not triggering "Push force" when it's supposed to. Instead it's showing "Cannot push; ..." Please see the screenshot gif.

### GitLens Version

13.0.3

### VS Code Version

Version: 1.72.2 (user setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No

### Git Version

git version 2.34.1

### Logs, Screenshots, Screen Captures, etc

![before](https://user-images.githubusercontent.com/26321479/197559483-b1b89169-a55d-4efe-bbcb-0fd971250b95.gif)

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's pre-release edition of GitLens?

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)

**Comment by ShafinKhadem** [comment]
I have verified that this has been fixed in pre-release edition of GitLens. Thanks.
