### ISSUE TITLE
Support Line History In Merge Editor

### ISSUE THREAD

**Issue by hediet** [gitkraken/vscode-gitlens#2297]
## Feature Request

The new merge editor in VS Code has 3 editor panes (4 if the base view is enabled).

It would be awesome if the GitLens line history could be supported in all 4 panes.
Currently it is only supported in the result view.

I think this feature would be a great addition to the merge editor and another compelling reason to install the GitLens extension.

## Implementation Details

The property `vscode.window.activeTextEditor` reflects which one of those 4 panes has focus:

* If the result view has focus, the document uri points to the actual file on disk. This is why the GitLens line history already works there.
* If any other pane gets focus, the uri looks like this:
    ```
    git:/c%3A/dev/microsoft/diff-merge-dataset/merge-git-playground/target.ts?%7B%22path%22%3A%22c%3A%5C%5Cdev%5C%5Cmicrosoft%5C%5Cdiff-merge-dataset%5C%5Cmerge-git-playground%5C%5Ctarget.ts%22%2C%22ref%22%3A%22%3A2%22%7D
    ```
    This is the decoded query part:
    ```
    {"path":"c:\\\\dev\\\\microsoft\\\\diff-merge-dataset\\\\merge-git-playground\\\\target.ts","ref":":3"}
    ```

    In case the *Base* pane is focused, `ref` is 1.
    In case the *Current* pane is focused, `ref` is 2.
    In case the *Incoming* pane is focused, `ref` is 3.

In case of a merge, there are the files `.git/ORIG_HEAD` and `.git/MERGE_HEAD`. `git merge-base` can be used to figure out which commit the `base` view shows.
Then, `git log` can be used to figure out the line history.

Please let us know what you think about this feature and the merge editor and if there is missing API that blocks implementing this feature request.
Thanks!

**Comment by eamodio** [comment]
@hediet Thanks for the feature suggestion! 

Why was a `ref` of 1, 2, or 3 chosen, rather than setting the ref to the appropriate SHA? If the `ref` param was the SHA, GitLens would "just work".

**Comment by hediet** [comment]
Good point! Didn't think about it.

(`ref` always works, even for stash conflicts, whereas SHA only works for merges and rebases)

**Comment by tpak** [comment]
I will add this here since it seems to be directly related. I just performed a merge and then "sync" to the origin repo and the Git Graph UI does not update to show that origin and local are in sync. Again, switching away and coming back forces a refresh and the UI then updates. 

<img width="700" alt="Screen Shot 2022-10-26 at 4 56 07 PM" src="https://user-images.githubusercontent.com/21483/198154425-b1c8dcf5-82a1-41f3-8bb7-fd5c59719f78.png">

**Comment by hediet** [comment]
Implemented upstream.
