### ISSUE TITLE
Unable to switch to upstream branch if an origin branch already exists with the same name

### ISSUE THREAD

**Issue by michaelweinold** [gitkraken/vscode-gitlens#2299]
### Description

I would like to switch to an upstream branch, but since I have an origin branch of the same name, switching is not possible:

```
[2022-10-28 07:11:59.820] /Users/user/.vscode/extensions/eamodio.gitlens-13.0.3/dist/gitlens.js:12:8193
Error: Command failed: /opt/homebrew/bin/git -c core.quotepath=false -c color.ui=false checkout -b main upstream/main --
fatal: a branch named 'main' already exists
```

### GitLens Version

v13.0.3

### VS Code Version

Version: 1.72.2
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:55.763Z (2 wks ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No

### Git Version

git version 2.37.2

### Logs, Screenshots, Screen Captures, etc

<img width="216" alt="Screenshot 2022-10-28 at 09 17 24" src="https://user-images.githubusercontent.com/23102087/198527163-f4984b4c-41fb-491f-b154-859272960fbd.png">

**Comment by michaelweinold** [comment]
Potentially related: https://github.com/gitkraken/vscode-gitlens/issues/709 and https://github.com/gitkraken/vscode-gitlens/issues/2163

**Comment by eamodio** [comment]
How are you trying to switch to that branch? When I tried GitLens asks me to create a new local branch.
