### ISSUE TITLE
Create Worktree button doesn't work in certain cases 

### ISSUE THREAD

**Issue by sedghi** [gitkraken/vscode-gitlens#2301]
### Description

Recently I cannot use the + button to create a worktree, basically the click on + does nothing

### GitLens Version

13.0.3

### VS Code Version

Version: 1.72.2 (Universal)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:16:30.254Z (2 wks ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No

### Git Version

git version 2.38.1

**Comment by eamodio** [comment]
While I've seen this once, I can't reproduce it. Do you have any more details when you see this? Do you have more than 1 repo loaded?

**Comment by sedghi** [comment]
No, I don't have more than one repo. How can I give more details?

**Comment by eamodio** [comment]
Can you maybe capture a video/gif of the behavior? 

Can you also please enable debug logging by running the _GitLens: Enable Debug Logging_ command from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ & _GitLens (Git)_ channels in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the logs from the _GitLens_ channel, and if its Git related please also attach the logs from the _GitLens (Git)_ channel.

Thank you!

**Comment by sedghi** [comment]
Funny thing, it works now! and I didn't update anything. I noticed this before that sometimes it works sometimes it does not. I will capture video and put logs here when it doesn't

**Comment by sedghi** [comment]
I have figured out when this happens. When there is more than one repository available in the GITLENS:Worktrees tab. As soon as I remove other repositories it works again

**Comment by eamodio** [comment]
Can you please verify this fix in the latest pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)

**Comment by d13** [comment]
LGTM!
