### ISSUE TITLE
Strange icon

### ISSUE THREAD

**Issue by bmarvinb** [gitkraken/vscode-gitlens#2302]
### Description

![CleanShot 2022-10-28 at 22 13 39@2x](https://user-images.githubusercontent.com/23120972/198714580-9635bb29-a845-467c-b677-d5a64ee72230.png)

When I select rebase icon with tag is looking strange, it doens't depens on theme, I think it's wrong, no? Border, and golder shadow look bad

### GitLens Version

13.0.3

**Comment by eamodio** [comment]
I'm not sure what the issue is here? That icon is a toggle for the quick pick to show tags or not.

**Comment by bmarvinb** [comment]
@eamodio why it has this border and shadow? It's different from other icons in a row

**Comment by eamodio** [comment]
Because it's a toggle (on / off) and in your screenshot it's on, e.g. selected. It basically follows the selection pattern of input toggles, but we don't have the ability to have it fully match the theme because of API limitations.

**Comment by bmarvinb** [comment]
it is not selected, it's the same. I recorded small video with demo, I clicked around this button, so it's not focused 
![CleanShot 2022-11-01 at 17 32 01](https://user-images.githubusercontent.com/23120972/199272931-f3109a18-3b6c-4ec7-a8d2-8af7bfd4b075.gif)


<img width="116" alt="CleanShot 2022-11-01 at 17 30 58@2x" src="https://user-images.githubusercontent.com/23120972/199272584-c6206d06-83bb-4fd6-915a-b049ec67dd4a.png">

**Comment by d13** [comment]
When I click to toggle the icon off, it loses the box:

https://user-images.githubusercontent.com/293282/199274341-91d75c7e-39f3-490e-be51-140f4f7e35fc.mov

**Comment by eamodio** [comment]
The box is indicating that the toggle is on, similar to input toggles: 

![image](https://user-images.githubusercontent.com/641685/199394863-73f1b488-8e95-4083-9821-3fff8c09c934.png)

This particular toggle, switches between showing and hiding tags.

![image](https://user-images.githubusercontent.com/641685/199394972-e34d7fb4-9580-4d09-b5fc-15968d42df53.png)
