### ISSUE TITLE
"Googlesource" gerrit only supports two levels of domain

### ISSUE THREAD

**Issue by Mattadore** [gitkraken/vscode-gitlens#2303]
### Description

1: try to use a domain with "googlesource" that has more than two levels of domain
2: it doesn't work :(

I work a "googlesource" repository that does not live on "googlesource.com" but uses "${domain}-review".  It might also make sense to just have the review url be a separate config variable templated from the base url, but for now this change is sufficient.

### GitLens Version

13.0.0

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's pre-release edition of GitLens?

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)
