### ISSUE TITLE
`gitlens.plusFeatures.enabled` not hiding GitLens+ subscription messages

### ISSUE THREAD

**Issue by segevfiner** [gitkraken/vscode-gitlens#2307]
### Description

1. Set `"gitlens.plusFeatures.enabled": false`.

I kinda expected it to also hide GitLens+ subscription messages from the status bar, bottom panel, sidebar, etc. But I have to hide them manually, does this setting even do anything ATM? It looks like plus features remain enabled even if I set it?

### GitLens Version

13.0.3

### VS Code Version

Version: 1.72.2 (Universal)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:16:30.254Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No

### Git Version

git version 2.38.1

**Comment by eamodio** [comment]
What subscription messages are you referring to? Can you post a screenshot?

The setting should hide all unavailable GitLens+ features -- e.g. a private repo without a GitLens Pro plan.

**Comment by d13** [comment]
I'm only able to reproduce the GitLens+ content showing on the Home View when `gitlens.plusFeatures.enabled: false`.

Can you post a screenshot of any others?

**Comment by segevfiner** [comment]
On a computer where a GitLens Plus/pro trial started without me asking and having `"gitlens.plusFeatures.enabled": false` the bottom Git Lens panel showed up.
