### ISSUE TITLE
Tree file icons are confusingly aligned

### ISSUE THREAD

**Issue by Timmmm** [gitkraken/vscode-gitlens#2309]
### Description

If you do `Compare working tree with master` for example, you get a file tree like this:

![image](https://user-images.githubusercontent.com/376842/199208443-7106d5ea-b40b-4fb6-a548-e395cd81c7ee.png)

This is really confusing because the entries for files are aligned *further left* than the entries for directories. It should look something like this:

![image](https://user-images.githubusercontent.com/376842/199209194-8effd399-b295-4b41-a1c6-64405c38398f.png)

### GitLens Version

13

### VS Code Version

VSCode 1.72.2, Mac, default themes.

**Comment by d13** [comment]
This alignment comes from a VS Code setting which is `8` by default:

```json
{
  "workbench.tree.indent": 8
}
```

![Screen Shot 2022-11-01 at 11 51 59 AM](https://user-images.githubusercontent.com/293282/199277649-30e3f415-feb8-4e33-a2fd-5827b89a107b.png)


For example, I increased it to 22 and got pretty close to the alignment I think you're looking for. Give it a try and see what works best for you. Hope that helps!


![Screen Shot 2022-11-01 at 11 51 45 AM](https://user-images.githubusercontent.com/293282/199278125-367f411c-2168-473e-89de-e54befab2cb3.png)

**Comment by eamodio** [comment]
Just to add a bit more context, VS Code handles the indent rendering and its been a long standing issue that with certain tree layouts, such as identified here (where the root node, e.g. `9 files changed`) has no icon, but children do the indentations get messed up.

I would encourage you or anyone to open an issue on the VS Code repository to get this resolved.

**Comment by eamodio** [comment]
Those are controlled by the VS Code File Icon theme.
