### ISSUE TITLE
Commit details secondary side bar banner doesn't stay dismissed

### ISSUE THREAD

**Issue by d13** [gitkraken/vscode-gitlens#2315]
Also, this small tip doesn't go away and when you click close it doesn't persist between sessions:

<img width="237" alt="Screenshot 2022-11-02 at 12 39 21 PM" src="https://user-images.githubusercontent.com/5606642/199440529-9fbf6c7e-4aee-4781-b275-4dc287bac112.png">

_Originally posted by @hakobpogh in https://github.com/gitkraken/vscode-gitlens/issues/2296#issuecomment-1299832960_

**Comment by d13** [comment]
Can you please verify this fix in tomorrow's pre-release edition of GitLens?

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78](https://user-images.githubusercontent.com/293282/200704748-f9f2686b-bb47-4a18-a122-5e1bf906c22e.png)

**Comment by d13** [comment]
One thing to note (I mentioned this [in another ticket](https://github.com/gitkraken/vscode-gitlens/issues/2329#issuecomment-1308015279)), VS Code doesn't tell us where the view is docked. 

With this fix, it will fix the issue of the banners re-appearing.

**Comment by hakobpogh** [comment]
I confirm that it keeps the "dismissed" state. I guess that's fine at least you don't need to dismiss it again and again.
