### ISSUE TITLE
Use Commit Details view for terminal links

### ISSUE THREAD

**Issue by eamodio** [gitkraken/vscode-gitlens#2320]
Also, I'd prefer seeing the commits panel on the side when I Cmd+Click on a git in the terminal.

_Originally posted by @hakobpogh in https://github.com/gitkraken/vscode-gitlens/issues/2296#issuecomment-1303153403_

**Comment by eamodio** [comment]
@hakobpogh Thanks for the suggestion!

Can you please verify this fix in tomorrow's pre-release edition of GitLens?

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)

**Comment by hakobpogh** [comment]
Yeah, It works. Now when you click on the commit hashes from the terminal, it opens the commit details view. The same is when you click on a row in the interactive rebase editor. But when you click on the commit hash, it still opens the popup. I've tested it on `v2022.11.604`.

**Comment by eamodio** [comment]
@hakobpogh awesome thank you. In tomorrow's pre-release I've also updated the commit sha link on the rebase editor to open the commit details view too (and focus it).
