### ISSUE TITLE
You should be able to reset to any commit in the commit graph

### ISSUE THREAD

**Issue by hakobpogh** [gitkraken/vscode-gitlens#2326]
I believe there should be a reset option on each commit to be able to reset to commit by just right-clicking on the item in the commit graph:

<img width="297" alt="Screenshot 2022-11-07 at 2 51 41 PM" src="https://user-images.githubusercontent.com/5606642/200292913-6c921ca0-49d5-436c-97c0-8b9036ac1829.png">

**Comment by hakobpogh** [comment]
This is especially helpful when you use rebases as your primary merging strategy. Then if you have one epic/story branch and you merge your features to it, frequently you might want to reset the local copy of your branch on the remote one, and the gitlens graph doesn't allow it.

To reproduce the case, create a branch on one computer, then push it. Then on some other computer, rebase and force push the same branch. Finally, on the first computer, fetch and try to reset your local branch on the remote. It just doesn't suggest resetting in the context menu at all. (You can see the photo)

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)

**Comment by hakobpogh** [comment]
I've tested it. Now it works. Thanks a lot.
