### ISSUE TITLE
FR: Remember UI settings in Commit Details panel

### ISSUE THREAD

**Issue by gdh1995** [gitkraken/vscode-gitlens#2329]
Recently GitLens added a `COMMIT DETAILS` panel, and I want to keep it as a collapsable panel in "Source Control" section of the sidebar, if I'm not viewing a commit. However, its default UI seems not configurable, make it not so convenient:
1. There's **almost always** a tip of `Move into Secondary Side Bar` at the top
2. There's a big `AUTOLINKS` sub-panel, and I want to keep it collapsed (or hidden if possible)

The most inconvenient issue is:
1. when I've read all I need in `FILES CHANGED`, I'll collapse the whole `COMMIT DETAILS` panel to save space for the panel of "commit message, button and file changes"
2. then when I view another commit and expand it again, the `Move into...` tip may occur again, and `AUTOLINKS` can also be auto expanded.
3. this means I have to do the 2 boring steps again and again

<details>
  <summary>Click here to show a snapshot</summary>
  <img src="https://user-images.githubusercontent.com/5547703/200460813-9081afcd-d90f-4add-a68c-5e730aa2c1e4.png" alt="snapshot">
</details>

**Comment by aminomancer** [comment]
I noticed a related issue — the `Move into Secondary Side Bar` tip repeatedly comes back for me, even though this view is actually in the secondary side bar already. Idk what the trigger is (maybe just reloading) but after dismissing the tip, eventually I'll notice that it's returned. So I guess in addition to remembering that the tip has been dismissed, it would also be good if it was aware that the view has already been moved to the secondary side bar.

**Comment by d13** [comment]
Thanks for your feedback! I'm tracking the tip not dismissing here: https://github.com/gitkraken/vscode-gitlens/issues/2315

**Comment by d13** [comment]
> it would also be good if it was aware that the view has already been moved to the secondary side bar.

Unfortunately, VS Code doesn't tell us where the view is docked ☹️

**Comment by d13** [comment]
Can you please verify this fix in tomorrow's pre-release edition of GitLens?

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78](https://user-images.githubusercontent.com/293282/200704748-f9f2686b-bb47-4a18-a122-5e1bf906c22e.png)

**Comment by sebastianzander** [comment]
For me the pre-release v2022.11.1104 does not fix the problem.

Still, whenever I switch the tab in the secondary side bar, either "Autolinks" is expanded or the "Move to Secondary Side Bar" notice is visible, again.
