### ISSUE TITLE
Scrollable option disappear when I try to hover on it

### ISSUE THREAD

**Issue by PawelNiedzwiecki** [gitkraken/vscode-gitlens#2331]
### Description

When I try to use hover annotations on particular line it, the annotation disappear when I try to hover on it. I'm using MacBook Pro M1 Pro chip.

- tried to disable all extentions except GitLens
- tried to reinstall VS Code
- tried using older GitLens version 

Nothing worked.

### GitLens Version

v13.0.4

### VS Code Version

Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-01T15:33:40.745Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No

### Git Version

git version 2.38.1

**Comment by eamodio** [comment]
Unfortunately VS Code controls how the hover behavior works and I know they made changes in the recent releases with the intent to make things better (and from my experience they mostly are). But if you are seeing specific issues getting the hover to not disappear, I would recommend opening an issue on the VS Code repository. It would also be great to get a GIF/video of the behavior you are seeing.

**Comment by PawelNiedzwiecki** [comment]
Thanks a lot @eamodio ! Will post it on VS Code. I have a feeling it might be even a MacOS issue but I will check with VSCode team first :)
