### ISSUE TITLE
Apply encodeURIComponent() to pieces of the custom remote URL

### ISSUE THREAD

**Issue by amir-f** [gitkraken/vscode-gitlens#2336]
### Description

We have set a _custom remote_ by specifying the following dictionary in the `.vscode/settings.json` file

```
"gitlens.remotes": [
    {
      "domain": "git.foo.com",
      "type": "Custom",
      "name": "Foo",
      "protocol": "https",
      "urls": {
        "repository": "https://foo.com/${repo}",
        "branches": "https://foo.com/${repo}/branches/master/",
        "branch": "https://foo.com/${repo}/browse/${branch}/",
        ...
      }
    }
  ],
```

However the branch name `${branch}` can itself have the `/` in it and this would make the URL invalid. What is the best way to apply **`encodeURIComponent()`** to the branch name? That is:

`https://foo.com/${repo}/browse/encodeURIComponent(${branch})/`

### GitLens Version

13.0.4

### VS Code Version

Version: 1.73.1 (Universal)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T02:08:38.961Z (22 hrs ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0

### Git Version

git version 2.37.0 (Apple Git-136)

**Comment by eamodio** [comment]
What are you seeing when you open a branch on this remote? I've tried the provided setup with branches with `/` in them and it seems works to work fine.

**Comment by amir-f** [comment]
The slash shows up in the URL but the server expect it to be URL encoded if it's the branch name. That is if the branch name is `ab/cd` This URL wont' work: `https://foo.com/some_repo/browse/ab/cd/` but this one does: `https://foo.com/some_repo/browse/ab%2Fcd/`

**Comment by eamodio** [comment]
Oh, hrm. What type of Git server is it?

**Comment by amir-f** [comment]
It's hosted using [Phabricator](https://secure.phabricator.com/book/phabricator/article/diffusion_hosting/)

**Comment by amir-f** [comment]
what other information is needed?

**Comment by eamodio** [comment]
Sorry I was travelling and the bot got to it before I labelled it appropriately.

**Comment by amir-f** [comment]
I see. I am not sure if it's Phabricator specific but fwiw this is an example URL pattern that works without `/` in the branch name:
`"fileInBranch": "https://phabricator.foo.com/${repo}/browse/${branch}/${file}${line}"`

so IIUC if there's a slash in `${branch}` it'll trip up the parser

**Comment by micahlt** [comment]
This would be a great (and fairly easy-to-do) addition!  The change would have to occur in https://github.com/gitkraken/vscode-gitlens/blob/fe5d12f93f825d4e8d5228bfd8fe449600877492/src/git/remotes/custom.ts

**Comment by eamodio** [comment]
The main issue here is that some providers need certain encoding and others done. To handle this, I've added alternate versions of all the tokens with a `_encoded` suffix, e.g. `${branch_encoded}` to allow for granular control over how the URL should be constructed.

NOTE, if you use any `*_encoded` tokens in the format string, we won't URL encode the whole URL, to give fine-grained control.

Can you please verify this fix in `v2023.5.25xx` pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by micahlt** [comment]
Thanks for the fast response!  It doesn't appear to have made any difference.  I switched to the prerelease version and verified that  I was on `2023.5.25xx`, and I changed `${branch}` to `${branch_encoded}`.  However, nothing has changed and the opening the branch `feat/calendar-embed` still results in an unencoded slash.

**Comment by eamodio** [comment]
Gotcha, I'll have to look into that. Do the copy commands work for you?

**Comment by micahlt** [comment]
That's odd, yes they do.

**Comment by micahlt** [comment]
It appears that only the actual `Open` commands are still broken.
