### ISSUE TITLE
Local remotes are incorrectly treated as private

### ISSUE THREAD

**Issue by AnouarDoukkali** [gitkraken/vscode-gitlens#2342]
hello folks , I just started to learn git ... so  i'm using git bundles to save a backup of the local repository with : 
`git bundle create ./backup/thisRepoBackup --all`
but when i try to restore it with : `git clone thisRepoBackup `  and visualise commits with commits-graph  gitlens ask to extend to gitlens+ 
could you add this feature to gitlens free ? otherwise how can i take a snapshot of the current repository to restore it later ?

**Comment by eamodio** [comment]
@AnouarDoukkali Can you show where GitLens is asking for GitLens+? That only happens for GitLens+ features -- Graph, Worktrees, Visual File History, and self-hosted GitHub/GitLab integrations on private repositories. And a private repository is determined by the reachability of the remotes configured on the repository.

**Comment by AnouarDoukkali** [comment]
@eamodio here's a [screenshot ](https://imgur.com/VZPhOXz) of the message after cloning a local bundle backup

**Comment by eamodio** [comment]
Do you have remotes configured for that repository? What do you see in the Remotes view?

**Comment by AnouarDoukkali** [comment]
@eamodio I see the  path of the local bundle backup  file  [screenshot](https://i.imgur.com/3LGbF3B.jpg)

**Comment by eamodio** [comment]
@AnouarDoukkali Ah -- that's a GitLens bug. We aren't correctly identifying that remote as a "local" remote.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)

**Comment by AnouarDoukkali** [comment]
@eamodio yessss it's working on the pre release version :) Thank you very much !
