### ISSUE TITLE
copying abbreviated commit SHAs is not working 

### ISSUE THREAD

**Issue by AnouarDoukkali** [gitkraken/vscode-gitlens#2344]
### Description

**commits SHAs are not abbreviated when copied to clipboard from commit details , or commit graph .**

### gitlens settings: 
 **"gitlens.advanced.abbreviatedShaLength": 7
 "gitlens.advanced.abbreviateShaOnCopy": true**
 
**Feature:**
**could a setting be added to always copying abbreviated SHA to clipboard whenever a commit is selected from the graph ?**

### GitLens Version

pre-release v2022.11.1204

### VS Code Version

Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

### Git Version

git version 2.38.1.windows.1

**Comment by eamodio** [comment]
> Feature: could a setting be added to always copying abbreviated SHA to clipboard whenever a commit is selected from the graph

Please open a separate feature request for this. Although to be honest it doesn't feel like a feature we'd add unless it was highly requested by the community. At the same time adding some keyboard shortcuts to copy the sha, etc would definitely be doable.

**Comment by AnouarDoukkali** [comment]
@eamodio a shortcut could be helpful too 👍🏻

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)

**Comment by AnouarDoukkali** [comment]
gitlens version : pre-release v2022.11.1404

still not working . it copy the full sha

**Comment by eamodio** [comment]
Sorry for the confusion, it won't be in until tomorrow's build, v2022.11.1504.
