### ISSUE TITLE
Allow adding keyboard shortcuts to Graph commits & stashes

### ISSUE THREAD

**Issue by AnouarDoukkali** [gitkraken/vscode-gitlens#2345]
it would be helpful if we can set a  shortcut in the command palette  to copy the abbreviated SHA.

**Comment by eamodio** [comment]
In tomorrow's pre-release edition of GitLens, you should be able to set your own keyboard shortcuts for many _Commit Graph_ commands.

Keyboard shortcuts can be applied to many of the `gitlens.graph.*` commands and should use `gitlens:webview:graph:focus && !gitlens:webview:graph:inputFocus` for their "When Expression" to only apply when the _Commit Graph_ is focused.

For example, add the following to your `keybindings.json` to allow <kbd>Ctrl</kbd>+<kbd>C</kbd> to copy the selected commit's SHA to the clipboard

```json
{
    "key": "ctrl+c",
    "command": "gitlens.graph.copySha",
    "when": "gitlens:webview:graph:focus && !gitlens:webview:graph:inputFocus"
}
```

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)

**Comment by eamodio** [comment]
@axosoft-ramint @d13 please verify this one. FYI, not all Graph commands will work, only commands that target a commit or stash.

**Comment by axosoft-ramint** [comment]
@eamodio Verified that it works for a few commands (copy SHA, copy message, refresh graph) on the latest pre-release.

**Comment by d13** [comment]
@eamodio this works for me as well

**Comment by eamodio** [comment]
Thanks!

**Comment by AnouarDoukkali** [comment]
@eamodio it works , thank you 👍🏻
