### ISSUE TITLE
Inline annotations are duplicated when there are multiple selections in the same line

### ISSUE THREAD

**Issue by YonatanGreenfeld** [gitkraken/vscode-gitlens#2346]
### Description

In every editor, create multiple cursors on the same line, and the inline annotation will be duplicated per cursor.

### GitLens Version

13.0.4

### VS Code Version

Version: 1.72.2 (Universal)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:16:30.254Z (1 mo ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No

### Git Version

git version 2.38.1

### Logs, Screenshots, Screen Captures, etc

![image](https://user-images.githubusercontent.com/100685375/201667673-05ffddb4-8258-41e0-b5e7-429756f5d93e.png)

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)

**Comment by YonatanGreenfeld** [comment]
Will do!

**Comment by YonatanGreenfeld** [comment]
Looking good!
![image](https://user-images.githubusercontent.com/100685375/202143592-7c547aa0-d815-49c9-9bc1-fa3a8688fcf5.png)
