### ISSUE TITLE
The scroll bar will be displayed when the cursor moves over commit message

### ISSUE THREAD

**Issue by zhiyiYo** [gitkraken/vscode-gitlens#2348]
### Description

As shown in the figure below, a scroll bar appears on the pop-up prompt
![image](https://user-images.githubusercontent.com/65096819/201802256-535a698e-d489-4fb1-a2d8-f72dd1a7bdae.png)

### GitLens Version

v2022.11.1404

### VS Code Version

Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22623

### Git Version

git version 2.38.1.windows.1

**Comment by eamodio** [comment]
Unfortunately, that is a bug in VS Code itself. Can you please [open an issue](https://github.com/microsoft/vscode/issues/new?assignees=&labels=&template=bug_report.md) on the VS Code repository? Thanks!
