### ISSUE TITLE
Commits and Branches views don't automatically refresh when using separate-git-dir

### ISSUE THREAD

**Issue by Molkree** [gitkraken/vscode-gitlens#2349]
### Description

1. Let's say we have a separate worktree and repository folder (.git). As an example create a new folder `worktree`, cd in it, and run `git init --separate-git-dir ..\example.git` to create a repository outside of worktree.
2. Then open VSC, create an empty file `file.txt`, and commit it (any message, "example commit" will do).
3. Commits and Branches views still show "No commits could be found." and require me to hit the "Refresh" button to see the commit.

In this example, I have committed myself, but the same issue is extended to pulling in a real repository, I have to refresh both views to see the changes.

P.S. I've also noticed that if I open the new Commit Graph page, then the Commits view will refresh without me hitting the "Refresh" button but the Branches view will not.

### GitLens Version

v2022.11.1504 (but current stable too, I've only checked preview afterwards)

### VS Code Version

Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

### Git Version

git version 2.38.1.windows.1

**Comment by agido-freudenreich** [comment]
I've the same problem since the last update.
We have a monorepo with a single git repository.
If I add the entire monorepo folder the repository is found and listed as expected. But if I open only a specific folder, in my case via the workspace feature, the repository is no longer found.
Worked before without any problems.

**Comment by agido-freudenreich** [comment]
@eamodio Thanks a lot, works!

**Comment by Molkree** [comment]
@eamodio, yes, everything appears to be refreshing correctly in the pre-release version. Thank you!
I'm not sure how you manage issues here so I'll let you decide if to close this now or when the rework lands in stable.

**Comment by eamodio** [comment]
Great thanks!
