### ISSUE TITLE
Add `monospace` formatting in commit messages

### ISSUE THREAD

**Issue by sebastianzander** [gitkraken/vscode-gitlens#2350]
I regularly use the backticks (`) to mark certain words in my commit messages like functions, classes, etc. In GitHub this is even translated to a monospace formatting, at least if it is in the first line of the commit message, like e.g.:

![github_monospace_commit_message](https://user-images.githubusercontent.com/11301464/202375969-90af46ec-a45b-4ad6-85d7-eecb411d4cff.jpg)

If the commit message has more than one line, the others will in general be formatted in monospace on GitHub.

I would love to see GitLens supporting monospace spans where ever a commit message appears, most importantly in the Commit Details and in the tooltip that appears whenever you hover the mouse pointer over a commit.

Best regards
Sebastian

P.S. love your extension ❤️

**Comment by axosoft-ramint** [comment]
Verified in latest pre-release
