### ISSUE TITLE
'GitLens: Compare working three with...' Not able to select branch using keyboard

### ISSUE THREAD

**Issue by itacud95** [gitkraken/vscode-gitlens#2354]
### Description

I am using GitLens latest version V13.1.0, installed from vscode extension. 

When comparing working three with branch, I used to be able to select which branch to compare with using the keyboard. After a update I am no longer able to use the keyboard to select branch to compare, I have to select which branch using the mouse. 

This is the 'window' which does not respond to keyboard events: 
![image](https://user-images.githubusercontent.com/25989444/202648788-b7c82119-96c8-4e78-9cd2-14a40299587a.png)

### GitLens Version

V13.01.0

### VS Code Version

Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T03:54:53.913Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.78-1-MANJARO
Sandboxed: No

### Git Version

git version 2.38.1 (linux)

**Comment by eamodio** [comment]
It looks like there was a recent behavior change to VS Code quick pick UI which sets focus incorrectly in certain cases. We've made a change to avoid that case so this should now be resolved.

FYI, if you press `Tab` the quick pick will move the focus into the input and everything should work as expected.
