### ISSUE TITLE
Search by changes stops working in version 13.x.x

### ISSUE THREAD

**Issue by hieu-n** [gitkraken/vscode-gitlens#2355]
### Description

Search by changes works fine in version 11.x.x and version 12.x.x, but returns no result in version 13.x.x.

### GitLens Version

13.1.0

### VS Code Version

Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T03:54:53.913Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-53-generic snap
Sandboxed: No

### Git Version

git version 2.25.1

### Logs, Screenshots, Screen Captures, etc

Search by changes in version 13.x.x:
![Screenshot_20221118_163901](https://user-images.githubusercontent.com/6425119/202670800-eaf69d8c-e130-4677-8a51-7810b30f99cb.png)

Search by changes in version 12.x.x:
![Screenshot_20221118_142935](https://user-images.githubusercontent.com/6425119/202670946-446bd763-0756-4b7c-bb6c-6904bccd732b.png)

**Comment by gchmiel** [comment]
Same issue with version 13.2.0

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)
