### ISSUE TITLE
File history becomes unavailable when the workspace contains private repo

### ISSUE THREAD

**Issue by ZeroRin** [gitkraken/vscode-gitlens#2362]
### Description

When there are multiple repos in the workspace (adding submodule, opening multiple folders within a workspace, etc.) and one of them is private, the file history becomes unavailable for the whole workspace.
In contrast, commit graph will treat each repo in the workspace differently

### GitLens Version

13.1.1

### VS Code Version

Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.17763
Sandboxed: No

### Git Version

git version 2.32.0.windows.2

**Comment by d13** [comment]
Could you provide a link to the public repo?

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)
