### ISSUE TITLE
my dev linux (redZone) could not connect to Internet， how to fix the 3 days or 7 days trial warning if 7 days later, I could not use gitlen13.1.1 any more? what a pity!

### ISSUE THREAD

**Issue by huanghx1990** [gitkraken/vscode-gitlens#2371]
### Description

1. My dev environment is Centos6.9 but could not connected to world wide website, So I could not register or login in my gitlens account.
2. Is it means that I could not use gitlens13.1.1 any more after 3 days or 7 days trial?

### GitLens Version

13.1.1

**Comment by d13** [comment]
GitLens is COMPLETELY FREE, NO ACCOUNT or anything, and can be used on ANY repo (local/public/private/etc).

GitLens+ features on local & public repos are also COMPLETELY FREE, NO ACCOUNT or anything. 

**ONLY GitLens+ features on private repos** require a Pro plan (or greater).

**Comment by eamodio** [comment]
@huanghx1990 So you don't have internet access at all in your dev environment? If that is the case, unfortunately we don't have a solution for accessing GitLens+ features without some access to the internet.
