### ISSUE TITLE
Missing Azure Devops Icon

### ISSUE THREAD

**Issue by schummar** [gitkraken/vscode-gitlens#2377]
### Description

Commit graph shows empy space instead of an origin icon for Azure Devops repositories. Devtools show that it tries to load an icons, which is missing:

`https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/marco/.vscode-server/extensions/eamodio.gitlens-13.1.1/images/dark/icon-vsts.svg`

I guess the icon has been removed at some point. There should either be a specific icon or some fallback.

### GitLens Version

13.1.1

### VS Code Version

Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

### Logs, Screenshots, Screen Captures, etc

![image](https://user-images.githubusercontent.com/2988557/204292779-446fe4ea-3e00-4a72-b58b-ccb5b5f4721e.png)

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)

**Comment by schummar** [comment]
Yes, it fixed in today's Pre-Release. Thank you.
