### ISSUE TITLE
can't use scrollbar in 'Commit Graph' view

### ISSUE THREAD

**Issue by Spongman** [gitkraken/vscode-gitlens#2381]
Type: <b>Bug</b>

clicking on the scrollbar in the 'Commit Graph' view causes a click event through to the commit beneath the scrollbar which causess the secondary sidebar to open on the right to that commit, moving the scrollbar and stopping the scroll.

- open the 'Commit Graph' view (containing a full screen of commits)
- click on a commit
- ensure that the commit info pane shows in the secondary sidebar on the *right*
- close the secondary sidebar
- drag the scrollbar in the 'Commit Graph' view:
  - the click goes 'through' the scollbar thumb and clicks the commit underneath
  - the secondary sidebar opens to show that commit
  - the 'Commit Graph' view shrinks to accommodate the secondary sidebar
  - the scrollbar is 'dropped'

Extension version: 13.1.1
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Connection to 'ssh-remote+fw.dfcn.com' could not be established
Remote OS version: Linux x64 4.4.0-19041-Microsoft
Remote OS version: Linux x64 3.10.0-957.1.3.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|47.66GB (5.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|31%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|37.34GB (24.32GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|37.34GB (24.32GB free)|
|VM|0%|

Connection to 'ssh-remote+fw.dfcn.com' could not be established

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2901)|
|Memory (System)|47.66GB (5.40GB free)|
|VM|31%|

|Item|Value|
|---|---|
|Remote|SSH: dropsy.corp.aetheros.com|
|OS|Linux x64 3.10.0-957.1.3.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU           X5570  @ 2.93GHz (16 x 1596)|
|Memory (System)|94.24GB (85.65GB free)|
|VM|0%|
</details>

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)

**Comment by axosoft-ramint** [comment]
Cannot reproduce on Windows 10 x64 in latest pre-release.

**Comment by Spongman** [comment]
much better, thanks!
