### ISSUE TITLE
GitKraken Web Typo

### ISSUE THREAD

**Issue by lukasong** [gitkraken/vscode-gitlens#2384]
### Description

**Where is the bug found:** https://www.gitkraken.com/github-student-developer-pack

**What is the bug:** Under the "GitLens" section of the webpage, there is a typo stating "benefit from additional d features like" (notice the additional d).

Sorry if this is the wrong place to submit something small like this, but I was unsure as to where else. Thanks for making such an awesome product and helping out us students o/

### GitLens Version

13.0.0

**Comment by d13** [comment]
Thanks for letting us know! We'll get it updated.

**Comment by d13** [comment]
> If you don’t already have GitKraken Cient and GitLens Installed:

This needs to be updated as well.
