### ISSUE TITLE
Hide/Show Menu options don't seem to work

### ISSUE THREAD

**Issue by X-lem** [gitkraken/vscode-gitlens#2393]
### Description

1. Open file that git tracks
2. Click "prev revision" icon
3. Right click menu
4. Check and Uncheck "next change" (you'll notice the file annotations icon appear/disappear)
5. There are several other show/hide items that don't seem to do what they are supposed to

I've uninstalled/reinstalled gitlinse/restarted VS code and this hasn't changed. Note: I'm using VS Code in WSL.

![image](https://user-images.githubusercontent.com/6555273/207675341-754fe7aa-3848-48e3-8296-78d059bc2a2b.png)

### GitLens Version

13.1.1

### VS Code Version

Version: 1.74.0 (user setup)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:38:16.075Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

### Git Version

git version 2.25.1

**Comment by eamodio** [comment]
@X-lem That menu hiding is provided directly by VS Code. My guess as to what is happening is that VS Code only allows a certain number of commands (icons) to be visible in that bar, so when you hide one, one of the others that weren't explicitly hidden but were pushed out of view, now have the space to be shown.

Although if that isn't the case, any issues here would need to be filed against the VS Code repository.

Thanks!
