### ISSUE TITLE
Work in progress file diff compares working tree with working tree, instead of working tree with head

### ISSUE THREAD

**Issue by AndreyDodonov-EH** [gitkraken/vscode-gitlens#2394]
### Description

Work in progress file diff compares working tree with working tree, instead of working tree with head
(see screencast below for details).

It results in not showing any differences.

### GitLens Version

Tried with 13 and 13 pre-prease

### VS Code Version

Version: 1.74.0
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:47:18.476Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-56-generic snap
Sandboxed: No

### Git Version

git version 2.34.1

### Logs, Screenshots, Screen Captures, etc

![GitLenseIssue](https://user-images.githubusercontent.com/44361144/207825172-70c737a7-86c2-4bf3-8b58-b28a1466e330.gif)

**Comment by eamodio** [comment]
Can you please verify this fix in the latest pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)

**Comment by eamodio** [comment]
@AndreyDodonov-EH sorry, the CI had an issue, the pre-release is out now.

**Comment by d13** [comment]
LGTM
