### ISSUE TITLE
Two refresh button in right click of commit

### ISSUE THREAD

**Issue by mohanbabu-zumen** [gitkraken/vscode-gitlens#2406]
### Description

Steps to Reproduce:

Expand commits on the left side and right-click it.
It shows two refresh button

Ref: https://github.com/microsoft/vscode/issues/169631#issuecomment-1361030498

![image](https://user-images.githubusercontent.com/102032328/208866009-97159d7a-6b78-4efa-997c-9057bc7d540a.png)

### GitLens Version

13.2.0

### VS Code Version

1.74.1 (user setup)

### Git Version

git version 2.37.2.windows.2

**Comment by eamodio** [comment]
It looks like you might have 2 editions of GitLens installed at the same time. Please ensure only 1 edition (stable or insiders) is installed and enabled.

Thanks!

**Comment by mohanbabu-zumen** [comment]
Thanks for the reply
