### ISSUE TITLE
Commit Graph Show Current Branch Only shows unrelated commits from other branches

### ISSUE THREAD

**Issue by RARelph** [gitkraken/vscode-gitlens#2409]
### Description

On a freshly installed VSCode (1.74.2) + GitLens (13.2.0) on MacOS (13.0.1), I'm trying to display the git log using GitLens Commit Graph with the Show Current Branch Only filter option. Several commits on unrelated branches still appear.

If I hover over the branch name on the left side of the Commit Graph, the unrelated commits dim. I simply want them to not appear at all.

### GitLens Version

13.2.0

### VS Code Version

Version: 1.74.2 (Universal)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:26:09.430Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.1.0
Sandboxed: No

### Git Version

git version 2.37.1 (Apple Git-137.1)

**Comment by eamodio** [comment]
Can you provide a screenshot of that? Are the commits in the parent chain of a stash? Does hiding stashes or tags make them go away?

Any more details you can provide would be greatly appreciated. Thanks!

**Comment by RARelph** [comment]
![image](https://user-images.githubusercontent.com/44270374/209010529-b656ea22-eae7-4fe8-aad7-6b8f340ed860.png)

Note that this was taken with the mouse hovering over the milan-mainline branch. Note the filter is selected to be Show Current Branch Only, but the unrelated commits displayed, but dimmed. There are no stashes.

But, yes, clicking on "Hide Tags" does address the issue. I would like to see tags... but only those on the current branch.

**Comment by eamodio** [comment]
Thanks! That definitely helps! We'll get that fixed!

**Comment by axosoft-ramint** [comment]
Should be addressed in the latest prerelease - graph dependency updated: https://github.com/gitkraken/vscode-gitlens/commit/184d831bea442691d50a655baca266fe26d94b75

**Comment by axosoft-ramint** [comment]
Can you please verify this fix in tomorrow's pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)
