### ISSUE TITLE
autolinks go to wrong remote URL

### ISSUE THREAD

**Issue by jfirebaugh** [gitkraken/vscode-gitlens#2425]
### Description

1. With a repository configured with two remotes:
  * `upstream`, pointing to the upstream source repository
  * `origin`, pointing to a personal fork
  (this is the configuration you end up with if you clone and fork via VSCode using the [GitHub Pull Requests and Issues extension](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github))
2. Now click an autolink generated by vscode-gitlens, for instance one pointing at a PR or issue.

Expected behavior: it opens the PR or issue on the original (`upstream`) repository.
Actual behavior: it opens a URL on your personal fork that 404s. You have to hand-edit the URL, replacing the user/org portion with the appropriate value.

### GitLens Version

13.2.0

### VS Code Version

Version: 1.74.2 (Universal)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:26:09.430Z (1 wk ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No

**Comment by mdebbar** [comment]
I had the same issue with [Githubinator](https://marketplace.visualstudio.com/items?itemName=chdsbd.githubinator) but I found a setting to fix it:

![image](https://github.com/gitkraken/vscode-gitlens/assets/1278212/ab63b1fb-770a-43cb-b8bc-ec9d42e01d31)

GitLens, on the other hand, doesn't provide such a setting (or at least I didn't find it). Please consider making this configurable to improve the experience of working in personal forks. Thanks!

(I'm also happy to contribute a fix if someone could point me in the right direction).

**Comment by eamodio** [comment]
Autolinks, similarly to the `Open * on Remote` and `Copy Remote * URL` commands, use a heuristic on trying to figure out the "best" remote if there is one, or the user can set the "default" remote that we should use in the _Remotes_ view.

![image](https://github.com/gitkraken/vscode-gitlens/assets/641685/fde66171-77f8-4dbd-9412-5ba054d4f377)

That default isn't a "setting" (so not in config), it is saved specifically for the current folder/workspace.

So, if you set your `upstream` to be the default, it should behave as you want. Note, there is caching so some things might not change until you reload/refresh views.

Alternatively, you can also connect GitLens to GitHub and autolinks get "enriched" with real data from GitHub.

I've also improved our heuristic for picking the "best" remote in https://github.com/gitkraken/vscode-gitlens/commit/d10f86753cd634fc80742a0b3fe452c027af97ba, which should be in tomorrow's pre-release.

Hope that helps!
