### ISSUE TITLE
Branches aren't sorting in date order correctly

### ISSUE THREAD

**Issue by callumgare** [gitkraken/vscode-gitlens#2436]
### Description

Despite setting my branches panel to sort branches by recent commit date the order does not appear to be connected to the date:
![Screenshot from 2023-01-06 13-11-44](https://user-images.githubusercontent.com/346340/210916231-77b2faaa-23ce-43fa-8dc0-65535123be65.png)
![Screenshot from 2023-01-06 13-11-35](https://user-images.githubusercontent.com/346340/210916245-3581a5a5-e191-403e-9a46-1b746730e90c.png)
Interestingly the order appears to be wrong in a different way if I change between ascending and descending date sorting.

If check the order the branches using `git branch --sort=committerdate` and `git branch --sort=-committerdate` they are sorted as expected:
![Screenshot from 2023-01-06 13-12-37](https://user-images.githubusercontent.com/346340/210916660-979a7fac-ed86-4658-901c-c551c5222ed8.png)
![Screenshot from 2023-01-06 13-14-17](https://user-images.githubusercontent.com/346340/210916676-d4b08e0c-249d-44e6-bb90-f8c4df9dcb64.png)

### GitLens Version

v13.2.0 (although the issue has happened for as long as I have been using GitLens for)

### VS Code Version

Version: 1.74.2
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:27:19.253Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-56-generic snap
Sandboxed: No

### Git Version

git version 2.34.1

**Comment by jkelroy** [comment]
Hello @callumgare, from your first screenshot, I can see that you have the branches `390-new-GA-events` and `beta` favorited, which will keep them at the top of the branch list. If you would like these branches to be sorted with the rest, you can hover over the branch and select the star icon to stop favoriting. 

From what I can see, the rest of the branches are sorted as expected.

![210916231-77b2faaa-23ce-43fa-8dc0-65535123be65](https://github.com/gitkraken/vscode-gitlens/assets/27739784/39bca578-a1b6-4063-a958-80f82cfa175b)
