### ISSUE TITLE
Dim merge commits setting wins over highlighted rows (e.g. search)

### ISSUE THREAD

**Issue by eamodio** [gitkraken/vscode-gitlens#2442]
So if you have _Dim Merge Commits Rows_ enabled, and then run a commit search that has merge commits in the search results, they will still end up being dimmed. Instead the highlight should win over the dimming.

**Comment by axosoft-ramint** [comment]
Should be fixed after updating to the latest graph component: 7758326ea366d7ef9d7acb9823794cb8faa91ad7

**Comment by eamodio** [comment]
Looks good -- thanks!
