### ISSUE TITLE
commit graph support hide BRANCH/TAG column

### ISSUE THREAD

**Issue by tjx666** [gitkraken/vscode-gitlens#2455]
this column takes up to much space:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/213009152-cb363673-cc3b-4628-b6cb-278037d5e4bb.png">

What more:

We can show branch name to tooltop here:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/213009503-664610ad-b76c-4ae6-86c8-b43367982238.png">

like git history is more clear:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/213009873-97935018-205d-4559-8a49-2e530b2c9d8a.png">

**Comment by tjx666** [comment]
@eamodio 

This column take up too much space, especial for small screen user.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/220992940-88003578-2eed-490b-9907-74b67299500d.png">

**Comment by tjx666** [comment]
Git history is more neat:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/220993591-e6bf55fe-55d2-4082-9b46-203f9baa0854.png">

**Comment by pallxk** [comment]
You can hide BRANCH/TAG column or others by right clicking on column header.

<img width="368" alt="Screenshot 2023-05-13 at 07 46 56" src="https://github.com/gitkraken/vscode-gitlens/assets/2920525/31e64ee4-afe0-462a-beb1-7785390bfa60">

The graph layout can also by changed to compact to save more space.

**Comment by eamodio** [comment]
You can also now shrink both the Branch/Tag and Author columns to icons, and compact the Graph column and get a streamlined experience: 

![image](https://github.com/gitkraken/vscode-gitlens/assets/641685/f1cefbdc-33d8-45dd-a86f-b4229b798395)

**Comment by eamodio** [comment]
This shipped in 13.6
