### ISSUE TITLE
Gitlens Remote provider doesn't work properly in "Commit graph" view

### ISSUE THREAD

**Issue by MrLuje** [gitkraken/vscode-gitlens#2460]
### Description

1. We have a self-hosted gitlab instance and use ssh for git connection
2. I added the following setting 
```yaml
"gitlens.remotes": [
  {
    "type": "GitLab",
    "domain": "git.mycompany.fr",
  },
]
```
3. In "Branches" view, I can use "Open branch on remote" fine
4. In "Commit graph" view, right-click on a branch and select "Open branch on remote"
5. It doesnt work : "No auto-detected or configured remote providers found..."

### GitLens Version

13.2.0

### VS Code Version

Version: 1.74.3 (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z (1 wk ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

### Git Version

git version 2.34.1

### Logs, Screenshots, Screen Captures, etc

This one works fine :
![image](https://user-images.githubusercontent.com/632075/213672894-c531bbaa-0610-45ba-acdd-3e8cbb5c442d.png)

This one doesn't 
![image](https://user-images.githubusercontent.com/632075/213672985-2bd3441f-0277-4b33-9cfb-47cf8ca479dd.png)

![image](https://user-images.githubusercontent.com/632075/213673436-8fa68adf-ebf4-4f43-8614-730121f604b1.png)

**Comment by Igorgro** [comment]
Having same issue. Moreover, when I click "Create Pull request" it doesn't open interface for creating merge request on GitLab

**Comment by vindby23** [comment]
May be your type should be github
it worked for me
type": "GitHub",

**Comment by axosoft-ramint** [comment]
Fixed in commit: https://github.com/gitkraken/vscode-gitlens/commit/fe6b26928ac77ed73f5066bf14398a205627b41e

**Comment by axosoft-ramint** [comment]
Can you please verify this fix in the pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)
