### ISSUE TITLE
My commits don't show up. 

### ISSUE THREAD

**Issue by Jhonmacc** [gitkraken/vscode-gitlens#2470]
### Description

My Vscode in the Gitlens in Source Control tab my commints never appear or the commints tab keeps on an infinite search and never brings the commints or histories to perform code comparisons.
I already reinstalled and vscode and removed all extensions but unfortunately without success.

<img width="294" alt="214691401-1185c223-adf7-4efe-92ed-743eb4f065b0" src="https://user-images.githubusercontent.com/20972080/214842416-03556284-605c-4b4a-a848-ada6f4423025.png">

SO: Windows 11

### GitLens Version

13.2.0

### VS Code Version

Version: 1.74.3 (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No

### Git Version

git version 2.39.1.windows.1

### Logs, Screenshots, Screen Captures, etc

<img width="294" alt="214691401-1185c223-adf7-4efe-92ed-743eb4f065b0" src="https://user-images.githubusercontent.com/20972080/214842848-a4acc9ad-2c00-41b5-b373-283cb0565294.png">

**Comment by d13** [comment]
Can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the both _GitLens_ and _GitLens (Git)_ channels.

Thank you!
