### ISSUE TITLE
Commit graph status bar show wrong last fetched date

### ISSUE THREAD

**Issue by ws333** [gitkraken/vscode-gitlens#2473]
### Description

Seems like the commit graph status bar last fetched date is not updated and stuck on 01.01.1970.

![Screenshot 2023-01-20 at 03 17 58](https://user-images.githubusercontent.com/22876520/215053929-6169b6d9-c191-4d74-803d-89dc634d6cf3.png)

Everything seemed to work besides this glitch.

I'm om a MacBook Pro M1 w/Monterey v12.6.2

### GitLens Version

13.2.0

### VS Code Version

Version: 1.74.3
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T17:05:47.808Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No

### Git Version

2.39.1

**Comment by jtanaka** [comment]
That happens when I open the window on the worktrees branches.

**Comment by ws333** [comment]
> That happens when I open the window on the worktrees branches.

Yes, same here, I was on a git worktree branc.

**Comment by d13** [comment]
I think I narrowed this down to any freshly cloned repo where the fetch has not been called yet.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)

**Comment by ws333** [comment]
> Can you please verify this fix in tomorrow's pre-release edition of GitLens? Thank you so much!
> 
> You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.
> 
> ![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)

@eamodio I just had a trial for a few days so not able to test it now.

@d13 The issue I found was with a worktree branch in a "old" repo, so not a freshly cloned repo. Anyway it might still have been fixed in the Pre-Release.

**Comment by ws333** [comment]
@eamodio Yes, I can confirm that the fetch date gets updated in the Pre-Release version 👍
