### ISSUE TITLE
Docs: Link to Revision Navigation is broken

### ISSUE THREAD

**Issue by guettli** [gitkraken/vscode-gitlens#2487]
### Description

This is the correct link: https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens#revision-navigation

But the heading links to: https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens#revision-navigation-

I am on a PR which fixes this.

### GitLens Version

13.2.0

**Comment by eamodio** [comment]
This unfortunately is a marketplace bug (which I've filed with them in the past) -- and those changes break GitHub links.
