### ISSUE TITLE
Open worktree command: list incomplete

### ISSUE THREAD

**Issue by AurisAudentis** [gitkraken/vscode-gitlens#2523]
### Description

In version 13.2, my worktree list (correctly) looks like this:
<img width="535" alt="image" src="https://user-images.githubusercontent.com/1330205/221194061-85a0391b-d9e2-4196-b090-b08f526d8545.png">
List is continued after the end of the screenshot.

In version 13.3, the open worktree list (incorrectly) looks like this:
<img width="610" alt="image" src="https://user-images.githubusercontent.com/1330205/221193850-b6b5aef2-cdd1-4ae5-98fc-808c451acef7.png">

### GitLens Version

13.3.0

### VS Code Version

Version: 1.75.1 (Universal)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z (2 wks ago)
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No

### Git Version

git version 2.37.1 (Apple Git-137.1)

### Logs, Screenshots, Screen Captures, etc

<img width="535" alt="image" src="https://user-images.githubusercontent.com/1330205/221194061-85a0391b-d9e2-4196-b090-b08f526d8545.png">
<img width="610" alt="image" src="https://user-images.githubusercontent.com/1330205/221193850-b6b5aef2-cdd1-4ae5-98fc-808c451acef7.png">

**Comment by d13** [comment]
I'm unable to reproduce this issue, unfortunately.

Can you please enable debug logging by running the _GitLens: Enable Debug Logging_ command from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ & _GitLens (Git)_ channels in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the logs from the _GitLens_ channel, and if its Git related please also attach the logs from the _GitLens (Git)_ channel.

Thank you!

**Comment by eamodio** [comment]
@AurisAudentis As @d13 mentioned logs would be great, but are those screenshots both from the repo at exactly the same point? Meaning if you do nothing but switch between GL 13.2 and 13.3 you see that difference?

**Comment by AurisAudentis** [comment]
Logs of the gitlens channel:
https://gist.github.com/AurisAudentis/ccd6af10ec084de37dc4e489b985687b
I don't seem to have any GitLens (Git) channel, but do have Git channel. Logs from that:
https://gist.github.com/AurisAudentis/5fa9b9ace4780a34068c4164d698b6b0

@eamodio I can confirm this is exactly the same repository. All I do is downgrade/upgrade, reload dev settings.
Please let me know if I can help with further data!

**Comment by eamodio** [comment]
@AurisAudentis We've made changes to Worktrees in the latest version, can you try it and see if this is still an issue for you?

And if so, what is the output of `git worktree list --porcelain` from the terminal?

**Comment by AurisAudentis** [comment]
@eamodio Thanks for looking into this! Have just upgraded both vscode and the plugin, but it unfortunately does not seem fixed. 

Worktree list output, seems short enough to just drop here:
```
maxiemgeldhof@OTA-MaxiemGeldhof-MBP-4DJK3 master % git worktree list --porcelain
worktree /Users/maxiemgeldhof/development/um
bare

worktree /Users/maxiemgeldhof/development/um/master
HEAD ab4b3862688f68a224c4e4d4a1a2e5c72a8460c5
branch refs/heads/revert-5158d7e0

worktree /Users/maxiemgeldhof/development/um/master.worktrees/cpq
HEAD 6eb221b42a682cdf3b2ecdff7ee517be8f399f3a
branch refs/heads/cpq-395-salesforce-service

worktree /Users/maxiemgeldhof/development/um/master.worktrees/cpq-392-salesforce-app
HEAD 52cbd1f32c74358fb825e1421ba4dc95f1bef572
branch refs/heads/cpq-402-implementing-features

worktree /Users/maxiemgeldhof/development/um/master.worktrees/TO-1309-parity-shop-regression-tests
HEAD 9145ca0bb0c2b606496ac452890c1c2922a08169
branch refs/heads/TO-1309-parity-shop-regression-tests

worktree /Users/maxiemgeldhof/development/um/master.worktrees/TO-1322-liveshop-staging-script
HEAD 2cd70243b8be801599bc499f9d94ea4687f7810d
branch refs/heads/TO-1292-liveshop-schedule-script
```

**Comment by AurisAudentis** [comment]
Hey guys! Is there anything more I can do for you?

**Comment by eamodio** [comment]
@AurisAudentis I'm so sorry for not getting back to you on this. Is this still an issue for you?
