### ISSUE TITLE
Expired version

### ISSUE THREAD

**Issue by austinbutler** [gitkraken/vscode-gitlens#2531]
### Description

I get this error `This GitLens pre-release version (2023.2.1404) has expired. Please upgrade to a more recent version.` and the extension doesn't work/load.

Based on https://github.com/gitkraken/vscode-gitlens/issues/2246 I though this was supposed to be resolved by now. At any rate, is the warning necessary, let alone not loading the extension?

### GitLens Version

2023.2.1404

### VS Code Version

Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:35:30.018Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Linux x64 6.2.0
Sandboxed: No

### Git Version

git version 2.39.1

**Comment by d13** [comment]
Older versions of Pre-release and Insiders expire after a couple weeks. The intent is for these to be updated regularly for early use and feedback as we publish new versions of Pre-release and Insiders everyday. Updating to latest pre-release will resolve your issue.

Normal release versions don't have that expiration as they are stable releases.

(#2246 was an issue from when we first tried using the pre-release feature in the VS marketplace and it was expiring way too soon which has been resolved.)

**Comment by austinbutler** [comment]
How does one determine a pre-release versus normal release on the marketplace? https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens

**Comment by d13** [comment]
The easiest way to see if you're version is a by clicking on the GitLens from the extensions sidebar and look for a "Pre-Release" badge. There's button below the version number to switch between Release and Pre-Release versions. A reload may be required after switching.

![Screen Shot 2023-03-02 at 3 05 35 PM](https://user-images.githubusercontent.com/293282/222540648-e6c52242-7815-4662-8163-062b1c9e218e.png)
