### ISSUE TITLE
Allow a default branch for "Open Changes >" and allow that to be the default on-click for a file

### ISSUE THREAD

**Issue by justinlulejian** [gitkraken/vscode-gitlens#2545]
When I've completed a large change I like to review all the changes I've made across all my commits compared to my upstream and make last-minute changes before uploading. This helps to catch those pesky printf()-style debugging statements that you've skimmed over when working on a hard problem and want to avoid submitting. 

The way to do this is:
1) Expand Search & Compare
2) Right-click the file and hover "Open Changes >"
3) Select "Open Changes with Branch or Tag"
4) Select "origin/main" (or whatever your upstream branch is)
5) This open a view in which you can compare and quickly edit the file (to remove)

Any other way either a) defaults to a different revision (last commit, which is empty...) or b) open the file in read-only mode so you can't edit it.

So my proposal is an extension settings that:
1) allows you to change the behavior such that when you left-click on the file after 1) above it will default to the "Open Changes with Branch or Tag" functionality
2) allows you to set the default of "Open Changes with Branch or Tag" to upstream
3) allows you to set this behavior to be the default on-click behavior so that simply clicking the file opens this view.

With this it would save many clicks on larger commits and greatly improve my productivity when cleaning up changed for review.

**Comment by eamodio** [comment]
@justinlulejian I've attached a video that shows a few ways that GitLens, I believe, supports what you are asking for. If not please let me know.


https://user-images.githubusercontent.com/641685/226033708-be657db5-1b5c-4b2d-b3f8-01b3ea192b76.mp4
