### ISSUE TITLE
GitLens keeps showing the Commit Details view automatically

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [gitkraken/vscode-gitlens#2554]
### Description

The relatively new "Commit View" panel in the Source Control menu automatically appears and opens itself regularly. Every time, I disable the panel through the context menu, but it gets reenabled at least when I reopen VSCode. I understand that you think this panel is helpful, but I don't need or use it; my panel space is very limited because I regularly handle large lists of remote repositories and branches. As any regular panel, it should stay removed and closed permanently and across program restarts when the user requests to do so.

### GitLens Version

13.3.2

### VS Code Version

Version: 1.76.0 (user setup)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:22:44.506Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

### Git Version

git version 2.39.1 (WSL Debian), git version 2.34.0.windows.1

**Comment by eamodio** [comment]
@kleinesfilmroellchen I assume you mean the "Commit Details" view, but not 100% sure -- can you show a GIF/video of it re-enabling itself when it shouldn't?

**Comment by kleinesfilmroellchen** [comment]
> @kleinesfilmroellchen I assume you mean the "Commit Details" view, but not 100% sure -- can you show a GIF/video of it re-enabling itself when it shouldn't?

Yes, that's the name.

**Comment by kleinesfilmroellchen** [comment]
https://user-images.githubusercontent.com/28656157/225573548-f79dfd92-f8e7-4578-8930-9f7b57bf9684.mp4

The most reliable reproducer I found was interactive rebase (the command alias I'm using is executing `git rebase -i --autosquash HEAD~10`), but there may be others.

**Comment by eamodio** [comment]
@kleinesfilmroellchen if this only happens for the _Rebase Editor_ or the _Commit Graph_, then there are settings to control this behavior:

For the _Rebase Editor_

![image](https://user-images.githubusercontent.com/641685/225770433-e9bdbc2e-f726-48b1-bd5b-8e4375781817.png)

For the _Commit Graph_

![image](https://user-images.githubusercontent.com/641685/225770526-4569e213-c0b8-4cc1-bcd3-483c6ab1d639.png)

Let me know if that solves the issue for you. Thanks!

**Comment by kleinesfilmroellchen** [comment]
Yes, this solves the issue.
