### ISSUE TITLE
Support user defined color setting for inline blame

### ISSUE THREAD

**Issue by jinglesthula** [gitkraken/vscode-gitlens#2558]
Near as I can tell, the extension uses the decorations API and internally specifies the color for the inline blame foreground and background.  This is ok, but contrast is not great, and is especially hard to see with a dark theme enabled.

Would love to see settings exposed to control this, like "gitlens.currentLine.foreground", "gitlens.currentLine.background", and "gitlens.currentLine.border".  This would make the accessibility much better.

**Comment by eamodio** [comment]
GitLens currently supports many theme customizable colors. For the inline blame the colors are (the names are old and didn't want to break backward compat):

`gitlens.trailingLineBackgroundColor`
`gitlens.trailingLineForegroundColor`

If you open the extension page for GitLens (from the Extension view) and switch to the "Feature Contributions" tab you can see all the themeable colors

![image](https://user-images.githubusercontent.com/641685/225463737-a263c6e2-c135-436b-94c0-910fea62d8ff.png)

Hope that helps!
