### ISSUE TITLE
Suuport open associated pull request without open a file

### ISSUE THREAD

**Issue by tjx666** [gitkraken/vscode-gitlens#2559]
For now, you can't open associated pull request if not focus to a file.
The opend pull request should relatived latest remote commit of current branch.

https://user-images.githubusercontent.com/41773861/224124267-5b76627c-5c21-41f5-944f-3390cf9d97ef.mov

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)

**Comment by tjx666** [comment]
I suggest next time you send above message add the version number:

![image](https://user-images.githubusercontent.com/41773861/225807873-60291c85-a76b-45d6-8467-f518b90a82ae.png)

**Comment by tjx666** [comment]
@eamodio I can verify the new feature work, but here doesn't show that pr:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/226091399-99728cc3-5890-450f-b9f6-650b87580533.png">

https://github.com/gitkraken/vscode-gitlens/issues/2555

**Comment by d13** [comment]
This is verified, I can open the associated pull-request with no files open
