### ISSUE TITLE
VSCode GitLens extension doesn't work any more, only shows ads and wants me to sign in somewhere

### ISSUE THREAD

**Issue by thomiel** [gitkraken/vscode-gitlens#2563]
### Description

GitLens has been a cool VSCode extension in the past. Since some time it just won't work, only displays ads and wants me to start a trial. Why has it been crippled that way?

I also tried the "Connect to GitHub" button, which didn't react. The extension seems to be completely disfunctional currently.

### GitLens Version

13.3.2

### VS Code Version

Version: 1.76.1 (system setup)
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:32:00.131Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

### Git Version

2.30.2

**Comment by thomiel** [comment]
Is it possible that GitLens has problems with Windows folders paths like `\\wsl.localhost\debian\home\some_user\some_project` ?

**Comment by thomiel** [comment]
Note that the native Source Control works as expected (provided that the WSL extension is installed to allow VS Code to run on the WSL2).

**Comment by thomiel** [comment]
Yes, it actually did help. Thanks.

Are you planning to programmatically detect if the extension freezes on a WSL during startup and offer or suggest to turn http proxy support off?

**Comment by eamodio** [comment]
@thomiel Can you provide more details on "extension freezes on a WSL during startup", since even if there are issues (proxy or otherwise) with connecting/validating GitLens+ there *should* be NO issues with all of GitLens' core features (which is everything outside the new GitLens+ only features -- Commit Graph, Visual File History, and Worktrees).

**Comment by eamodio** [comment]
Also in regards to your title: "VSCode GitLens extension doesn't work any more, only shows ads and wants me to sign in somewhere"

GitLens doesn't require you to sign in or anything UNLESS you are trying to use the GitLens+ features (e.g. Commit Graph, Visual File History, and Worktrees) on a private repository. So, we definitely would love to understand what you are seeing so more details and logs, and/or screenshots/video could be very helpful. Thanks!

**Comment by thomiel** [comment]
It's just that GitLens signin, Pro Trial and Connect to GitHub were the only options I had. There was no Contributors section. Appeared to me like a paywall.

**Comment by d13** [comment]
Resolved with aa81444dfabb33dca8c887fb773c520868ed7320
