### ISSUE TITLE
hide context menu in output panel

### ISSUE THREAD

**Issue by tjx666** [gitkraken/vscode-gitlens#2566]
### Description

1. open aoutput panel
2. right click to open context menu

### GitLens Version

v13.3.2

### VS Code Version

Version: 1.76.1 (Universal)
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:32:09.831Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No

### Git Version

git version 2.39.2

### Logs, Screenshots, Screen Captures, etc

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/224568106-8f760a4c-b7fe-4ce0-ab2d-12829c29890e.png">

**Comment by hahaaha** [comment]
I think i can try to fix this problem :)

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)

**Comment by hahaaha** [comment]
@eamodio hello~, I try to verify this fix, but find not work.  So I'm check the commit, find you add `gitlens:activeFileStatus =~ /tracked/` , i'm not true why you add this code snippet.  maybe we can talk about this section.
ps: I new open pr to fix this issue, i'm verify this pr can work. If have any problem, please tell me. we can talk about too.

**Comment by tjx666** [comment]
ref: https://github.com/streetsidesoftware/vscode-spell-checker/issues/2580#event-8747657636

**Comment by eamodio** [comment]
@hahaaha a better fix went in last night and is in today's pre-release version. It also covered all the commands that could be added to the editor context menu.

@tjx666 I'm not sure what your comment was about?

**Comment by hahaaha** [comment]
> @hahaaha a better fix went in last night and is in today's pre-release version. It also covered all the commands that could be added to the editor context menu.
> 
> @tjx666 I'm not sure what your comment was about?

nice~👍
