### ISSUE TITLE
Change Open Commit Details command to Toggle Commit Details

### ISSUE THREAD

**Issue by Eduardogbg** [gitkraken/vscode-gitlens#2578]
So currently there's no command to close the commit details view, which is a bit annoying. Various panels have commands which toggle them, meaning you can use the same shortcut to open the view and then to close it. I think it would be beneficial to have this command for the commit details view.

**Comment by eamodio** [comment]
VS Code provides commands to close the sidebar, panel, or secondary side bar -- what are you looking for that would be different than those?

**Comment by Eduardogbg** [comment]
Well, I didn't know about this, my bad. I guess it is more desirable to just use the secondary side bar shortcut than to change the behaviour for the commit details then. Thanks.
