### ISSUE TITLE
File history doesn't match Line history & file blame view

### ISSUE THREAD

**Issue by cegekaJG** [gitkraken/vscode-gitlens#2579]
### Description

I had to move some files from a subfolder to its parent folder, essentially renaming them all. In order to preserve the history, I added `-CC` and later `-CCC` to `gitlens.advanced.blame.customArguments` to have git look across files. As a result, the Line History sidebar View, Current File Blame and File Blame View all show the correct history. Unfortunately, the File History View still only lists the most recent commit as the entire history. I'm guessing the file history uses different arguments from the other blame features, but is it possible to correct this?

### GitLens Version

13.3.2

### VS Code Version

Version: 1.76.2 (user setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.20348
Sandboxed: No

### Git Version

git version 2.39.0.windows.1

### Logs, Screenshots, Screen Captures, etc

![image](https://user-images.githubusercontent.com/120664985/225615778-3bf4b6a1-a953-4883-97a0-193802a6451a.png)

**Comment by eamodio** [comment]
Sounds like we may need to add the equivalent of `gitlens.advanced.blame.customArguments` for the log calls in the file history.

**Comment by cegekaJG** [comment]
After some searching I found the setting `gitlens.advanced.fileHistoryFollowsRenames` which does what I asked for. Since my original request has been fulfilled, I'll close this issue.

![image](https://user-images.githubusercontent.com/120664985/225856973-af5f8e9d-17cb-4dd8-acb3-bf379bfdd048.png)
