### ISSUE TITLE
Exclude A File in gitignore

### ISSUE THREAD

**Issue by gidimiz** [gitkraken/vscode-gitlens#2580]
Hi.

Im using PlatformIO with gitglens and ihave a complete folder in the gitignore. Im trying to to exclude a file to be added to the git, but nothing works. 
I tried adding a ! before the file as the default of gitignore, that didnt help. I also tried to add to the .git\info\exclude file the path and that also didnt help.
Can you advise if im missing anything or this is a missing feature? 
Regards.

**Comment by eamodio** [comment]
@gidimiz I'm not sure I understand the problem you are having. Are you having an issue with GitLens? Or is this a Git issue/question?

If you are trying to have Git (and by proxy VS Code & GitLens) ignore a folder, you can just add the folder name to a `.gitignore` file at the root of your repository.

Does that help? Or can you provide more details?

**Comment by gidimiz** [comment]
@eamodio  Thanks for the quick reply.
Yes, im using GtLens. No, I dont know where the issue is coming from.
I know how to add to ignore a folder. But from inside that folder I do want to add a file to back it up. 
i.e. If I have a folder to ignore:
lib/*
and I do want to git a file from in that folder, usually I will:
!lib/readme.txt
But this doesnt work and its not comparing this file to the git.
I hope its more clear now.

**Comment by eamodio** [comment]
This sounds like a Git question and still unsure how this relates to GitLens. But using `!lib/readme.txt` should indeed "unignore" `lib/readme.txt`, so what is the problem you are seeing?

**Comment by gidimiz** [comment]
@eamodio Its not effecting the list of files. Using ! doesnt change the anything and the file is still ignored.

**Comment by eamodio** [comment]
List of files where? In the VS Code Source Control view? Can you provide a screenshot?

**Comment by gidimiz** [comment]
![0QEKT5aW1Y](https://user-images.githubusercontent.com/13189923/225894851-df3d9dbd-1489-458c-81cc-5bed6e398eff.png)
Even if I change the file in config.h, its still ignored and I dont see it in the source control.

**Comment by eamodio** [comment]
That area of VS Code is provided by the built-in Git extension for VS Code, not GitLens. So you'd need to open an issue on the VS Code repository.

To ensure it is a VS Code issue, and just not a Git issue -- when you run `git status` in the terminal do you see your `config.h` file listed? If so, then this is a VS Code bug, if not, then it's some issue with your `.gitignore` (though it looks ok to me -- assuming the path is correct) or a Git issue (unlikely).

**Comment by eamodio** [comment]
FYI, you can figure out why Git is ignoring your file by running `git check-ignore -v FILE-NAME`. It should tell you the ignore pattern that matches the filename and which config file the pattern came from.
