### ISSUE TITLE
After adding submodule the gitlens not showing the change list

### ISSUE THREAD

**Issue by sfaroy** [gitkraken/vscode-gitlens#2608]
### Description

I work in vscode in remote linux environment. I have a project with 4-5 submodules (depending on the branch...) and after adding the 5th submodule, the "source control" panel where I see the change list stopped functioning. Instead of viewing the changes in the project and all of its submodule, I have a single "Publish Branch" button.

### GitLens Version

13.4.0

### VS Code Version

Version: 1.72.0 (user setup)
Commit: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
Date: 2022-10-04T23:20:39.912Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

### Git Version

2.17.1

### Logs, Screenshots, Screen Captures, etc

![image](https://user-images.githubusercontent.com/3100892/228064133-c8613dd2-cba0-4945-baaf-54bd0a801666.png)

**Comment by jkelroy** [comment]
Hello @sfaroy, Source Control is offered by VS Code so you will need to [open an issue](https://github.com/microsoft/vscode/issues/new?assignees=&labels=&template=bug_report.md) on the VS Code repository. Thanks!
