### ISSUE TITLE
If you check out a branch that is hidden, GitLens should show the branch still

### ISSUE THREAD

**Issue by jkelroy** [gitkraken/vscode-gitlens#2609]
### Description

When you have a hidden local branch and you check it out, it would be nice if the branch was automatically shown still.

1. Right-click a local branch > Hide
2. Check out that branch

### GitLens Version

13.4.0

### VS Code Version

Version: 1.76.2
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:53:46.528Z (1 wk ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes

### Git Version

git version 2.37.1 (Apple Git-137.1)

**Comment by axosoft-ramint** [comment]
Fixed in the latest graph version.

**Comment by axosoft-ramint** [comment]
Can you please verify this fix in tomorrow's pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)

**Comment by d13** [comment]
Verified
