### ISSUE TITLE
GitLens does not honor VS Code telemetry settings after install

### ISSUE THREAD

**Issue by tdworz** [gitkraken/vscode-gitlens#2612]
### Description

This report is a follow-up to a negative review I wrote about GitLens. You may see my frustrated review and the response by Eric from GitKraken on the reviews page: https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens&ssr=false#review-details (I don't see any way to link directly to my review so if you are viewing this issue far in the future, my review may no longer exist at this link).

The problem I have is that GitLens does not respect my global VS Code telemetry settings after installation. I would expect for GitLens to either (a) comply with my settings for VS Code telemetry or (b) make it abundantly clear that VS Code telemetry settings are not being honored and direct me to manually choose whether or not I want telemetry to be enabled or disabled.

### GitLens Version

13.4.0

### VS Code Version

Version: 1.76.2
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:57:21.103Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 6.2.8-arch1-1
Sandboxed: No

### Git Version

2.40.0

### Logs, Screenshots, Screen Captures, etc

I have recorded my screen installing GitLens for you to see the exact behavior I experienced. While I did uninstall GitLens to re-install it in the recording (meaning the installation on the video is not technically a clean install on a system that has never had GitLens installed), I assure you the behavior in the video is the behavior I experienced when I did install GitLens for the first time.

Here is the video documenting my experience: https://www.youtube.com/watch?v=hlJdn11P2MQ

**Comment by d13** [comment]
Thanks for taking the time to open an issue and record a video. This video has been super helpful in understanding your concern!

Our code checks that BOTH the VS Code telemetry setting `"telemetry.telemetryLevel"` AND  the GitLens setting `"gitlens.telemetry.enabled"` are enabled. As noted by Eric in the review, you can verify this in our code: 

https://github.com/gitkraken/vscode-gitlens/blob/c65b6fded3dff1936ae93dfafef4eceb30359873/src/telemetry/telemetry.ts#L69-L87

`env.isTelemetryEnabled` is the VS Code Setting and `configuration.get('telemetry.enabled', undefined, true)` is the GitLens setting. 

**Both must be on.** If either are disabled... no telemetry. 

I hope this clarifies things, but you could also verify using a network sniffer to feel confident about this.

To help avoid confusion in the future, [we've added a note (89eeceb)](https://github.com/gitkraken/vscode-gitlens/commit/89eeceb9ec54b53d8d5780ed36d21425cd64c656) to our setting that telemetry will ONLY be collected if BOTH the setting and VS Code telemetry are enabled.

**Comment by eamodio** [comment]
Thanks again for taking the time to help us understand this.

Here is the updated setting description in the commit @d13 noted:

![image](https://user-images.githubusercontent.com/641685/228717447-8548a1a5-0b07-4cc6-872a-0606dcfcf5a1.png)

That will be in tomorrow's pre-release and next week's stable release.

**Comment by tdworz** [comment]
Thank you for your prompt response. I think this alleviates my concerns.

Strictly related to UI as I understand actual behavior now -- I'm curious, why not just have the box unchecked when VS Code telemetry is disabled? That seems like a cleaner approach to UI than leaving the box checked with your detailed explanation.

**Comment by eamodio** [comment]
@tdworz Those settings are the user-chosen settings (user-level, workspace-level, or even folder-level). We don't write settings without user interaction. And unfortunately, VS Code doesn't offer the ability to control enablement of settings or (as far as I know) have the default of a setting dependent on another setting.
