### ISSUE TITLE
Setting to turn off suggested commit messages

### ISSUE THREAD

**Issue by mullaney** [gitkraken/vscode-gitlens#2618]
The generated commit messages is an interesting idea, but in practice the suggestions have been wildly off and distracting. **Could you add a setting so that we can turn this off?** (Personally, I think it should be off by default for now).

For anyone running into this problem, I think this effectively shuts it off:

```
"gitlens.experimental.generateCommitMessagePrompt": "Use 0 words, and 0 characters"
```

**Comment by d13** [comment]
GitLens will only generate messages when you run the `GitLens: Generate Commit Message (Experimental)` Command.

I would double check other extensions providing AI Assistance, example:
<img width="692" alt="Screen Shot 2023-04-03 at 6 32 48 PM" src="https://user-images.githubusercontent.com/293282/229641803-b92dbb38-045d-4858-a77f-7355dc553c12.png">
