### ISSUE TITLE
Gitlens+ features not unlocked with GitKraken Teams account

### ISSUE THREAD

**Issue by umdstu** [gitkraken/vscode-gitlens#2624]
### Description

When logged into my account (Plan: GitKraken Teams), I'm still getting prompted to upgrade to Pro, and it's also indicating i'm using GitLens Free. GitKraken Teams is suppose to include everything from Pro, so this is unexpected behavior.

```
[2023-04-07 08:56:33.579] ClientRequest.<anonymous>
FetchError: request to https://api.gitkraken.com/gitlens/checkin failed, reason: getaddrinfo ENOTFOUND api.gitkraken.com
[2023-04-07 08:56:33.587] Om.checkInAndValidateCore
Error: Unable to validate account; status=undefined: undefined
```

### GitLens Version

13.4.0

### VS Code Version

Version: 1.77.0 (Universal)
Commit: 7f329fe6c66b0f86ae1574c2911b681ad5a45d63
Date: 2023-03-29T09:57:11.797Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.4.0
Sandboxed: No

### Git Version

git version 2.39.2 (Apple Git-143)

**Comment by jkelroy** [comment]
Hello @umdstu, [GitKraken Client](https://www.gitkraken.com/git-client/pricing) and [GitLens](https://www.gitkraken.com/gitlens/pricing) have separate licenses. A GitKraken Teams license does not provide access to GitLens + features. If you would like both GitKraken Client and GitLens, you can consider upgrading to the [Bundle](https://www.gitkraken.com/gitkraken-client-gitlens-bundle-pricing) license. If you have additional questions about this, you can reach out to the support team [here](https://help.gitkraken.com/gitlens/gl-contact-support/).
