### ISSUE TITLE
When on VSCode web, add handling for failing repo discovery

### ISSUE THREAD

**Issue by eamodio** [gitkraken/vscode-gitlens#2629]
There has been an issue sometimes if there are no files open or anything in vscode.dev/github.dev

![Image](https://user-images.githubusercontent.com/67011668/222523829-2ccf5aae-f08a-44f9-9ba7-d403e87f6dbe.png)

It used to be infrequent, but now it seems to always happen -- and it seems to correct itself after a while (the branch will show up in the statusbar and the top area will refresh), but we don't detect a change.

We have opened an issue for this: https://github.com/microsoft/vscode-remote-repositories-github/issues/308

In the meantime, we might want to look into adding some extra round of detection if we are on the web and there is a workspace folder -- like after a short delay or something if no repos were detected.

Maybe if we are on the web, add a `.then` onto https://github.com/gitkraken/vscode-gitlens/blob/3940ef7c20cb446cb1a6c9e490470e26c38b61d5/src/git/gitProviderService.ts#L472

And if no repositories were discovered, do a settimeout for like 500ms or 1s and run the discovery once more.

**Comment by joyceerhl** [comment]
@eamodio did you ever find a consistent repro for this one / do you have a link that this always happens on?

**Comment by sergeibbb** [comment]
@eamodio 
I've reviewed that on github and vscode.

1. ❌ Looks like there is lack of GitLens views in the statusbar:
    <img width="600" height="655" alt="Image" src="https://github.com/user-attachments/assets/b06e72ba-2312-422d-b38d-d425684055eb" />

    And I do not see any branches onn other views:
    <img width="600" height="1630" alt="Image" src="https://github.com/user-attachments/assets/6b628194-bc53-443b-ae17-23001c37328b" />

2. ❓ Repo name does not show-up anymore, but it might be VSCode's changes.
    <img width="400" height="672" alt="Image" src="https://github.com/user-attachments/assets/b8049ed5-b022-4465-87e2-bca0c005b046" />
3. ❌ GitLens panel sometimes does not show-up (on both). But it appears for a very short moment and then disappears:
    <img width="400" height="1154" alt="Image" src="https://github.com/user-attachments/assets/e5cec3e0-a81d-42d9-b00d-36922129f85e" />

When I open a file, the GitLens panel appears on both:
<img width="400" height="1224" alt="Image" src="https://github.com/user-attachments/assets/ed2ccd86-edd8-42a2-a358-2632de2ac32d" />
