### ISSUE TITLE
'Gitlens: Home' will not stay collapsed, Always reopens when opening vscode

### ISSUE THREAD

**Issue by drewmiranda-gl** [gitkraken/vscode-gitlens#2631]
### Description

When using vscode with the gitlens extension installed, gitlens repeatedly re-expands its items in the 'explore' section of the left most vscode menus. I cannot find anyway to permanently dismiss this and its very distracting :(

![image](https://user-images.githubusercontent.com/107503402/231554059-0f6fb7fa-efec-401c-ae78-906330ddc3e7.png)

I've tried to uninstall/reinstall the add-on with no change.

### GitLens Version

13

### VS Code Version

Version: 1.77.2 (Universal)
Commit: e344f1f539a80912a0e9357cec841f36ce97a4e2
Date: 2023-04-06T10:12:31.126Z (6 days ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: No

**Comment by jkelroy** [comment]
Hello @drewmiranda-gl, when quitting and opening VS Code (1.77.3), I am seeing that the GitLens: Home view remains collapsed when it is in Explorer. Are you performing any other action or will this expand when collapsed every time you quit and open VS Code?

As an alternative, you can hide the GitLens: Home view from the context menu on right-click or drag and drop it into the sidebar to have it removed from Explorer.

https://user-images.githubusercontent.com/27739784/231580227-2faf53d1-ca22-4f70-9f15-8c0819dae38e.mp4

**Comment by drewmiranda-gl** [comment]
Thanks for the reply! I wonder if this is a MacOS specific bug? In any case hiding from home and dragging to the sidebar work perfectly, thank you!
