### ISSUE TITLE
[Feature] Support search and open  file history change

### ISSUE THREAD

**Issue by tjx666** [gitkraken/vscode-gitlens#2641]
![image](https://user-images.githubusercontent.com/41773861/232373595-e8794c45-698d-44ea-89ce-6e14175feaae.png)

**Comment by eamodio** [comment]
Not sure I understand the ask here. Are you asking to jump to the File History view from the Command Palette? If so:

![image](https://user-images.githubusercontent.com/641685/234971863-672f0179-830a-463b-8bc2-4cbce64d34f9.png)

**Comment by tjx666** [comment]
No, my meaning is to provide a history search picker, not jump to the view. @eamodio

**Comment by eamodio** [comment]
The history picker is the first option in the image above. The latter two options are the views.

**Comment by tjx666** [comment]
I try the first option, which is not I want. I expect like show me a list like the timelime, and I can search the commit to open the diff

![image](https://user-images.githubusercontent.com/41773861/235108649-afe54520-76d0-4de9-97d5-d3c58011ef7a.png)

**Comment by tjx666** [comment]
What is the difference between `GitLens: Quick Open File History` and `GitLens: Show File History`?

![image](https://user-images.githubusercontent.com/41773861/235109861-b5c7e84e-eb10-4cd1-8bfe-a6a2939799d0.png)

**Comment by tjx666** [comment]
I hope here can provide a button to open the change:

![image](https://user-images.githubusercontent.com/41773861/235110319-0461f888-0d5c-4f02-a3c5-6ad6a09f05ab.png)

**Comment by eamodio** [comment]
> What is the difference between `GitLens: Quick Open File History` and `GitLens: Show File History`?
They do the same thing -- just alternate searches. The latter existed before GitLens had a File History view, and the former was added later to be clearer in the menus.

> I hope here can provide a button to open the change:

So you don't have click on an item and then choose?

![image](https://user-images.githubusercontent.com/641685/235547536-2cc4360e-960e-4c0a-883f-5b0a298cecbe.png)

**Comment by tjx666** [comment]
@eamodio yes

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's (`v2023.8.11xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by tjx666** [comment]
@eamodio works fine. Thanks
