### ISSUE TITLE
[Feature Request] file context menu items to compare single file with another branch or ref

### ISSUE THREAD

**Issue by jedwards1211** [gitkraken/vscode-gitlens#2648]
Back when I used Eclipse I could right-click on a file or editor tab and select a menu item to compare the file (i.e. the working copy) with another branch or revision. It would open a diff editor for just that file.

Does GitLens really not have a way to compare a single file?  This is one of the most common things I want to do, if I had a way to do it I would probably use it more often than any other GitLens feature.

**Comment by jedwards1211** [comment]
Sorry I missed that, was just coming to say I found it.  "Commit Changes" is an unexpected name for that, sounds like something I'd go to when I want to create a Git Commit. Something like "Git Compare" would be much more obvious.

**Comment by eamodio** [comment]
@jedwards1211 I very much agree and we will be looking at auditing many of our menus and commands in the near future for better clarity and discoverability.
