### ISSUE TITLE
Add option to disable OpenAI/generate commit message

### ISSUE THREAD

**Issue by rognstad** [gitkraken/vscode-gitlens#2652]
Please add an option to disable the "generate commit message" feature and others that send information to OpenAI. Many companies have strict policies regarding the release of IP that this feature potentially violates. Thanks!

**Comment by eamodio** [comment]
Can you provide more details on why a "disable" option is useful? The AI features are not automatic -- they need to be manually triggered through an explicit user action, and then you are prompted to allow the sending of the required information to OpenAI.

**Comment by rognstad** [comment]
If the option is visible, people are going to be tempted to click on it. The resulting popup has a fair bit of text, and OpenAI isn't mentioned until the fifth line. Plenty of people unwisely reflexively hit enter or proceed through confirmation dialogs. Given an example organization where no one is supposed to send code to AI models, it would be much preferable to disable that option in all of their workspaces than rely on every individual to never make this particular mistake

**Comment by eamodio** [comment]
Gotcha -- thanks for the additional context.

**Comment by griffi-gh** [comment]
i hate the ai stuff and hate openai even more.  
I want an option that hides all AI features, like "hide all Gitlens+ Features" option.

**Comment by JeanTerblanche** [comment]
+1 for a setting for this - and also the **Explain this Commit** panel below.

A workspace setting will at least provide a mechanism for organizations who wish to limit data sharing with 3rd parties.

In general, having the ability to disable **Experimental** or **GitLens+ features** would also be very useful.

![image](https://github.com/gitkraken/vscode-gitlens/assets/1457538/94fd5c5b-4a9e-4fc5-8567-2f66ac15ce10)

**Comment by griffi-gh** [comment]
> +1 for a setting for this - and also the **Explain this Commit** panel below.
> 
> A workspace setting will at least provide a mechanism for organizations who wish to limit data sharing with 3rd parties.
> 
> In general, having the ability to disable **Experimental** or **GitLens+ features** would also be very useful.
> 
> ![image](https://user-images.githubusercontent.com/1457538/242913891-94fd5c5b-4a9e-4fc5-8567-2f66ac15ce10.png)

There's already an option to hide all GL+ features (you can enable it after your trial ends)

**Comment by DanielPower** [comment]
I certainly won't be subscribing to GitLens if it's going to force these options to be visible.

Many companies (mine included) do not allow the use of unauthorized AI tools that involve uploading of source code for analysis. And that's a very reasonable stance.

You're taking up valuable visual real estate in my editor, for a feature I cannot and do not want to use. And increasing the probability that developers are going to break company security policy.

**Comment by griffi-gh** [comment]
> I certainly won't be subscribing to GitLens if it's going to force these options to be visible.

the features are free for local and public repos.  

you can hide them if you want, just wait for your 14 day trial to expire and then open the command pallete -> Hide GitLens+ features

**Comment by michalbielecki** [comment]
I already have GitLens+ features hidden but still see "Explain (AI)" panel in GitLens inspect view

**Comment by eamodio** [comment]
@michalbielecki that's because it's not a restricted/paid feature.

**Comment by michalbielecki** [comment]
I was referring to the comment above claiming that disabling paid features would hide AI related stuff

**Comment by DanielPower** [comment]
> > I certainly won't be subscribing to GitLens if it's going to force these options to be visible.
> 
> the features are free for local and public repos.
> 
> you can hide them if you want, just wait for your 14 day trial to expire and then open the command pallete -> Hide GitLens+ features

I recognize that I can hide them with the option you mentioned on a free plan. However that option does not work on a paid account. Thus my statement that I would not subscribe.

The company has decided to make it so that paying for a subscription makes it impossible to hide this functionality. Thus for me a paid subscription is objectively worse than the free plan. Paying for a subscription would not be a consideration for me until that is addressed.

**Comment by CyprusSocialite** [comment]
> Can you provide more details on why a "disable" option is useful? The AI features are not automatic -- they need to be manually triggered through an explicit user action, and then you are prompted to allow the sending of the required information to OpenAI.

For screen real estate at the very least. "Explain (AI)" and Autolinks clutter the commit details panel whether you use those features or not - the latter even when completely disabled in settings!

**Comment by eamodio** [comment]
@DanielPower The AI features have nothing to do with free/paid plans at all -- they aren't gated and aren't pro features. This request to hide them is completely valid, but again is completely separate from Pro etc

**Comment by douira** [comment]
This is a new button that's taking away a little bit of space that I don't want to spend on something I don't want to use. Needing to resort to hacky css to get rid of this seems unnecessarily hard and terrible DX.

**Comment by douira** [comment]
It would be good extension etiquette not to introduce features (_especially if experimental_) without a way to disable them. VSCode upstream does it this too and they're very careful about making changes to things that users have expectations about.
Apart from that, I've found [the file that controls this feature](https://github.com/gitkraken/vscode-gitlens/blob/main/src/env/node/git/commitMessageProvider.ts#L31) and there appears to be mentions of a configuration option called  `ai.experimental.generateCommitMessage.enabled` which doesn't however seem to be an option configurable in the settings.json. It appears all that's missing is the addition of the setting value in the [`package.json`](https://github.com/gitkraken/vscode-gitlens/blob/main/package.json) with a optionally a description so that vscode can give this configuration value to the extension.

The fix is trivial.

**Comment by eamodio** [comment]
@douira The setting name is `gitlens.ai.experimental.generateCommitMessage.enabled` (note the `gitlens.` prefix).

**Comment by douira** [comment]
Even with the prefix, vscode does not recognize this setting as existing:
![Screenshot 2023-11-05 at 04 11 46](https://github.com/gitkraken/vscode-gitlens/assets/17120022/f9c3410f-0706-4d70-9cdf-77ddb1798dde)
You can see how it's greyed out compared to the other setting. Vscode provides the hint that it's an "unknown configuration setting" in the tooltip.

**Comment by douira** [comment]
![Screenshot 2023-11-05 at 04 15 43](https://github.com/gitkraken/vscode-gitlens/assets/17120022/ee1e7f56-989f-4ab5-8101-11c07da7f2b7)
You can also see that it's missing from the settings UI even though the other settings adjacent in `package.json` are not missing.

**Comment by douira** [comment]
Yes I am aware that the prefix is necessary since it's added automatically for configuration used within the extension. Thanks for getting around to fixing this issue after all this time.

**Comment by eamodio** [comment]
@douira If you were aware of it, why did you post suggesting the setting didn't exist or didn't work?

I added that setting when I added support to contribute to the new button in the SCM input box (https://github.com/gitkraken/vscode-gitlens/commit/41cae896a19cabf43474f64f364db7053dfc1f0a), explicitly for the reason that it highly visible and something that users could definitely want to disable. 

https://github.com/gitkraken/vscode-gitlens/blob/8dd2ac6b54fa21350400a4c9c132d9f573028cfc/package.json#L3080-L3086

**Comment by zigomir** [comment]
> @douira The setting name is `gitlens.ai.experimental.generateCommitMessage.enabled` (note the `gitlens.` prefix).

this doesn't work for me

My main issue with this AI feature is that I used to be able to type my commit message, hit `tab` and then hit `enter` and be done with it. Now after hitting a tab this `Generate commit message` kicks in and rewrites my commit message – very annoying 😔

**Comment by eamodio** [comment]
@zigomir My guess is that you have Copilot or another extension installed that is also contributing to that button.

**Comment by zigomir** [comment]
@eamodio oh, you're right, I'm sorry for the noise 😊

**Comment by kpostekk** [comment]
> > @douira The setting name is `gitlens.ai.experimental.generateCommitMessage.enabled` (note the `gitlens.` prefix).
> 
> this doesn't work for me
> 
> My main issue with this AI feature is that I used to be able to type my commit message, hit `tab` and then hit `enter` and be done with it. Now after hitting a tab this `Generate commit message` kicks in and rewrites my commit message – very annoying 😔

My solution: https://github.com/microsoft/vscode-copilot-release/issues/359#issuecomment-1798324788

**Comment by SampsonCrowley** [comment]
> Can you provide more details on why a "disable" option is useful? The AI features are not automatic -- they need to be manually triggered through an explicit user action, and then you are prompted to allow the sending of the required information to OpenAI.

it's also extremely annoying when the button covers part of what I'm typing for a feature I'l never use or be allowed to

**Comment by SampsonCrowley** [comment]
![Screenshot 2023-11-30 at 10 28 37 AM](https://github.com/gitkraken/vscode-gitlens/assets/22461638/03e2eb6d-eea8-4bcd-b7d9-c3b7b15b486c)

**Comment by d13** [comment]
@SampsonCrowley - its a bug with VS Code (https://github.com/gitkraken/vscode-gitlens/issues/3034)
