### ISSUE TITLE
can not open a new project

### ISSUE THREAD

**Issue by rockeet** [gitkraken/vscode-gitlens#2653]
Type: <b>Bug</b>

In remote explorer, can not open another remote project

Extension version: 13.5.0
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes
Connection to 'ssh-remote+file-server' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz (64 x 2494)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|255.92GB (231.94GB free)|
|Process Argv|--crash-reporter-id b7d10aef-5fbb-4e9e-8394-f690b63a456c|
|Screen Reader|no|
|VM|27%|

Connection to 'ssh-remote+file-server' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30716742
pythonclientmvcf:30725893

```

</details>

**Comment by eamodio** [comment]
The Remote Explorer is a VS Code feature not a GitLens feature.  Please [open an issue](https://github.com/microsoft/vscode/issues/new?assignees=&labels=&template=bug_report.md) on the VS Code repository? Thanks!

**Comment by rockeet** [comment]
This bug is located by VSCode `Start Extension Bisect`, I don't know the detail.
