### ISSUE TITLE
Toggle zen mode not working until you restart vscode

### ISSUE THREAD

**Issue by kossa** [gitkraken/vscode-gitlens#2654]
### Description

1. Open a project
2. In command palette choose: Gitlens: Toggle Zen Mode
3. The Zen mode is not applied until you restart vscode

Video here: https://www.loom.com/share/86af762c6e6d4f1e8a9f421fbf6dd51b

### GitLens Version

v2023.4.2705

### VS Code Version

Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:41:48.638Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: No

### Git Version

git version 2.40.1

### Logs, Screenshots, Screen Captures, etc

https://www.loom.com/share/86af762c6e6d4f1e8a9f421fbf6dd51b

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's (v2023.04.28XX) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by kossa** [comment]
The same issue using v2023.4.2705

**Comment by eamodio** [comment]
Sorry it needs to be v2023.04.28xx, which isn't out yet (CI will run in a few more hours)

**Comment by kossa** [comment]
Ok @eamodio will wait :)

**Comment by kossa** [comment]
Yes I confirm, the bug was fixed using v2023.4.2805
