### ISSUE TITLE
Commands executed in the terminal fail to honor found Git path

### ISSUE THREAD

**Issue by anzz1** [gitkraken/vscode-gitlens#2660]
### Description

1. On Windows, "git.exe" is not on PATH, yes this is intended.
2. settings.json has `"git.path": "C:\\sys\\git\\bin\\git.exe"`
3. GitLens still tries to execute "git" from PATH

Same as #132

However, this is no problem as there is a `gitlens.advanced.path` configuration option which lets you set the path to the binary ! Problem solved ?

Oh wait, no . Some rocket scientist thought it ought to be removed, as "it is no longer needed". So this problem was unsolved in the time between that issue and now.

https://newreleases.io/project/github/gitkraken/vscode-gitlens/release/v9.0.0 , bottom of page

### GitLens Version

12.2.2

### VS Code Version

Version: 1.70.2 (user setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 6.1.7601

### Logs, Screenshots, Screen Captures, etc

Tries to use git at PATH:
![image](https://user-images.githubusercontent.com/13628128/235414751-9960c12d-247e-4153-bbde-f7addb4d7722.png)

Path setting was removed:
![image](https://user-images.githubusercontent.com/13628128/235415317-c3b75593-4694-4608-bcb8-5a79e11ca7b4.png)

![image](https://user-images.githubusercontent.com/13628128/235415627-9e0c8d20-42bb-493f-adf0-a8dbdc82c678.png)

![image](https://user-images.githubusercontent.com/13628128/235415891-72c217f7-c43b-442a-958a-3e0cd8a0be58.png)

**Comment by eamodio** [comment]
The issue here has nothing to do with `gitlens.advanced.path` being removed -- because it is NOT needed anymore. It was added before the Git extension had the `git.path` setting. The real issue here is that commands executed in the terminal are not honoring that location -- and instead relying on Git to be on the path.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's (`v2023.5.02xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)
