### ISSUE TITLE
Debounce bug: file blame isn't cleared when editing document while text in output window changes

### ISSUE THREAD

**Issue by russelldavis** [gitkraken/vscode-gitlens#2663]
### Description

Repro steps:
1. Run "Gitlens: Enable debug logging" command
2. Open the Output panel in VS Code and select "GitLens" in the dropdown to see the debug logs
3. Turn on File Blame (run the "Gitlens: Toggle File Blame" command)
4. Type a character to edit the current file

Expected: The File Blame annotations should disappear.
Actual: The File Blame annotations remain, and editing becomes janky (newly typed characters appear inside the blame gutter).

I did some debugging and tracked this down to a problem with the debounce behavior for the `onTextDocumentChanged` event at https://github.com/gitkraken/vscode-gitlens/blob/b1f879373c3d190998a1b378d0ddfc90e9a53d89/src/trackers/documentTracker.ts#L80

The problem is that it is debouncing events that can come from different sources. In this case, a change event is first fired for the active file. Then, within the debounce timeframe, a change event is fired for the output window. so the first event (from the active file) gets dropped. The event for the output window gets processed, but since it's for the output window, it doesn't have any effect.

### GitLens Version

13.5.0

### VS Code Version

Version: 1.78.0
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:15:29.774Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: No

### Git Version

 2.39.1

### Logs, Screenshots, Screen Captures, etc

<img width="1117" alt="Screenshot 2023-05-07 at 11 07 28 PM" src="https://user-images.githubusercontent.com/551404/236746912-3a962155-34d0-433d-acd9-63601eb56bf2.png">

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's (`v2023.12.13xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)
