### ISSUE TITLE
compare branches deep link support

### ISSUE THREAD

**Issue by tjx666** [gitkraken/vscode-gitlens#2670]
<img width="1440" alt="image" src="https://github.com/microsoft/vscode/assets/41773861/867adba6-6a53-49a1-aff5-9fc5f105ba2a">

should consider following page:

- pull request page, like: https://github.com/microsoft/vscode/pull/182141
- compare page, like: https://github.com/tjx666/awesome-chrome-extension-boilerplate/compare/master...vue3?expand=1

refs:

- https://github.com/microsoft/vscode/issues/182047

**Comment by axosoft-ramint** [comment]
@tjx666 we added support for deep links for comparisons to the pre-release.

Note that so far, we've only added support for the links themselves, not yet a way to generate them. We are working on a chrome extension as @eamodio pointed out [here](https://github.com/microsoft/vscode/issues/182047#issuecomment-1542665122) in which we can utilize this support to link into GitLens Search & Compare from GitHub as your concept image seems to reference.

The format for a comparison deep link is `vscode://eamodio.gitlens/link/r/(repoId)/compare/(ref1)[../...](ref2)?url=(remoteUrl)`

where:

- `repoId` is the hash of the first commit of the repo, is optional, and can be replaced with `-` if not known
- `ref` and `ref2` can be commit SHAs, branch names, or tag names. Both are required.
- `[../...]` means you can use either `..` or `...` between the two refs as a separator.
- `remoteUrl` is the url of the remote, which can be url encoded or not. For example: `url=https://github.com/microsoft/vscode`. It is required.

Here's an example, which represents the comparison between the `main` branch and `v14.0.1` tag: vscode://eamodio.gitlens/link/r/-/compare/main...v14.0.1?url=https://github.com/gitkraken/vscode-gitlens.git

A link of this format should open the Search & Compare view and show the comparison if you have the repo open:
![image](https://github.com/gitkraken/vscode-gitlens/assets/67011668/7e7ba5a9-f31c-4bd2-b595-5142e95ce063)

To test this, you need to be on the latest pre-release version of GitLens, which you can switch to on the Extension's banner at the top of the extension page:

![image](https://github.com/gitkraken/vscode-gitlens/assets/67011668/a9424f3e-73b5-4008-ba29-970f13f43c76)
