### ISSUE TITLE
Navigation controls hidden

### ISSUE THREAD

**Issue by sedghi** [gitkraken/vscode-gitlens#2675]
### Description

recently I don't see the navigation controls after going couple of commits back

![image](https://github.com/gitkraken/vscode-gitlens/assets/7490180/e9e9e342-aaa3-4153-b5f5-0b1db55e9b00)

But then they get hidden inside the dropdown 

![image](https://github.com/gitkraken/vscode-gitlens/assets/7490180/c2f504c1-9fa6-4b55-9aa5-3e1823a390aa)

### GitLens Version

v2023.5.1205

### VS Code Version

Version: 1.78.2 (Universal)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:44:45.204Z (1 day ago)
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No

### Git Version

git version 2.40.0

**Comment by jkelroy** [comment]
Hello @sedghi, this is a limitation/restriction of VS Code as it only allows a certain number of icons in the editor toolbar before they will be moved to the `...` icon. If you would like to be able to pin specific actions or see more in the editor toolbar, I would recommend submitting a feature request to the [VS Code repository](https://github.com/microsoft/vscode/issues/new/choose).

**Comment by sedghi** [comment]
I tried again now and don't see it happening any more, so thanks
