### ISSUE TITLE
Merging branch produces path error

### ISSUE THREAD

**Issue by JoelLeach** [gitkraken/vscode-gitlens#2677]
### Description

I updated VS Code and GitLens to the latest versions today on Windows 11, and I am now receiving an error when I merge a branch into the current branch.  I'm not sure which versions I was on before, but I did not have the issue until updating. Note that I have Git installed in an odd location (D:\Program Files), but I think the same issue would occur if installed in C:\Program Files.  To reproduce:

1. Right-click on the desired branch and select Switch to Branch...
2. Right-click on the branch to merge and select Merge Branch into Current Branch...
3. Confirm the merge.  The following appeared in the GitLens terminal:

```
PS D:\AppsWeb\nexus-angular> D:/Program Files/Git/cmd/git.exe -C "d:/AppsWeb/nexus-angular" -c "core.editor=code --wait --reuse-window" merge dev
D:/Program : The term 'D:/Program' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.
At line:1 char:1
+ D:/Program Files/Git/cmd/git.exe -C "d:/AppsWeb/nexus-angular" -c "co ...
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:/Program:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I restarted VS Code after I encountered the error the first time, but that did not help.  It's obvious that Windows doesn't like the spaces in the path name. (I thought that Windows cmd could find paths like this even without quotes, but apparently that is no longer the case).  I expected that adding quotes around the path would fix the issue, but instead it caused git parsing errors:

```
PS D:\AppsWeb\nexus-angular> "D:/Program Files/Git/cmd/git.exe" -C "d:/AppsWeb/nexus-angular" -c "core.editor=code --wait --reuse-window" merge dev
At line:1 char:36
+ "D:/Program Files/Git/cmd/git.exe" -C "d:/AppsWeb/nexus-angular" -c " ...
+                                    ~~
Unexpected token '-C' in expression or statement.
At line:1 char:39
+ ... /Program Files/Git/cmd/git.exe" -C "d:/AppsWeb/nexus-angular" -c "cor ...
+                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token '"d:/AppsWeb/nexus-angular"' in expression or statement.
At line:1 char:66
+ ... ogram Files/Git/cmd/git.exe" -C "d:/AppsWeb/nexus-angular" -c "core.e ...
+                                                                ~~
Unexpected token '-c' in expression or statement.
At line:1 char:69
+ ... eb/nexus-angular" -c "core.editor=code --wait --reuse-window" merge d ...
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token '"core.editor=code --wait --reuse-window"' in expression or statement.
At line:1 char:110
+ ... /nexus-angular" -c "core.editor=code --wait --reuse-window" merge dev
+                                                                 ~~~~~
Unexpected token 'merge' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
```
The merge was successful after removing the full path from git.exe, because D:\Program Files\Git\cmd is in my Windows path.
`git.exe -C "d:/AppsWeb/nexus-angular" -c "core.editor=code --wait --reuse-window" merge dev`

### GitLens Version

13.6.0

### VS Code Version

Version: 1.78.2 (system setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

### Git Version

git version 2.37.3.windows.1

**Comment by frg2089** [comment]
you should add `&` before your string in powershell.
```powershell
& "D:/Program Files/Git/cmd/git.exe" -C "d:/AppsWeb/nexus-angular" -c "core.editor=code --wait --reuse-window" merge dev
```
https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7.2#call-operator-

**Comment by eamodio** [comment]
@JoelLeach Sorry for the trouble -- this broke as part of another fix to run the Git command without relying on it being in the PATH. It looks like when we are trying to get the short version of  "D:/Program Files/Git/cmd/git.exe" we are failing. Can you run this command and post the output? Thanks!

`for %I in ("D:/Program Files/Git/cmd/git.exe") do @echo %~sI`

**Comment by eamodio** [comment]
@JoelLeach Another question -- does `D:\Program Files\Git\cmd\git.exe` exist?

**Comment by eamodio** [comment]
I just published a new pre-release version with more logging and a fallback for Powershell (assuming I can detect it properly). Can you please see if this issue is still reproducible in the pre-release edition of GitLens? Thanks!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by JoelLeach** [comment]
Thanks for jumping on this quickly.  I have switched to the pre-release version, and I will let you know what happens with my next merge.  In the meantime, here are answers to your other questions:

> @JoelLeach Sorry for the trouble -- this broke as part of another fix to run the Git command without relying on it being in the PATH. It looks like when we are trying to get the short version of "D:\Program Files\Git\cmd\git.exe" we are failing. Can you run this command from the Windows Command Prompt and post the output? Thanks!
> 
> `for %I in ("D:\Program Files\Git\cmd\git.exe") do @echo %~sI`

Here is the result: 
`D:\Program Files\Git\cmd\git.exe`

Yes, that file/path does exist on my system.  FYI, I manually created D:\Program Files (with similar permissions to C:\Program Files) for development tools, but Windows does not produce a shortened path without spaces for it. **dir /x** reveals that short paths are only produced for my C: and not the other drives.  There is a way to force it (https://superuser.com/a/792852), but it's probably not something you want to depend upon.

**Comment by IceBjerg** [comment]
Hey everyone!

I was getting the exact same issue for a couple of weeks now. 
My problem occurred while "deleting" a local branch. 

I can confirm, switching to the Pre-Release version solved the issue. 

Output with released version: 
![image](https://github.com/gitkraken/vscode-gitlens/assets/26023511/3b3a4c8b-0f76-4fa5-a9da-dcfca362c1c5)

Output with pre-release version: 
![image](https://github.com/gitkraken/vscode-gitlens/assets/26023511/7ba20d17-4cca-4056-906a-6209884ae866)

**Comment by IceBjerg** [comment]
Hey everyone!

I was getting the exact same issue for a couple of weeks now.
My problem occurred while "deleting" a local branch.

I can confirm, switching to the Pre-Release version solved the issue.

Output with released version:
![image](https://github.com/gitkraken/vscode-gitlens/assets/26023511/3d877616-e2dc-40dc-9d9a-7b718f1bdf93)

Output with pre-release version:
![image](https://github.com/gitkraken/vscode-gitlens/assets/26023511/c623ec73-f41c-45a4-9e79-3edf0f206c26)
