### ISSUE TITLE
GitLens hangs on github.dev on Safari

### ISSUE THREAD

**Issue by simonmichael** [gitkraken/vscode-gitlens#2689]
### Description

On github.dev, eg at https://github.dev/github/explore,
after installing GitLens extension,
I click on the GitLens button,
but the pane remains empty, with a spinner, for ever.

![Screen Shot 2023-05-19 at 10 38 56](https://github.com/gitkraken/vscode-gitlens/assets/10144/064ee0d5-22de-492c-aeae-f0cf700643a6)

### GitLens Version

v2023.5.1805

**Comment by jkelroy** [comment]
Hello @simonmichael, I am not seeing an issue with v2023.5.1805 or any other pre-release version in Google Chrome. What browser and version are you using? Are you able to see if this persists on a different browser and in a private/incognito window?

**Comment by simonmichael** [comment]
@jkelroy I see it in Safari 16.2 on mac. 

In Brave , the GitLens icon does not appear in the activity bar, and there is an error notification:

> Error loading webview: Error: Could not register service worker. Please make sure third party cookies are enabled: NotSupportedError: Failed to register a ServiceWorker for scope ('https://1n0ufikvpi4h4vqckld1crj3spao9nr3le81qj3j0dkhic6bf812.vscode-cdn.net/stable/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/contrib/webview/browser/pre/') with script ('https://1n0ufikvpi4h4vqckld1crj3spao9nr3le81qj3j0dkhic6bf812.vscode-cdn.net/stable/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/contrib/webview/browser/pre/service-worker.js?v=4&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&remoteAuthority='): The user denied permission to use Service Worker.

**Comment by simonmichael** [comment]
(but after allowing all cookies and installing the GitLens extension for Brave, it worked as expected.)

**Comment by eamodio** [comment]
@simonmichael Does only the GitLens Home view "hang"? Do any other GitLens view work? Does the Commit Graph and/or the Welcome (Quick Setup) experiences work?

**Comment by eamodio** [comment]
@jkelroy Can you please verify this fix in the `2023.6.03xx` (tomorrow's) version of the pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by eamodio** [comment]
@jkelroy Were you able to verify this?

**Comment by jkelroy** [comment]
@eamodio I am still seeing the same behavior as described above when using pre-release `v2023.6.1405`.
