### ISSUE TITLE
Visual File History limited to 4 years ?

### ISSUE THREAD

**Issue by simonmichael** [gitkraken/vscode-gitlens#2690]
The longest Timeframe I can select for Visual File History is 4 years. Is this normal ? Could it be increased to allow viewing lon histories ?

**Comment by Buyzed** [comment]
Nice to meet.

**Comment by eamodio** [comment]
Can you please verify this fix in the `v2023.5.25xx` pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by simonmichael** [comment]
Thank you - yes, I now see the Full History option, and it seems to be working but I also see a github rate limit error:

![image](https://github.com/gitkraken/vscode-gitlens/assets/10144/de9ac315-7c5a-4eb1-b987-f990888d78d3)

**Comment by eamodio** [comment]
@simonmichael yeah, on virtual repositories we are beholden to GitHub rate limits, so we try to be conservative to not overwhelm/use all of them. You can change the `gitlens.visualHistory.queryLimit` to up that number, but you may very well get rate limited.
