### ISSUE TITLE
dont't create output panel until log message first time

### ISSUE THREAD

**Issue by tjx666** [gitkraken/vscode-gitlens#2700]
<img width="1076" alt="image" src="https://github.com/gitkraken/vscode-gitlens/assets/41773861/8c468945-8b67-4d4f-954e-4b19a5c692d8">

**Comment by eamodio** [comment]
Not sure I agree with not creating it, but rather maybe we should always output something there, and maybe tell you how to turn on more logging.

**Comment by tjx666** [comment]
For now, will always log activate info:

```
GitLens (pre-release) v2024.11.205 activating in Cursor (1.93.1) on the desktop; language='en', ...
