### ISSUE TITLE
Isolate CSS styles of the GK graph to avoid problems when using it from any external web application

### ISSUE THREAD

**Issue by ericf-axosoft** [gitkraken/vscode-gitlens#2704]
### Description

Right now, the GK graph library is including CSS styles directly to the `body`. We should modify that to avoid having display issues or CSS conflicts when using the library from any other external web application.

See internal task for more details: [GK-3692](https://gitkraken.atlassian.net/browse/GK-3692)

### GitLens Version

12.0.0

**Comment by axosoft-ramint** [comment]
Done in: f1892002cc812b116b793fcf3226f01c5ba99ec7
