### ISSUE TITLE
I can't parameter the remote how a local gitolite server

### ISSUE THREAD

**Issue by KlsBecker** [gitkraken/vscode-gitlens#2705]
### Description

Could someone tell me how I perform the parameterization of a local gitolite server, as my remote git?

Below is the output I get with the "git remote -vv" command:

```
$ git remote -vv
origin  gitolite@my.domain.com:repo (fetch)
origin  gitolite@my.domain.com:repo (push)
```

I only find examples of https servers...

Is there a way to make this works? 

PS: I use the WSL2 with Ubuntu 18.04

### GitLens Version

13.6.0

### VS Code Version

Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

### Git Version

git version 2.17.1

**Comment by jkelroy** [comment]
Hello @KlsBecker, are you looking to update your remote URL? If so, this is not currently supported in GitLens but we have an existing feature request to support this [here](https://github.com/gitkraken/vscode-gitlens/issues/1019). 

You can update the remote URL from VS Code of the command line - [here](https://stackoverflow.com/questions/51979534/how-can-i-change-the-origin-remote-in-vscode) is a good reference on how to do either.
