### ISSUE TITLE
Gitlens does not combine source control in VS Code

### ISSUE THREAD

**Issue by heydavee** [gitkraken/vscode-gitlens#2707]
### Description

Usually i can commit my files and check other commits in one view. For the last few days it seems, that gitlense does not combine these 2 views. I already went through the "Getting Started" and chose the default gitlense experience but the menu is still split. What can i do?

### GitLens Version

13

### VS Code Version

Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:44:45.204Z (3 wks ago)
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No

### Git Version

git version 2.38.1

### Logs, Screenshots, Screen Captures, etc

<img width="175" alt="Bildschirm­foto 2023-06-01 um 08 51 57" src="https://github.com/gitkraken/vscode-gitlens/assets/5037624/4842dcec-b345-4806-9f9c-f1e36a7a6a0b">

<img width="175" alt="Bildschirm­foto 2023-06-01 um 08 57 22" src="https://github.com/gitkraken/vscode-gitlens/assets/5037624/c4b99826-c8d3-494e-8992-79a4aa463b22">

**Comment by emptyVoid** [comment]
Hello @jkelroy, is there any way to get rid of "GITLENS:" prefix in the moved views?
![image](https://github.com/gitkraken/vscode-gitlens/assets/13639229/e68de19c-7b0e-4766-8bf4-60e4e16edffd)

**Comment by eamodio** [comment]
Sadly no, it's an unfortunate limitation of the VS Code apis because those views "default" home is no longer the SCM view so they force a prefix on them.

@sbatten there isn't any way around this right?

**Comment by antonio-santos** [comment]
I had the same problem.
You can drag the default "Source-Control" (with Commits) into GitLens "Source-Control".
Then you can costumize your view with something like this:
<img width="216" alt="image" src="https://github.com/gitkraken/vscode-gitlens/assets/32710188/899cf3ac-16f1-431d-83c4-2dc6d04dbc4d">

And this is what my current view looks like right now:
<img width="673" alt="Screenshot 2023-06-19 at 04 51 01" src="https://github.com/gitkraken/vscode-gitlens/assets/32710188/8c3bab8b-488a-43c9-93d2-11afe4a77047">
