### ISSUE TITLE
Name shows as "You" inconsistently

### ISSUE THREAD

**Issue by theonlypwner** [gitkraken/vscode-gitlens#2708]
### Description

1. Make a change in a file.
2. GitLens shows "You, now • uncommitted changes"
3. Stage the change.
4. Commit the change.
5. Close the file.
6. Open the file.
7. Click the same line where the change was made.
8. GitLens shows the git author name instead of "You".

The expected behavior is that the displayed name should be consistent, possibly determined by a setting (#1230).

### GitLens Version

13.6.0

### VS Code Version

Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

### Git Version

git version 2.40.1.windows.1

**Comment by jkelroy** [comment]
Hello @theonlypwner, I am not seeing the same behavior following your steps but you may not be seeing "You" if you have committed to this repository using different user.name's in your .gitconfig. In this case, you can use the [.mailmap](https://git-scm.com/docs/gitmailmap) file to include all of the names used to commit and after, GitLens will always show "You".

**Comment by Buyzed** [comment]
JOY

**Comment by theonlypwner** [comment]
I did some further testing and found that the issue was that in my git config, `user.email` was unset, but `git commit` was able to auto-detect the email.

Setting `user.email` fixed the issue, and commits now consistently show `You`.

@jkelroy The bug is actually that when `user.email` is unset, GitLens doesn't do the auto-detection that `git commit` does.
