### ISSUE TITLE
No branch name in lower left

### ISSUE THREAD

**Issue by JessyPiesco** [gitkraken/vscode-gitlens#2709]
### Description

I updated my mac, which caused me to redo git on my vs code
once redone git itself is working I can push, pull ect but I no longer have my branch name listed in the lower left. 

### GitLens Version

GitLens 13

### VS Code Version

Version: 1.76.1 (Universal)
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:32:09.831Z (2 mos ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.5.0
Sandboxed: No

### Git Version

git version 2.39.2 (Apple Git-143)

**Comment by Buyzed** [comment]
https://github.com/gitkraken/vscode-gitlens/issues/2709#issuecomment-1572574371

**Comment by Buyzed** [comment]
https://github.com/gitkraken/vscode-gitlens/issues/2709#issuecomment-1572574371
