### ISSUE TITLE
Ability to disable Gitlens sidebar on startup/window reload

### ISSUE THREAD

**Issue by Nicholas-Autio-Mitchell** [gitkraken/vscode-gitlens#2725]
> Describe the feature you'd like

Simply put: a setting to disable GitLens from appearing in focus within the Sidebar on startup or when running `Developer: Reload Window`.

-----------------------------

Currently, when starting VSCode and also when reloading the window (e.g. after installing extensions or changing certain settings), I am always greeted with the GitLens sidebar tabs - it is always opened.

This is what I see:

![image](https://github.com/gitkraken/vscode-gitlens/assets/12820901/dbd86ca2-325c-4056-900a-cacf22c7b3be)

I have hidden the two GitLens icons on the sidebar, but they both appear on startup and only disappear after I move to another icon e.g. File Explorer.

I have the following settings enabled:

```json
{
    "gitlens.plusFeatures.enabled": false,
    "gitlens.showWelcomeOnInstall": false,
    "gitlens.showWhatsNewAfterUpgrades": false,
}
```

* Currently using VSCode Insiders:
    - Version 1.79.0-insider
    - Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
    - Date: 2023-06-07T14:33:06.501Z
* GitLens — Git supercharged v2023.6.805  Pre-release
* Mac & Linux

The last step I see is to uninstall the extension, but hoping for something else I've missed 🤞

**Comment by eamodio** [comment]
Really sorry for the trouble, which was an unfortunate bug in pre-release which has been fixed (https://github.com/gitkraken/vscode-gitlens/commit/f5e98f27050347667ac498f630163fe4971451bc) and a new pre-release it out . The notification was intended to show only once.
