### ISSUE TITLE
Submodule commit graph will not open in the panel layout

### ISSUE THREAD

**Issue by jkelroy** [gitkraken/vscode-gitlens#2728]
### Description

1. clone this repository https://github.com/jkelroy/main-repo.git and open it in VS Code
2. In the Source Control view, attempt to open the submodule's commit graph by selecting `show commit graph`

Expected behavior: The submodules (vscode-gitlens) commit graph is opened

Actual Behavior: The parent repository (main-repo) is opened in the commit graph

This works as expected in the release version (13.6) but does not work in the pre-release (v2023.6.810).

![image](https://github.com/gitkraken/vscode-gitlens/assets/27739784/c9d7ee7c-7e78-467d-a8c0-7f8c55ad1112)

### GitLens Version

v2023.6.810

### VS Code Version

Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T15:00:40.428Z (4 wks ago)
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes

### Git Version

2.37.1 (Apple Git-137.1)

### Logs, Screenshots, Screen Captures, etc

[gitlens.txt](https://github.com/gitkraken/vscode-gitlens/files/11693978/gitlens.txt)

https://github.com/gitkraken/vscode-gitlens/assets/27739784/87c24730-d39b-45be-98f9-3b47c2eafaa2

**Comment by axosoft-ramint** [comment]
The issue seems to be related to the graph being in "Panel" layout. 

![Image](https://github.com/gitkraken/vscode-gitlens/assets/67011668/e5855993-422b-4d00-a9a4-ac4dc9816d32)

If you switch the layout to "Editor" layout and then try the repro steps above again, it should open the graph to the correct repo.

**Comment by jkelroy** [comment]
@axosoft-ramint yes, it looks like I cannot view the submodule when its in the panel layout. I updated the title of this issue. 

https://github.com/gitkraken/vscode-gitlens/assets/27739784/f5891455-557e-4a25-aff8-ba4d6c9c81a8

**Comment by lee1409** [comment]
Gitlens version
v13.6.0

VS Code
Version: 1.78.2 (Universal)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:44:45.204Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.4.0
Sandboxed: Yes


https://github.com/gitkraken/vscode-gitlens/assets/7869711/ede1b6d6-2f5d-488e-859a-ca725b393a31

**Comment by axosoft-ramint** [comment]
Fixed in commit: da288f50bc1cf085da970fe74a85bd5db699a02e
