### ISSUE TITLE
Please make Graph draggable to editor area

### ISSUE THREAD

**Issue by Igorgro** [gitkraken/vscode-gitlens#2741]
Before the 14.0.0 update the graph view was an editor, it  was possible to move it between editor grops to view it side-by-side wwith editors. Now it is attached to the bottom panel and can no longer be dragged to editor area. Please please return the previous behavior. Also, previously graph commit selection was synchronized with "commit details" view and it was very useable, but now it has its own "commit graph details" view which uses additional space on screen but used to provide the same info as the main view. Please revert the previous behavior or make an option to use main "commit details view" instead of the graph 's one

**Comment by Igorgro** [comment]
What I had before update:

![before](https://github.com/gitkraken/vscode-gitlens/assets/22894169/0212c79f-24eb-4272-8086-9798713ea8b2)

And what I have after:

![after](https://github.com/gitkraken/vscode-gitlens/assets/22894169/cda2b782-07c6-4262-b335-fad1d585f171)

**Comment by axosoft-ramint** [comment]
@Igorgro try opening the settings menu on the upper right corner of the graph and choosing `Switch Commit Graph to Editor Layout`.

![image](https://github.com/gitkraken/vscode-gitlens/assets/67011668/14ed90b6-9a61-4094-adab-c82d24c3f3b2)

This should also synchronize the commit graph back with the commit details view as it was before.

**Comment by Igorgro** [comment]
@axosoft-ramint ok, thank you very much!
