### ISSUE TITLE
Search & Compare: Element with id ... is already registered

### ISSUE THREAD

**Issue by icleolion** [gitkraken/vscode-gitlens#2742]
### Description

Main issue is when searching commits by message, result count is returned, but no results are listed, instead I get an error pop up, two examples of which are shown below.

1. Some searches will return results no problem.
2. Some searches will return the count, display the error, not show the results, but if I toggle either of the two following settings then the results will show.
"gitlens.views.searchAndCompare.avatars"
"gitlens.views.searchAndCompare.files.compact"
3. Some searches will return the count, display the error, and will refuse to show the results even if I toggle the above settings.

This issue has been around for a while, and feels like it is getting worse, i.e. more searches are falling into scenarios 2 and 3 above.

### GitLens Version

14.0.0

### VS Code Version

Version: 1.79.1 (user setup)
Commit: 4cb974a7aed77a74c7813bdccd99ee0d04901215
Date: 2023-06-12T16:14:05.102Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

### Git Version

git version 2.38.1.windows.1

### Logs, Screenshots, Screen Captures, etc

![image](https://github.com/gitkraken/vscode-gitlens/assets/47498402/ad01ffd6-00b7-44f2-87f8-df061326270a)
![image](https://github.com/gitkraken/vscode-gitlens/assets/47498402/0ce39ac2-8ba2-48f5-bc8b-76415dc8efed)

**Comment by eamodio** [comment]
@icleolion How often does this happen? Is it only certain searches? When it does happen press the refresh button on the node (if that doesn't work then press the refresh button for the whole view) -- does it still happen?

Unfortunately, I can't reproduce this and looking at the uniqueness of the ids I don't see any obvious issues. So any details reproducible steps -- even a screenshot/video could be helpful tracking this down.

Thanks!

**Comment by icleolion** [comment]
![gitlens](https://github.com/gitkraken/vscode-gitlens/assets/47498402/9a140924-ab75-4653-8811-b13546bcfe3a)

Hi, thanks for your suggestions, I hadn't thought of trying the refresh button on the view, that has the same impact as toggling the settings, but with the advantage of being a lot more convenient so I'll be using that going forward!  Above is a video of me showing a mixed bag of results when doing searches.

The problem is happening more often as time goes on and only certain searches are affected.  Happy to attempt to provide more information that you think might be helpful if the video doesn't clear things up.  I'd rather not have to continue using `git log --oneline --grep=PATTERN` as a fallback.

**Comment by icleolion** [comment]
Thanks for the fix.  I've tried pre-release edition, tried a few dozen searches including those above and all is working well.

**Comment by Princeprince559** [comment]
@princeprince559
