### ISSUE TITLE
Some GitHub Enterprise instances are unable to utilize the Focus View

### ISSUE THREAD

**Issue by jkelroy** [gitkraken/vscode-gitlens#2744]
### Description

Some users have reported issues when trying to use the focus view with GitHub Enterprise instances. Currently, the two issues reported have been:
- [Not being able to see issues](https://github.com/gitkraken/vscode-gitlens/discussions/2535#discussioncomment-6183495)
- Seeing "no remotes set up"

### GitLens Version

14.0

**Comment by adamdoe** [comment]
I'm seeing this same issue. 

When I open focus view I can't seem to get passed the banner that reads:

No GitHub remotes are connected
This enables access to Pull Requests and Issues in the Focus View as well as provide additional information inside hovers and the Commit Details view, such as auto-linked issues and pull requests and avatars.

**Comment by adamdoe** [comment]
@d13 & @jkelroy - this is appearing fixed for me from the latest release.
