### ISSUE TITLE
associated pull request is not the latest opened branch

### ISSUE THREAD

**Issue by tjx666** [gitkraken/vscode-gitlens#2751]
### Description

I had a branch had been merged before and I open a new pull request with it now, but the associated pull request show the old merged.

### GitLens Version

14.0.0

### VS Code Version

Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:33.551Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

### Git Version

git version 2.41.0

### Logs, Screenshots, Screen Captures, etc

![image](https://github.com/gitkraken/vscode-gitlens/assets/41773861/39770a2f-2d9b-4bd1-ac2a-273434590cb2)

**Comment by jkelroy** [comment]
Hello @tjx666, I am not able to reproduce this behavior. To confirm, as this pull request was recently created, if you fetch does the open pull request show under the branch as expected?

If not, where is this repository hosted? Are you able to reproduce this on any repository by simply opening/merging a pull request and then opening another pull request from the same branch?

**Comment by tjx666** [comment]
I will provide more info when I occur this issue again
