### ISSUE TITLE
I signed up in the VS code and not getting the option of initializing repository . Kindly help 

### ISSUE THREAD

**Issue by PrachiMaan** [gitkraken/vscode-gitlens#2762]

**Comment by jkelroy** [comment]
Hello @PrachiMaan, while GitLens does not offer a way to initialize a repository, this is offered by VS Code and you can see more on this here.

https://code.visualstudio.com/docs/sourcecontrol/intro-to-git#_initialize-a-repository-in-a-local-folder

In addition, you can also use the [terminal](https://code.visualstudio.com/docs/terminal/basics) and [git init](https://git-scm.com/docs/git-init) to initialize a repository.
