### ISSUE TITLE
Explain with AI returns error

### ISSUE THREAD

**Issue by grass29** [gitkraken/vscode-gitlens#2767]
### Description

When clicking "Explain this commit", getting this error:
_request to https://api.openai.com/v1/chat/completions failed, reason: socket hang up_

Open AI usage page shows that the API has been used, however. So apparently GitLens was able to send a request, but wasn't able to process the response. 

### GitLens Version

v14.0.1

### VS Code Version

Version: 1.80.0-insider
Commit: 49b8e2d5410795e5a23a9c6b7f99b97f4afb4b47
Date: 2023-06-23T13:52:27.216Z
Electron: 22.3.13
ElectronBuildId: 21803499
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.19.0-45-generic snap

**Comment by pnck** [comment]
@Roberto-Vizcarra 

I got  an similar issue, when I click "explain this commit" I received a message something like `reason: read ECONNRESET`.
It happens no matter how I change the proxy settings,  neither `gitlens.proxy:{url:xxx}` nor global (vscode's) proxy works.

I also checked the gitlens debug output, but there is nothing about http requests or network errors.
