### ISSUE TITLE
Feature to disable GitLens in specific workspaces

### ISSUE THREAD

**Issue by nayo0513** [gitkraken/vscode-gitlens#2783]
I play competitive programming and I manage the environment with Git.
But, I bother the display about Git on VSCode, so I disabled the display about Git in .vscode/settings.json

```
    "git.enabled": false,
```
Then, when I open workspace in VSCode, the following Gitlens warning appers.
```
GitLens was unable to find Git. Please make sure Git is installed. Also ensure that Git is either in the PATH, or that 'git.path' is pointed to its installed location.
```
```
GitLens requires Git to be enabled. Please re-enable Git — set `git.enabled` to true and reload.
```
So I looked for a setting to turn off Gitlens, but couldn't find it.
I thought it would be be nice to have the ability to disable Gitlens in certain workspaces.

**Comment by eamodio** [comment]
You can achieve this today by choosing _Disable (Workspace)_ from the extensions view:

![image](https://github.com/gitkraken/vscode-gitlens/assets/641685/9b34ed7b-e897-47fb-a963-e406b29a2776)

Hope that helps!
