### ISSUE TITLE
Error: Unable to generate commit message in github codespaces

### ISSUE THREAD

**Issue by bigdiff** [gitkraken/vscode-gitlens#2787]
### Description

1. Create a github codespace
2. Add GitLens
3. Activate generate commit message
4. Add my OpenAI API key
5. Stage some code in a repo
6. Try to generate a commit message
7. See error "Error: Unable to generate commit message: 429: Too Many Requests"

### GitLens Version

v14.0.1

### VS Code Version

Visual Studio Code
Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:55:41.903Z (2 wks ago)
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

### Git Version

2.41.0

### Logs, Screenshots, Screen Captures, etc

Just to add to the above issue that I tried to generate a commit message with the same API key and it generated just fine locally. My guess is that GitHub Codespaces IPs are sending too many requests to OpenAI and OpenAI are just blocking those IPs.

So it would be nice to have the API call proxied through GitLens servers to avoid this issues.

**Comment by jkelroy** [comment]
@bigdiff I was unable to reproduce this behavior following your steps (using Google Chrome).

Do you have a [proxy configured in VS Code](https://help.gitkraken.com/gitlens/gitlens-faq/#can-gitlens-or-visual-studio-code-work-with-a-proxy) that your browser not be respecting?  

If not, can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane. Once enabled, please reproduce the issue, and attach the log from the both _GitLens_ and _GitLens (Git)_ channels.
