### ISSUE TITLE
Bugs in the GitLens search for a local path git executable (Linux)

### ISSUE THREAD

**Issue by SteelBlueVision** [gitkraken/vscode-gitlens#2795]
### Description

GitLens on Linux cannot correctly process a symlink that is used to define the location of a local version of git.

For example:

/home/myname/bin/git.sh with mode flags: rwxr-xr-x
/home/myname/bin/git -> /home/myname/bin/git.sh # Symlink to git.sh named git

export PATH=/home/myname/bin:...

With the above setup, GitLens will not realize that the /home/myname/bin/git symlink refers to an "executable." The reason is because it is not properly, in its code, traversing the symlink to the actual file that it links to to check its executable flags.

#### Bonus Bug

GitLens should be able to correctly resolve a git path specified using VS Code notation for an environment variable (as distinct from a VSCode internally set variable) of the form "${env:SOME_VARIABLE}" and map this in its code to "$SOME_VARIABLE" before using it to perform searches within the process' environment, so that paths like: "${env:HOME}/myname/bin/git" # Can properly resolve.

For example:
#### In one of the myriad of VS Code config files - choose your poison
```
{
  # Either of these two path notations to git should work correctly
  # Note: And do work correctly for usage of Git outside of GitLens
  #   (e.g., within the MS supplied Git extensions for VS Code)

  ################################################################################################################ 
  # Case #1: Use of VS Code notation: "${env:HOME}", to refer to the variable HOME with the process environment
  ################################################################################################################ 
  "git.path"="${env:HOME}/myname/bin/git", # Should properly resolve

  # But fails with (GitLens debug log message): 
  #  findSpecificGit(${env:HOME}/myname/bin/git) * Unable to find git: Error: spawn ${env:HOME}/bin/git ENOENT [44ms]
  # Note: A substitution of 'HOME' for 'env:HOME' must be performed _before_ any ENV based resolutions of a variable

  # ..., or:
 
  ################################################################################################################ 
  # Case #2: Direct use of the environment variable "$HOME" to refer to its value as specified in the proc env
  ################################################################################################################ 
  "git.path"="$HOME/myname/bin/git", # Should properly resolve (and presently does)
  
  # Note: Of course, even this method, which will at least resolve the pathname correctly, will still run into the
  #   aforementioned symlink issue if a symlink is used to refer to the git executable:
  #   e.g., "$HOME/myname/bin/git" -> "$HOME/myname/bin/git.sh" # with mode flags: rwxr-xr-x
  #   ..., instead of the use of a direct path to the executable:
  #   e.g., "$HOME/myname/bin/git.sh" # with mode flags: rwxr-xr-x
```

### GitLens Version

v2023.6.2705

### VS Code Version

1.79.2

### Git Version

git 2.27.0

**Comment by jkelroy** [comment]
Hello @SteelBlueVision, can you expand on your setup a bit further? i.e. how did you set up git.sh?

Additionally, can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane. Once enabled, please reproduce the issue, and attach the log from the both _GitLens_ and _GitLens (Git)_ channels.
