### ISSUE TITLE
Merge the activitiy bar 'Gitlens Inspect', 'Gitlens', and 'Source Control' into one

### ISSUE THREAD

**Issue by aswasn** [gitkraken/vscode-gitlens#2799]
It's unnecessary to have 3 icons in the bar, which consumes a lot of spaces.

**Comment by jkelroy** [comment]
Hello @aswasn, you can drag and drop views into a different sidebar. Once you move all views, the sidebar icon will be removed. 

https://github.com/gitkraken/vscode-gitlens/assets/27739784/e9fa3b1b-0b67-4a52-a244-97b99988ded0
