### ISSUE TITLE
I want gitlens here

### ISSUE THREAD

**Issue by hammad-ali18** [gitkraken/vscode-gitlens#2802]
The gitlens isnot available for me

**Comment by jkelroy** [comment]
Hello @hammad-ali18, can you please expand on this request? How is GitLens not available for you?

You can install the GitLens extension for Visual Studio Code [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens). If you have any issues installing GitLens or using it, can you please expand on the behavior you see?
