### ISSUE TITLE
I am unable to see opened folder in git lens.

### ISSUE THREAD

**Issue by mk813y** [gitkraken/vscode-gitlens#2806]
### Description

![image](https://github.com/gitkraken/vscode-gitlens/assets/138771212/65bda49a-a0eb-436a-8759-3ee6afc959e5)

### GitLens Version

13.5.0

### Logs, Screenshots, Screen Captures, etc

![image](https://github.com/gitkraken/vscode-gitlens/assets/138771212/def2bbf0-983b-4c2a-bb46-b4b9d6b8645c)

**Comment by jkelroy** [comment]
Hello @mk813y, does this persist in the latest version of GitLens (14.0.1)?

<img width="453" alt="Screenshot 2023-07-12 at 8 08 19 AM" src="https://github.com/gitkraken/vscode-gitlens/assets/27739784/3ec305c6-6697-45a5-a22e-290c9a0c6b8c">

 If so, does this folder contain a .git folder? Is there anything unique about the folder being opened?

**Comment by mk813y** [comment]
Hi Joey,

There is no update showing and I am using latest version 13.5.0.

***@***.***

The folder does contain .git folder but it does not appear in VS code . I can see it in windows explorer view.
***@***.***

I did not notice anything unusual.

Thanks,
Monal

**Comment by jkelroy** [comment]
The latest version is 14.1 - you should be able to install that from this [link](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens). 

If the issue persists in the latest version, can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane. Once enabled, please reproduce the issue, and attach the log from the both _GitLens_ and _GitLens (Git)_ channels.

**Comment by eamodio** [comment]
Please make sure you are using VS Code version 1.78 or later, which is required by GitLens 14+
