### ISSUE TITLE
gitlens inspect commit details view not showing (error)

### ISSUE THREAD

**Issue by aecAperia** [gitkraken/vscode-gitlens#2812]
### Description

I have a paid Gitkraken and GitLens Pro license. I have installed the VS Code v14.1.0 extension. Everything seems to be working for me, except that the GitLens inspect commit details view is not showing. I see only an error there. See screenshot attached.
    "An error occured while loading view: gitlens.views.commitDetails"

![image](https://github.com/gitkraken/vscode-gitlens/assets/137965848/a815c0cb-3f35-438f-86cf-76438d3e0bc2)

===>> Please help. I cannot see commit details with GitLens. This is the main feature of GitLens!!!!

### GitLens Version

14.1.0

### VS Code Version

Version: 1.79.2 (user setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

### Git Version

version 2.41.0.windows.1

**Comment by aecAperia** [comment]
===>> Please help. I cannot see commit details with GitLens. This is the main feature of GitLens!!!!

**Comment by jkelroy** [comment]
Hello @aecAperia, does this persist if you switch to the pre-release? 

![image](https://github.com/gitkraken/vscode-gitlens/assets/27739784/2ebb5cfb-58ea-422f-8b38-4420f6925b84)

If so, is this happening for any repository and commit or only specific ones? For example, do you see this when selecting a commit from the [GitLens repository](https://github.com/gitkraken/vscode-gitlens)? 

Also, can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane. Once enabled, please reproduce the issue, and attach the log from the both _GitLens_ and _GitLens (Git)_ channels.

**Comment by aecAperia** [comment]
When I switched to pre-release, it works now.

Do you still need debug info. Want to close the case now, since it looks like the pre-release version fixed the issue?

**Comment by jkelroy** [comment]
Glad to hear that. If this does persist, feel free to open up a new issue and provide the extended logs.
