### ISSUE TITLE
GitLens reauthenticates infinitely

### ISSUE THREAD

**Issue by InTEGr8or** [gitkraken/vscode-gitlens#2813]
### Description

1. When I try to use GitLens I get this message repeatedly.
2. I click **Reauthenticate** because that's the only answer allowed to the question.
3. It opens a browser window briefly and either allows me to authenticate the app or just closes the browser window, and then asks me the same question about 10-45 seconds later.

This was happening before I switched to Insiders Nightly and the pre-release GitLens also, so moving to nightly/pre-release did not fix it.

It's a continuous nag pop-up and makes the product totally unusable.

### GitLens Version

v14.1.0

### VS Code Version

Version: 1.81.0-insider (user setup)
Commit: dc142e4cd111b8f370d0549d8c207df7de55facd
Date: 2023-07-14T10:43:06.630Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

### Git Version

git version 2.38.1.windows.1

### Logs, Screenshots, Screen Captures, etc

Also, why is **Reauthenticate** the only option? 

Why won't it let me _not_ provide additional access?

![image](https://github.com/gitkraken/vscode-gitlens/assets/1802850/75a54c8b-a2dd-4acc-8d1b-7989eed963d5)

```[tasklist]
### Tasks
```

**Comment by jkelroy** [comment]
Hello @InTEGr8or, does your Github instance require a VPN? If so, this may be a duplicate of #2698.

**Comment by InTEGr8or** [comment]
My Github instance is github.com. I don't think I need a VPN for anything because I'm not using a VPN.

I see this a lot in the GitLens log
```
[2023-07-19 02:19:55.678] GitHubApi.handleRequestError
Error: Your 'github' credentials do not have the required access
```

It also runs this `git rev-parse --show-toplevel` and then says it's not a git directory or the child of a git directory, but when I try it myself it returns the path of the git directory parent.

**Comment by InTEGr8or** [comment]
When I click this it seems to open a web page, but maybe it tries to open a popup and I have the pop-up blocker on. I am using Edge and I think the popup blocker is default.

Then it waits another 10 - 300 seconds and tells me to reauthenticate again.

![image](https://github.com/gitkraken/vscode-gitlens/assets/1802850/6ee16365-2ccb-4a1b-9d54-2ee522aad898)

**Comment by InTEGr8or** [comment]
Looking at some of these other `issues`, it seems like this might have something to do with it. I have an account with business units.

[Can't reset GitLens token in GitLens settings](https://github.com/gitkraken/vscode-gitlens/issues/1935#issuecomment-1085971925)

**Comment by InTEGr8or** [comment]
I have disabled all my other extensions and I don't seem to be having the problem anymore.

I'll open a separate issue if I can track it down to a specific extension (if it's this one)
