### ISSUE TITLE
GitLens Inspect: "Files Changed" not following when switching between commits in File History

### ISSUE THREAD

**Issue by GrimmiMeloni** [gitkraken/vscode-gitlens#2814]
### Description

1. File A has several commits in its history.
2. Open the file
3. Open GitLens Inpsect sidebar
4. In File History, click on a commit which not only changed File A, but also has changed File B
5. On the files changed tab, click File B
6. On the files changed tab, again click File A
7. In the File History, click any other commit
8. Files Changed, Commit Details, etc... everything is "stuck" on the previously selected commit

### GitLens Version

14.1.0

### VS Code Version

Version: 1.80.1
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:20:58.115Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0

OS: Darwin arm64 22.5.0

### Git Version

git version 2.39.2 (Apple Git-143)

### Logs, Screenshots, Screen Captures, etc

https://github.com/gitkraken/vscode-gitlens/assets/5851977/dbe62423-161f-4069-b395-f2eaa8e235b1

**Comment by eamodio** [comment]
@d13 Can you take a look at this -- my guess is it has to do with the "soft" pinning we do when you click on a file in the commit details view.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's (`v2023.10.18xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by GrimmiMeloni** [comment]
@eamodio lgtm in pre-release to me. Thanks for fixing this! 👍🏻
