### ISSUE TITLE
No commits could be found

### ISSUE THREAD

**Issue by JoeyRxy** [gitkraken/vscode-gitlens#2815]
### Description

<img width="551" alt="image" src="https://github.com/gitkraken/vscode-gitlens/assets/33261764/ae9d6234-fcf0-420e-8181-26cb1754d37d">

As you can see, the commits tab and branches tab are both empty. But branches show up when I click the git branch in status bar.

error message in OUTPUT panel in vscode, when I refresh the commits tab:
```
git rev-parse --abbrev-ref --symbolic-full-name @ @{u} -- • Command failed: /bin/git -c core.quotepath=false -c color.ui=false rev-parse --abbrev-ref --symbolic-full-name @ @{u} -- • ambiguous argument '@': unknown revision or path not in the working tree. • Use '--' to separate paths from revisions, like this: • 'git <command> [<revision>...] -- [<file>...]' [5ms]
```

I have many git repos, but only this one goes wrong.

### GitLens Version

14.1.0

### VS Code Version

Version: 1.80.0 (Universal)
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
Date: 2023-07-04T13:39:33.766Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0

### Git Version

1.8.3.1

### Logs, Screenshots, Screen Captures, etc

[2023-07-17 11:41:39.975] [      9ms] [<my-repo>] git for-each-ref --format=%3ch%3e%(HEAD)%3cn%3e%(refname)%3cu%3e%(upstream:short)%3ct%3e%(upstream:track)%3cr%3e%(objectname)%3cd%3e%(committerdate:iso8601) refs/heads refs/remotes
[2023-07-17 11:41:39.981] [      5ms] [<my-repo>] git rev-parse --abbrev-ref --symbolic-full-name @ @{u} -- • FAILED

Error: Command failed: /bin/git -c core.quotepath=false -c color.ui=false rev-parse --abbrev-ref --symbolic-full-name @ @{u} --
fatal: ambiguous argument '@': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

**Comment by jkelroy** [comment]
Hello @JoeyRxy, it looks like you are using a very old version of git `1.8.3.1`. If you upgrade Git to a more recent version (2.7.2+) does this persist?
