### ISSUE TITLE
repo can be identified

### ISSUE THREAD

**Issue by mmpotulo28** [gitkraken/vscode-gitlens#2817]
### Description

i have opened a repo on vs code, but the extention, stil says i should open a repo

### GitLens Version

12.0.0

### VS Code Version

Version: 1.79.2 (user setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by eamodio** [comment]
Please upgrade to the latest version of GitLens (14.1) and see if you are still having the same issue.

If so, can you provide more details about what you are opening and how (remote, opening the parent folder, etc)?. Also, can you please enable debug logging by running the _GitLens: Enable Debug Logging_ command from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ & _GitLens (Git)_ channels in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the logs from the _GitLens_ and _GitLens (Git)_ channels.

Thank you!

**Comment by mmpotulo28** [comment]
I am sorted. Thank you
