### ISSUE TITLE
autolinks show ticket's original title

### ISSUE THREAD

**Issue by latel** [gitkraken/vscode-gitlens#2819]
autolinks works great, however it can be better if ticket's related infomations is displayed alongside as well
![image](https://github.com/gitkraken/vscode-gitlens/assets/5621862/0b9755be-cd1d-4e64-94fc-8c31adb00dab)

if we are using gitlab or github integration, we can show issue's title here

**Comment by eamodio** [comment]
We believe this issue has been resolved in the latest version of GitLens. Please let us know if it is still an issue for you and we can re-open this.

**Comment by eamodio** [comment]
This is supported today for GitHub and GitLab autolinks. What is the service you are asking for here?
