### ISSUE TITLE
Would be nice to be able to hide the issues since I don't use them.

### ISSUE THREAD

**Issue by jkelroy** [gitkraken/vscode-gitlens#2820]
Would be nice to be able to hide the issues since I don't use them.

_Originally posted by @ifireball in https://github.com/gitkraken/vscode-gitlens/discussions/2535#discussioncomment-6459386_

**Comment by eamodio** [comment]
This will be unneeded in with the upcoming changes to the Focus view, which is much more of a unified view -- which can have issues filtered out.

**Comment by eamodio** [comment]
This has been completed in GitLens 14.3
