### ISSUE TITLE
Can't add github remote and thus cannot use Focus view

### ISSUE THREAD

**Issue by mraveux** [gitkraken/vscode-gitlens#2826]
### Description

I wanted to try the "focus view".
The "No GitHub remotes are connected" message was displayed on it, with a button to "Connect to github"
Clicking the button does absolutely nothing, and I don't find other ways to connect to github, thus cannot use focus mode whatsoever.

### GitLens Version

v14.1.1

### VS Code Version

Version: 1.81.0-insider (Universal)
Commit: 02d3b49d8035a9b30db3b0ae706796af9b1a4260
Date: 2023-07-17T05:33:53.966Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.3.0

### Git Version

git version 2.39.0

### Logs, Screenshots, Screen Captures, etc

<img width="634" alt="Screenshot 2023-07-21 at 18 10 29" src="https://github.com/gitkraken/vscode-gitlens/assets/7260891/a7006c12-3032-48f7-8764-87223e416f02">

**Comment by jkelroy** [comment]
Hello @mraveux, are you able to connect the GitHub integration from a line blame hover? If not, do you get any response when trying this way? https://help.gitkraken.com/gitlens/gitlens-features/#connecting-the-github-integration

If not, by chance do you have a repository open that has a remote added from another service as #2685 describes?
