### ISSUE TITLE
Option to sort repositories

### ISSUE THREAD

**Issue by shayded-exe** [gitkraken/vscode-gitlens#2836]
I have about 20 repositories in my workspace. In the repositories view they seem to be sorted at complete random.

I would like the option to have them sorted alphabetically.

**Comment by eamodio** [comment]
They should be sorted in the order of their discovery (e.g. the layout of the file system), which if you are using a VS Code `.code-workspace` file, you can control the order by the order of the folders in that file.

But this is a completely valid feature request -- alphabetic is one option, another good one might be recency (e.g. last fetched date) or both.

This is sounds like a good first issue for someone in the community to tackle. Thanks!

**Comment by shayded-exe** [comment]
@eamodio Yeah I have a bit of a weird situation at a big (non-tech) company that results in my repo list being effectively a random order.

I'd tackle this myself but I have an overflowingly full plate right now!

**Comment by aidoskanapyanov** [comment]
Hi @shayded-exe, @eamodio! 👋
I saw that this issue hasn't been resolved yet. Do you guys mind if work on this issue?

**Comment by eamodio** [comment]
Sure, sounds great! Thank you!

**Comment by shayded-exe** [comment]
Yeah that'd be great!

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's (`v2023.11.01xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by axosoft-ramint** [comment]
Verified in 14.5.0
