### ISSUE TITLE
Limited support for untrusted workspaces is not available making GitLens obsolete on untrusted repos

### ISSUE THREAD

**Issue by mic345** [gitkraken/vscode-gitlens#2838]
### Description

1. Install GitLens
2. Open an untrusted repo.
3. Enable [limited support](https://code.visualstudio.com/docs/editor/workspace-trust#_extensions:~:text=Limited%20in%20Restricted%20Mode) for untrusted workspaces
4. Bug: GitLens features are disabled.

```
 "extensions.supportUntrustedWorkspaces": {
        "eamodio.gitlens": {
            "supported": "limited",
        }
    },
```

### GitLens Version

14.1.1

### VS Code Version

Version: 1.80.2 (user setup)
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Date: 2023-07-27T20:40:28.909Z
Electron: 22.3.14
ElectronBuildId: 22695494
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

### Git Version

git version 2.41.0.windows.3

**Comment by eamodio** [comment]
This is by-design for security.

**Comment by mic345** [comment]
Hi eamodio and thanks for the prompt response!

Disabling an entire plugin on untrusted workspaces may cause developers to mark small or medium public repos as trusted or even their own repos while using third parties code, which can be an even bigger security risk, as it will affect all installed plugins.

To address this, vscode added the “partial” option, which enables plugins to work while disabling features that can be used maliciously. See more on the [workspace trust extension guide](https://code.visualstudio.com/api/extension-guides/workspace-trust#static-declarations).

Even though this may be involved in some work and an ongoing effort to support it with every new feature, I really hope you will consider supporting it. We love your plugin and miss it dearly since we can not enable full trust on our workspaces.

Take care and have a wonderful week 😊
Mic.

**Comment by eamodio** [comment]
GitLens used to support the "limited" mode, but because basically ANY call to Git on an untrusted folder has possible security implications, I had to disable it completely. Which is also the same thing that was decided for the built-in Git extension in VS Code.

**Comment by mic345** [comment]
Hi eamodio and thank you for the detailed response!

I believe some git calls may have potential security implications, while others less, depending on the actual git command and its configuration. For example running a `git diff` without any hooks doesn’t sound like supplying a threat actor a vulnerability to work with. 

That said, I can see your point –  the complexity of fine tuning and selecting what would be safe to run, and what may introduce a vulnerability may be overwhelming and require a dedicated security team by itself.

Two notes for future readers:

- The built-in Git extension in VS Code is working (partially) on trusted folders when configured as limited.
- If your repository includes 3rd party code (including `node_modules`) you should consider your repository as untrusted.

Anyways, thanks for all the help 🙂
mic.
