### ISSUE TITLE
Error when trying to browse commits

### ISSUE THREAD

**Issue by arquer** [gitkraken/vscode-gitlens#2841]
### Description

<img width="619" alt="Screenshot 2023-08-02 at 11 37 46 AM" src="https://github.com/gitkraken/vscode-gitlens/assets/10212172/7232ec92-c42c-4a0d-b84c-e38f8fd3b51c">

I see this issue when I try to expand the commit list all the time. I see there was a bug report in 2021 that has been closed since then https://github.com/gitkraken/vscode-gitlens/issues/1405

### GitLens Version

14.1.1

### VS Code Version

Version: 1.80.2 (Universal)
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Date: 2023-07-27T21:05:41.366Z (5 days ago)
Electron: 22.3.14
ElectronBuildId: 22695494
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

### Git Version

git version 2.34.1

**Comment by eamodio** [comment]
@arquer is it always the same commit id? Is this in the _Commits_ view? Does it happen with others? Do you have multiple repositories open or just one?

**Comment by arquer** [comment]
1. No, this happens whenever I try to expand the drop-down list of commits in a branch.
2. This happens in the "Source Control" pane and I try to expand branch's main commits (see attached image).
3. I do have multiple git repositories open in my VSCode workspace
4. I have tried expanding other branche's commits and I seem to only get that error for main.

<img width="786" alt="Screenshot 2023-08-02 at 12 02 48 PM" src="https://github.com/gitkraken/vscode-gitlens/assets/10212172/a421e86a-37aa-4846-abab-98a2259682b5">

**Comment by pairedLeaves** [comment]
I just got into the same issue after an VSCode update!

====git version 2.36.0=====
====gitlens version 14.2.0==

Luckily I happened to see a workaround:
Downgraded the gitlens back to v14.1.1 and then this trouble seems disappearing.

Inside my repo:
'git remote' lists multiple remote sites.
'git remote -v' lists remote sites wherein two of them are configured with the same URL.

And I just tried an experiment:
Re-upgrade the gitlens to v14.2.0 and run 'git remote remove XXX' to delete one duplicate site, this 'already registered' error disappeared and gitlens works normally.

**Comment by eamodio** [comment]
Thank you for the extra details and I think this should be fixed.

Can you please verify this fix in tomorrow's (`v2023.8.08xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by arquer** [comment]
I am running v2023.8.1505 and just saw this again...

<img width="1913" alt="image" src="https://github.com/gitkraken/vscode-gitlens/assets/10212172/3c267daa-a9c9-4a06-be57-8b99e72850bc">

I am trying to reproduce it but can't seem to be able to... so I can't give much info, still I thought I would let you know
