### ISSUE TITLE
14.2.0 Breaks "pull" action works fine in 14.1.1

### ISSUE THREAD

**Issue by httpete** [gitkraken/vscode-gitlens#2847]
### Description

I am using GitLens with the SSH plugin. In the "Branches" view I click the "pull" arrow on a branch. It does not refresh and pull, removing the Red text and the indication that it is out of sync

In 14.1.1 it works perfectly. 

### GitLens Version

14.2

### VS Code Version

Latest

### Git Version

git version 2.39.3

**Comment by axosoft-ramint** [comment]
@httpete Question as I investigate: do you have `Git: Fetch on Pull` enabled/checked in either your user or workspace settings? 

![image](https://github.com/gitkraken/vscode-gitlens/assets/67011668/2a73975d-c02b-4a23-afdf-17fb4d97a2a1)

**Comment by httpete** [comment]
I do not. Right out the box.

**Comment by axosoft-ramint** [comment]
Thanks for checking @httpete . Would you mind also trying the following: add the line: `"gitlens.experimental.nativeGit": true` to your settings JSON and then after reloading (so that the new setting takes effect), try the pull action again and let me know if it's still broken for you? (You can remove the line after testing if it doesn't resolve the issue for you.)

![image](https://github.com/gitkraken/vscode-gitlens/assets/67011668/a7f491c3-2fef-44f9-9f06-5d07964a7570)

![image](https://github.com/gitkraken/vscode-gitlens/assets/67011668/e6963e4a-228e-495c-97f3-9be2f6cef434)

**Comment by Neuhaus93** [comment]
I'm having the same issue. And 14.1.1 works fine for me as well.
@axosoft-ramint I tried to add the provided line on my settings JSON but it didn't work.

**Comment by axosoft-ramint** [comment]
@Neuhaus93 are you also using GitLens with the Remote SSH plugin?

**Comment by Neuhaus93** [comment]
@axosoft-ramint Negative, I'm not using it.

**Comment by axosoft-ramint** [comment]
Thanks. Just to confirm, which of the following is happening to you when clicking the `Pull` arrow? I'm assuming it's 2 but want to make sure.

1.  The pull action is not actually happening (the branch doesn't change in the repo), but the "out of sync" status goes away on the branch as if it pulled successfully
2. The pull action is not actually happening, and the "out of sync" status doesn't change in the view
3. The pull action is happening, but the branch still shows as "out of sync" in the view

**Comment by eamodio** [comment]
Can you also please enable debug logging by running the _GitLens: Enable Debug Logging_ command from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ & _GitLens (Git)_ channels in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the logs from the _GitLens_ and _GitLens (Git)_ channels.

Thank you!

**Comment by Neuhaus93** [comment]
@axosoft-ramint It's case 2.
I attached the logs from when I click the button to when it stops loading.
I also noticed that it only fails when I'm in a different branch from the one I'm trying to pull. If it's the same, it works.

[gitlens-log.log](https://github.com/gitkraken/vscode-gitlens/files/12307458/gitlens-log.log)

**Comment by eamodio** [comment]
Thank you for the extra details and I think this should now be fixed.

Can you please verify this fix in tomorrow's (`v2023.8.10xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by Neuhaus93** [comment]
@eamodio I just tried it with the pre-release version and can confirm it works. Thanks for the quick fix.

**Comment by httpete** [comment]
I can report 14.2.1 works perfectly. THANKS!
