### ISSUE TITLE
For custom remotes, the URL resulting from the `branches` is truncated

### ISSUE THREAD

**Issue by huyz** [gitkraken/vscode-gitlens#2850]
### Description

1. When configuring `urls` for `Custom` `gitlens.remotes`, part of the URL template is ignored. For example
```json
    "gitlens.remotes": [
      {
        "regex": "github-custom.*",
        "type": "Custom",
        "urls": {
           "branches": "https://github.com/${repoBase}/${repoPath}/branches",
```
or
```json
      {
        "regex": "bitbucket-custom",
        "type": "Custom",
        "urls": {
          "branches": "https://bitbucket.org/${repoBase}/${repoPath}/branches",
```

2. In the tools sidebar, if I right-click on a remote or an item called `branches` and then click to the menu entry `Open branches on remote`, the resulting URL is correct except the `/branches` is missing at the end. 
3. Just to test, if you move the `/branches` to before `${repoPath}`, then the URL won't be truncated. But then of course, the URL would be wrong.

There is no problem with built-in remote types—just custom `branches` URL template.

### GitLens Version

14.2.0

### VS Code Version

Version: 1.81.0
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:38:28.722Z (6 days ago)
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.6.0

### Git Version

2.41.0

**Comment by eamodio** [comment]
Thank you for the report! This should now be resolved.

Can you please verify this fix in tomorrow's (`v2023.8.10xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)
