### ISSUE TITLE
The commit of multiple branches of cherry-pick is very troublesome

### ISSUE THREAD

**Issue by pavlelee** [gitkraken/vscode-gitlens#2871]
When cherry-pick between different branches, the current interaction is very troublesome. I need to log the commit hash that needs to be requires cherry-pick in b and c branch, and then search for each commit hash. 

This can be optimized to select b and c branch in the location in the picture, and then cherry-pick it directly on the page.
![image](https://github.com/gitkraken/vscode-gitlens/assets/5382358/78a4d985-a6fc-4072-b6d0-e26af7d72ef1)

**Comment by eamodio** [comment]
Can you please add more detail as to the issue you are experiencing and/or the steps to reproduce it? I'm not sure I'm following the request here.

Thank you!
