### ISSUE TITLE
Gitlens doesn't recognize account which is already signed in in customed profile

### ISSUE THREAD

**Issue by MikuAndRabbit** [gitkraken/vscode-gitlens#2878]
#### Experience

I can't use an account that I'm already signed in to in a custom profile, i.e. Gitlens shows that the account is signed in, but the interface of features like Commit Graph still shows that login is required. However, it works fine in the default profile of vscode.

#### Reproduce

1. Switch to a customed profile.
2. Log in to Gitlens Account.
3. Open a local git repository in vscode.
4. Check out the Gitlens plugin's Commit Graph interface (login required here).
5. Only such a welcome prompt will pop up after clicking.

### GitLens Version

14.2.1

### VS Code Version

Version: 1.81.1 (Universal)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:20:33.924Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

### Git Version

git version 2.37.3

### Logs, Screenshots, Screen Captures, etc

Screenshot of Commit Graph Page in Customed Profile

![1692839558596GbbxUM](https://github.com/gitkraken/vscode-gitlens/assets/52323820/03f04e18-835d-4726-86c0-3966b03b6130)

**Comment by jiang263** [comment]
me too

**Comment by eamodio** [comment]
Hrm, I'm not able to reproduce this. How are creating the new profile? Starting from empty? Or a copy?

Can you please enable debug logging by running the _GitLens: Enable Debug Logging_ command from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ & _GitLens (Git)_ channels in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the logs from the _GitLens_ and _GitLens (Git)_ channels.

Thank you!

**Comment by MikuAndRabbit** [comment]
> Hrm, I'm not able to reproduce this. How are creating the new profile? Starting from empty? Or a copy?
> 
> Can you please enable debug logging by running the _GitLens: Enable Debug Logging_ command from the Command Palette (F1 or ctrl/cmd+shift+p). This will enable logging to the _GitLens_ & _GitLens (Git)_ channels in the _Output_ pane.
> 
> Once enabled, please reproduce the issue, and attach the logs from the _GitLens_ and _GitLens (Git)_ channels.
> 
> Thank you!

Thank you for your reply.

I create the custom profile by copying from default profile. And following logs are from Gitlens in a custom profile. It may seem like a problem accessing https://api.gitkraken.com/gitlens/checkin, but I was able to make sure my network was working.

```
[2023-08-25 00:15:50.870] Gunzip.<anonymous>
FetchError: Invalid response body while trying to fetch https://api.gitkraken.com/gitlens/checkin: read ECONNRESET
[2023-08-25 00:15:50.870] SubscriptionService.checkInAndValidateCore
Error: Unable to validate account; status=undefined: undefined
```
The remaining logs (in default profile) contain my account information, so I would like to be sent to your email or official Gitlens email address, and I would like you to provide a way for me to submit the rest of the log content.

Thank you for your assistance.

**Comment by MikuAndRabbit** [comment]
> Hrm, I'm not able to reproduce this. How are creating the new profile? Starting from empty? Or a copy?
> 
> Can you please enable debug logging by running the _GitLens: Enable Debug Logging_ command from the Command Palette (F1 or ctrl/cmd+shift+p). This will enable logging to the _GitLens_ & _GitLens (Git)_ channels in the _Output_ pane.
> 
> Once enabled, please reproduce the issue, and attach the logs from the _GitLens_ and _GitLens (Git)_ channels.
> 
> Thank you!

Additional testing

I just created a profile from none and installed Gitlens in this profile. Testing has shown that Gitlens recognizes the Gitlens account I'm signed in to in this profile. In addition, I tested creating a profile from the default profile that also correctly identifies the Gitlens account that is already logged in. But confusingly, in profiles that don't currently recognize logins, my reinstallation of Gitlens doesn't solve this problem. 

Based on these phenomena, I suspect that the cause of the problem may be that the profile I created earlier was copied from the default profile, but I was not logged into my Gitlens account at the time. Perhaps the problem is due to how vscode implements profilef replication.

**Comment by MikuAndRabbit** [comment]
> Hrm, I'm not able to reproduce this. How are creating the new profile? Starting from empty? Or a copy?
> 
> Can you please enable debug logging by running the _GitLens: Enable Debug Logging_ command from the Command Palette (F1 or ctrl/cmd+shift+p). This will enable logging to the _GitLens_ & _GitLens (Git)_ channels in the _Output_ pane.
> 
> Once enabled, please reproduce the issue, and attach the logs from the _GitLens_ and _GitLens (Git)_ channels.
> 
> Thank you!

Surprisingly, I just logged in again in the custom profile that had the problem before (log out in the default profile first), and the problem suddenly didn't exist. It's really confusing, the problem appears in vague and disappears without clarity.
