### ISSUE TITLE
Deep Link Bug: When opening vscode as a part of a deep link, sometimes it asks to manually open a repo even if it's already open

### ISSUE THREAD

**Issue by axosoft-ramint** [gitkraken/vscode-gitlens#2880]
Note: This may be a race condition between the deep link's repo check and GitLens' repo discovery. We may need to delay the deep link processing until GitLens has had a chance to finish repo discovery.

**Comment by jkelroy** [comment]
My Repro Steps on macOS (13.2.1) - will not consistently happen but happens very often:
- open a repository in VS Code
- close VS Code (and the commit graph if already open)
- Select `Open with GitKraken` on the clone menu from a GitHub repository - I am using this repo https://github.com/jkelroy/be-test
- Select `GitLens in VS Code`
- makes me manually navigate to open the repository

[Video](https://www.transferbigfiles.com/1a0a6c79-b8ac-48b7-a62e-821f47ad8335/0Avg5ABDY6z0Pp2cGETQww2)

Logs: [gitlens.txt](https://github.com/gitkraken/vscode-gitlens/files/12433206/gitlens.txt)

GitLens: v14.2.1

```
Visual Studio Code

Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:40:25.698Z (2 wks ago)
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.3.0
```

**Comment by fai8146767** [comment]
###
