### ISSUE TITLE
Graph Bug: Sometimes the graph seems to infinitely load when opening

### ISSUE THREAD

**Issue by axosoft-ramint** [gitkraken/vscode-gitlens#2882]

**Comment by jkelroy** [comment]
My Repro Steps on macOS (13.2.1) - will not consistently happen but happens very often:
- open a repository in VS Code
- open the commit graph for this repository (can happen without this but consistently happens with it open)
- close VS Code 
- Select `Open with GitKraken` on the clone menu from a GitHub repository - I am using this repo https://github.com/jkelroy/be-test
- Select `GitLens in VS Code`
- makes me manually navigate to open the repository

[Video](https://www.transferbigfiles.com/1a0a6c79-b8ac-48b7-a62e-821f47ad8335/0Avg5ABDY6z0Pp2cGETQww2)

Logs: [gitlens.txt](https://github.com/gitkraken/vscode-gitlens/files/12433206/gitlens.txt)

GitLens: v14.2.1

```
Visual Studio Code

Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:40:25.698Z (2 wks ago)
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.3.0
```

**Comment by axosoft-ramint** [comment]
Can't seem to repro this one. I thought I'd seen traces of it before but currently no matter what I do (including the steps above, and other ways of opening the graph after closing and refreshing the repo or vscode), the graph seems to finish loading each time. Noting that we will need to rule out OS as a factor here.

**Comment by jkelroy** [comment]
I also cannot repro this on Windows either but can on mac.

**Comment by axosoft-ramint** [comment]
I can't reproduce the `no repository selected` issue above, and @d13 couldn't reproduce the original issue (graph not loading) on Mac. Not sure of a way forward here without being able to successfully repro the original issue.

**Comment by eamodio** [comment]
Can you please see if this issue is still reproducible in the pre-release edition of GitLens? Thanks!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by jkelroy** [comment]
No longer persisting for me. Closing the issue.
