### ISSUE TITLE
Repositories view stuck in loading state

### ISSUE THREAD

**Issue by Nedgeva** [gitkraken/vscode-gitlens#2896]
### Description

Happens for me for different inhouse Git/Atlassian Bitbucket repositories.
Switching to earlier versions like those in GitLess fork does the job well.

### GitLens Version

v14.2.1 (same for pre-release)

### VS Code Version

Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

### Git Version

git version 2.42.0.windows.1

**Comment by eamodio** [comment]
Can you please add more detail as to the issue you are experiencing and/or the steps to reproduce it?

Also, if this issue is reproducible, can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the both _GitLens_ and _GitLens (Git)_ channels.

Thank you!

**Comment by Nedgeva** [comment]
Can't say something special regarding STR. Just opening same ol' repo in VSCode as usual. Was working for me flawlessly week-or-two ago. While "Repositories" tab always remains in loading state, I still able to perform routine git tasks like pulling/pushing and so on.

GitLens log output: https://pastebin.com/uez0vBgF
GitLens (Git) log output: https://pastebin.com/eQHVHgFT

Here is how it looks like:
![image](https://github.com/gitkraken/vscode-gitlens/assets/19298874/d25846ed-a1fa-4240-a6f8-da2d2e6d701c)

**Comment by Nedgeva** [comment]
Here's the logs from GitLess for same repo:

GitLess log output: https://pastebin.com/zWpxDvBc
GitLess (Git) log output: https://pastebin.com/1Yzj6vy2

**Comment by Nedgeva** [comment]
> This issue needs more information and has not had recent activity. Please provide the missing information or it will be closed in 7 days. Thanks!

Debugging logs was provided. Waiting for resolution.

**Comment by eamodio** [comment]
I believe I've found the underlying issue -- it seems our fetch request to validate repository "visibility" (public vs private) seems to never return sometimes. I've added a 30s timeout to ensure it won't hang indefinitely.

Can you please verify this fix in tomorrow's (`v2023.9.09xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)
