### ISSUE TITLE
Vscode new version 1.81 hide popup immediately GitLens commit details

### ISSUE THREAD

**Issue by quyenvsp** [gitkraken/vscode-gitlens#2906]
### Description

Does this issue occur when use old version 1.80.2?: No

- VS Code Version: 1.81.1
- OS Version: Windows 11

Steps to Reproduce:

1. Install plugin [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)
2. Hover Commit message for show suggest
3. Click Commit ID for show Quick commit details

Expert:
Quick commit details popup should show and keep present.

Actually:
Popup show but hide immediately

Log:

When occur:
```
TRACE CommandService#executeCommand gitlens.showQuickCommitDetails
(22) log.ts:401 TRACE CommandService#executeCommand _setContext
```

When work normally:
```
TRACE CommandService#executeCommand gitlens.showQuickCommitDetails
(11) log.ts:401 TRACE CommandService#executeCommand _setContext
```

https://github.com/microsoft/vscode/assets/35319492/50002bb4-5abc-41aa-8f93-e8e83cb991f4

### GitLens Version

14.2.1

### VS Code Version

Version: 1.81.1 (system setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

### Git Version

git version 2.42.0.windows.2

**Comment by eamodio** [comment]
Can you still reproduce this in 1.82?

**Comment by quyenvsp** [comment]
@eamodio yes it still here.

Version: 1.82.1 (system setup)
Commit: 6509174151d557a81c9d0b5f8a5a1e9274db5585
Date: 2023-09-08T08:45:05.575Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

Gitlens plugin version: 14.3.0

I am using hyper v virtual machine for reproduce. Just only Gitlens installed with default clean Vscode.

Here are more log, you can see `CommandService#executeCommand _setContext`, when it work only (11). when not work it show (22) times

![image](https://github.com/gitkraken/vscode-gitlens/assets/35319492/026e0072-8c00-4d98-a167-bbe1a4d8e4cf)

**Comment by eamodio** [comment]
VS Code controls the focus behavior that is likely causing this. Please open an issue on the VS Code repository. Thanks!

**Comment by quyenvsp** [comment]
I already filled issue then they closed because Third party plugin. But can
you reproduce it?

Vào 14:14, Th 5, 14 thg 9, 2023 Eric Amodio ***@***.***> đã
viết:

**Comment by Genericreqd** [comment]
[](url)

**Comment by quyenvsp** [comment]
Thank you, from begin I have installed on Hyper-V virtual and only Gitlens plugin installed for sure all is Default setting.
Today, it still happen with all latest Windows 11, Vscode, Gitlens plugin.
But no problem, because you can't reproduce and I fixed by install customize Gitlens build myself. So all seem fine here.
