### ISSUE TITLE
Relaxed or more customizable PR detection

### ISSUE THREAD

**Issue by brunnerh** [gitkraken/vscode-gitlens#2908]
With remotes configured (at least with `AzureDevOps`) it generates PR links from commit comments that look like:
```
Merged PR 1234: ...
```

But if someone is using a localized version, the generated commit can have a different format, e.g.
```
PR 1234 (...) gemergt.
```

In this case no link is generated.
It would be nice if any match of `PR <number>` would be shown as a link or the matching could be customized.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's (`v2023.9.13xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by brunnerh** [comment]
Works as expected, thanks!
