### ISSUE TITLE
Source Control Repositories window pane does not support scroll, and gets too tall

### ISSUE THREAD

**Issue by erikschul** [gitkraken/vscode-gitlens#2919]
### Description

When working with many repositories, the "Source Control Repositories" window pane gets too tall, and occupies too much space:

<img width="557" alt="image" src="https://github.com/gitkraken/vscode-gitlens/assets/128804597/a8e602f5-d79d-45c7-98b4-0261946bd768">

It should be height-adjustable, and scrollable.

### GitLens Version

v14.3.0

### VS Code Version

Version: 1.81.1

**Comment by eamodio** [comment]
Unfortunately there isn't anything GitLens can do here, that UI is managed by VS Code directly. I would suggest opening an issue on the VS Code repository.
