### ISSUE TITLE
Apply Changes should create new files when needed

### ISSUE THREAD

**Issue by tjx666** [gitkraken/vscode-gitlens#2928]
![image](https://github.com/gitkraken/vscode-gitlens/assets/41773861/48f53dee-78ab-4144-b71f-fec23022b96c)

![image](https://github.com/gitkraken/vscode-gitlens/assets/41773861/56772e76-d455-45b6-b867-76bd6559ea62)

**Comment by axosoft-ramint** [comment]
Verified on the pre-release
