### ISSUE TITLE
Cursor IDE (VSCode version) Unable to Use GitLens

### ISSUE THREAD

**Issue by aselunar** [gitkraken/vscode-gitlens#2929]
### Description

I have changed .vscode/extensions/eamodio.gitlens-14.3.0/package.json to include this property: "enabledApiProposals": ["treeItemCheckbox"],
	
I have started cursor with this command: cursor . --enable-proposed-api eamodio.gitlens

Despite this, when I click on 'Source Control' -> 'Commits' -> 'Compare Working Tree with main' and then drill down into a folder with a changed file, I get this error:
  

```
Extension 'eamodio.gitlens' CANNOT use API proposal: treeItemCheckbox. Its package.json#enabledApiProposals-property declares: [] but NOT treeItemCheckbox. The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api eamodio.gitlens. Note that the cursor and control proposals are only available for built-in extensions
```

and none of the changed files will display.

### GitLens Version

v14.3.0 and v2023.9.2105

### VS Code Version

Cursor

ersion: 0.10.4
VSCode Version: 1.80.1
Commit: c0db898419c36107211de244bdcf5f412c1a4920
Date: 2023-09-10T05:39:06.846Z (1 wk ago)
Electron: 22.3.10
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.3.0

### Git Version

git version 2.39.2 (Apple Git-143)

**Comment by eamodio** [comment]
This is an issue with Cursor and not GitLens. GitLens states (in its `package.json`) what version of VS Code is required for that version of GitLens to work correctly, and it sounds like Cursor isn't honoring that and allowing a later version of GitLens to be installed on a version of Cursor that doesn't have the required APIs. Please open an issue with Cursor about this. Thanks!
