### ISSUE TITLE
Alt+click only works when window is focused

### ISSUE THREAD

**Issue by Stadly** [gitkraken/vscode-gitlens#2933]
### Description

When hovering commits, there is a button for quickly copying the commit SHA. By holding `Alt` while clicking the button, the commit message is copied.

This works well when the VS Code window is focused. When the window is not focused, the commit SHA is copied even when the `Alt` key is pressed.

### GitLens Version

14.3.0

### VS Code Version

Version: 1.82.2 (system setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

### Git Version

git version 2.40.1

### Logs, Screenshots, Screen Captures, etc

![image](https://github.com/gitkraken/vscode-gitlens/assets/7263579/69e53f88-2a27-4ebb-b7ec-5f79699653d2)

**Comment by Stadly** [comment]
Did some testing, and discovered that the issue only occurs when it is another VS Code window that is focused.

In the video, you'll see me clicking the copy button on a commit 4 times while holding down the Alt key:
1. The VS Code window is focused => the commit message is copied.
2. Notepad is focused => the commit message is copied.
3. The VS Code window is focused => the commit message is copied (same as step 1, don't know why I did it again 😅).
4. Another VS Code window is focused => the commit id is copied!

https://github.com/gitkraken/vscode-gitlens/assets/7263579/b73637e1-576c-49c0-8906-264f5e946685

**Comment by eamodio** [comment]
Unfortunately, that is a bug in VS Code itself. GitLens can only express what the `alt` command should be, but VS Code is in control over executing it. Can you please [open an issue](https://github.com/microsoft/vscode/issues/new?assignees=&labels=&template=bug_report.md) on the VS Code repository? Thanks!
