### ISSUE TITLE
Icons not loading on NixOS

### ISSUE THREAD

**Issue by katexochen** [gitkraken/vscode-gitlens#2935]
### Description

Hey, cross-linking the following issue from nixpkgs: https://github.com/NixOS/nixpkgs/issues/218031

To sum up, icons can't be loaded due to the way/path they are accessed by, see the explanation in https://github.com/NixOS/nixpkgs/issues/218031#issuecomment-1546756782 .

Not sure if this is something that you can easily fix upstream, but I'd like to raise awareness and help would be really appreciated. :)

### GitLens Version

14.1.1

### VS Code Version

Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:18:39.991Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.5.1

### Git Version

git version 2.41.0

### Logs, Screenshots, Screen Captures, etc

Screenshots can be found in the linked issue.

**Comment by eamodio** [comment]
This isn't something GitLens can control. GitLens just provides its icon font as a contribution point to VS Code and VS Code is responsible for loading it.
