### ISSUE TITLE
Invalid Request when trying to generate a commit message using Anthropic API 

### ISSUE THREAD

**Issue by MohamedEmary** [gitkraken/vscode-gitlens#2941]
### Description

When trying to generate a commit messaage using Anthropic Claude 2 API key I got invalid request with error code 400

### GitLens Version

14.3.0

### VS Code Version

Version: 1.82.1 (user setup)
Commit: 6509174151d557a81c9d0b5f8a5a1e9274db5585
Date: 2023-09-08T08:45:05.575Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

### Git Version

git version 2.36.1.windows.1

### Logs, Screenshots, Screen Captures, etc

![Error Message](https://github.com/gitkraken/vscode-gitlens/assets/64380567/f4e1b9e6-7a2e-446a-a0a2-2fab99b21fb7)

![Error Notification Message](https://github.com/gitkraken/vscode-gitlens/assets/64380567/86d3a32b-990a-4fa0-a1f7-e4382ace2306)

**Comment by MohamedEmary** [comment]
Unfortunately while trying to solve the issue I thought maybe a new API key would work so I deleted the current one and created a new one to use in the extension but found out that the reset API key option is only available for OpenAI models.
I have even tried remove the extension entirely from vscode, remove vscode cache and the extension folder in

%USERPROFILE%\.vscode\extensions

, then reinstalled the extension again but the API is somehow still stored and I can't add a different one.


________________________________

**Comment by eamodio** [comment]
Sorry about that, in tomorrow's pre-release (`v2023.09.29xx`) I've changed the `Reset OpenAI Key` command to be `Reset AI Key` and now it will properly reset the key for the selected provider (OpenAI or Anthropic). I've also fixed the missing header, so it should fix the 400 error as well.

Can you please verify this fix in tomorrow's (`v2023.09.29xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by MohamedEmary** [comment]
Great! Everything is working as expected now.

- [x] I was able to reset my Anthropic API and use another one 
- [x] Invalid request error has been fixed
