### ISSUE TITLE
Allow filtering of merge commits in File History view

### ISSUE THREAD

**Issue by alexr00** [gitkraken/vscode-gitlens#2944]
I like to use the File History view to quickly find the owner of a file. In repositories that use PRs with merge commits, the File History view quickly becomes useless:

<img width="398" alt="image" src="https://github.com/gitkraken/vscode-gitlens/assets/38270282/1581d50f-e31b-403f-9569-e90e83191f3a">

I would love to have a way to filter out some of these unhelpful commits from the view. If it's not possible to detect commits that were part of a merge commit then just allowing a regex to filter commit titles could work.

**Comment by eamodio** [comment]
I've defaulted the _File History_ view to follow renames. I've also removed merge commits from the _File History_ view by default, and added a _[Show|Hide] Merge Commits_ toggle to the view's `...` menu and a corresponding `gitlens.advanced.fileHistoryShowMergeCommits` setting to specify whether merge commits will be show in file histories.

Can you please verify this fix in tomorrow's (`v2023.10.07xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by alexr00** [comment]
Verified! This is a huge improvement, thank you!
