### ISSUE TITLE
Inline blame not working because of missing ignoreRevsFile

### ISSUE THREAD

**Issue by ivasic** [gitkraken/vscode-gitlens#2952]
### Description

I can't get GitLens to show anything inline in one of my projects. It works from the primary sidebar (reads the repo, commits, everything...) but struggles to do anything inline. I enabled the logging and this is what I get:
```
[2023-10-09 11:59:29.502] [  9b9] GitProviderService.getRepository
[2023-10-09 11:59:29.502] [  9b9] GitProviderService.getRepository returned E(/Users/myuser/repo) [0ms]
[2023-10-09 11:59:29.502] [  9b8] GitProviderService.getOrOpenRepository returned E(/Users/myuser/repo) [0ms]
[2023-10-09 11:59:29.502] [  9ba] GitProviderService.getBlameForLine
[2023-10-09 11:59:29.502] [  9bb] LocalGitProvider.getBlameForLine
[2023-10-09 11:59:29.503] [  9bc] LocalGitProvider.getBlame
[2023-10-09 11:59:29.503] [  9bc] LocalGitProvider.getBlame completed [0ms]
[2023-10-09 11:59:29.503] [  9bb] LocalGitProvider.getBlameForLine completed [0ms]
[2023-10-09 11:59:29.503] [  9ba] GitProviderService.getBlameForLine completed [0ms]
[2023-10-09 11:59:29.503] ShowMessage(warn, 'Unable to show commit file details. The file is probably not under source control.', suppressFileNotUnderSourceControlWarning, {"title":"Don't Show Again"})
```

GitLens works without issues in another project so I'm suspecting something is bothering it in this one particularly. First thing that comes to mind is that I'm using the [Monorepo Workspace](https://marketplace.visualstudio.com/items?itemName=folke.vscode-monorepo-workspace) plugin for this project but the setup is not that complicated, here's the relevant part:
```
"folders": [
		{
			"name": "✨ root",
			"path": ".."
		},
		{
			"name": "backend",
			"path": "../backend"
		},
		{
			"name": "frontend",
			"path": "../frontend"
		},
	],
```

Any ideas?

### GitLens Version

14.3.0

### VS Code Version

Version: 1.83.0 (Universal)
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:13:15.449Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

### Git Version

git version 2.39.3 (Apple Git-145)

**Comment by eamodio** [comment]
Can you provide more details on your setup? Where in the folder hierarchy is the `.git` folder? Is this just normal folders on disk, or symlinks or network drives?

It would also be great to get full logs with the repo discovery.

**Comment by ivasic** [comment]
Hi Eric, thanks for looking into this!
The hierarchy is pretty simple, looks like this:
```
myproject
│
├── .git
│
├── backend
│
└── frontend
```

so `.git` is in the very root of the project. There are no symlinks, network drives, submodules anything like that. Monorepo plugin loads a workspace from the root so that vscode plays nice with both BE and FE.

I've attached the full logs this time, hope this helps

[lenslogs.txt](https://github.com/gitkraken/vscode-gitlens/files/12878447/lenslogs.txt)

**Comment by eamodio** [comment]
From the logs everything looks like it is working as expected. I also setup a super simple example: [multiroot.zip](https://github.com/gitkraken/vscode-gitlens/files/12884320/multiroot.zip) -- can you take a look and see if the inline blame works for you on that? And if so, can you change it to more accurately reflect your setup?

**Comment by ivasic** [comment]
my `*.code-workspace` lives under `.vscode` folder in the root directory. But I've just tried your example (thanks for setting that up btw) and I get the same thing with inline blame not doing its thing. The sidebar works, I could see your commit details but the inline part fails with the same warning message I sent in the 1st post.

Have you noticed the lines in the log file where it says `GitProviderService.getRepository returned E`? I assumed that this `E` means "error", or am I mistaken?

[logs2.txt](https://github.com/gitkraken/vscode-gitlens/files/12892643/logs2.txt)

**Comment by eamodio** [comment]
Hrm, I still see nothing wrong in that log other than the `Unable to show commit file details` at the end. Can you record a video of what is happening? Can you also send over your `settings.json`?

That `E()` in the logs is not an error, it is unfortunately just a minification artifact, since the `Repository` class apparently got minified to `E`.

**Comment by ivasic** [comment]
Ah gotcha. I was kind of hoping that indicated an error which was supposed to help debug it.. 
[Here's a short video](https://drive.google.com/file/d/1p3bV4LLizf8jWK1fDkkGGyjF1QX8wNL5/view) of what's going on and my user `settings.json` file. Appreciate you having a look.

```
{
    "workbench.iconTheme": "vscode-icons",
    "window.commandCenter": true,
    "[python]": {
        "editor.defaultFormatter": "ms-python.python",
        "editor.formatOnType": true
    },
    "yaml.schemas": {
        "file:///Users/ivvasic/.vscode/extensions/atlassian.atlascode-3.0.7/resources/schemas/pipelines-schema.json": "bitbucket-pipelines.yml"
    },
    "atlascode.bitbucket.pipelines.explorerEnabled": false,
    "atlascode.bitbucket.issues.explorerEnabled": false,
    "atlascode.jira.todoIssues.enabled": false,
    "redhat.telemetry.enabled": false,
    "editor.smoothScrolling": true,
    "workbench.list.smoothScrolling": true,
    "editor.renderWhitespace": "none",
    "atlascode.bitbucket.explorer.enabled": true,
    "atlascode.bitbucket.statusbar.showLogin": true,
    "atlascode.bitbucket.explorer.notifications.pullRequestCreated": true,
    "[yaml]": {
        "editor.insertSpaces": true,
        "editor.tabSize": 2,
        "editor.autoIndent": "keep",
        "gitlens.codeLens.scopes": [
            "document"
        ],
        "editor.quickSuggestions": {
            "other": true,
            "comments": false,
            "strings": true
        }
    },
    "terminal.integrated.smoothScrolling": true,
    "workbench.fontAliasing": "auto",
    "atlascode.jira.enabled": true,
    "atlascode.bitbucket.enabled": true,
    "diffEditor.renderSideBySide": false,
    "errorLens.delay": 1500,
    "circleci.notifications.areActive": "yes",
    "vsicons.dontShowNewVersionMessage": true,
    "files.associations": {
        "*.html": "jinja"
    },
    "gitlens.outputLevel": "verbose",
    "window.zoomLevel": -1,
}
```

**Comment by eamodio** [comment]
I'm really at a loss. Can you maybe try disabling other extensions to see if there is any conflict (errorLens maybe?)? Also can you set `"gitlens.outputLevel": "debug",` and repro and see if there is any better information in there (`debug` is the most verbose)

**Comment by ivasic** [comment]
Thanks for the tip, I was under the impression that `verbose` is the most verbose level :) 
I got some errors in the log now, maybe that helps. 

[logs3.txt](https://github.com/gitkraken/vscode-gitlens/files/12929590/logs3.txt)

Also, I tried disabling _all_ plugins but gitlens and monorepo workspace and got the same thing :/ 
I tried creating a new project, simple one, no monorepo just a few files and it doesn't work there either. Very strange cause I have a different project on the same machine where it does work without any issues.

**Comment by eamodio** [comment]
What do you get if you run `git blame --root --incremental -- backend/src/back.ts` from the `/Users/ivvasic/Downloads/multiroot` folder?

**Comment by ivasic** [comment]
Ahhh... found the problem. The output was: `fatal: could not open object name list: .git-blame-ignore-revs`.

I had 
```
[blame]
        ignoreRevsFile = .git-blame-ignore-revs
```
in my global `.gitconfig` and git doesn't seem to like it when `.git-blame-ignore-revs` is not found in the repo :( 
Removing this setting (or adding an empty `.git-blame-ignore-revs` file) fixes the issue and GitLens works as expected.

Eric, thanks a lot for helping me debug this, I hope you got some value out of all this and it wasn't a total waste of time.

**Comment by eamodio** [comment]
Thanks for the help getting to the bottom of it!

Since contrary to the Git docs, there doesn't seem to be a way to override the `blame.ignoreRevsFile` on the command line, so I've added better error handling to alert the user to this case.

**Comment by aGoodOne** [comment]
ich habe seit 4 Jahren 3 handys mit 3 unterschiedlichen Sim. Ich habe aber nur 2 email adressen und bin daher mit einer email adresse auf 2 handys angemeldet. da die schlüssel mit der Nutzung des Kontos installiert werden habe ich die schlüssel quasi 2x und jedes handy erzeugt ein anderes ergebnis. wenn man nur mit 2 handys validiert sind fast 1/3 der daten schrott. Das 3 handy wurde auch in mein LAN-Heimnetz integriert, und ich glaube er verschlüsselt die daten mit dem handy was gerade verfügbar ist da ich nicht immer 3 handys dabei habe.
