### ISSUE TITLE
Feat: Add pull options: git pull (--rebase) --autostash

### ISSUE THREAD

**Issue by Onekki** [gitkraken/vscode-gitlens#2954]
Add autostash option when pull

**Comment by eamodio** [comment]
Can you please add more detail to what you would like to see here? Thanks!

**Comment by eamodio** [comment]
FYI, you can add
```
[pull]
	autoStash = true
```

To your .gitconfig and it will always autostash.

**Comment by Onekki** [comment]
> FYI, you can add
> 
> ```
> [pull]
> 	autoStash = true
> ```
> 
> To your `.gitconfig` and it will always autostash.

Thank you for your answer
