### ISSUE TITLE
> Is it a requirement to create a gitlens+ account and sign-in to use gitlens now?

### ISSUE THREAD

**Issue by Shadi-CW3** [gitkraken/vscode-gitlens#2955]
> Is it a requirement to create a gitlens+ account and sign-in to use gitlens now?

GitLens is COMPLETELY FREE, NO ACCOUNT or anything, and can be used on ANY repo (local/public/private/etc).

**GitLens+ features on local & public repos** are also COMPLETELY FREE, NO ACCOUNT or anything. ONLY **GitLens+ features on private repos** require a Pro plan (or greater).

> I just installed gitlens on a new machine and there's nothing in the GitLens tab in VSCode other than a bunch of blurb about gitlens features.
>
> When I click the "CLOSE" button at the bottom it closes the slide-out.
>
> I can't find the familiar branches/commits/stashes/etc. info that I'm used to on my other machines where I've been running GitLens in the past.

By default, those GitLens views are located on the Source Control panel:
![Screen Shot 2022-11-23 at 1 31 18 PM](https://user-images.githubusercontent.com/293282/203622325-318bfcb1-96f8-4ebb-ba31-4af80403f3f3.png)

If you would like to move those views to the GitLens side panel, simply click the GitLens icon in the "Features" section of the Home view:
![Screen Shot 2022-11-23 at 1 33 09 PM](https://user-images.githubusercontent.com/293282/203622560-07650d4c-5d18-461e-85b5-af5d3ebf472a.png)

_Originally posted by @d13 in https://github.com/gitkraken/vscode-gitlens/discussions/2372#discussioncomment-4219245_

**Comment by eamodio** [comment]
@Shadi-CW3 What is the question here? An account is not required to use GitLens, but is required for access to Pro features on private repositories and for cloud-based Pro features.

**Comment by Shadi-CW3** [comment]
CW3 Inc
