### ISSUE TITLE
Open Changes with previous revision button is hidden

### ISSUE THREAD

**Issue by nmoreaud** [gitkraken/vscode-gitlens#2956]
### Description

![image](https://github.com/gitkraken/vscode-gitlens/assets/2413781/126f1ba4-83d3-4349-bbe6-667324524c3e)

If I click on previous version:
![image](https://github.com/gitkraken/vscode-gitlens/assets/2413781/7f372bf0-5401-444c-8251-23385709213c)

If I click again:
![image](https://github.com/gitkraken/vscode-gitlens/assets/2413781/4b851aab-fd16-4bbe-a869-002fb4362626)

Then the previous button is hidden, though still accessible through the "..." menu.
I would like it to remain visible, is it possible?

### GitLens Version

v14.3.0

### VS Code Version

Version: 1.83.0 (user setup)
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:12:16.321Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by eamodio** [comment]
Unfortunately, that is a "feature" of VS Code -- they've changed it so only a certain number of items can be shown at the same time in that toolbar. So as long as there are too many items there, some will fall off into the `...` menu. You can choose to manually hide some of the other icons, which will stop other from falling off.

**Comment by nmoreaud** [comment]
Could you tell me the easiest way to choose which buttons to display?

**Comment by 737** [comment]
Thank you, but every time you click on it, a new tab opens, which can be maintained?
