### ISSUE TITLE
Revision Navigation Doesn't Work

### ISSUE THREAD

**Issue by DScheglov** [gitkraken/vscode-gitlens#2973]
### Description

After Clicking on the Previous Revision Button VS Code displays the correspondent changes and hides the revision navigation buttons

### GitLens Version

v14.4.0

### VS Code Version

Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:45:31.402Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.2.0-34-generic

### Git Version

git version 2.34.1

**Comment by d13** [comment]
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/2956

VS Code will move buttons into the `...` menu after certain number of actions are added to the toolbar. We cannot control this unfortunately.

**Comment by DScheglov** [comment]
@d13 
unfortunatelly it works in the different way: it opens a new tab with changes between revisions ...

Well, in any case thank you for your answer and for GitLens Extension

**Comment by eamodio** [comment]
@DScheglov  Can you show a video of what you are seeing?

**Comment by DScheglov** [comment]
@eamodio 
I'm not sure that is an unexpected behaviour -- it is just not the same as it was before, when I could navigate between revisions in the same tab:

Please find the screen cast attached

[Screencast from 18-10-2023 14:34:35.webm](https://github.com/gitkraken/vscode-gitlens/assets/9888941/db762444-0c6f-4100-8bf3-0f3d502dac7b)

**Comment by jkelroy** [comment]
@DScheglov in your settings.json (command/ctrl + shift + P > _Preferences: Open User Settings(JSON)_) do you have `"workbench.editor.enablePreview": false`? If so, try setting this to `true` instead.

**Comment by DScheglov** [comment]
@jkelroy 
sorry for late answer ... was sick
![image](https://github.com/gitkraken/vscode-gitlens/assets/9888941/6e44e5b5-2267-4e20-90c5-fbddf7a3893b)

I've set to `true` this parameter and now it works as expected -- thank you for help. But it will be great to get this nav.buttons back ))

I guess the issue could be closed.

**Comment by Insood** [comment]
Would it make sense to set that as the default for the extension?

**Comment by vinodhum** [comment]
Hi I am running into same issue, after click on previous revision for first time, icons to navigate previous and next revision disappear, any idea how to fix it.

first time
![image](https://github.com/gitkraken/vscode-gitlens/assets/5168174/c4071ba1-0ba4-444a-b53c-bf57e4cc9a74)

then
![image](https://github.com/gitkraken/vscode-gitlens/assets/5168174/e0f0fb68-bf55-4184-903d-f9bf956622e9)
