### ISSUE TITLE
Diff view is generating an invalid URI

### ISSUE THREAD

**Issue by dansoper** [gitkraken/vscode-gitlens#2978]
### Description

This is related to an error I'm receiving from the C# extension in VS Code.

[https://github.com/dotnet/vscode-csharp/issues/6256](https://github.com/dotnet/vscode-csharp/issues/6256)

The error from the C# extension is:

```
[Error - 2:59:56 PM] Document pull failed for text document gitlens://7b22726566223a2263663039393534326130303366306633393361326436353064656665643139393932616234366335222c227265706f50617468223a22633a2f55736572732f44616e536f7065722f736f757263652f702d64726976652f4769744c61622f6566732d636f72652f6566732d636f72652d7365727665722d73696465227d/c%3A/Users/DanSoper/source/stuff/Controllers/MyController.cs?%7B%22ref%22%3A%22cf09954%22%7D
  Message: Invalid URI: The hostname could not be parsed. 
```

So, although the C# is generating the error, it is technically because the GitLens URI is not technically a valid URI.  I have no idea if this is something that can be changed? I did have a brief look and couldn't find an existing issue. Apologies if I have missed it.

### GitLens Version

14.4.0

### VS Code Version

Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

### Logs, Screenshots, Screen Captures, etc

![image](https://github.com/gitkraken/vscode-gitlens/assets/14397428/6edf4d3c-6902-45df-8772-3116121ef11b)

**Comment by eamodio** [comment]
AFAIK that is a valid URL, I don't know why the C# extension would have issues with it. But it would need to be fixed on their end.
