### ISSUE TITLE
First name for inline blame?

### ISSUE THREAD

**Issue by ipkpjersi** [gitkraken/vscode-gitlens#2980]
Hi,

I took a look and it seems like as far as I can tell, there's no duplicate issue for this and basically there's no way to be able to display only the author's first name for inline blame? This would be a really awesome feature for me to only display the author's first name in the inline blame.

Cheers.

**Comment by Sweetdevil144** [comment]
Hey, would you like the inline blame display to be Optional. This may indeed be a nice improvement.

Best.

**Comment by ipkpjersi** [comment]
Yeah, I think having it be optional would be nice - you could pick either full name or first name.

**Comment by eamodio** [comment]
Added 2 new formatting tokens `${authorFirst}` and `${authorLast}` that can be used in inline blame, commit hovers, etc

For example, they can be used in the following settings:
`gitlens.currentLine.format` -- inline blame
`gitlens.hovers.detailsMarkdownFormat` -- blame hovers
`gitlens.blame.format` -- file blame
`gitlens.views.formats.commits.*` -- commits in views
`gitlens.statusBar.format` -- status bar blame
`gitlens.statusBar.tooltipFormat` -- status bar hover

Can you please verify this fix in tomorrow's (`v2024.09.25xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by ipkpjersi** [comment]
I have tested it just now and can confirm it works. Thanks!
