### ISSUE TITLE
Unable to remove all marks on reviewed files with a single operation

### ISSUE THREAD

**Issue by zapateo** [gitkraken/vscode-gitlens#2987]
### Description

Issue #836 discussed and introduced the ability to mark certain files as reviewed. However, when using this feature, I'm unable to deselect all the marked files, which can be quite inconvenient when dealing with revisions involving many files.

Is there a way to perform this operation without manually deselecting each file?

Dismissing and re-creating the compare view does not solve the problem, as it leaves the checkboxes marked.

### GitLens Version

14.4.0

### VS Code Version

Version: 1.83.1
Release: 23285
Commit: 36d13de33ac0d6c684f10f99cff352e2f58228b3
Date: 2023-10-12T18:26:29.496Z
Electron: 25.8.4
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.5.6-200.fc38.x86_64

### Git Version

git version 2.41.0

### Logs, Screenshots, Screen Captures, etc

The number of marked checkboxes can grow significantly, in some cases up to 50, 100 marked files.

![immagine](https://github.com/gitkraken/vscode-gitlens/assets/11294400/8bc37c03-37e5-4e69-877c-58865081d7b8)

**Comment by eamodio** [comment]
Thanks for the report! There were some bugs in there where the checked files weren't getting cleared out appropriately when you cleared/dismissed a comparison which are now fixed.

And I've added a _Clear Reviewed Files_ command in the right-click menu of the comparisons (and the files node itself) to clear them manually.

Can you please verify this fix in tomorrow's (`v2023.10.26xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by zapateo** [comment]
> Thanks for the report! There were some bugs in there where the checked files weren't getting cleared out appropriately when you cleared/dismissed a comparison which are now fixed.
> 
> And I've added a _Clear Reviewed Files_ command in the right-click menu of the comparisons (and the files node itself) to clear them manually.
> 
> Can you please verify this fix in tomorrow's (`v2023.10.26xx`) pre-release edition of GitLens? Thank you so much!
> 
> You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.
> 
> ![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

Thank you! I confirm that this works as expected! 😊
