### ISSUE TITLE
VS Code Breadcrumb symbols become invisible when GitLens is enabled

### ISSUE THREAD

**Issue by sivanni** [gitkraken/vscode-gitlens#2994]
### Description

1. WSL under Windows 11, 
2. VS Code, extensions under WSL:Ubuntu: Python, Pylance, GitLens, GitHubCopilot, GitHubCopilot chat, Black Formatter, Excel viewer

### GitLens Version

 v14.4.1

### VS Code Version

Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

### Git Version

2.34.1

### Logs, Screenshots, Screen Captures, etc

Expected behavior:
![image](https://github.com/gitkraken/vscode-gitlens/assets/15344995/877b243c-2912-451e-a071-7a8ecc56d1b9)
After enabling GitLens and reloading VS Code
![image](https://github.com/gitkraken/vscode-gitlens/assets/15344995/1f2e58e1-42ae-4033-bb5e-40ef43723892)

**Comment by eamodio** [comment]
Unfortunately, that sounds like a bug in VS Code itself, as GitLens shouldn't be able to affect that in any way. Can you please [open an issue](https://github.com/microsoft/vscode/issues/new?assignees=&labels=&template=bug_report.md) on the VS Code repository? Thanks!
