### ISSUE TITLE
"push to commit" pushes everything instead of up to the selected commit 

### ISSUE THREAD

**Issue by kchang718** [gitkraken/vscode-gitlens#2997]
### Description

Push to Commit feature pushes everything instead of the given commit

<img width="132" alt="image" src="https://github.com/gitkraken/vscode-gitlens/assets/76565293/ee458380-4786-4e01-864e-503b61aec509">

 clicking on the up arrow expect to push to the labeled commit, but everything goes out instead

It's been happening for a while.  I'm unsure if it's GitLens or something to do with my git settings.  I can do it on the command line fine.

### GitLens Version

14.4.1

### VS Code Version

Version: 1.84.0 (user setup)
Commit: d037ac076cee195194f93ce6fe2bdfe2969cc82d
Date: 2023-11-01T11:29:04.398Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

### Git Version

git version 2.42.0

**Comment by eamodio** [comment]
Ouch! Really sorry about that.

Can you please verify this fix in tomorrow's (`v2023.11.03xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by kchang718** [comment]
looks good now.  thanks!
