### ISSUE TITLE
Add "search in sidebar" option to quickpick search dialog

### ISSUE THREAD

**Issue by losnappas** [gitkraken/vscode-gitlens#3001]
I like the "quick pick search" feature because it's very keyboard friendly, however when in a large repo I start a search, I have to wait for quite a long time before I can see the results (and usually I move them to the sidebar then, so I don't lose them). So what I'd like is an option to type my search query in the widget, but then commit the search in the sidebar.

Widget in question:

![image](https://github.com/gitkraken/vscode-gitlens/assets/25119292/5d8d0108-b01e-41fb-9e4a-9f0923363b3e)

**Comment by eamodio** [comment]
Sounds like a great idea for a setting on that -- and the hard work is already done, because if you open the quickpick from the _Search & Compare_ view then it works this way currently.

**Comment by eamodio** [comment]
Not sure exactly when this was added, but this exists now.
![image](https://github.com/gitkraken/vscode-gitlens/assets/641685/7305f35c-a5ac-44c6-a993-5a9fa08749d5)
