### ISSUE TITLE
Generate Commit Message "OpenAI GPT-4 Turbo" Support

### ISSUE THREAD

**Issue by 4itech-paul** [gitkraken/vscode-gitlens#3005]
Is it possible to incorporate support for OpenAI GPT-4 Turbo into the "Generate Commit Message" feature? This model was recently released.

**Comment by ivanscorral** [comment]
You can manually set the model to "gpt-4-1106-preview" in VS Code's settings.json like this:

`"gitlens.ai.experimental.openai.model": "gpt-4-1106-preview"`

I can confirm this works, even if VSCode displays a warning saying that the value is not accepted. You can check this by setting the model to some model that does not exist. This will return a 404 error, meaning that the extension correctly reads the model you manually set here.

Also, after ~10 minutes after executing some requests using this model you should be able to see the usage popping up in [https://platform.openai.com/usage](https://platform.openai.com/usage). 

In my experimentation, GPT-4 Turbo yields much better results than GPT-4, while being much faster and, although more costly than 3.5 Turbo, its quality is far beyond.

Hope this is helpful.

**Comment by 4itech-paul** [comment]
thanks a lot

**Comment by eamodio** [comment]
In tomorrow's pre-release this will be a supported option as well as refined prompts for better outputs
