### ISSUE TITLE
Regression: cannot stage multiple files at once

### ISSUE THREAD

**Issue by eugenenelou** [gitkraken/vscode-gitlens#3007]
### Description

I'm used to staging files in bulk via the "GitLens" inspect view.

But with my latest upgrade the options to stage multiple files at once disappeared and I only have the `+` button per file.

Also It now puts the view "Commit" that I don't care about before "Working Changes" and I didn't find a way to disable this behaviour.
And the sidebar icon no longer indicates whether there are pending file changes.

I don't believe this loss of useful feature is wanted, but if they are I'd like to know the reasoning.

edit: I tried downgrading to a version I know used to have this (13.5.0) but I still have the same thing. Could it be due to a VSCode upgrade?

### GitLens Version

14.4.1

### VS Code Version

Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:45:31.402Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.2.0-32-generic

### Git Version

git version 2.34.1

### Logs, Screenshots, Screen Captures, etc

![image](https://github.com/gitkraken/vscode-gitlens/assets/22316677/4475b5c0-5f99-4b34-a8e6-1d43df72d2a5)

**Comment by fai8146767** [comment]
###

**Comment by eugenenelou** [comment]
@eamodio Thanks it explains a lot! I have no idea how I switched to the GitLens view or how to revert the switch, I combed through the settings.

**Comment by eamodio** [comment]
You can drag it back, or right-click on it and choose _Reset Location_ to put it back where it should be. FYI, that works on any VS Code view.

**Comment by eugenenelou** [comment]
Perfect ! thanks a lot, yes I never used this before :sweat_smile:
