### ISSUE TITLE
Inline/hover details on the Commit Graph

### ISSUE THREAD

**Issue by EHMilon** [gitkraken/vscode-gitlens#3008]
###  When we want to see git changes, changes file should open in right side or dropdown or tooltip instead open in sidebar.

![demo](https://github.com/gitkraken/vscode-gitlens/assets/107425940/b3246379-1f0d-429e-84d2-35a1cae6a287)

**Comment by d13** [comment]
GitGraph is not maintained by us. Please open an issue on their repo: https://github.com/mhutchie/vscode-git-graph/issues

**Comment by EHMilon** [comment]
> GitGraph is not maintained by us
I am requesting the features to GitLens. I used this .gif image from git graph as example.

**Comment by dimateos** [comment]
Would also love if it could be docked at the bottom of the view. I think the commits details could get some improvements as discussed in https://github.com/gitkraken/vscode-gitlens/issues/2366 too.
> Not the same as docking the current view in terminal panel, but inside the editor (hopefully nicely integrated with the graph view). Also using git-graph as an example:

![image](https://github.com/gitkraken/vscode-gitlens/assets/26868611/8ae46e02-bc25-43e5-97dd-3baaa7d42005)

**Comment by eamodio** [comment]
This issue has been addressed in the latest (or recent) version of GitLens. If you are still experiencing this, please let us know and we can re-open the issue or open a new issue if this is already locked.
