### ISSUE TITLE
"Compare with main" button

### ISSUE THREAD

**Issue by lukepighetti** [gitkraken/vscode-gitlens#3012]
Compare with `main` is a super common workflow for us and I haven't found an easy way to do this. End up having to go through configuring a comparison and it always clears out when I make a commit.

**Comment by sukronc** [comment]
> Compare with `main` is a super common workflow for us and I haven't found an easy way to do this. End up having to go through configuring a comparison and it always clears out when I make a commit.
- [installed ]

**Comment by eamodio** [comment]
Can you provide more details on what you'd like to see?

> End up having to go through configuring a comparison and it always clears out when I make a commit.

And what do you mean here? Can you show the behavior?

FYI, GitLens already has configurable comparisons in multiple views, Commits, Branches, Search & Compare.

For example, in the _Commits_ view, you can click this row and select the `main` branch and it will be remembered (we remember  the chosen comparison for each source branch)

![image](https://github.com/gitkraken/vscode-gitlens/assets/641685/de993714-43ce-4584-b066-c981419c3001)

This same comparison also available in the _Branches_ view:

![image](https://github.com/gitkraken/vscode-gitlens/assets/641685/eae5a9ec-cda2-474d-97d2-bcf03685a581)

And in the Search & Compare view you can add a comparison for a commit/branch/tag/HEAD to any other and they are remembered as well:

![image](https://github.com/gitkraken/vscode-gitlens/assets/641685/87c37d38-65ca-4a1a-88dc-c36cee823b04)
