### ISSUE TITLE
Line blame overlay is broken when commit message contains a `)`

### ISSUE THREAD

**Issue by jnjaeschke** [gitkraken/vscode-gitlens#3018]
### Description

Best described using the picture below. :)

When a commit message contains a `)`, the "open in commit graph" link in the gitlens line blame overlay is broken. This is a regular annoyance on my end because a colleague typically writes commit messages like `Part 1) Description`.

If the closed `)` is opened in the commit message as well (e.g. `Test ()`), the behavior is as expected.

Steps to reproduce:
Create a commit with message `Test )` to see the broken behavior.
Create a commit with message `Test ()` to see that a closed parenthesis which doesn't have an opened parenthesis is the issue.

### GitLens Version

14.5.0

### VS Code Version

Version: 1.84.2 (Universal)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:33.687Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0

### Git Version

git version 2.39.2

### Logs, Screenshots, Screen Captures, etc

![grafik](https://github.com/gitkraken/vscode-gitlens/assets/32952989/91b77553-7a8c-4588-8f9b-7cc54134a43b)

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's (`v2023.11.16xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by jnjaeschke** [comment]
That fixed it, awesome! Thank you so much for the quick response :)
