### ISSUE TITLE
Compare folder contents among different revisions

### ISSUE THREAD

**Issue by widoz** [gitkraken/vscode-gitlens#3020]
In a nutshell, would be nice to have the same Open Changes Menu which appear when selecting a file working with directories.

**Comment by eamodio** [comment]
Can you please add more detail as I'm not sure I'm understanding the feature request here? Thank you!

**Comment by widoz** [comment]
Hi there, sure. Sorry if it wasn't clearn enough.

In the screenshot below, you can open the changes for a file and compare it with a Branch or a Tag. But you can't do that for directories.

<img width="611" alt="image" src="https://github.com/gitkraken/vscode-gitlens/assets/1917784/e07212a3-b56b-4a95-9aa9-e130de576af6">

**Comment by eamodio** [comment]
Thanks, but I'm still not clear on what an action there would do. What would you expect to happen if there was an option for directories?

**Comment by widoz** [comment]
Well, I assume the content of two directories can be compared by Branch, Tag or Revision. 

For instance, having a dir `module/A` I can right click on it and compare the same directory on another branch.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's (`v2023.12.11xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by widoz** [comment]
Hi @eamodio 

First of all thanks a bunch for the addition, I'm able to see the option for the directories and I can have a view of the multi diff. One thing though, not sure yet if it might be related to a extension conflict, if I select a directory containing multiple directories and level I obtain a list like the following one, where there are some directories named with number even thought them do not exists in my project. 

<img width="688" alt="image" src="https://github.com/gitkraken/vscode-gitlens/assets/1917784/8406de28-9873-4144-90af-a62ca1ecd67e">

More the a conflict with an extension I guess it might be because the file not exists anymore in the current branch.
For instance one of those directories contain the content of a file `posts-post-type-controller.tsx` I do have in the `main` (the one using for diff)  branch but not in the current one.

**Comment by eamodio** [comment]
@widoz Thanks for the report -- I opened https://github.com/gitkraken/vscode-gitlens/issues/3062 to track it
