### ISSUE TITLE
`generateCommitMessagePrompt` is no longer considered when generating commit messages

### ISSUE THREAD

**Issue by vitebo** [gitkraken/vscode-gitlens#3025]
### Description

I've been generating commits using the extension for quite some time, and it has been very helpful. However, since an update around October, my prompt is no longer considered when generating commit messages. The prompt is crucial for maintaining a commit message pattern that I've established.

### GitLens Version

14.5.0

### VS Code Version

Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:57.054Z (1 wk ago)
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0

### Git Version

git version 2.39.3 (Apple Git-145)

**Comment by eamodio** [comment]
There haven't been any changes in 14.5 other than in the models themselves, though I very recently I've made significant changes to the feature to control the models more effectively.

Can you please see if this works better in the pre-release edition of GitLens? Thanks!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by vitebo** [comment]
I'm still dealing with the same issue in the pre-release version, but I'm starting to wonder if it's something on my end.

I cloned the repository and ran it on my computer to see if I could make the bug happen, but unfortunately, it didn't show up. [This line](https://github.com/gitkraken/vscode-gitlens/blob/main/src/ai/openaiProvider.ts#L38) matches exactly with the prompt I set, and the result totally makes sense.

I'll dig a bit deeper, maybe uninstall a few extensions or tweak some settings. If I find something useful, I'll update it here in the issue.

If you think this problem might be a bit outside the main scope, it's cool to consider this issue as resolved too.

**Comment by fisforfaheem** [comment]
why gitlens is taking over the copilot commit generators??? I pay for copilot .... but now gitlens is forcing me to use openAI api why???

**Comment by eamodio** [comment]
@fisforfaheem you can turn off this GitLens feature by setting `gitlens.ai.experimental.generateCommitMessage.enabled` to `false`

**Comment by eamodio** [comment]
Going to close this out, feel free to open a new issue or comment back if needed.
