### ISSUE TITLE
gitlens is messing with copilot, and showing its own commit generate icon instead of recent vscode copoit one why?

### ISSUE THREAD

**Issue by fisforfaheem** [gitkraken/vscode-gitlens#3030]
### Description

why gitlens is taking over the copilot commit generators??? I pay for copilot .... but now gitlens is forcing me to use openAI api why???

### GitLens Version

13

**Comment by gsuiteautomations** [comment]
Damn I have the same issue

**Comment by d13** [comment]
Sorry for the confusion all! Having actions in that commit box is new and VS Code working through bugs on their end to correct the experience.

In the meantime, you can disable our Generate Commit Message action by setting `gitlens.ai.experimental.generateCommitMessage.enabled` to `false`.

**Comment by iraklisg** [comment]
> Sorry for the confusion all! Having actions in that commit box is a new feature and VS Code is working through bugs on their end to correct the experience.
> 
> In the meantime, you can disable our Generate Commit Message action by setting `gitlens.ai.experimental.generateCommitMessage.enabled` to `false`.

Enabling the `gitlens.ai.experimental.generateCommitMessage.enabled` totaly hides the sparkle icon next to the commit message field, meaning that although I have Github Copilot enabled, I cannot generate messages. Am I missing something here?
