### ISSUE TITLE
AI Commit message icon covers text

### ISSUE THREAD

**Issue by Roberto-Vizcarra** [gitkraken/vscode-gitlens#3034]
### Description

AI Commit message icon in source control commit message field covers text at the end of the text box
![image](https://github.com/gitkraken/vscode-gitlens/assets/98343055/7e92218a-e742-4bbe-a3e7-2e1d8486c1e4)

![image](https://github.com/gitkraken/vscode-gitlens/assets/98343055/fec18aaa-a5c8-4bd2-b61c-c33594f15ae8)

### GitLens Version

14.5.1

### VS Code Version

Version: 1.84.2 (system setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by d13** [comment]
This is a VS Code bug.
