### ISSUE TITLE
I had a folder with a git repo alread opened in VS Code, but gitlens didn't detect it

### ISSUE THREAD

**Issue by trydalch** [gitkraken/vscode-gitlens#3037]
### Description

1. Windows 11 file system
2. Git installed in wsl
3. VS Code opened from W11 (not using remote and wsl)
4. Added gitlens extension (I'm a pro subscriber)
5. No repository detected

### GitLens Version

14.5.1

### VS Code Version

Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

### Git Version

git version 2.34.1

### Logs, Screenshots, Screen Captures, etc

![image](https://github.com/gitkraken/vscode-gitlens/assets/17228930/dee4917f-6131-4f34-afc8-bd98aa6571e0)

**Comment by trydalch** [comment]
Closed all windows of VS Code and re-opened and it loaded everything properly.

**Comment by wiland99** [comment]
Should this issue be closed?

**Comment by trydalch** [comment]
Yes, thank you. The issue is resolved.
________________________________
