### ISSUE TITLE
Menu disappeared

### ISSUE THREAD

**Issue by philister** [gitkraken/vscode-gitlens#3044]
### Description

Since vscode 1.85 the git-menu (eg to push force, branch rebase, ...) disappeared.
Tried with release and prerelease version of gitlens.

Thanks for 

### GitLens Version

v2023.12.804

### VS Code Version

Version: 1.85.0
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T22:27:05.695Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.5.0-10010-tuxedo
(actually Ubuntu 22.04)

### Git Version

git version 2.34.1

### Logs, Screenshots, Screen Captures, etc

![grafik](https://github.com/gitkraken/vscode-gitlens/assets/118358/566f1d2c-5607-48ec-b76e-49f615204934)

**Comment by eamodio** [comment]
Unsure what happened there, but that is a feature of VS Code itself, not GitLens. You can [open an issue](https://github.com/microsoft/vscode/issues/new?assignees=&labels=&template=bug_report.md) on the VS Code repository.

**Comment by philister** [comment]
Where do I find that menu now? You dont have that problem?

Funny: When I have more than one repository in that workspace, another menu is appearing, where I find what I'm looking for. So for now I have to add a unnecessary dummy repo to get another unnecessary line to access the functions.

![grafik](https://github.com/gitkraken/vscode-gitlens/assets/118358/18ea7e39-e871-4394-90b2-20df1760d583)
