### ISSUE TITLE
Add support for multi-file diff editor

### ISSUE THREAD

**Issue by Igorgro** [gitkraken/vscode-gitlens#3047]
Multi-file diff editor was added in [Novemeber update](https://code.visualstudio.com/updates/v1_85#_multifile-diff-editor) and allows to view multiple diffs in one editor. Currently it allows to view diffs for uncommited and staged changes. It would be awesome if Gitlens added support for this editor for viewing commit changes.

**Comment by eamodio** [comment]
In the pre-release edition of GitLens, set `"gitlens.experimental.openChangesInMultiDiffEditor": true` and the _Open All Changes` and _Open All Changes with Working Tree_ commands will use the multi-diff editor (assuming `"multiDiffEditor.experimental.enabled": true` is also set).

We're working on other changes as well which should land shortly, as well as having separate commands to open the multi-diff vs individual diffs -- the biggest blocker is how to concisely name both options 😄

**Comment by eamodio** [comment]
Now when you set `"gitlens.experimental.openChangesInMultiDiffEditor": true` you will see 2 additional options:

![image](https://github.com/gitkraken/vscode-gitlens/assets/641685/98f1df1b-7200-45bc-90b7-1a2a145e1ac8)


The _Open All Changes_ and _Open All Changes with Working Tree_ commands will use the multi-diff editor, while the others will use the previous behavior -- opening each file in a new diff editor.

**Comment by eamodio** [comment]
The setting is now `gitlens.views.openChangesInMultiDiffEditor` and it is enabled by default.
