### ISSUE TITLE
Add `Open in Integrated Terminal` option for repository in `Repositories` section of `Source Control` tab

### ISSUE THREAD

**Issue by ShadowCreator250** [gitkraken/vscode-gitlens#3053]
1. Environment
  - VSCode version
    ```
    Version: 1.84.2 (system setup)
	Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
	Date: 2023-11-09T10:51:52.184Z
	Electron: 25.9.2
	ElectronBuildId: 24603566
	Chromium: 114.0.5735.289
	Node.js: 18.15.0
	V8: 11.4.183.29-electron.0
	OS: Windows_NT x64 10.0.19045
    ```
  - Gitlense version: `v14.5.2` 
2. Config (the imho relevant ones)
  - `"terminal.explorerKind": "integrated"`
  - `"terminal.external.windowsExec": "C:\\WINDOWS\\System32\\cmd.exe"`
  - `"terminal.integrated.defaultProfile.windows": "Git Bash"`
  - `"terminal.sourceControlRepositoriesKind": "integrated"`
3. Reproduce
  - open project with 1 or more repositories
  - ensure you have Gitlens installed
  - go to the `Source Control` Tab
  - open the `Repositories` section
  - right click on 1 of the displayed repos
  - click on `Open in Terminal`
  - (on Windows) a new CMD window opens
    ![Repositories menu with the "Open in Terminal" option](https://github.com/gitkraken/vscode-gitlens/assets/52125935/3ad2b52b-fb13-448d-91c8-b15c98286374)

In the Source Control Repositories section (which I think is VSCode native), an `Open in Integrated Terminal` option exists.
![Source Control Repositories Menu with the "Open in Integrated Terminal" option](https://github.com/gitkraken/vscode-gitlens/assets/52125935/4e368792-1d9e-4247-b339-7d29b1114d1e)

Gitlens is usually integrated into VSCode quite well, which leads me to believe that changing the option to use the integrated terminal or adding an option for using the integrated terminal was overlooked.

**Comment by eamodio** [comment]
Can you please verify this change in tomorrow's (`v2023.12.13xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by ShadowCreator250** [comment]
I just did, it works as expected. Thanks!
