### ISSUE TITLE
missing icon at gitlens setting

### ISSUE THREAD

**Issue by nickbanana** [gitkraken/vscode-gitlens#3063]
### Description

collapse/expand icon seems off style, or just could find icon file

### GitLens Version

14.6.1

### VS Code Version

version: 1.85.1 (user setup)
commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

### Git Version

git version 2.40.0.windows.1

### Logs, Screenshots, Screen Captures, etc

![image](https://github.com/gitkraken/vscode-gitlens/assets/7685505/0e8007da-80f5-44b3-b1b7-134598c1b517)

**Comment by d13** [comment]
Can you please verify this change in tomorrow's (`v2023.12.20xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by nickbanana** [comment]
> Can you please verify this change in tomorrow's (`v2023.12.20xx`) pre-release edition of GitLens? Thank you so much!
> 
> You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.
> 
> ![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

Right now the pre-release version is `v2023.12.1904` so the fix isn't exist on said pre-release version right?

**Comment by d13** [comment]
> > Can you please verify this change in tomorrow's (`v2023.12.20xx`) pre-release edition of GitLens? Thank you so much!
> > You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.
> > ![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)
> 
> Right now the pre-release version is `v2023.12.1904` so the fix isn't exist on said pre-release version right?

Correct, pre-release `v2023.12.20xx` is not out yet.

**Comment by nickbanana** [comment]
> Can you please verify this change in tomorrow's (`v2023.12.20xx`) pre-release edition of GitLens? Thank you so much!
> 
> You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.
> 
> ![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

![image](https://github.com/gitkraken/vscode-gitlens/assets/7685505/88813699-982b-4d01-b836-4e3636afdd5f)
yes the change is live on pre-release `v2023.12.2004`
