### ISSUE TITLE
Dirtying Large File Indefinitely Suspends Git Line Blame

### ISSUE THREAD

**Issue by gluxon** [gitkraken/vscode-gitlens#3066]
## Description

I love GitLens and get a lot of value out of it. The "_GitLens Current Line Blame_" is particularly valuable and something I use all the time. Multiple times a day, I've noticed VS Code get into a state where the line blame disappears.

Here's a screenshot of the feature I'm referring to:

<img width="1179" alt="Screenshot 2023-12-19 at 9 27 35 PM" src="https://github.com/gitkraken/vscode-gitlens/assets/906558/2331dc43-7e05-4696-8a59-c9eff7396903">

Here's a screenshot of what it looks like when the feature mysteriously disappears. When this happens, it completely disappears and is not present as a status bar item when I right click on the bottom status bar.

<img width="1179" alt="Screenshot 2023-12-19 at 9 28 25 PM" src="https://github.com/gitkraken/vscode-gitlens/assets/906558/a1ae12d3-3fb7-45ce-a968-8d860029c584">

I usually have to restart the VS Code extension server to get out of this state.

## Investigating

I've had this problem for multiple years. It's been very difficult to replicate since it usually happens a few hours into my work day and hadn't appeared in the past when I cloned the GitLens repo and started an [_Extension Development Host_ window](https://code.visualstudio.com/api/get-started/your-first-extension#debugging-the-extension).

Today, I was feeling particularly motivated to debug and figured out how to attach an interactive debugger with source maps to an already running Extension Host process after it got into this bad state. 😎

I noticed that `this.updateState` is never called when I get into the bad state due to `this.suspended` always evaluating to `true` here.

<img width="1303" alt="Screenshot 2023-12-19 at 4 54 34 PM" src="https://github.com/gitkraken/vscode-gitlens/assets/906558/45f4f841-2c7d-411e-8f0d-dcea2ae77336">

## Theory

I'm not exactly sure how `this.suspended` became `true` indefinitely in my editor today, but reading GitLens's source code, I see one reproducible way this could happen:

1. A user edits a file causing the editor state to become  "dirty" and `this.suspend()` to be called.

https://github.com/gitkraken/vscode-gitlens/blob/a70e2b930a9e10697b919b158dbf3e244a8bdd5c/src/trackers/gitLineTracker.ts#L107-L113

2. After the user stops editing the file for 5 seconds (the `advanced.blame.delayAfterEdit` time), the `onDirtyIdleTriggered` callback is fired and `this.resume()` is _supposed_ to unsuspend `GitLineTracker`.

https://github.com/gitkraken/vscode-gitlens/blob/a70e2b930a9e10697b919b158dbf3e244a8bdd5c/src/trackers/gitLineTracker.ts#L95-L100

As the code above shows, this intentionally doesn't resume the `GitLineTracker` if the dirty file is `>5000` lines long (or `advanced.blame.sizeThresholdAfterEdit`). That part feels correct.

However, what's surprising (and this code doesn't seem to handle), is the case when users switch tabs or open a different file after the idle timeout. The `GitLineTracker` shared instance is still suspended for the previous large file and never resumes for other smaller files in other tabs.

## Steps to Reproduce

I was excited to see the theory above is indeed reproducible. Using the current latest version at the time of writing (`v14.6.1`) and the GitLens code base itself:

1. Open `src/trackers/gitLineTracker.ts` and observe the current line blame updating properly as the cursor moves.
2. Open `yarn.lock` (currently at `7582` lines) and make an edit.
3. Wait 5 seconds.
4. Close the file and do not save changes.
5. Observe the current line blame no longer appear in `gitLineTracker.ts` or any other file.

https://github.com/gitkraken/vscode-gitlens/assets/906558/29e44897-ce46-47d9-a6f3-235404f03a37

## Pull Request

Here's one possible fix. https://github.com/gitkraken/vscode-gitlens/pull/3067

----

### GitLens Version

v14.6.1

### VS Code Version

Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:16.874Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.2.0

### Git Version

git version 2.43.0

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's (`v2024.01.15xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by gluxon** [comment]
Can do! Thanks for reviewing the fix and the numerous improvements on top. The new UI will make this much clearer.

**Comment by gluxon** [comment]
> Can you please verify this fix in tomorrow's (v2024.01.15xx) pre-release edition of GitLens? Thank you so much!

Verified! Using version `v2024.1.1504`, the blame immediately updates after closing a dirty large file. I used `pnpm-lock.yaml` for this test, which is around ~18K lines.



https://github.com/gitkraken/vscode-gitlens/assets/906558/8a5ccf5f-205e-4950-983b-067884c735e6
