### ISSUE TITLE
File History shows branch names that obscure the commit title

### ISSUE THREAD

**Issue by roblourens** [gitkraken/vscode-gitlens#3072]
### Description

- Open the File History view on a repo
- See that there is a branch name on each entry. In our case, these are really long, so I can't read the actual commit title

<img width="926" alt="image" src="https://github.com/gitkraken/vscode-gitlens/assets/323878/d5f334de-3d70-4c8d-a2f1-eda1c512ccb9">

We have a lot of these, I think they come from using the new Merge Queues feature. I'm not sure what this is trying to show, but maybe showing these could be configurable, if it isn't already?

### GitLens Version

v2023.12.2004

### VS Code Version

Version: 1.86.0-insider
Commit: 9621add46007f7a1ab37d1fce9bcdcecca62aeb0
Date: 2023-12-20T05:38:07.020Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.86.0-insider Chrome/118.0.5993.159 Electron/27.1.3 Safari/537.36

### Git Version

git version 2.41.0

**Comment by roblourens** [comment]
I also found that I can run `git fetch -p` to clean these up for these temporary branches that have been deleted. But they will keep coming back over time.

**Comment by eamodio** [comment]
@roblourens 

You can control this today via the `gitlens.views.formats.commits.label` setting.

For example, the following will truncate the tips to be no longer than 11 characters:

```json
    "gitlens.views.formats.commits.label": "${❰ tips|11? ❱➤  }${message}",
```

You can also remove the `${❰ tips|11? ❱➤  }` section completely to not show the tips at all.

Also, in tomorrow's pre-release I've set the default format to truncate the tips to 11 characters, and added the ability to set the truncation to 0 meaning it could be used as an indicator, e.g. setting it to the following will just show `❰❱➤  ` (or any characters you want as an indicator)

```json
    "gitlens.views.formats.commits.label": "${❰ tips|0 ❱➤  }${message}",
```

**Comment by roblourens** [comment]
Cool, thanks!
