### ISSUE TITLE
Root repo folder was deleted after clicking "Delete to Trash" on a commit. now I can't find it in the Trash

### ISSUE THREAD

**Issue by NoamNol** [gitkraken/vscode-gitlens#3080]
### Description

I had my git repo opened in vscode.
There was a commit in remote that wasn’t pulled yet.
I right-clicked on the commit and then clicked "Delete to Trash".
Now everything inside the repo folder is gone, including the .git folder and ignored files. I have nothing left ):

I also don't see it in the Trash folder (I'm using mac)

* Please don't allow such a destructive option. (and never delete the .git folder)
* Why is it not in the Trash - where should it be? Please explain these things and maybe add an option to recover from vscode.

![Screenshot 2023-12-26 at 15 49 19](https://github.com/microsoft/vscode/assets/45405044/3dada615-f5a7-489e-b248-7e4dedf216bb)

### GitLens Version

14.6.1

### VS Code Version

Version: 1.85.1 (Universal)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:06.308Z (1 wk ago)
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.2.0

### Git Version

2.39.1

**Comment by NoamNol** [comment]
Originally opened in https://github.com/microsoft/vscode/issues/201504

**Comment by eamodio** [comment]
Commented here: https://github.com/microsoft/vscode/issues/201504#issuecomment-1869820725
