### ISSUE TITLE
Terminal executed commands fail if the GitLens terminal is closed

### ISSUE THREAD

**Issue by eamodio** [gitkraken/vscode-gitlens#3087]
GitLens is not reopening the terminal if the user closes it.

**Comment by eamodio** [comment]
It looks like there was a change in the VS Code terminal APIs where the terminal's name can change as it is closing (probably a bug), so we should not rely on name matching.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's (`v2024.01.05xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by jkelroy** [comment]
Confirmed this works as expected for me in the latest pre-release.
