### ISSUE TITLE
Cannot track changes made on resx files in vscode's source control

### ISSUE THREAD

**Issue by magmukendi** [gitkraken/vscode-gitlens#3093]
### Description

I am trying to track the changes I have made on Visual Studio code's source control, but the changes made don't appear on the `resx` file as they usually appear on another file such as source code, readme file, or xml etc.

In the following screenshot as an illustration, I have changed the value in the first column from `Add migration`  to `Remove migration` but this is not reflected in the resx when open from the source control for tracking changes.

![work tree for resx file](https://github.com/pmahend1/resxpress/assets/64711820/12cc74d2-553d-434f-aae1-7b7383c895ca)

Usually when the changes made are displayed, the deleted characters are highlighted in red and the added characters are highlighted in green. I have provided a screenshot below for illustration.

![work tree for other files](https://github.com/pmahend1/resxpress/assets/64711820/5d574b6c-28c8-49a7-a905-469077bc4cd6)

I am not sure if this issue should be reported to vscode, gitlens or the resx extension. It would be great if you could point me to the right direction to get this issue fixed for other developers that would go through the same issue.

Happy New Year, Cheers 🥂!

### GitLens Version

14.6.1

### VS Code Version

Version: 1.83.1 (Universal)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:46:55.789Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 23.1.0

### Git Version

git version 2.39.2 (Apple Git-143)

### Logs, Screenshots, Screen Captures, etc

![work tree for resx file](https://github.com/pmahend1/resxpress/assets/64711820/12cc74d2-553d-434f-aae1-7b7383c895ca)

![work tree for other files](https://github.com/pmahend1/resxpress/assets/64711820/5d574b6c-28c8-49a7-a905-469077bc4cd6)

**Comment by jkelroy** [comment]
Hello @magmukendi, it looks like the extension resXpress is what provides the preview view for these files. With this disabled you should be able to see the diff as expected and GitLens is working as expected on .resx files as far as I can see.

I would recommend reaching out to the resXpress team for configuring this extension as desired.
