### ISSUE TITLE
Always-on file annotations

### ISSUE THREAD

**Issue by Nicholas-Autio-Mitchell** [gitkraken/vscode-gitlens#3115]
This is a follow-up to a previously posted (solved) issue: https://github.com/gitkraken/vscode-gitlens/issues/1988

**Summary**: the git blame heat-map (rendered in the left git diff gutter) is not shown all the time -- it would be great to have a setting to ensure it is "aways on".

Currently, when opening a new VScode window or just a new repo, the blame heat-map must be toggled on while focus is on an open file (this works fine). Opening another file tracked by git, we see the blame heat-map appear after a few seonds (also works as expected). However if I close all git-tracked files e.g. whilst working on other files that are not yet git-tracked, and **then** open any git-tracked file, the blame heat-maps do not show up. They must be toggled on once again.

The setting I use for toggling is `gitlens.toggleFileHeatmap`, with a keybinding.

@eamodio for viz

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's (`v2024.01.26xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by Nicholas-Autio-Mitchell** [comment]
Tested this in pre-release with version `v2024.1.2604`

Opening files, toggling gutter-blame to be active, then closing all files and re-opening: gutter-blame is still active. I would say this solves the issues as originally described 👍 

One thing I have noticed now: when in `editorFocus` (cursor is active in an editor pane), with the gutter-blame active -- if I press `Esc`, the gutter-blame is deactivated. I am not sure by which mechanism this happens, but it requires re-toggling gutter-blame to be on and so breaks the "always on" gutter-blame I was hoping for.

@eamodio - I will let you decide if this is worth investigating/fixing; totally realise I am being super nit-picky here!

**Comment by eamodio** [comment]
@Nicholas-Autio-Mitchell there is a relatively new setting `gitlens.fileAnnotations.dismissOnEscape` which can be disabled to turn off the `ESC` behavior.

I am wondering if that behavior should be the "default" if you set the annotation to be for the window (rather than per-file), but I'm not sure on that. I'd love to hear from you and others on that.
