### ISSUE TITLE
Typos in package.json and README.md

### ISSUE THREAD

**Issue by yutotnh** [gitkraken/vscode-gitlens#3116]
### Description

I found typos in package.json and README.md.
https://github.com/gitkraken/vscode-gitlens/blob/d2f8ed219fef956ac2cbf3c9d3f709440728561d/package.json#L3302

https://github.com/gitkraken/vscode-gitlens/blob/d2f8ed219fef956ac2cbf3c9d3f709440728561d/README.md?plain=1#L430

I will submit a pull request for this issue later.

### GitLens Version

14.7.0

### VS Code Version

Version: 1.85.2 (user setup)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

### Git Version

git version 2.42.1

## package.json
![image](https://github.com/gitkraken/vscode-gitlens/assets/57719497/b0f1d3d5-ce2b-4b6a-b1f7-9b5b453066f8)

## README.md
![image](https://github.com/gitkraken/vscode-gitlens/assets/57719497/ecb58703-2de6-4c73-981d-977f207b01a4)

**Comment by wiland99** [comment]
Should this issue be closed?

**Comment by yutotnh** [comment]
This issue was resolved in #3117.
Therefore, it is closed.
