### ISSUE TITLE
Add option for disable 'xx hidden lines' in 'Preview reversion' view

### ISSUE THREAD

**Issue by swq123459** [gitkraken/vscode-gitlens#3123]
![image](https://github.com/gitkraken/vscode-gitlens/assets/35790719/12766d56-0006-4186-bec9-0964f21115b5)
![image](https://github.com/gitkraken/vscode-gitlens/assets/35790719/cdf4e1dd-f9d4-4a53-b187-9d11ef7daec3)

**Comment by eamodio** [comment]
That is not a GitLens feature -- that is provided by VS Code.
