### ISSUE TITLE
SHA column in commit graph only shows 7 digits of SHA (convention is 8 digits)

### ISSUE THREAD

**Issue by thorade** [gitkraken/vscode-gitlens#3129]
### Description

Almost all git tools shorten the SHA to 8 digits. 
git lens is the only tool that I have seen that uses 7 digits, see screenshot.
Could you please consider shortening to 8 digits, like everybody else?

![image](https://github.com/gitkraken/vscode-gitlens/assets/314571/89a9f2eb-454b-497b-817d-a73fe86202b6)

### GitLens Version

14.7.0

### VS Code Version

Version: 1.85.2 (user setup)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

### Git Version

git version 2.43.0.windows.1

### Logs, Screenshots, Screen Captures, etc

![image](https://github.com/gitkraken/vscode-gitlens/assets/314571/bf0bb2d2-17f6-4137-9347-c836b92798ac)

**Comment by d13** [comment]
@thorade - GitLens currently supports controlling the length of the shortened SHA. Please add the following to your settings:

```json
{
  "gitlens.advanced.abbreviatedShaLength": 8
}
```
