### ISSUE TITLE
A collaborator-only commit view in the current branch

### ISSUE THREAD

**Issue by H-G-Hristov** [gitkraken/vscode-gitlens#3131]
Type: <b>Feature Request</b>

When using rebase it is easy to have your own commits stacked on top and it is easy to view them.
But if using merge then that becomes difficult. Is it possible to have a view that displays only the commits of a set of a colloaborators in the current branch and not all commits.
Something similar to what's available with Compare branches but then it means that it is necessary these branches to be properly synced, which isn't convenient.

In that review I'd like to be able to review the changes and to be able to easily open the file for editing, etc.

Extension version: 14.7.0
VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:27:46.147Z)
OS version: Linux x64 6.5.0-15-generic snap
Modes:

**Comment by eamodio** [comment]
I'm not sure I fully understand the question, but does the following option help?

![image](https://github.com/gitkraken/vscode-gitlens/assets/641685/04728983-b749-4adf-b223-32366a9380ea)
