### ISSUE TITLE
unable to log in to gitkraken

### ISSUE THREAD

**Issue by steven-varga** [gitkraken/vscode-gitlens#3132]
### Description

1. I am experiencing frustration by not able to use a commercial product I paid for
2. all links in user interface to log in to paid account are out of service preventing me using features I paid for

### GitLens Version

v2024.2.304

### VS Code Version

Version: 1.82.1 5c3853e4d80e47e2c9b77dd595cd353b4b1fe4bc

### Git Version

git version 2.34.1 ubuntu 22.04

### Logs, Screenshots, Screen Captures, etc

Previously I was able to click on `sign in` shown below then log in to the pay for play services, not anymore. Adding insult to injury I am forced to use the non-functioning **upgrade** which doesn't function, and here we are... . I liked the product, please don't change my mind and make me stopping paying for it. 
```
Sign up for access to our developer productivity and collaboration services, e.g. Workspaces, or [sign in](command:gitlens.plus.login).
```
ps: the non functioning link could be related the message below; please congratulate your security team, and on the same note ask them to contemplate if paying customers can't use the product, what motivates them to keep paying? Cheers! 

![git-kraken-login](https://github.com/gitkraken/vscode-gitlens/assets/10566766/f0062731-30f7-4902-90ea-0bf280657b16)

**Comment by jkelroy** [comment]
Hello @steven-varga, I worked with you over email but would like to provide context here and close out this issue as well. 

To reiterate, we confirmed you were able to revert back to version 14.6.1 to log in without issue. Additionally, we have adjusted our Cloudflare settings so you should no longer be seeing this in the current version (14.7). Can you please confirm this is working as expected now?
