### ISSUE TITLE
Allow Create branch option when switching to branch

### ISSUE THREAD

**Issue by DKhalil** [gitkraken/vscode-gitlens#3138]
### Description

Before the last update (?) when opening the menu to switch branches and typing in a new branches name, it would automatically offer the option to create a new branch with said name - that was super convenient, but sadly is no longer there.

### GitLens Version

v14.7.0

### VS Code Version

Version: 1.86.0 (user setup)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:28:19.990Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

### Logs, Screenshots, Screen Captures, etc

![image](https://github.com/gitkraken/vscode-gitlens/assets/497250/f826afc2-fe6d-4e30-9c36-7948ad0ebe92)

**Comment by eamodio** [comment]
@DKhalil AFAICT that feature never existed in GitLens (maybe the built-in Git extension supported that at one time?). In any case its a good feature request.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's (`v2024.02.09xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by DKhalil** [comment]
@eamodio will do! Thanks for the 'fix'? I really thought this was a gitlens feature. Anyway, thanks!

**Comment by axosoft-ramint** [comment]
Verified

**Comment by DKhalil** [comment]
I'm not seeing it in the pre-release
