### ISSUE TITLE
Search & Compare fails to remember items after restart

### ISSUE THREAD

**Issue by amordovskiy** [gitkraken/vscode-gitlens#3146]
### Description

I used "Pin" during "Comparing" to keep it when VSCode restarts.
There is no "Pin" now and no setting in json is available.
The problem is noticed by me earlier than 14.8.0.

### GitLens Version

14.8.0

### VS Code Version

Version: 1.86.1 (Universal)
Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
Date: 2024-02-07T09:09:01.236Z (5 days ago)
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 22.6.0

### Git Version

git version 2.39.3

### Logs, Screenshots, Screen Captures, etc

<img width="427" alt="image" src="https://github.com/gitkraken/vscode-gitlens/assets/156684627/15498b3f-eee6-4f6d-9659-4f3bc2dad10f">

**Comment by amordovskiy** [comment]
@eamodio ok! But the items do vanish after VSCode restart.
I'll try to create a new issue.
ps. The problem is noticed working with ssh-remote plugin

**Comment by eamodio** [comment]
@amordovskiy Hrm -- yes please open another issue. I can't reproduce the problem, although since that data is stored "per-workspace" if you are opening a new workspace each time, then it would make sense.

**Comment by eamodio** [comment]
@amordovskiy there was a fix for a timing issue that caused the remembrance to break, this should now be resolved. Sorry!
 
Can you please verify this fix in tomorrow's (`v2024.03.04xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by axosoft-ramint** [comment]
Verified in 14.9

**Comment by amordovskiy** [comment]
Yeah, I've just upgrade to 14.9 and the problem has vanished. TY!
