### ISSUE TITLE
Authentication doesn't work with GitHub Codespaces

### ISSUE THREAD

**Issue by Malix-off** [gitkraken/vscode-gitlens#3152]
### Description

When authenticating to Git Kraken, the vscode extension doesn't fetch the code while the auto-redirect correctly but happens, but it redirects so fast that the code can't be copied, super annoying.

1. Open a GitHub Codespace
2. Try to Sign-in

### GitLens Version

v14.8.1

### VS Code Version

Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:35:55.911Z (4 wks ago)
Browser: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

### Logs, Screenshots, Screen Captures, etc

1. ![image](https://github.com/gitkraken/vscode-gitlens/assets/76160668/ded3aa70-dcea-419a-960c-6500088382fe)
2. ![image](https://github.com/gitkraken/vscode-gitlens/assets/76160668/ef237052-0fa0-4da7-9631-a0be4dbcfbb6)
3. ![image](https://github.com/gitkraken/vscode-gitlens/assets/76160668/b99315d3-e2d2-49b7-94f1-a97cb3c4f71d)

**Comment by Malix-off** [comment]
Thanks @jkelroy, 
I guess it has been reported before?
Which versions does it affect?
Can you link the bug tracking issue?

**Comment by jkelroy** [comment]
@Malix-off this is the only open issue for this. It affects version 14.7-14.8.2. 

One other workaround is that in the current version, the code (`code=`) can be copied from the URL to provide to GitLens.

**Comment by jkelroy** [comment]
@Malix-off this has now been addressed in the pre-release. Can you check if this is now working as expected for you?

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/27739784/240437025-f9f6b0cf-cda3-4b53-973b-3689f1e4481a.png)

**Comment by Malix-off** [comment]
It works, gg!
