### ISSUE TITLE
"Allow relative date formatting" / gitlens.defaultDateStyle not working

### ISSUE THREAD

**Issue by drujd** [gitkraken/vscode-gitlens#3153]
### Description

The "Allow relative date formatting" checkbox / gitlens.defaultDateStyle setting does not seem to do anything at all. I have tried both current release and prerelease versions of GitLens and regardless of version, dates are always displayed in the relative format in both commit graph and commit detail with no option to change that.

### GitLens Version

14.8.2 and 2024.2.1704

### VS Code Version

Version: 1.86.2
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:41:37.860Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.7.4-arch1-1-00004-g979c5aee1211-dirty

### Git Version

git version 2.43.2

**Comment by eamodio** [comment]
The Commit Graph has its own date style setting `gitlens.graph.dateStyle` to allow you to control the behavior there. In tomorrow's pre-release I've changed the default of that setting to fallback to `gitlens.defaultDateStyle` if not specifically specified.

As for the Commit Details view -- we are not currently honoring that setting and should be.

**Comment by drujd** [comment]
And where IS it used, then?

**Comment by axosoft-ramint** [comment]
Verified in the 14.9 release.
