### ISSUE TITLE
Add back option to add worktree to workspace on creation

### ISSUE THREAD

**Issue by jkelroy** [gitkraken/vscode-gitlens#3160]
In 14.8+, the option to `Add Worktree to Workspace` was removed from the worktree creation flow. This should be added back. 
<img width="607" alt="Screenshot 2024-02-20 at 11 22 34 AM" src="https://github.com/gitkraken/vscode-gitlens/assets/27739784/cb687042-227b-49f2-99fd-cef511d83c32">

**Comment by DOCTYPEmike** [comment]
Whom do I have the pleasure of working with I only do honest straight forward business as the world and safety of the people and the United States rely on all of us to be united and work as a team

**Comment by axosoft-ramint** [comment]
Verified in 14.9.0.
