### ISSUE TITLE
GitLens not working as expected

### ISSUE THREAD

**Issue by RICKYBOYDEGRACIA** [gitkraken/vscode-gitlens#3165]
### Description

![image](https://github.com/gitkraken/vscode-gitlens/assets/100891098/45ba7148-bd9c-45be-b348-374bcfa9954d)

- I can't see past commits

### GitLens Version

v14.8.2

**Comment by RICKYBOYDEGRACIA** [comment]
I can't see any prev. commits

**Comment by d13** [comment]
Can you provide more detail as to how and where you are trying to see those previous commits? If you can, please include a screenshot.

**Comment by RICKYBOYDEGRACIA** [comment]
issue now solved, I just remove all extensions and try to have one ( GitlLens ) it's weird actually. I do that last Friday (then restart) and it's not working but now (Monday) it's suddenly working fine.
