### ISSUE TITLE
Update To The New Logo

### ISSUE THREAD

**Issue by Barzi-Ahmed** [gitkraken/vscode-gitlens#3191]
Hi, 
GitLens logo in extension marketplace is old version. I suggest to update it to the new logo icon in marketplace and other places.
![3](https://github.com/gitkraken/vscode-gitlens/assets/135956133/7ab19d19-32b7-41fd-b93b-295cb05216a8)
![2png](https://github.com/gitkraken/vscode-gitlens/assets/135956133/269338f3-2730-428a-a2b7-7652d3699017)

New Version:
![Screenshot 2024-03-19 165939](https://github.com/gitkraken/vscode-gitlens/assets/135956133/afbe244f-f801-415c-8e98-37ea1c9182ae)

**Comment by d13** [comment]
Hi @Barzi-Ahmed 👋  

We have multiple variants of our logo and we are using our "high-fidelity" variant on the marketplace. Thanks for looking out!
