### ISSUE TITLE
Allow Empty Commit

### ISSUE THREAD

**Issue by hardik-thirstydevs** [gitkraken/vscode-gitlens#3195]
This feature will allow us to commit without any file changes. Git already provides this terminal command as follows:
`git commit --allow-empty -m "Commit Message goes here"`

Right now button stays disabled but after feature implement it could say "Empty Commit"
![image](https://github.com/gitkraken/vscode-gitlens/assets/116257835/7cca47d3-9b3b-46ca-9be3-65ffad03e509)

**Comment by eamodio** [comment]
That is a feature of VS Code itself (the built-in Git extension). Can you please [open an issue](https://github.com/microsoft/vscode/issues/new?assignees=&labels=&template=bug_report.md) on the VS Code repository? Thanks!
