### ISSUE TITLE
Identifying bugs in local modifications

### ISSUE THREAD

**Issue by chall1123** [gitkraken/vscode-gitlens#3207]
### Description

Unable to obtain local modifications
![image](https://github.com/gitkraken/vscode-gitlens/assets/37236882/0bf35225-4797-4575-a841-6827f88050c8)

### GitLens Version

11.7.2(2023.9.1405)

### VS Code Version

vscode 1.81.1

### Git Version

2.27.0

### Logs, Screenshots, Screen Captures, etc

![image](https://github.com/gitkraken/vscode-gitlens/assets/37236882/ed2d6003-181b-46d4-a483-f872caf374e5)
I occasionally add thousands of files, but after checkout, I only make a few modifications. The extension still cannot work normal, and I have to restart vscode to restore it to normal. I'm not sure if the new version solves this problem. I tried updating the plugin, but the latest extension cannot be installed on my 1.81.1

**Comment by d13** [comment]
The Source Control view is a feature of VS Code itself (the built-in Git extension). Can you please [open an issue](https://github.com/microsoft/vscode/issues/new?assignees=&labels=&template=bug_report.md) on the VS Code repository? Thanks!
