### ISSUE TITLE
The users' avatars in Gitlens use default style, not Github account

### ISSUE THREAD

**Issue by Tommy-Yao** [gitkraken/vscode-gitlens#3220]
### Description

As follow image, The commit made by Github's merge shows correct avatar, but other commits show "robo" avatar.

![image](https://github.com/gitkraken/vscode-gitlens/assets/82805260/93a966f6-b603-4050-b5ee-0f1c9ac3648d)

The avatar worked well in my previous VM, but it doesn't works on my new VM. Because previous VM has other issues, I setup a new one.
Is there any extra settings for this?

### GitLens Version

14.9.0

### VS Code Version

版本: 1.88.0
提交: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
日期: 2024-04-03T13:25:57.039Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.5.0-26-generic
Ubuntu 22.04

### Git Version

git version 2.34.1

**Comment by jkelroy** [comment]
Hello @Tommy-Yao, if a users Gravatar cannot be obtained, Gitlens will show the `gitlens.defaultGravatarsStyle` https://help.gitkraken.com/gitlens/gitlens-settings/#misc-settings.

**Comment by jkelroy** [comment]
Additionally, make sure you have connected the [GitHub](https://help.gitkraken.com/gitlens/gitlens-features/#connecting-the-github-integration) integration.

**Comment by Tommy-Yao** [comment]
@jkelroy Thank you. It works for me.
"Connecting the GitHub Integration" is the missing step. I have to make it authorized by my organization.
