### ISSUE TITLE
Cannot use word "detached" in branch names

### ISSUE THREAD

**Issue by jmayoralas** [gitkraken/vscode-gitlens#3221]
### Description

As you can see in the image, when a branch name contains the word "detached" it shows in a detached state.

![imagen](https://github.com/gitkraken/vscode-gitlens/assets/20075656/05b4f862-8b75-4677-a41d-9cc44fe0200d)

### GitLens Version

14.9.0

### VS Code Version

Version: 1.88.0 (user setup)
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:26:18.741Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19045

### Git Version

git version 2.20.1

**Comment by jkelroy** [comment]
Hello @jmayoralas, this appears to be only a visual bug where the branch name (in the branch sidebar or commit graph) shows the commit SHA incorrectly.  If you run _git status_ from the terminal, you should see that you are not actually in a detached head state. If you are seeing different behavior, please let me know.

**Comment by jmayoralas** [comment]
Indeed, git from the command line works as expected, but if I try, for example, push that branch to origin, I get an error.

![imagen](https://github.com/gitkraken/vscode-gitlens/assets/20075656/b5bd9c1b-84bb-44bc-94be-3b9b4be8ffa0)
![imagen](https://github.com/gitkraken/vscode-gitlens/assets/20075656/9aa6ac0b-937c-4920-837d-f39b2904ef1d)
