### ISSUE TITLE
Git repo is  already opened, but it still says to open folder or directory.

### ISSUE THREAD

**Issue by devenS7** [gitkraken/vscode-gitlens#3235]
### Description

I just installed gitLens. Git repo is  already opened, but it still says to open folder or directory.

### GitLens Version

14.9.0

**Comment by devenS7** [comment]
![image](https://github.com/gitkraken/vscode-gitlens/assets/37117300/7960896c-735e-4c05-bf8e-483447b7358a)

**Comment by jkelroy** [comment]
Hello @devenS7, if you select Source Control sidebar (ctrl + shift + G) is VS Code able to detect the repository? 

If so, is there anything unique about where the repository is stored locally i.e. are you working with a network drive, dropbox, etc, or is there anything unique about the repository i.e. how it was cloned, does it work with submodules, etc? 

Can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the both _GitLens_ and _GitLens (Git)_ channels.

**Comment by devenS7** [comment]
Hi, 
If you notice, the shared screenshot on top it shows 'CSS-PRACTICE [GitHub]'. The repo is in documents folder. For more it is opened in Source Explorer as well.
![image](https://github.com/gitkraken/vscode-gitlens/assets/37117300/43560d8d-ced7-4ceb-9d12-8363a7559597)

Do I need to provide some access to GitLens to my GitHub account, if so how?

**Comment by devenS7** [comment]
Resolved! Needed to open repository from local.
