### ISSUE TITLE
Feature Request: Enable Gitkraken to work over a ssh with a remote machine similar to Microsoft's Remote SSH VS Code plugin

### ISSUE THREAD

**Issue by prmichaelsen** [gitkraken/vscode-gitlens#3252]
GitLens works perfectly with Remote SSH. I wonder if Gitkraken can add support for editing files on a remote as well? Thanks

**Comment by jkelroy** [comment]
Hello @prmichaelsen, feature requests for GitKraken Client are on feedback.gitkraken.com. We have an existing request for supporting Remote SSH connections that you may note your interest in [here](https://feedback.gitkraken.com/suggestions/223779/repository-management-on-remote-machine-using-ssh-connection).

**Comment by prmichaelsen** [comment]
Looks like I left a comment on that request 1 year ago, small world. It
seems to have a lot of support, is 160 votes a lot relative to other
requests? It would be neat

Software Development Engineer - Amazon
