### ISSUE TITLE
Unable to pull branch when the local branch whose name differs from its tracking branch

### ISSUE THREAD

**Issue by gtianw** [gitkraken/vscode-gitlens#3277]
### Description

1.For example, local branch name is `sampleA` and upstream is `origin/sampleB`.
2.Click the pull button in the commits view.
3.Notification will output: Unable to pull branch `sampleA` from origin.

### GitLens Version

14.9.1

### VS Code Version

版本: 1.89.0 (system setup)
提交: b58957e67ee1e712cebf466b995adf4c5307b2bd
日期: 2024-05-01T02:09:22.859Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19045

### Git Version

git version 2.44.0.windows.1

**Comment by gtianw** [comment]
Additional information: `sampleA` is a worktree.

**Comment by Natka198902** [comment]
> ### Opis
> 1. Na przykład nazwa oddziału lokalnego to, `sampleA`a nazwa oddziału nadrzędnego to `origin/sampleB`. 2. Kliknij przycisk ściągania w widoku zatwierdzeń. 3. Zostanie wyświetlone powiadomienie: Nie można pobrać gałęzi `sampleA`ze źródła.
> 
> ### Wersja GitLensa
> 14.9.1
> 
> ### Wersja kodu VS
> Wersja: 1.89.0 (konfiguracja systemu) : b58957e67ee1e712cebf466b995adf4c5307b2bd Wersja: 2024-05-01T02:09:22.859Z Electron: 28.2.8 ElectronBuildId: 27744544 Chrom ium: 120.0.6099.291 Node.js: 18.18.2 V8: 12.0.267.19- elektron.0 System operacyjny: Windows_NT x64 10.0.19045
> 
> ### Wersja Gita
> git wersja 2.44.0.windows.1
> 
> ### Dzienniki, zrzuty ekranu, zrzuty ekranu itp
> _Brak odpowiedzi_

[](url)

**Comment by Natka198902** [comment]
> ### Opis
> 1. Na przykład nazwa oddziału lokalnego to, `sampleA`a nazwa oddziału nadrzędnego to `origin/sampleB`. 2. Kliknij przycisk ściągania w widoku zatwierdzeń. 3. Zostanie wyświetlone powiadomienie: Nie można pobrać gałęzi `sampleA`ze źródła.
> 
> ### Wersja GitLensa
> 14.9.1
> 
> ### Wersja kodu VS
> Wersja: 1.89.0 (konfiguracja systemu) : b58957e67ee1e712cebf466b995adf4c5307b2bd Wersja: 2024-05-01T02:09:22.859Z Electron: 28.2.8 ElectronBuildId: 27744544 Chrom ium: 120.0.6099.291 Node.js: 18.18.2 V8: 12.0.267.19- elektron.0 System operacyjny: Windows_NT x64 10.0.19045
> 
> ### Wersja Gita
> git wersja 2.44.0.windows.1
> 
> ### Dzienniki, zrzuty ekranu, zrzuty ekranu itp
> _Brak odpowiedzi_
@barneycarroll 


> Informacje dodatkowe: `sampleA`jest drzewem roboczym.

``

**Comment by axosoft-ramint** [comment]
@gtianw Can you please verify this fix in tomorrow's pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)

**Comment by gtianw** [comment]
The problem still exists in v2024.5.1605(pre-release).

**Comment by axosoft-ramint** [comment]
@gtianw Sorry, I should be more specific - the pre-release will update approx. 9-10 hours from now. Can you try again after that? Version should be something like 2024.5.17xx

**Comment by gtianw** [comment]
v2024.5.1905(pre-release) works fine.
