### ISSUE TITLE
Switching branches via the Source Control -> Branches Panel

### ISSUE THREAD

**Issue by nistre** [gitkraken/vscode-gitlens#3287]
### Description

In the latest update attempting to switch branches, like before, using the Source Control -> Branches Panel, I now get prompted to Sign into a pro account or start a trial.  The first time I open VSCode I can switch once but then after that I get prompted for the Pro account.

### GitLens Version

15.0.1

### Logs, Screenshots, Screen Captures, etc

![image](https://github.com/gitkraken/vscode-gitlens/assets/10407645/9bf87548-97d0-4c86-8813-23c58fd67bea)
![image](https://github.com/gitkraken/vscode-gitlens/assets/10407645/3aad8da7-8a3e-4522-8c64-a49359a1889e)

**Comment by jkelroy** [comment]
Hello @nistre, this has been addressed in 15.0.2. You can update from Extensions > select _Update_ or the settings icon > _Install Another Version..._. 
![Screenshot 2024-05-14 at 1 00 41 PM](https://github.com/gitkraken/vscode-gitlens/assets/27739784/03695ef3-6238-4635-98a1-e05649501a30)

**Comment by nistre** [comment]
Yup, that worked, thank you for the quick response!
