### ISSUE TITLE
Add support for short date on Git blame 

### ISSUE THREAD

**Issue by jmg-duarte** [gitkraken/vscode-gitlens#3292]
There's already [support for the long date](https://github.com/gitkraken/vscode-gitlens/wiki/Custom-Formatting#commit-tokens), which can be changed using `gitlens.defaultDateFormat`, however, I don't want to change the long date format for everything.

I'm open to develop this if you provide just a bit of guidance to shortcut onboarding on to the project.

**Comment by d13** [comment]
have you tried changing `gitlens.blame.dateFormat`?

**Comment by jmg-duarte** [comment]
@d13 apologies for the delay. That seems to have worked but I also lost context on this issue. Closing now.
