### ISSUE TITLE
Incorrect pluralization in Authors lens

### ISSUE THREAD

**Issue by bm-w** [gitkraken/vscode-gitlens#3295]
### Description

A little header appears above code blocks that shows the latest change and the authors that have contributed, such as:
> Jane Doe, 2 months ago | 4 authors (Jane Doe and others)

When there are only two authors, it still says e.g. “2 authors (Jane Doe and others)” — that should say not say “others”, but e.g. “other” / “another” / “one other”, since when there are two authors and one is named then there is only one other:
> Jane Doe, 2 months ago | 2 authors (Jane Doe and one other)

### GitLens Version

15.0.3

### VS Code Version

Version: 1.88.1
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:43:08.196Z (1 mo ago)
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

### Git Version

git version 2.39.3 (Apple Git-146)

### Logs, Screenshots, Screen Captures, etc

<img width="440" alt="image" src="https://github.com/gitkraken/vscode-gitlens/assets/1379069/4d7b3236-86b6-4729-b28f-332804011327">

**Comment by d13** [comment]
Resolved with https://github.com/gitkraken/vscode-gitlens/pull/3296
