### ISSUE TITLE
Compare active file with main

### ISSUE THREAD

**Issue by wiegell** [gitkraken/vscode-gitlens#3312]
I think this functionality has somewhat been requested before in:
https://github.com/gitkraken/vscode-gitlens/issues/3012

I would like a feature to be able to quickly open the current active file in a compare-view with the current state of my main branch. I know this is possible through the "Search and compare" functionality, but that requires multiple clicks and on a large branch, that can contain many files, it can further take some time to locate the current file in the sidebar.

Thanks in advance

**Comment by d13** [comment]
@wiegell - there's an "Open Changes" action in the editor toolbar. Is that what you're looking for?


https://github.com/gitkraken/vscode-gitlens/assets/293282/5748e959-09d6-476f-b181-f1f42bf64e3d

**Comment by wiegell** [comment]
Not exactly no. The functionality i found what does what i needed is the one from the command:
`Gitlens: Compare with branch` and then select main. So i can sum up changes from multiple commits in the active file.
