### ISSUE TITLE
The graph filter area is not displayed

### ISSUE THREAD

**Issue by FE-Mars** [gitkraken/vscode-gitlens#3314]
### Description

![Uploading iShot_2024-05-23_11.29.12.png…]()

### GitLens Version

15.0.4

### VS Code Version

Version: 1.89.1 (Universal)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:14:24.611Z 
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.5.0

### Git Version

git version 2.41.0

**Comment by jkelroy** [comment]
Hello @FE-Mars, it looks like your image may not have uploaded successfully. Can you please provide an screenshot of the issue you are seeing with the graph filter?
