### ISSUE TITLE
Extension pop-up does not stay open anymore

### ISSUE THREAD

**Issue by juancarlosjr97** [gitkraken/vscode-gitlens#3316]
### Description

Previously, not sure which version, the pop-up used to stay open, and recently, I noticed that it does not do that anymore. I went through the settings and I could not find any details about it.

### GitLens Version

15.0.4

### VS Code Version

  - Version: 1.89.1 (Universal)
  - Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
  - Date: 2024-05-07T05:14:24.611Z (2 wks ago)
  - Electron: 28.2.8
  - ElectronBuildId: 27744544
  - Chromium: 120.0.6099.291
  - Node.js: 18.18.2
  - V8: 12.0.267.19-electron.0
  - OS: Darwin arm64 23.5.0

### Git Version

git version 2.40.0

### Logs, Screenshots, Screen Captures, etc

![Screenshot 2024-05-24 at 8 23 14 AM](https://github.com/gitkraken/vscode-gitlens/assets/36451129/37d26d7b-c507-43a1-88e0-84522acd837a)

**Comment by d13** [comment]
@juancarlosjr97 -  if you click in the empty-space of the hover, it will become focused and stay opened until you click away.

https://github.com/gitkraken/vscode-gitlens/assets/293282/cadc1866-2296-436c-b34b-3a00721c012f

**Comment by juancarlosjr97** [comment]
Thank you @d13 for recording the video. It appears I am not able to do the same as you. I also recorded a video just in case it might be something I am doing wrong.

https://github.com/gitkraken/vscode-gitlens/assets/36451129/e654adb4-d05a-4946-8e5c-0ea13a9c7fae

**Comment by eamodio** [comment]
Unfortunately VS Code completely controls the hover behavior you are experiencing. Can you please [open an issue](https://github.com/microsoft/vscode/issues/new?assignees=&labels=&template=bug_report.md) on the VS Code repository? Thanks!
