### ISSUE TITLE
Make changing the AI key easier

### ISSUE THREAD

**Issue by elliottmejia** [gitkraken/vscode-gitlens#3344]
### Description

This is not a bug as much as a complete lack of feature functionality. There is no option in settings, no button, no prompt upon API key error. In finding my first key would not work due to project restrictions, I quickly found there was no option to actually change the key. This feature is dead in the water for me.

### GitLens Version

v15.0.4

### VS Code Version

Version: 1.89.1 (Universal)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:14:24.611Z (1 mo ago)
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.3.0

### Git Version

git version 2.45.2

**Comment by eamodio** [comment]
You can use the `GitLens: Reset Stored AI Key` from the Command Palette. Hope that helps!

**Comment by eamodio** [comment]
In the next pre-release `GitLens: Reset Stored AI Key` has been renamed to `GitLens: Reset Stored AI Keys...` and it has a confirmation to clear all AI keys or just the current provider.

Also in the next pre-release there is a new button in the toolbar of the AI model picker:

![image](https://github.com/gitkraken/vscode-gitlens/assets/641685/d85cf841-e80c-43c6-963d-c50c81652bf7)

You can open model picker via the `GitLens: Switch AI Model` command from the Command Palette

**Comment by elliottmejia** [comment]
Thank you!
