### ISSUE TITLE
Gitlens doesn't recognize the repository

### ISSUE THREAD

**Issue by valentina-arras** [gitkraken/vscode-gitlens#3371]
### Description

The plugin worked perfectly until a couple of weeks ago. Now, it doesn't see that I'm on a Git repository anymore therefore I can not see any history info for the file or the code line. 

### GitLens Version

15.1.0

### VS Code Version

1.90.2

### Git Version

Embedded Git 2.41.0

**Comment by d13** [comment]
Can you please enable debug logging by running the _GitLens: Enable Debug Logging_ command from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ & _GitLens (Git)_ channels in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the logs from the _GitLens_ and _GitLens (Git)_ channels.

Thank you!
