### ISSUE TITLE
Post-merge review of #3356

### ISSUE THREAD

**Issue by eamodio** [gitkraken/vscode-gitlens#3379]
Review of https://github.com/gitkraken/vscode-gitlens/pull/3356

- [x] Can we consolidate the following to hide that complexity inside the `integration.connect()` call?

  https://github.com/gitkraken/vscode-gitlens/blob/2f9750e155965c06bc8ff2e253cc1ad905868680/src/commands/remoteProviders.ts#L99-L115

  https://github.com/gitkraken/vscode-gitlens/blob/2f9750e155965c06bc8ff2e253cc1ad905868680/src/plus/focus/focus.ts#L162-L177

- [x] Suggest changing the notion of "secret" to "session"/"stored session"/"auth":

  https://github.com/gitkraken/vscode-gitlens/blob/305d406cc7fe4247ad3cfae86cb860b87b4659ef/src/plus/integrations/authentication/integrationAuthentication.ts#L71-L96

- [x] Restrict the `key` params to be a subset of `SecretKeys` to avoid something else getting in there

  https://github.com/gitkraken/vscode-gitlens/blob/305d406cc7fe4247ad3cfae86cb860b87b4659ef/src/plus/integrations/authentication/integrationAuthentication.ts#L71-L96

-  Generally avoid `Promise.all` and use `Promose.allSettled` when we want to wait for everything -- as `Promise.all` will throw on the first rejected promise

https://gitkraken.atlassian.net/browse/GLVSC-591

**Comment by sergeibbb** [comment]
@eamodio 

> Suggest changing the notion of "secret" to "session"/"stored session"/"auth":

I'm taking "auth". I pick anything but "session", because there is a layer of "<actOn>Session" methods that call to "<actOn>Secret" methods (that are kind of a lower level), that's why I took a different word for that.

**Comment by sergeibbb** [comment]
@eamodio 

> Restrict the key params to be a subset of SecretKeys to avoid something else getting in there

Do you mean adding a check on its value at runtime?

**Comment by eamodio** [comment]
> @eamodio
> 
> > Restrict the key params to be a subset of SecretKeys to avoid something else getting in there
> 
> Do you mean adding a check on its value at runtime?

More to just create a restricted type, e.g.

```ts
export type SecretKeys =
	| `gitlens.${AIProviders}.key`
	| `gitlens.plus.auth:${Environment}`
	| IntegrationAuthenticationKeys;

export type IntegrationAuthenticationKeys =
	| `gitlens.integration.auth:${IntegrationId}|${string}`
	| `gitlens.integration.auth.cloud:${IntegrationId}|${string}`;
```

And then use that new type
