### ISSUE TITLE
Github credentials Erro

### ISSUE THREAD

**Issue by shrikantbmali** [gitkraken/vscode-gitlens#3392]
### Description

One one needs to be connected to VPN to access a particular repo, gitlens keeps bothering with this error until I connect to VPN. Either it show only once or give me a setting to disable all such notitication.
![image](https://github.com/user-attachments/assets/341ab9e9-027a-4e9a-9c3b-c31de124b86e)

### GitLens Version

15.2.0

### VS Code Version

Version: 1.91.1 (user setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

### Git Version

git version 2.45.2.windows.1

**Comment by eamodio** [comment]
@shrikantbmali Is new since 15.2?
