### ISSUE TITLE
line blame and file blame stop showing right after upgrading to pro

### ISSUE THREAD

**Issue by Husky931** [gitkraken/vscode-gitlens#3396]
### Description

Git line blame and file blame was showing and right after i upgraded to pro the gitlens was visible, but inline black + file blame menu dissapeared. I am using Cursor IDE - Version: 0.36.2 | VSCode Version: 1.89.1

I have tried toogling between Zen mode and Reviews mode, sign out / sign in, switch from Pre-release mode / Release, nothing made it appear

### GitLens Version

15.2.0

### VS Code Version

I am using Cursor IDE

Version: 0.36.2
VSCode Version: 1.89.1

**Comment by eamodio** [comment]
Can you please enable debug logging by running the _GitLens: Enable Debug Logging_ command from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ & _GitLens (Git)_ channels in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the logs from the _GitLens_ and _GitLens (Git)_ channels.

Thank you!
