### ISSUE TITLE
Blame annotations & revision navigation are missing in 15.2.1 when using remote (WSL, SSH, etc) repositories

### ISSUE THREAD

**Issue by moltob** [gitkraken/vscode-gitlens#3423]
### Description

I have to rewrite this... Looks like the file blame command is gone? Disappeared exactly with this new version.

After loosing it on my work machine, I retried at home: Before the update it worked, right after it no longer did.

### GitLens Version

15.2.1

### VS Code Version

Work:

Version: 1.91.1 (user setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

Home:

Identical, except for OS: Windows_NT x64 10.0.22631

### Git Version

Work/Home: git version 2.34.1

### Logs, Screenshots, Screen Captures, etc

That's all I am offered:

![image](https://github.com/user-attachments/assets/7d7e5eb3-269c-4892-b643-db16f7c090a6)

**Comment by moltob** [comment]
I should mentioned that while VSC is running on Windows, GitLens and the repo live in WSL. But again very different versions at Work/Home:

- Win10 vs Win11 Host
- Proxy Usage vs direct
- VPN Usage vs direct
- NAT vs transparent WSL network
- ...

So I don't think there is an issue on those...

**Comment by coreylafferty** [comment]
Can confirm this. Switching back to 15.2.0 shows Blame and the toolbar. With 15.2.1 the toolbar and commands (Blame, Heatmap, etc.) are gone.

**Comment by eamodio** [comment]
In the latest version we had to rework how we handle context to support toolbar commands because of VS Code changes, but we haven't seen any negative impact (only positive) so the more info we can get here would be greatly appreciated.

Can you please enable debug logging by running the _GitLens: Enable Debug Logging_ command from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ & _GitLens (Git)_ channels in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the logs from the _GitLens_ and _GitLens (Git)_ channels.

Thank you!

**Comment by eamodio** [comment]
Ugh, I see the problem -- there is a disconnect between how VS Code reports URIs in its context. The document tells us its `file://` but in the context they set it to `vscode-remote://` so we don't match.

Can you please verify this fix in tomorrow's (`v2024.07.26xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by moltob** [comment]
Will do once the version is available (not yet right now).

**Comment by moltob** [comment]
The release version become available about 20 mins ago on the VS market place. I can confirm it is working again. I had to redo my keyboard shortcut, there were some duplicates in the keymap now...

But other than that it's as expected again. Thanks.

**Comment by TechTronixx** [comment]
Can confirm revision navigation is working in the Pre-Release version thanks!

**Comment by eamodio** [comment]
@moltob what duplicate shortcuts?

**Comment by moltob** [comment]
Unforunately, I cannot reproduce. But this morning (and also saw this yesterday at some point in 15.2.1) I had entries for file blame 2 or 3 times in that menu:

![image](https://github.com/user-attachments/assets/76465873-d06d-48a7-b27d-350fd7f4f399)

Only one had my shortcut, but apparently that ways not the active one.

While this happened at work with today's prerelease, it did not happen at home with 15.2.2.

**Comment by eamodio** [comment]
@moltob not sure what was going on there, hopefully its resolved.

Unfortunately, my original fix was incomplete and cause other negative side effects. A pre-release is available now with a complete fix, and a new patch release is building right now and should be out shortly.

Sorry for the inconvenience!

**Comment by moltob** [comment]
I believe this is still partly broken (15.2.3). In fact I am not able to revert/update to _any_ version in order to get file blame back. I suggest to reopen this issue until it is really resolved.

It is working at home, but not at work (WSL @ Win 10). Attached is the debug log after relaunch of VSC. After loading, the command menu does not show the file blame command.

[gitlens-git.log](https://github.com/user-attachments/files/16407622/gitlens-git.log)
[gitlens.log](https://github.com/user-attachments/files/16407623/gitlens.log)

**Comment by moltob** [comment]
Also just noticed that in the commit graph, there seems to be something running (and not ending) in the background, as the little blue progress indicator keeps running:

![image](https://github.com/user-attachments/assets/d8a3e7b9-4b7e-442a-ad66-dacbe7f52586)

**Comment by moltob** [comment]
This morning after a thorough restart of my work machine including Windows, WSL, etc. the blame command is back. My shortcuts are not immediately qworking, as I have the duplicates again. Here FYI:

![image](https://github.com/user-attachments/assets/d671e51d-7700-4f8b-9569-1b1ad01cd03f)

The `resourcePath` versions are now `User`, while the (corrected, actual?) `resource` versions are originated in the Plugin. Did these change in the process? Is that the reason?

I then selected "Reset Keybinding" for the two `User` ones and they disappeared. Then I was able to use them again.

**Comment by eamodio** [comment]
@moltob Can please you open a new issue about the Graph progress sticking and add any more details as to when you see it?

The `User` ones are the ones you defined/customized (or at least should be), and those are referencing `resourcePath` which won't work anymore -- it needs to be `resource` again. And the others with `resource` are provided by GitLens directly.
