### ISSUE TITLE
Don't show gitlens context menu items in Copilot Chat codeblock editors

### ISSUE THREAD

**Issue by roblourens** [gitkraken/vscode-gitlens#3443]
### Description

- Have a codeblock in a copilot chat response
- Right click, see several Gitlens commands

This is a bit noisy, I'd prefer to help you hide them. You could use the `inChat` context key to target chat specifically. Or you could check the `resourceScheme` key for schemes that you know you can handle. Let me know if this isn't sufficient or if I can do anything to help!

### GitLens Version

v2024.8.213 (pre-release)

### VS Code Version

Version: 1.93.0-insider
Commit: 3b27f1f74bc09fe2e2068997fcd42768be44a4e3
Date: 2024-08-02T05:03:53.254Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.93.0-insider Chrome/124.0.6367.243 Electron/30.1.2 Safari/537.36

### Logs, Screenshots, Screen Captures, etc

![Image](https://github.com/user-attachments/assets/b3cb1586-e55f-427b-ac89-d62c820e3710)

**Comment by eamodio** [comment]
@roblourens thanks for the report! I've now better scoped the schemes, but VS Code seems to report different schemes to the API vs the `resource*` context keys, so hopefully I've captured them all. For example, using WSL/SSH gives `file` schemes via the window/editor APIs, but the `resource*` context keys use `vscode-remote`.

Can you please verify this fix in tomorrow's (`v2024.8.06xx`) pre-release edition of GitLens? Thank you so much! 

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by roblourens** [comment]
Thanks for the fix! I see it. 

I think the scheme context key difference is by design, inside the remote extension host you are dealing with local `file` resources, but on the window side where the context key lives, the file has the `vscode-remote` scheme because it's not local. If your extension was running in the local EH of a remote window, you would see `vscode-remote` there too.

**Comment by eamodio** [comment]
@roblourens Ah, that makes sense. Are there any other schemes like `vscode-remote` that we should be aware of that behave similarly?

Also do you know any better way to adapt those `file` resources into the correct URI on the other side? This is what we are doing today:

https://github.com/gitkraken/vscode-gitlens/blob/620887af3753a790dd4f587b0755a009ba9d4243/src/system/utils.ts#L322-L341

**Comment by roblourens** [comment]
Yeah, I think that's probably the best method you have to get the URI, but, does this just feed into `setContext` to use it in a context key? You _might_ be able to pass the URI to that, instead of a string, then it would get URI-transformed automatically and stringified for the context key. Not sure about that though.
