### ISSUE TITLE
Cannot merge branch into detached HEAD

### ISSUE THREAD

**Issue by MetRonnie** [gitkraken/vscode-gitlens#3445]
### Description

1. Check out a commit in detached HEAD mode
2. Right click a branch and choose "Merge Branch Into Current Branch..."
    ![image](https://github.com/user-attachments/assets/33e7767f-c245-4dec-ad64-6622be462c9f)

It doesn't work, and gives this incorrect message despite HEAD not containing the changes from the branch

![image](https://github.com/user-attachments/assets/dfe21553-c67f-43d6-baa4-46d3c3713b97)

> Nothing to merge; (\<SHA\>) is already up to date

### GitLens Version

15.2.3

### VS Code Version

Version: 1.92.0 (system setup)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

### Git Version

git version 2.46.0.windows.1

### Logs, Screenshots, Screen Captures, etc

No new lines in the GitLens log when I try this

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's (`v2024.8.06xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by MetRonnie** [comment]
Yes it now works (tested with `v2024.8.705`)
