### ISSUE TITLE
The sidebar displays Git commit records.

### ISSUE THREAD

**Issue by al6nlee** [gitkraken/vscode-gitlens#3454]
For example, JetBrains' product displays Git commit records in the sidebar instead of just showing one line of commit at the end of each line.
![image](https://github.com/user-attachments/assets/90ae06af-4a3b-4954-941a-965718614697)

**Comment by eamodio** [comment]
@al6nlee I'm not really sure what you are asking for, but are you looking for the [File Blame](https://help.gitkraken.com/gitlens/gitlens-features/#file-blame) feature?

If not, can you please add more detail as to the issue or feature you are requesting?

Thank you!

**Comment by al6nlee** [comment]
Thank you for your response. I have found the location for the configuration. It already existed.
![image](https://github.com/user-attachments/assets/e5c1f150-7efa-4aeb-9a40-3fd587806666)

**Comment by al6nlee** [comment]
![image](https://github.com/user-attachments/assets/86de6e8b-f3b5-4ffd-b7ba-b73fe2e31166)
