### ISSUE TITLE
When the extension is installed in the host the icons which are indicating the changes or conflicts are blinking continously

### ISSUE THREAD

**Issue by Kishore-TPF** [gitkraken/vscode-gitlens#3483]
### Description

when open an remote file it looks good. But when the host folder open throught the connect to ssh host it is happening

1. Open a remote connection through connect to host
2. Install the gitlens extension on the server
3. Once the instllation completed just edit some files or create some files the indicators to display the changes will be blinking nearby the filenames and folder names

Thease are my system info:

CPUs	Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)
GPU Status	2d_canvas: enabled canvas_oop_rasterization: enabled_on direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_graphite: disabled_off video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: enabled webnn: disabled_off
Load (avg)	
Memory (System)	15.76GB (4.15GB free)
Process Argv	. --crash-reporter-id b3c90cfa-d29d-4505-a1b3-1e3e255f6828
Screen Reader	no
VM	0%
OS	Linux x64 6.8.0-40-generic
CPUs	Intel(R) Xeon(R) CPU E31220 @ 3.10GHz (3 x 0)
Memory (System)	15.62GB (12.15GB free)
VM	100%

![image](https://github.com/user-attachments/assets/01c8adee-f2a4-47a3-87b6-d3b9d6e2cab2)

### GitLens Version

v15.2.1

### VS Code Version

Version: 1.92.2 (user setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

### Git Version

2.41.0.windows.1

**Comment by eamodio** [comment]
Can you expand on where these status icons are? And can you show where/how they are blinking (video?)?

Thank you!

**Comment by Kishore-TPF** [comment]
I have attached the screenshot already, the font color will be changed to yellow if we make any changes right. That thing is blinking continuously.

Not only the yellow icon but all the color changes which will indicate the git changes are blinking when we are trying to access the host file.
