### ISSUE TITLE
branches in worktrees are no longer collapsed into folder groupings

### ISSUE THREAD

**Issue by mazer1310** [gitkraken/vscode-gitlens#3518]
### Description

After updating to GitLens 15.4.0, branches that are in their own worktrees are no longer collapsed into folder groupings within the Branches tab.  We have many different release/* and develop/* branches at any given time, and I frequently have multiple worktrees.  The collapsed view has been wonderful to only display branches that are currently relevant.  However, after updating GitLens, many of those branches that used to be collapsed into "develop" or "release" subfolders within the branches view are now appearing at the top level instead.   
![vscode-branches](https://github.com/user-attachments/assets/e6e6ffba-26ff-4098-8fb8-ebc566c90a25)

In the screen capture, develop/pc_i, develop/pc_h, develop/pc_d, and release/9.0 should all be collapsed into the "develop" or "release" subfolders respectively, while "PPC-11497-pc_i-update-gsoap-ssl-session-caching" should be visible at the top level.

All four of the affected branches are currently residing in their own worktrees, while two develop and release branches that are not in worktrees are correctly collapsed.

I was unable to find a setting that controls this behavior.  

### GitLens Version

15.4.0

### VS Code Version

Version: 1.92.2 (system setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22621

### Git Version

git version 2.46.0.windows.1

**Comment by eamodio** [comment]
Sorry about that -- this was a bug in that we were not allowing branches on worktrees to be compacted, but it was supposed to only be worktrees that were open in the current window (similar to the behavior we do for the current branch).

Can you please verify this fix in tomorrow's (`v2024.9.06xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by mazer1310** [comment]
> Can you please verify this fix in tomorrow's (v2024.9.06xx) pre-release edition of GitLens?

@eamodio :  confirmed.  v2024.9.605 is working correctly.  Thank you for the quick turnaround!
