### ISSUE TITLE
Launchpad: Search for another PR

### ISSUE THREAD

**Issue by axosoft-ramint** [gitkraken/vscode-gitlens#3543]
Add ability to search for a PR not in the Launchpad list. UX needs to be talked through.

Normally our algorithm provides the Launchpad with some subset of all PRs. So, the full list of PRs accessible to the user is wider. The current search looks only for PRs selected for the Launchpad and  we want user to be able to search among all other available PRs.

The current idea, but needs discussion and may be changed:
- User can use the text input in the Launchpad quickpick, either in the main Launchpad list/step or through some other/new step, to search for a PR using its url. For example: `https://github.com/gitkraken/vscode-gitlens/pull/3500`. Or if that fails, we could just do a PR search with the integration using the user's search query.
- If no item in the existing categorized list matches the search, we check other PRs in the repo (or repos) matching the user's text to see if we can find a matching PR, and show a Focus item (default to "other" category) for it.
- The user can then open that item and take actions on it like any other Launchpad item.

## Notes
- Should first discuss design/UX with the team. For example: should there instead be a "search for a different PR" button or action item in the Launchpad list? Would that make it more discoverable?
- Thinking of using `integration.getPullRequest` for the PR search when the user uses PR url, and `integration.searchPullRequests` for more general search, but the exact function/query may change depending on final design.
- Note that if we use `integration.getPullRequest` or `integration.searchPullRequests`, they must be implemented for GitLab since Launchpad supports GitLab as well (currently it is only implemented for GitHub). This might be a good opportunity to add this functionality to the shared provider library, but for now we can implement them locally for GitLab as needed.

### PR1. Search by URL GitHub
If I copy and paste a PR url directly into the input box on the main step, it should search for that PR
     
1. ✅ filter the current list for the specified PR if it's there
2. ✅ otherwise search for the specified PR by its ID
3. ✅ make sure it's debounced properly
4. Fix few search bugs:
  - ✅ Fix bug of not clearing the found item
  - ✅ Fix bug of incorrect local search by PR-id
5. ✅ be friendly to incomplete URLs or URLs with additional parts
6. 💡 waiting for code review feedback

### PR2. Add full search mode

Add an always visible item such as "Search everywhere". If it's clicked, switch to the mode that searches across all PRs the user has access to using the search terms.

1. ⏺️ ...
2. ⏺️ Bug: Local search cannot find items of collapsed groups.

### PR3. GitLab
Support GitLab MR urls and search across all PRs on GitLab.

1. ⏺️ wrap GitHub specific code, so other providers could be added easily
2. ⏺️ add GitLab

### Change query while searching
In order to debug this part I increase the debouncing timeout and add delays into the debounced procedure.
1. While searching get back from API search to local filter:
2. While searching get Back from API search to local search by URI
  - in 1-2, check that the current search is cancelled, its result is not applied
3. While searching change the search query
  - the second result is applied
  - the first debounced promise is not cancelled, so it enters the finally method at the same time when the second query enters
  - inside of the first debounced request we see that the cancellation token require us to cancel, so we don't apply the result

### Change query after the search
1. After an API search get back to the local filter
2. After an API search get back to the local search by URI
  - in 1-2, check that the additional search is removed from the result (e.g. it cannot be found by its title)

**Comment by sergeibbb** [comment]
@axosoft-ramint 

Question. In the old code I see how the `quickpick.value` affects that groups are being hidden. But I don't see where does the actual filtering happen. Is it provided by VSCode itself?

**Comment by axosoft-ramint** [comment]
@sergeibbb VSCode indeed internally filters the quickpick items to only those that match your search (though I'm not sure exactly what parts of the quickpick items it uses to match, other than their main label). There is an `alwaysShow` (I forgot the exact name) property we can toggle on/off for items as a hack to get around this internal filtering, and that's what the old code is using.

**Comment by sergeibbb** [comment]
Hi @axosoft-ramint 

I have a noob question for you. What does the returning boolean from the event handler means in a QuickPickStep?

```
onDidChangeValue?(quickpick: QuickPick<DirectiveQuickPickItem | T>): boolean | Promise<boolean>;
```

https://github.com/gitkraken/vscode-gitlens/compare/main...draft/3543-pr-search#diff-25ee8b0447aeac38780fa0402ebffabcbbbc8c30024e1a61e681ec5d8e6694bcL555-R609

**Comment by axosoft-ramint** [comment]
> Hi @axosoft-ramint
> 
> I have 3 questions for you.
> 
> The first is a noob one. What does the returning boolean from the event handler means in a QuickPickStep?
> 
> ```
> onDidChangeValue?(quickpick: QuickPick<DirectiveQuickPickItem | T>): boolean | Promise<boolean>;
> ```

@eamodio Can you shed some light on this one? I'm actually not sure and the API doesn't specify clearly.

@sergeibbb I didn't see any other open questions in the post - let me know if I missed anything.

**Comment by sergeibbb** [comment]
Hi @axosoft-ramint I have a question for you.

The debouncer is designed to be disposable. But do you have an idea where it's better to register it as a disposable object? Now it's managed by `LaunchpadItemQuickPickItem` that doesn't implement `Disposable` nor handling disposing in any other way.

Probably if we could detect a moment when the Launchpad panel becomes hidden, that would let us to cancel the requests that are in progress.

**Comment by axosoft-ramint** [comment]
@sergeibbb I would suggest that we clear/cancel/dispose the debouncer whenever the Launchpad itself, rather than an item, changes to a different step, is hidden, or is otherwise disposed.

**Comment by sergeibbb** [comment]
@axosoft-ramint 
Right. It's in `LaunchpadCommand` now. I've pasted the wrong name, I'm sorry.

So, every time we see that the LaunchpadCommand changes step or gets closed. It's on every `yield step`, isn't it?

How do we detect that it's closed?


> or is otherwise disposed.
`LaunchpadCommand` seems to be not disposable.

**Comment by axosoft-ramint** [comment]
@sergeibbb Not the command object but the (quickpick)[https://code.visualstudio.com/api/references/vscode-api#QuickPick], which would be a param in step events like `onDidChangeValue`.

cc @eamodio in case there's an easier way

**Comment by sergeibbb** [comment]
@axosoft-ramint @eamodio 

Yeah. I thought that I should control the `quickpick`. However, I'm not sure how to do it right.

I get the `quickpick` object each time from arguments. So, I don't even know whether it's the same object or not, therefore it's not clear when I should subscribe on its events such as `onDidHide` and how to detect that its step changes.
