### ISSUE TITLE
Open multi-diff editor when opening a new worktree from a PR

### ISSUE THREAD

**Issue by eamodio** [gitkraken/vscode-gitlens#3549]
When we complete the flow of creating a worktree from a PR, we should open the changes in the PR in the multi-diff editor.

If the GH PR extension is installed, we should try to either get it to open the multi-diff editor, or figure out the uri schemes they are using so that commenting will work in that editor.

**Comment by d13** [comment]
So let's split this into two separate deliverables:

- Using the completion of the deeplink to open a workspace, open the multi-diff using our normal functionality `openAllChanges`
- GH PR extension detection

**Comment by sergeibbb** [comment]
@nzaytsev @axosoft-ramint 

I cannot verify :-(

https://github.com/user-attachments/assets/d8cae634-729c-4d3d-bdc7-75c8ff8248fc

**Comment by sergeibbb** [comment]
Thank you @axosoft-ramint!


Confirmed:
https://github.com/user-attachments/assets/b0264ecf-b784-4592-b89e-d3c3c38c0301
