### ISSUE TITLE
Onboarding checklist in Home

### ISSUE THREAD

**Issue by nzaytsev** [gitkraken/vscode-gitlens#3552]
The goal is to increase awareness and exposure to GitLens features, especially for new users.

https://www.figma.com/file/ZRm91LPm0zpyfLwM1wwMZZ?type=design%27&node-id=1:3953

![Screenshot 2024-09-09 at 10 35 19](https://github.com/user-attachments/assets/76d23210-b6fb-4df5-9a65-82cffa81827d)

**Comment by d13** [comment]
This is replaced with https://github.com/gitkraken/vscode-gitlens/issues/3656
