### ISSUE TITLE
Gitlens fails to register buttons on top-right corner

### ISSUE THREAD

**Issue by axonasif** [gitkraken/vscode-gitlens#3571]
### Description

https://github.com/user-attachments/assets/d9a45744-a732-4598-b6b4-f220cc0815e6

- Open a repo in Gitpod VS Code web (e.g. https://gitpod.io/new/?autostart=false&workspaceClass=g1-large#https://github.com/gitkraken/vscode-gitlens)
- Install latest (`v15.5.0` at the time of writing) `Gitlens` from the Extensions panel.
- Open a file.
- Notice how none of the Gitlens buttons are registered on the top-right editor tabs row.
- Now install `v15.2.0` of Gitlens from the Extensions panel and reload your browser tab/window.
- The buttons are properly registered now.

Something changed (ref: [/compare/v15.2.0...v15.2.1](https://github.com/gitkraken/vscode-gitlens/compare/v15.2.0...v15.2.1)) after `v15.2.0` version which is causing it to fail to register the menu buttons in VSCode web.

### GitLens Version

15.5.0

### VS Code Version

https://github.com/gitpod-io/openvscode-server
Version: 1.93.0
Commit: 9fb9b0e32ba3f2abcb214577ef14173b0df7e8d2
Date: 2024-09-06T18:46:15.461Z (6 days ago)
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0

### Git Version

git version 2.46.0

### Logs, Screenshots, Screen Captures, etc

[4-GitLens.log](https://github.com/user-attachments/files/16989250/4-GitLens.log)

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's (`v2024.09.26xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by axosoft-ramint** [comment]
Verified in latest pre-release
