### ISSUE TITLE
Fix telemetry event for 'upgrade' actions taken from the promo banner in Launchpad

### ISSUE THREAD

**Issue by axosoft-ramint** [gitkraken/vscode-gitlens#3576]
Currently the event data being sent out on `subscription/action` is this:

action = 'upgrade'
source.detail.action = 'focus'
source.detail.step.title = 'GitLens Launchpad  ᴘʀᴏ'
source.name = 'git-commands'

Source should be 'launchpad'. 'git-commands' doesn't make sense and 'focus' is deprecated naming.

**Comment by eamodio** [comment]
If we change that it will affect reporting on the "git-command" usage. So we will need to check with @trevor-polidore.

Might want to do this as part of the broader rename of focus to launchpad too
