### ISSUE TITLE
"Delete Branch" option is sometimes unexpectedly missing

### ISSUE THREAD

**Issue by eamodio** [gitkraken/vscode-gitlens#3582]
Continued from #3514

_Originally posted by @DmitryEfimenko in https://github.com/gitkraken/vscode-gitlens/issues/3514#issuecomment-2351009234_

> There's now potentially a related issue. The "Delete Branch" option is completely gone. Previously, the "Delete option" would not show when you are on the branch that you want to delete. But, I made sure it's not the case.
>
> Also, see the result of these commands:
> ```sh
> git worktree list
> C:/Source/art/art-backend  b5033fb [master]
> ```
>
> ```sh
> git branch
>   fix/75
> * master
> ```
>
>
> ![image](https://github.com/user-attachments/assets/6c3fe98f-f222-4c85-b4cc-8342186f41a3)
> 
> It's worth mentioning that I experience the issue with missing "Delete Branch" button in one repository, but not the other. Although, my git workflow is usually the same. Not sure what the difference is

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's (`v2024.09.16xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by eamodio** [comment]
To verify: 
 - Open VS Code with a repo with 2 branches (A & B)
 - Start on branch A
 - Verify that _Delete Branch..._ IS NOT on the context menu for branch A (since it is the current branch) 
 - Verify that _Delete Branch..._ IS on the context menu for branch B
 - Switch to branch B
 - Verify that _Delete Branch..._ IS on the context menu for branch A
 - Verify that _Delete Branch..._ IS NOT on the context menu for branch B (since it is now the current branch)

**Comment by axosoft-ramint** [comment]
> To verify:
> 
> * Open VS Code with a repo with 2 branches (A & B)
> * Start on branch A
> * Verify that _Delete Branch..._ IS NOT on the context menu for branch A (since it is the current branch)
> * Verify that _Delete Branch..._ IS on the context menu for branch B
> * Switch to branch B
> * Verify that _Delete Branch..._ IS on the context menu for branch A
> * Verify that _Delete Branch..._ IS NOT on the context menu for branch B (since it is now the current branch)

Verified using the above steps.
