### ISSUE TITLE
Unable to log into Cursor with Pro account

### ISSUE THREAD

**Issue by MantraMedia** [gitkraken/vscode-gitlens#3603]
### Description

Using Cursor and having an active Pro subscription I am unable to log in or retrieve an auth token as I am always getting redirected to the Launchpad.

Also reported in #3222 in multiple comments , eg https://github.com/gitkraken/vscode-gitlens/issues/3222#issuecomment-2351028471 but no one seems to care here 

### GitLens Version

v15.5.1

### VS Code Version

Cursor 0.41.1

**Comment by buyou0821** [comment]
same issue

**Comment by allanpoppe2** [comment]
Same issue, can't login, pls add support.

**Comment by jkelroy** [comment]
This is something our team is currently looking into. You can still sign in using a previous version. To do this, go to Extensions > select the gear icon for GitLens > _Install Another Version..._ > Use v14.6.1. 

![Screenshot 2024-09-23 at 9 02 30 AM](https://github.com/user-attachments/assets/818f6828-0783-49a2-aa9d-a2473afd9451)

After that, you can sign into GitLens and you will have the option to _Show auth _URL_ to provide back to Cursor. You can then upgrade GitLens to the current version and remain signed in.

![Screenshot 2024-09-23 at 9 09 18 AM](https://github.com/user-attachments/assets/8cd5fddd-7fc2-4831-8ded-d536fc2a0cf5)

**Comment by MantraMedia** [comment]
This works. Thank you!

**Comment by jkelroy** [comment]
This has now been addressed. 

https://github.com/gitkraken/vscode-gitlens/issues/3222#issuecomment-2369114858
