### ISSUE TITLE
Title: GitLens integration website opens on every launch of VSCode and/or change profile

### ISSUE THREAD

**Issue by DevDorrejo** [gitkraken/vscode-gitlens#3608]
### Description

1. Environment:
    - openSUSE Tumbleweed (snapshot 20240922).
    - Windows 11 Enterprise 23H2.
2. Issue:
    - Every time I open VSCode and/or change profile, the GitLens integration website automatically opens.
3. Steps to Reproduce:
    - Launch VSCode and/or change profile.
    - Observe that the GitLens website opens automatically without any interaction.

### GitLens Version

15.5.1

### VS Code Version

Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z (1 wk ago)
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.93.1 Chrome/124.0.6367.243 Electron/30.4.0 Safari/537.36

### Git Version

git version 2.46.1

**Comment by axosoft-ramint** [comment]
@DevDorrejo Can you please enable debug logging by running the _GitLens: Enable Debug Logging_ command from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ & _GitLens (Git)_ channels in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the logs from the _GitLens_ and _GitLens (Git)_ channels.

Also, a few other questions to help investigate:

1. What type of repository do you have open in the window(s) where this occurs? GitHub, GitLab, GitHub Enterprise, GitLab Self-Managed, etc.
2. Would you mind also sending the full url that GitLens is sending you out to from VSCode?
3. When this happens, can you open the Remotes view and let me know if you have any remotes disconnected? Any disconnected ones should show a single plug icon that says `Connect Remote Integration` when hovering over it. See screenshot below. 
<img width="515" alt="image" src="https://github.com/user-attachments/assets/9781a7c7-4b05-4aca-a066-64d2e45308a1">

**Comment by DevDorrejo** [comment]
1. Not repository in use, only opening VSCode and/or changing profile.
2. URL (https://gitkraken.dev/connect?source=gitlens&provider=gitlab&redirect_uri=vscode%3A%2F%2Feamodio.gitlens%2Fdid-authenticate-cloud-integration%3FwindowId%3D1)
3. Not remote, everything in local.

Debug info:

[gitlens.txt](https://github.com/user-attachments/files/17106244/gitlens.txt)

**Comment by axosoft-ramint** [comment]
@DevDorrejo Can you please verify this fix in the pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by DevDorrejo** [comment]
The pre-release fix the issue, not more opening the integration page each time open vscode and/or change profile.

thank you very much @axosoft-ramint
