### ISSUE TITLE
Launchpad UX Improvements

### ISSUE THREAD

**Issue by justinrobots** [gitkraken/vscode-gitlens#3614]
For Draft PRs:
- [x] #3654
- [x] #3655

For "Other" section:
- [x] Sort PRs to put current user's PRs at the top of the list
- [x] Add a visual separator between user's "Other" PRs and collaborators' PRs

In Launchpad item detail menu:
- [x] Rename "Switch to Branch on Worktree" option to "Switch to Branch", since there is an option to open on a worktree in this flow
- [x] Pin and Snooze icon buttons should be in the item header

**Comment by axosoft-ramint** [comment]
Removing "add option to search all PRs" and "add option to start work" because these are separate top-level issues
