### ISSUE TITLE
Launchpad View UX Improvements

### ISSUE THREAD

**Issue by justinrobots** [gitkraken/vscode-gitlens#3615]
General:
- [x] Replace "Compare Pull Request" hover icon button with "Open in Worktree". (keep both in context menu)
- [x] Remember the collapsed/expanded states of sections
- [x] If the branch you are on has a launchpad item, expand that by default.

For Draft PRs:
- [x] Duplicate Draft PRs for which the user has a review request into "Needs your review" section
- [x] Display a draft icon for Draft PRs in the "Needs your review" section

For "Other" section:
- [x] Sort PRs to put current user's PRs at the top of the list

For pinned items:
- [x] When an item is pinned, the "Pinned" category doesn't appear in the Launchpad View until a full reload. It should appear immediately with the pinned item.
- [x] Pinned items should appear above non-pinned items in their respective categories.

**Comment by axosoft-ramint** [comment]
Done in commits:
db4e98d1703ab06eb2ce5da6fc9663eb81661d1c
14b115a31bde421c709268928b1da9a124733b64
4967dfe4e28739599a99e9a56d3887ea72e3a30e
