### ISSUE TITLE
Auto-links not working for alphanumberic issue numbers

### ISSUE THREAD

**Issue by nathanielobrown** [gitkraken/vscode-gitlens#3617]
### Description

I'm finding that auto-links are not working for alpha-numeric issue numbers, even with the `"alphanumeric": true,` setting turned on.

@d13, was great to meet you some months back, perhaps you could take a look?

### GitLens Version

v15.5.1

### VS Code Version

Version: 1.93.1 (Universal)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z (2 wks ago)
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

### Git Version

git version 2.39.3 (Apple Git-146)

### Logs, Screenshots, Screen Captures, etc

Had to use my phone camera as hitting "Command" closes the tooltip!

![CleanShot 2024-09-26 at 11 50 55@2x](https://github.com/user-attachments/assets/7364dd60-c420-4ff0-8f27-58a97c1389c1)

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's (`v2024.09.30xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by axosoft-ramint** [comment]
Verified on the latest pre-release.
