### ISSUE TITLE
New Home View

### ISSUE THREAD

**Issue by justinrobots** [gitkraken/vscode-gitlens#3620]
Replace the existing Home View in GitLens with one that has more valuable information for devs that they will return to frequently throughout their workflow. The designs and ideas below are still being developed, so ask if you have questions and we'll discuss changes as a team.

[Designs (WIP)](https://www.figma.com/design/C5tCGmWybTLZJZHmVYJ7Iz/GitLens-Home-Exploration---Q4-2024?node-id=0-1&t=LInvgAmwFQ0mNCwB-1)

Themes / Sections for this new view:
### Launchpad Summary
- If users don't have integrations connected, guide them to connect to view Launchpad Summary
- When necessary integrations are connected, display the Launchpad Summary
### Start Work
- A primary CTA that guides users to start work by creating a branch or worktree. Ideally, this would leverage issue integrations to start work from an issue, name the branch/worktree according to naming conventions, etc.
### Repo Context
- Display the current repo as the context for sections below, and allow users to change that context if there are multiple repos open in VS Code.
- If no integrations are connected, guide users to connect them so they get rich PR and issue information in branches/worktrees listed below.
- For any branches/worktrees listed in this section, if there is an associated PR, then the "card" will display the PR as the primary element and the branch/worktree as secondary.
#### Current
- The currently checked-out branch or worktree for the given repo context
#### Active
- Any worktrees that are active on the current repository but not in the current VS Code window
#### Recently Modified
- Branches/worktrees that have recent changes. We'll need to determine a timeframe if this will be static, but ideally users would be able to set the timeframe and even the author.
#### Stale
- Branches/worktrees that haven't been modified since a specific date (older than a week, a month, etc.). This would allow people to cleanup old branches.

### Card Types
There are two primary card types in the designs today: Branch/Worktree cards and PR cards
#### Branch/Worktree Cards
- display an icon for the type (branch or worktree) and the title
- display branch information: author (this is a new concept where we would identify the primary contributor for the branch), working changes (files modified, added, etc.), and upstream/downstream changes.
- clicking on various elements should initiate actions like checking out the branch, pulling/pushing, etc. (these designs are still in progress.
#### PR Cards
- the primary context of these cards it the PR, so we display a PR icon and the PR title.
- pull request info: collaborators, repo status (review status, ci status, etc.), and Launchpad status (e.g, Requires your review)
- branch info: basically repeating information from the branch card, subordinate to the PR
#### Related issues
- Branch and PR cards could both show related issues. If, for example, Jira is connected, we could list the issue associated with the branch in these cards, along with the type (story, task, etc.) and status (backlog, in progress, etc.)

```[tasklist]
### Tasks
- [ ] https://github.com/gitkraken/vscode-gitlens/issues/3621
- [ ] https://github.com/gitkraken/vscode-gitlens/issues/3706
```

**Comment by justinrobots** [comment]
Things I've noticed during testing:
[ ] Current branch does not display working directory changes
[ ] `Create Pull Request` option on branch no-ops if no changes have been committed or pushed. This should ideally guide users to commit + push and then open a PR, but should at least be disabled if it can't do anything. A tooltip to explain why would be helpful if we disable it.

**Comment by axosoft-ramint** [comment]
New home view is currently active in pre-release, so this is verified.
