### ISSUE TITLE
GitHub issues - urgent

### ISSUE THREAD

**Issue by MCLELLANINTERNATIONAL** [gitkraken/vscode-gitlens#3637]
Hi, 

I have created js, css, html and images files in VS Code. I then tried to open a repository in GitHub (wdd131) it does not allow me to create a branch. I tried to commit the files to push through to Github however there is nothing in GitHub and I keep getting an issue of 404. I am therefor unable to publish my files. 
my on assignment needs to be in by saturday as it is over 2 weeks and i have ben struggle with this issue for days.

Kind Regards
Kim Brown

**Comment by d13** [comment]
Did you clone the repo from GitHub?

Did you try `git push -u origin {name of branch}`?

**Comment by MCLELLANINTERNATIONAL** [comment]
yes
________________________________

**Comment by MCLELLANINTERNATIONAL** [comment]
git remote add origin https://github.com/MCLELLANINTERNATIONAL/wdd131.git
git push -u origin main

i tried this
________________________________

**Comment by d13** [comment]
Is there something specific you are using GitLens for in this situation? It looks like you are just using the terminal. 

I was able to create an [empty repo in GitHub](https://github.com/d13/test-empty and from the terminal, I created an init commit and pushed it to the repo on GitHub.
