### ISSUE TITLE
Interactive Rebase interface partially unreadable in high contrast dark color theme

### ISSUE THREAD

**Issue by sparr** [gitkraken/vscode-gitlens#3646]
### Description

My theme settings are dark and high contrast and I cannot read the dropdown or main button in the attached screenshot.

### GitLens Version

15.5.1

### VS Code Version

Version: 1.93.1
Release: 24256
Commit: dbab3f8e8c5da7ca1bde636806e0a973e497aa01
Date: 2024-09-18T01:06:54.725Z
Electron: 30.4.0
ElectronBuildId: undefined
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Linux x64 6.10.10-arch1-1

### Git Version

2.46.2

### Logs, Screenshots, Screen Captures, etc

![Image](https://github.com/user-attachments/assets/e4b9d0e5-890f-4ecd-9367-b8e3ec0d733f)

**Comment by d13** [comment]
@nzaytsev - Dropdown colors are fixed, but button text labels still appear unstyled on high-contrast themes. Essentially, anywhere we have CSS selectors for `vscode-light` and `vscode-dark` classes we also need to include `vscode-high-contrast-light` and `vscode-high-contrast` respectively.

**Comment by sergeibbb** [comment]
I'm a bad verifier for this, because on my machine VS Code uses system pop-up. It's better someone else to check it:

![Image](https://github.com/user-attachments/assets/d8ff8da4-1475-4b4c-a62b-c50d14c97efc)

**Comment by axosoft-ramint** [comment]
Seems to work in current pre-release

![Image](https://github.com/user-attachments/assets/c45e4d21-45d2-45ea-9971-18fef83c9667)
