### ISSUE TITLE
"Create & Switch to Local Branch" from remote branch no longer prefills local branch name to match remote branch name

### ISSUE THREAD

**Issue by dburleson** [gitkraken/vscode-gitlens#3650]
### Description

Since the latest update 15.6.0 (2024-10-17), when creating a new local branch from a remote branch, the prompt for the local branch name is no longer defaulted/prefilled to match the remote branch. Thus this now requires a user to type in the full branch name, which can be quite tedious at times if you wish for your local branches to match your remote branches.

To replicate:

1. In Source Control, under Remotes, choose 'Switch to Branch...' next to the branch you wish to checkout.
2. Select 'Create & Switch to Local Branch' when prompted
3. Note that your are asked to enter the name of the new local branch, which is now blank without any option to default to the same branch name as remote.

### GitLens Version

15.6.0

### VS Code Version

Version: 1.94.0 (user setup)
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

### Git Version

git version 2.34.1

### Logs, Screenshots, Screen Captures, etc

![Image](https://github.com/user-attachments/assets/05868249-05b0-4993-a706-2f7c0e2da3c5)
![Image](https://github.com/user-attachments/assets/507b6097-d407-4dcf-8132-c677bc67d028)

**Comment by eamodio** [comment]
Sorry for the issue, can you please verify this fix in tomorrow's (`v2024.10.09xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by gburkhow** [comment]
https://github.com/gitkraken/vscode-gitlens/issues/new/choose
