### ISSUE TITLE
"Open on Remote (Web)" does not use tracked branch name

### ISSUE THREAD

**Issue by nistre** [gitkraken/vscode-gitlens#3651]
### Description

1. Locally branch off a remote branch
2. Rename local branch so the local branch name does not match the remote branch name, but the remote branch is still tracked on the local
3. With Right-Click context menu, Right-Click an open file or one in the Explorer that is on the remote branch
4. Hover "Open on Remote (Web)"
5. Click "Open File on Remote" or "Open File on Remote From..." and select a local branch that tracks a remote branch of a different name

Result: The URL generated uses the local branch name
Expected: The URL generated would use remote branch name that the local branch is set to track

My gitlens config in VSCode:
```json
{
    "gitlens.advanced.abbreviateShaOnCopy": true,
    "gitlens.mode.active": "zen",
    "gitlens.heatmap.toggleMode": "window",
    "gitlens.advanced.messages": {
        "suppressCreatePullRequestPrompt": true
    },
    "gitlens.gitCommands.skipConfirmations": [
        "fetch:command",
        "stash-push:command",
        "switch:command",
        "branch-create:command"
    ],
    "gitlens.autolinks": [
        {
            "prefix": "#",
            "url": "https://<CompanySite>.com/Collection/Project/_workitems/edit/<num>/"
        }
    ],
    "gitlens.remotes": [{
        "domain": "<CompanySite.com",
        "type": "AzureDevOps",
        "name": "<Company>",
        "protocol": "https",
        "urls": {
            "repository": "https://<CompanySite>.com/${repo}",
            "branches": "https://<CompanySite>.com/${repo}/branches",
            "branch": "https://<CompanySite>.com/${repo}/commits/${branch}",
            "commit": "https://<CompanySite>.com/${repo}/commit/${id}",
            "file": "https://<CompanySite>.com/${repo}?path=${file}${line}",
            "fileInBranch": "https://<CompanySite>.com/${repo}/blob/${branch}/${file}${line}",
            "fileInCommit": "https://<CompanySite>.com/${repo}/blob/${id}/${file}${line}",
            "fileLine": "#L${line}",
            "fileRange": "#L${start}-L${end}"
            }
        }
    ],
}
```

Note: I know that going the longer route of "Open on Remote (Web)" -> "Open File on Remote From..." -> Search branch on remote, does works; but it seems unnecessary as the tracked branch on the remote would be accessible to gitlens and I believe a reasonable expectation for a prompt to "Open File on Remote" would use the branch name tracked on the remote and not the local branch name.

If there is a configuration change that could resolve this, I didn't find it in my research.

### GitLens Version

15.6.0

### VS Code Version

Version: 1.94.0 (user setup)
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22621

### Git Version

git version 2.46.0.windows.1

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's (`v2024.10.09xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

I've also updated the _Open Branch on Remote_ and _Open Current Branch on Remote_ commands as well.

**Comment by nistre** [comment]
I switched to pre-release v2024.10.905 and tried this morning.
Here are some ways I tried opening local on remote:
- Command `Gitlens: Open branch on Remote` -> Opens on correct tracked branch
- Context menu or command `Gitlens: Open File on Remote From...` and select the local branch -> Opens on correct tracked branch
- Context menu or command `Gitlens: Open File on Remote` -> **URL is still using local branch name instead of tracked branch name**

**Comment by eamodio** [comment]
@nistre Thanks so much and great catch! I've fixed that last `Gitlens: Open File on Remote` case and that will be in tomorrow's (`v2024.10.10xx`) pre-release

**Comment by nistre** [comment]
Tested this morning on pre-release v2024.10.1005 and all four previously noted cases worked!!  Thank you!
