### ISSUE TITLE
Creating a worktree from within a worktree chooses the wrong path

### ISSUE THREAD

**Issue by eamodio** [gitkraken/vscode-gitlens#3657]

**Comment by sergeibbb** [comment]
my testing:
- created a worktree from a worktree that is inside of the `<root>` ✅
- created a worktree from a worktree with complex branch name, such as `<root>/featrue/feature-name` ✅
- created a worktree from a worktree in a detached folder and check that it uses the same `<root>` as all other worktrees. ✅
- New root:
	- open a worktree in the old root
	- create a worktree choosing a new root
	- then use it to open a new worktree with the same root ⚠️ Alarm!!! It uses the old root!
	- then use it to open a new worktree with changing the root again ⏺️
	- Then use the opened worktree of the old root to create a new worktree in the root. Check that it uses the new root. ⚠️ Alarm!!! It uses the old root!
