### ISSUE TITLE
Add `tags` to settings that are preview or experimental

### ISSUE THREAD

**Issue by d13** [gitkraken/vscode-gitlens#3682]
Added tags display on VS Code's settings editor:

![Image](https://github.com/user-attachments/assets/863fe0cb-cfc5-4869-bf63-1001f9edb507)

Where to add tags:

![Image](https://github.com/user-attachments/assets/3b68f9da-fc66-4c22-b015-85859d8c957b)

Supports `experimental` or `preview`

**Comment by nzaytsev** [comment]
@d13 - Is the feature available for insiders only? I don't see the labels on the latest build for macOS. 

![Image](https://github.com/user-attachments/assets/cfbd4009-dc5b-4b4c-95ca-903122d22b31)

![Image](https://github.com/user-attachments/assets/d83b4545-2cd6-4d26-a9d1-e532ac2f394c)
