### ISSUE TITLE
Deprecate current 3 day preview trial

### ISSUE THREAD

**Issue by justinrobots** [gitkraken/vscode-gitlens#3688]
We're replacing the current 3 day preview trial with a new feature preview (see parent issue).

The entry points into the existing 3 day preview trial should be removed, but the system should remain in place in the case we need to bring it back.

See @eamodio or @d13 for technical clarification or questions.

**Comment by d13** [comment]
For this, we only want to remove the ability to start a preview trial in the UI. That way, we don't need to remove any account state logic.

**Comment by sergiolms** [comment]
Solved in https://github.com/gitkraken/vscode-gitlens/commit/3d4b046cb446829bb8870d23806baf65ef74bad5
