### ISSUE TITLE
Create a confirmation modal for the new graph preview

### ISSUE THREAD

**Issue by justinrobots** [gitkraken/vscode-gitlens#3689]
1. Add a confirmation modal that describes the new graph preview and allows users to continue to view the graph on private repos for a limited number of days. This will take the place of the existing 3 day preview trial modal for the graph.
2. Use the messaging from the existing modal (see image below), but change `Continuing gives you 3 days to preview the Commit Graph and local Pro features.` to `Continuing gives you 3 days to preview the Commit Graph on private repositories.`
3. Add telemetry for when the graph preview starts

Example of existing modal to be replaced:
![Image](https://github.com/user-attachments/assets/cc686ee4-11af-4e2a-a4d0-f92ef9ec1d28)

**Comment by sergiolms** [comment]
Solved in https://github.com/gitkraken/vscode-gitlens/commit/3d4b046cb446829bb8870d23806baf65ef74bad5
