### ISSUE TITLE
Unable to disable commit graph

### ISSUE THREAD

**Issue by thenakulchawla** [gitkraken/vscode-gitlens#3695]
### Description

On installing gitlens pro, I am unable to disable commit graph.
It overrides my vscode terminal.
My `Terminal` is renamed to `GitLens` and the terminal is now in the 3rd tab with 2 tabs of commit graph.

Nothing shows up in the original gitlens tab.

I could not find relevant documentation for disabling this.

My gitlens configuration
```
	"gitlens.graph.defaultItemLimit":             404,
	"gitlens.views.commits.showBranchComparison": false,
	"gitlens.plusFeatures.enabled":               false,
	"gitlens.virtualRepositories.enabled":        false,
	"gitlens.terminal.overrideGitEditor":         false,
	"gitlens.terminalLinks.showDetailsView":      false,
	"gitlens.graph.dateFormat":                   null,
	"gitlens.graph.minimap.enabled":              false,
	"gitlens.graph.allowMultiple":                false,
	"gitlens.graph.scrollMarkers.enabled":        false,
	"gitlens.graph.pullRequests.enabled":         false,
	"gitlens.graph.avatars":                      false,
	"gitlens.graph.statusBar.enabled":            false,
	"gitlens.graph.showDetailsView":              false,
	"gitlens.graph.showUpstreamStatus":           false,
	"gitlens.showWelcomeOnInstall":               false,
	"gitlens.codeLens.recentChange.command":      false,
	"gitlens.graph.sidebar.enabled":              false,
	"gitlens.graph.branchesVisibility":           "current",
	"gitlens.terminalLinks.enabled":              false,
	"gitlens.advanced.messages": {
		"suppressLineUncommittedWarning": true,
	},
```

### GitLens Version

15.6.2

### VS Code Version

Version: 1.94.2 (Universal)
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

### Git Version

git version 2.47.0

### Logs, Screenshots, Screen Captures, etc

![Image](https://github.com/user-attachments/assets/cee47299-4c4e-4a08-9e20-6072d2ef4f61)
![Image](https://github.com/user-attachments/assets/a12fa688-5b54-4c4e-a2bd-3dc26a7ca7e0)

**Comment by eamodio** [comment]
It looks like you (accidentally) dragged the Terminal into the GitLens section -- you can undo that by right-clicking on the Terminal and select the `Reset Location`.
