### ISSUE TITLE
Remove the filtered out commits in commits graph

### ISSUE THREAD

**Issue by tjx666** [gitkraken/vscode-gitlens#3710]
For now, gitlens dim the filtered out commits, but the better view is just remove the filtered out commits.

I want to filter my changes, I just want to see my commits, the dimmed commits occupy too much space.

![Image](https://github.com/user-attachments/assets/5603ab02-be09-44cf-b7b2-70569d7a311d)

**Comment by d13** [comment]
This is currently available in the pre-release edition of GitLens! 

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

Simply click the filter button just before search box to hide the rows. Give it a try and let us know what you think. 

![Image](https://github.com/user-attachments/assets/6996d920-a5f8-4a86-85cb-2c35db388501)

**Comment by tjx666** [comment]
work fine, thank you.

Maybe not a related question, how to make gitlens know these are same people(me)?

![Image](https://github.com/user-attachments/assets/be706471-724f-41ee-82c2-85e6b2e3ebf8)

**Comment by eamodio** [comment]
@tjx666 You can use a `.mailmap` file, https://git-scm.com/docs/gitmailmap. If one exists, Git and GitLens will use it.

**Comment by tjx666** [comment]
learned a lot, thanks @eamodio
