### ISSUE TITLE
Webviews can have issues with high contrast themes

### ISSUE THREAD

**Issue by d13** [gitkraken/vscode-gitlens#3734]
Observed in https://github.com/gitkraken/vscode-gitlens/issues/3646 

Essentially, anywhere we have CSS selectors for `vscode-light` and `vscode-dark` classes we also need to include `vscode-high-contrast-light` and `vscode-high-contrast` respectively.

**Comment by sergeibbb** [comment]
@d13 

Where should I look at to see the problem and to see that it's fixed. Was it a specific element of UI?

cc @nzaytsev

**Comment by axosoft-ramint** [comment]
Looks like we addressed this everywhere except for the graph minimap, but seeing no visual issues with it in high-contrast light or dark, I'm marking this as verified.
