### ISSUE TITLE
Start Work: add hover tooltip on an issue item

### ISSUE THREAD

**Issue by sergeibbb** [gitkraken/vscode-gitlens#3743]
This issue is a follow-up of #3621

## The problem

The issue description/body is not showing in the hover tooltip of each issue. We used to have this at the "confirm" step where you could choose an action on that issue, but since that step is gone now, there is no way to read the issue description without opening the issue. 

<img src="https://github.com/user-attachments/assets/44e0a236-5644-44b9-a8e6-9614a9282e70" width="400">

## The solution
We should have the current description, and then a blank line, and then the issue body, so that the current description lines show as they are now in the quickpick but if you hover over one of them, you can see the full issue body in the tooltip.

![Image](https://github.com/user-attachments/assets/0114a0c8-617b-4bba-b10a-618139aa80e8)

**Comment by axosoft-ramint** [comment]
> a blank line doesn't look good
> 
> Do you know how to fix it?

@sergeibbb How are you creating the blank line? I suggest padding with a ton of whitespace characters rather than just using a line-break, but not sure if you've tried that already here.

**Comment by sergeibbb** [comment]
@axosoft-ramint 

Spaces work almost nice. But it shows ellipsis:

<img src="https://github.com/user-attachments/assets/e635f2c8-c951-4a4c-b99f-cb7e0a03f6a8" width="600">
