### ISSUE TITLE
Stashes View disappeared

### ISSUE THREAD

**Issue by vagos30f** [gitkraken/vscode-gitlens#3760]
### Description

After updating  on v16.0.0 the stashes menu disappeared from the source control view. 

I noticed that If i uncheck the box on the `settings.gitlens.views.scm.grouped.views` then it appeared again. It looks like the logic got flipped in the update. 

### GitLens Version

16.0.0

### VS Code Version

Version: 1.95.2
Commit: e8653663e8840adaf45af01eab5c627a5af81807
Date: 2024-11-07T11:07:22.054Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 6.8.0-48-generic snap

### Git Version

git version 2.43.0

### Logs, Screenshots, Screen Captures, etc

![Image](https://github.com/user-attachments/assets/d322aa36-6d7a-4997-9f50-1b615422e081)
![Image](https://github.com/user-attachments/assets/9f066610-2318-4817-959e-b92482beb8af)

**Comment by dpage-mdsol** [comment]
I'm glad we can get them back, but I'm not a fan of the grouping.

**Comment by shaynasymons** [comment]
This was a pain to find the answer to.
