### ISSUE TITLE
Launchpad Search: search only when nothing is found

### ISSUE THREAD

**Issue by sergeibbb** [gitkraken/vscode-gitlens#3763]
This issue is a follow-up of #3543

## The problem

- Users starts searching in the Launchpad
- Some items that are presented become visible immediately
- But after a second or two API search finishes and its result appear so the initial items stops being visible.

That's because we cannot control order of items in the quickpick when it's in the search/filtering state.

## The solution
Search only when nothing is found locally.

**Comment by sergeibbb** [comment]
Hi @eamodio 

In main I see changes related to this: that implement manual trigger to search. Should this ticket have been closed as cancelled?

cc @justinrobots

**Comment by eamodio** [comment]
Yeah this can be closed as complete.
