### ISSUE TITLE
Default worktree displays as a branch instead of a Worktree in home.

### ISSUE THREAD

**Issue by justinrobots** [gitkraken/vscode-gitlens#3764]
### Description

Reported in [this discussion thread](https://github.com/gitkraken/vscode-gitlens/discussions/3721#discussioncomment-11265194).

The default worktree is being displayed as a branch in the new Home view. This means there is only an option to switch to the branch, not open that worktree.

### GitLens Version

16.0.0

### Logs, Screenshots, Screen Captures, etc

https://github.com/gitkraken/vscode-gitlens/discussions/3721#discussioncomment-11265194

**Comment by d13** [comment]
Resolved with 1665ce9845928e632fe2e145919db2f3f9884c7d
