### ISSUE TITLE
Pin/snooze in Launchpad trigger a full refresh and are no longer optimistic

### ISSUE THREAD

**Issue by axosoft-ramint** [gitkraken/vscode-gitlens#3791]
Clicking "pin/snooze" on Launchpad items would previously be optimistic, immediately updating the affected item before calling the backend. Now it waits for a full refresh before anything changes.

**Comment by nzaytsev** [comment]
It's optimistic, but can we do something with after fetch scroll up

https://github.com/user-attachments/assets/5452acdf-53ff-4335-a045-078e7a64272a

And something wrong with request cancelation. For example:
Let the server response time is 300 ms. I'm clicking to the pin to PR1 (0ms), PR2 (100ms) and PR3 (200ms).

The result is:
  - 0ms: PR1 is pinned
  - 100ms: PR1 and PR2 are pinned
  - 200ms: PR1, PR2 and PR3 are pinned
  - 300ms: PR1 is pinned
  - 400ms: PR1 and PR2 are pinned
  - 500ms: PR1, PR2 and PR3 are pinned


https://github.com/user-attachments/assets/31b052d2-a0c7-4f28-900b-7b758639f9a8

**Comment by axosoft-ramint** [comment]
@nzaytsev I don't think we can do anything about the scroll-up since that is the quickpick behavior when items are refreshed. Regarding the cancellation though, would you mind writing a follow-up issue for it?

Marking this one as verified since the behavior is now optimistic as intended.

**Comment by nzaytsev** [comment]
@axosoft-ramint - I realize that there's nothing to do with scroll-up behavior, but there could be a trick. When the new list items is the same to previous, we could just not update the list and keep the optimistic state. And what about cancelation?
