### ISSUE TITLE
Interactive rebase on the same branch is not working

### ISSUE THREAD

**Issue by shuky-shukrun** [gitkraken/vscode-gitlens#3794]
### Description

Hi,

Interactive rebase on the same branch with older commit is not possible (to squash older commits for example).
A `Nothing to do` message always appears.

I went back to v16.0.2 and it's working. I think the issue started from #3747 fix. 

Steps to reproduce:
1. Checkout any branch
2. Use `Gitlens: Git Rebase...` from command pallet
3. Choose the same branch and older commit
4. See `Nothing to do` message

Thanks!

### GitLens Version

16.0.3

### VS Code Version

Version: 1.95.3 (system setup)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631

### Git Version

git version 2.46.0.windows.1

**Comment by axosoft-ramint** [comment]
Should be fixed in commit: 77a573be2400e91befd365edc772f71192c8c1a6

**Comment by axosoft-ramint** [comment]
@shuky-shukrun Can you please verify this fix in the pre-release edition of GitLens (`v2024.11.2504`)? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by axosoft-ramint** [comment]
**Update:** this fix should now be in the latest release version of the extension as well (16.0.4).

**Comment by RodrigoMural** [comment]
I arrived here with the same problem. I can confirm it is fixed in 16.0.4. Thanks a lot for the super quick fix! 😄
