### ISSUE TITLE
Invert flow for start work on an issue to pick issue first

### ISSUE THREAD

**Issue by justinrobots** [gitkraken/vscode-gitlens#3809]
After initiating the "Start work from an issue" flow:
- Ask user to search for/select an issue first
- Then initiate the current branch creation flow:
  - this flow will end with a selection to "Create and switch to a branch" or "Create the branch on a new worktree"
  - don't show the option to create a branch without switching to it in this flow, since the intent is to start work now

Related to #3808 that removes the normal branch creation flow from the "Start work" button.

**Comment by axosoft-ramint** [comment]
Done in commit: cf00fc452598226924feb5b4c2c515b759ad6fb9
