### ISSUE TITLE
Display PR and Issue cards for trial and Pro users

### ISSUE THREAD

**Issue by justinrobots** [gitkraken/vscode-gitlens#3829]
In Home view, show the following only during trials and for Pro accounts:
- [ ] PR cards
- [ ] Issue cards
- [ ] Avatars in branch cards

**Comment by d13** [comment]
Resolved with 11932f788cee5981f8d5197061109d15f9259cc8

**Comment by nzaytsev** [comment]
There are active PR/issue buttons for community users that work but don't change the home view state after action is finished

![Image](https://github.com/user-attachments/assets/e27afe6c-2955-4bad-956c-be3fece8e355)

Same for recent

 ![Image](https://github.com/user-attachments/assets/1411216a-a4ac-4a60-b93e-46ef5e3aad71)
