### ISSUE TITLE
Commit View vanished with newest update.

### ISSUE THREAD

**Issue by mjmatthiesen** [gitkraken/vscode-gitlens#3830]
### Description

1. Previously in the source control tab/view I had a commit view (and more) provided by gitlens
2. These views are now gone replaced by the generic "gitlens" view.
3. This is a UX mistake as it increases clicks needlessly.
4. How can I get back the previous superior separate views back?

### GitLens Version

16.0.4

### VS Code Version

Version: 1.95.2 (system setup)
Commit: e8653663e8840adaf45af01eab5c627a5af81807
Date: 2024-11-07T11:07:22.054Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.19045

### Logs, Screenshots, Screen Captures, etc

Previous versions:
![Image](https://github.com/user-attachments/assets/c1223ffb-f72d-474e-9df0-c92990815a23)

New version that randomly removed features:
![Image](https://github.com/user-attachments/assets/b455f335-fc2c-45b0-939e-18c24b8b0499)

**Comment by eamodio** [comment]
See https://github.com/gitkraken/vscode-gitlens/issues/3766 and [this discussion](https://github.com/gitkraken/vscode-gitlens/discussions/3762)

You can easily detach one or all views depending on your needs.
