### ISSUE TITLE
When no issues are returned, show an option to connect integrations

### ISSUE THREAD

**Issue by justinrobots** [gitkraken/vscode-gitlens#3833]
When users are in the start work flow and they don't see any issues when they get to the issue selection section, display an option in the menu that sends them to connect an integration.

**Comment by nzaytsev** [comment]
It would be fine to check all integrations-depend parts on the home view. For example, I cannot associate an issue without integration connected, and it's fine, but I can create a PR and will no see it or get the 'PR already exists' error

https://github.com/user-attachments/assets/bb48ea17-77e7-4fb7-a014-6ab59175798f

But it's out of scope of this issue, it works as expected for the start work workflow
