### ISSUE TITLE
Reword placeholder input text during base branch selection step

### ISSUE THREAD

**Issue by justinrobots** [gitkraken/vscode-gitlens#3834]
We've noticed some confusion at the step where users need to select a base branch to create a new branch from. They usually start typing the name of the branch instead of selecting a base, which removes all quick pick options to proceed because no branches match the input.

We should consider updating text to be more clear (see image for current text).
- Title bar: "Select base for new branch"
- Input placeholder: "Select base to create the new branch from (or enter a revision using #)".

![Image](https://github.com/user-attachments/assets/4872e739-36d1-4909-ae55-f3e1eef02449)

**Comment by axosoft-ramint** [comment]
Done in commit: 3b4e917b26fc9950b1450c5a3edf12a75fe5ee20
