### ISSUE TITLE
Menu item to raise a pull request

### ISSUE THREAD

**Issue by kolya-ay** [gitkraken/vscode-gitlens#386]
As soon as GitLens already supports all the major git hosting providers it would be cool to have a command to open pull/merge request creation page from branches list. Something near to "Open Branch in Remote"..

**Comment by iyashpal** [comment]
@eamodio it would be great to have this functionality in GitLens. At least, we don't have to install another separate extension for this particular functionality.

Thank you

**Comment by eamodio** [comment]
GitLens now shows associated PRs with branches (and commits), so you can see information about the PR and jump to view it on GitHub. GitLens also has a _Create Pull Request..._ action when you right-click on a branch (as long as that branch is published to the remote). And that will take you to GitHub to create a PR for that branch or if you have the GitHub Pull Request and Issues extension installed can offer to create the PR directly in VS Code. Additionally, GitLens should prompt you with a notification when you publish a new branch to a remote and ask if you want to open a PR.
