### ISSUE TITLE
Remove unused media assets

### ISSUE THREAD

**Issue by d13** [gitkraken/vscode-gitlens#3860]
Delete any media files that we are no longer using to ensure we're not bundling unnecessary files into the VSIX.

**Comment by nzaytsev** [comment]
As the first step I just ignored all docs images, as they're loaded from raw.githubusercontent.com 

The vsix size is reduced from 28.5Mb to 7.9Mb

![Image](https://github.com/user-attachments/assets/9c5c4ec3-a57c-458b-a98a-dac39b9b21e2)
