### ISSUE TITLE
Support association of issues with branches outside of autolinks

### ISSUE THREAD

**Issue by ramin-t** [gitkraken/vscode-gitlens#3870]
Currently, we use autolinks on branch name to associate issues with branches in home. This is brittle, and can break if you don't name the branch in just the right way.

So we want to allow issues to be linked to branches and for this to be saved ideally somewhere that is resilient, cross-product, and local.

Current idea is to use the git config.

Once this is enabled, when Start Work is used, the branch should be associated with the chosen issue using this feature. It should then be used in conjunction with autolinks to get associated issues for a branch.

**Comment by axosoft-ramint** [comment]
Associated PR (mentioned above) is merged.
