### ISSUE TITLE
Add button to open Home View from Graph

### ISSUE THREAD

**Issue by justinrobots** [gitkraken/vscode-gitlens#3873]
Add a button to the Commit Graph header that opens the GitLens Home View so users can easily jump between Home and the Graph.

- use the GitLens logo
- add a hover style similar to the existing "Open in GitHub button" (see example)
- add a tooltip on hover that says "Open GitLens Home View"
- open the GitLens Home View when clicked

Mockup:
<img width="513" alt="Image" src="https://github.com/user-attachments/assets/18476b06-823a-4410-a36e-897c9d5e314f" />

Example of the "Open in GitHub button":
<img width="291" alt="Image" src="https://github.com/user-attachments/assets/8ec500a5-99a5-48e7-a59d-8aaceb884127" />

**Comment by nzaytsev** [comment]
@justinrobots - would it make sense to add a similar button to the home view to have ability to open the commit graph?

**Comment by eamodio** [comment]
@justinrobots do we really want this on the left side? Shouldn't it be on the right side, to the right of launchpad? I would also suggest we have a little more description for what Home is (like we do for the launchpad button)

@nzaytsev we do have a button on Home to go to the Graph

**Comment by eamodio** [comment]
@nzaytsev Please move this button to the right of the Launchpad item.
