### ISSUE TITLE
Use branch and worktree state icons in Home View

### ISSUE THREAD

**Issue by justinrobots** [gitkraken/vscode-gitlens#3890]
In Home View, we currently use generic branch and worktree icons:

<img width="900" alt="Image" src="https://github.com/user-attachments/assets/f831cf9e-3709-4b66-8dbd-a41f84ba47cf" />

We want to use the icons from the GitLens Branches view that represent branch and worktree state in the cards in Home View instead of the generic icons.

Example of branch and worktree icons in Branches view:
<img width="381" alt="Image" src="https://github.com/user-attachments/assets/a86deb8f-f64e-4471-a52f-f7f402d084a8" />

**Comment by eamodio** [comment]
This is done and in pre-release already.
