### ISSUE TITLE
Autolinks with hashtag prefix stopped working since v16.1.0

### ISSUE THREAD

**Issue by vox-koracz** [gitkraken/vscode-gitlens#3899]
### Description

I have configured autolinks prefixed with '#' to quickly navigate from commit message to related issues in redmine.
Since version v16.1.0, the link redirects to an issue in GitLab with that number, which obviously does not exist (404). It was working fine before latest version.
Is this intentional behavior, and is it possible to restore the previous functionality?

(I've replaced real domain with example.com for screenshot purposes)
![Image](https://github.com/user-attachments/assets/6c7ee7db-d6ac-4f63-a34c-fb86135f60ea)

![Image](https://github.com/user-attachments/assets/4212a667-0111-4c42-9bef-9492c6a53b2c)

### GitLens Version

16.1.0

### VS Code Version

Version: 1.96.2 (user setup)
Commit: fabdb6a30b49f79a7aba0f2ad9df9b399473380f
Date: 2024-12-19T10:22:47.216Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631

### Git Version

2.34.1

**Comment by axosoft-ramint** [comment]
@vox-koracz Can you please verify this fix in tomorrow's pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by vox-koracz** [comment]
@axosoft-ramint 
I switched to the pre-release version of GitLens and unfortunately the problem still exists on my side
![Image](https://github.com/user-attachments/assets/e6a638dd-4b2f-4017-bfbe-1aec9809f05d)

![Image](https://github.com/user-attachments/assets/75176b75-8ea6-46b7-9601-7f9909fd8f23)

**Comment by axosoft-ramint** [comment]
@vox-koracz The pre-release won't be updated until tomorrow - mind checking back then (roughly 24 hrs)?
