### ISSUE TITLE
Git lens no more provides option to create and switch branch

### ISSUE THREAD

**Issue by IAM5K** [gitkraken/vscode-gitlens#3905]
### Description

# Issue 1 
1. Open git panel in Vs code
2. Check your current branch
3. Click on create branch
4. Fill the details

Earlier we used to get the option for  create and switch, create and don't switch etc.
Current problem is with the git folder hierarchy it is difficult to find the branch after creating and it feels irritating

Example: We use branch name as "Feat/SOME-ID" and if there are already 20 branch with folder name Feat then it gets lost. 

![Image](https://github.com/user-attachments/assets/4b4c31a5-6414-419b-8f75-a85731fd944e)

# Issue 2
1. Once the branch is created then try publshing the branch from the UI, the publish brach icon. It fails with the error below.
![Image](https://github.com/user-attachments/assets/a63796dc-2f2b-41cc-8882-d416e7507518)

2. Meanwhile the brach can be published by using cli.

Both these issues were not there in previous versions of git

### GitLens Version

 2024.12.2404

### VS Code Version

Version: 1.96.2
Commit: fabdb6a30b49f79a7aba0f2ad9df9b399473380f
Date: 2024-12-19T10:22:47.216Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Linux x64 6.8.0-51-generic

### Git Version

git version 2.43.0

**Comment by sergeibbb** [comment]
Hi @IAM5K 
Let me ask few questions to better understand the problem.

1. What is the expected behavior? to switch or not to switch?
2. What do you mean by getting lost? If you "create and switch", then the new branch becomes your current branch, right?
3. In your steps you mention "create branch" (I suppose on "branches" panel), but the screenshot is for "switch to branch" on "remotes" panel. Do you mean "switch to remote"?

**Comment by IAM5K** [comment]
Hi @sergeibbb ,
Answer to your question:
1. Expected behavior is that it asks and when we select "create and switch", it switch to newly created branch. Currently it is not asking. So flow is, we click on create branch on panel/UI, it asks the name of branch to be created and done. I know this is easy but we remain in the old branch and don't get automatically switched to new branch.
2. Option Lost means, i don't get that option to "create and switch" anymore.
3. Screenshot is of very older version. In current and previous version it can't be seen.

**Comment by sergeibbb** [comment]
Hi @IAM5K 

Is it possible that an option has been checked as default so it has stopped asking:
<img width="956" alt="Image" src="https://github.com/user-attachments/assets/e0a4f4f7-8709-487e-afe2-c6269ce24889" />

This selection goes to user's settings JSON as `gitlens.gitCommands.skipConfirmations`:

<img width="467" alt="Image" src="https://github.com/user-attachments/assets/4acdba0a-8526-4341-b882-23c75e4651d8" />

When I delete "branch-create:command" record from my User settings JSON, I start seeing this option:
<img width="642" alt="Image" src="https://github.com/user-attachments/assets/62044c53-a3c7-4545-87af-3fd876a49fa3" />

**Comment by IAM5K** [comment]
Let me check this out.

**Comment by IAM5K** [comment]
Thanks this worked.
