### ISSUE TITLE
Add feature to compare branch and filter commits and files changes by author

### ISSUE THREAD

**Issue by llezenelrahc** [gitkraken/vscode-gitlens#570]
is there any feature to compare branch and filter commit and file changes by author ?
for i want to review some merged branches who did something,any idea to complish this task?

**Comment by eamodio** [comment]
Unfortunately not currently -- although I have started (laid the basic groundwork) on the implementation of this feature.

**Comment by bpasero** [comment]
I would love to have this feature (filter comparing between 2 commits by author).

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's (`v2023.10.21xx`) pre-release edition of GitLens? Thank you so much!

![image](https://github.com/gitkraken/vscode-gitlens/assets/641685/f669a052-6959-4765-a0ea-5f28368208ff)

You can do it for the whole _Commits_ view too

![image](https://github.com/gitkraken/vscode-gitlens/assets/641685/f7cbc74f-ede9-4dd4-8029-32f81c337022)


You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by axosoft-ramint** [comment]
Verified in 14.5.0
