### ISSUE TITLE
GitLens commands are mistakenly enabled for non-disk-based workspace files

### ISSUE THREAD

**Issue by johnspurlock** [gitkraken/vscode-gitlens#630]
- GitLens Version: 9.4.1

Steps to Reproduce:

1. Add the [MemFS](https://marketplace.visualstudio.com/items?itemName=jrieken.vscode-memfs) extension (or the [fsprovider-sample](https://github.com/Microsoft/vscode-extension-samples/tree/master/fsprovider-sample) in the vscode-extension-samples repo)

2. Create an MemFS workspace.  > MemFS: Setup Workspace

3. Create some new files in the workspace using the explorer.

4. Right-click on the new files in the explorer.

Expected: GitLens commands should not appear in the menu

Actual: GitLens commands appear in the menu

You may want to look at [Document Selectors](https://code.visualstudio.com/api/references/document-selector) or something similar to filter out non-disk files.

**Comment by eamodio** [comment]
We believe this issue has been resolved in the latest (or recent) version of GitLens. If you are still experiencing this, please let us know and we can re-open the issue or open a new issue if this is already locked.
