### ISSUE TITLE
Add a progress checkmark or similar in the compare view to track which files we have already finished comparing

### ISSUE THREAD

**Issue by KevinMallinson** [gitkraken/vscode-gitlens#836]
When I am reviewing a large pull request, e.g. 200 files changed, it's easy to lose track of which files I have already reviewed.

It would be good if we could manually "mark" a file as "already reviewed", so we can easily distinguish which ones we have already reviewed.

**Comment by ChrisdeWolf** [comment]
I also am looking for this feature. I see vscode-github-pull-request extension has implemented something that would be perfect (link to original issue: https://github.com/microsoft/vscode-pull-request-github/issues/520). I am generally just looking to check-off files I have already viewed when reviewing a large PR.
