### ISSUE TITLE
Icon color does not use foreground color

### ISSUE THREAD

**Issue by atomiks** [gitkraken/vscode-gitlens#958]
- GitLens Version: 10.2.1
  
- VSCode Version: 1.42.0
- OS Version: macOS 10.15.2

Steps to Reproduce:

Top right: 

![img](https://i.imgur.com/QgHDrRG.png)

The GitLens icons are gray rather than saturated with the blue hue. I think this is the global `"foreground"` color but not certain.

**Comment by eamodio** [comment]
Unfortunately this is because VS Code now uses an icon font for its icons, but extensions can only use SVG (which causes the exact issue you noted).

See: https://github.com/microsoft/vscode/issues/85297 & https://github.com/microsoft/vscode/issues/85182

**Comment by xsrvmy** [comment]
Is it possible to regenerate the icons in the extension folder to match the current theme?

**Comment by eamodio** [comment]
GitLens can now provide its own set of additional "codicons" so this is no longer blocked.

**Comment by d13** [comment]
Our custom codicons are in!

Resolved with 8fa90c2c6d95431c96afef59bc9092fec154480e
