### ISSUE TITLE
Show copy relative path in the contextual menu

### ISSUE THREAD

**Issue by BerserkWolfS** [gitkraken/vscode-gitlens#969]
Hello, 

is it possible to show the command "copy relative path" in the contextual menu like in the explorer ?

![image](https://user-images.githubusercontent.com/5680798/75567713-420a2280-5a52-11ea-82c9-e54ea4c6140d.png)

The point here is that I use git along with another versioning tool at work. Git offers me some flexibility I don't have with the other tool, but when I have to use the other tool, I need at a moment or another the names of the files I have modified between two git branches. GitLens is truly awesome for this, since I can have this information easily, but getting the files paths is quite bothersome (especially when the list of file is huge...) since the only way I found until now is to right click on the file to open it, and then on the editor name, to right click again to get the relative path name. 

Thanks

**Comment by carlo-ev** [comment]
Hey can I get this issue a go?
I have used the project for a while now and wanting to make contributions to it.
This issue seems simple enough to start but wanted to verified if it was assigned already before trying to do a pull request.
